<a href="https://colab.research.google.com/github/a-memoir/Automated-Medical-Report-NNH/blob/main/14oct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
import os
import json
import pandas as pd
import torch

base = Path("/content/drive/MyDrive/NoiSoi_Matching")
v5 = base / "baseline_model_v5"

print("=" * 70)
print("1. RUNTIME")
print("=" * 70)
print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
print("Fresh notebook objects:")
for name in ["model_v5", "V5Model", "test_loader", "tokenizer",
             "image_processor", "test_dataset"]:
    print(f"  {name}: {'exists' if name in globals() else 'not initialized'}")

print("\n" + "=" * 70)
print("2. CHECKPOINTS")
print("=" * 70)
for name in ["best.pt", "last.pt"]:
    p = v5 / "checkpoints" / name
    print(f"{name}: exists={p.exists()}")
    if p.exists():
        print(f"  Size: {p.stat().st_size / (1024**3):.3f} GiB")

print("\n" + "=" * 70)
print("3. DATA FILES")
print("=" * 70)
paths = {
    "V4 case manifest": base / "baseline_model_v4" / "v4_training_manifest.csv",
    "Image manifest": base / "final_manifest" / "final_dataset_manifest.csv",
    "Structured targets": base / "v3_ontology_v2" / "v3_structured_targets_v2_2.csv",
    "Ontology mapping": base / "baseline_model_v4" / "diagnostics" / "frozen_concept_ontology_mapping.csv",
    "Training summary": v5 / "diagnostics" / "v5_final_training_summary.json",
}
for label, p in paths.items():
    print(f"{label}: exists={p.exists()}", end="")
    if p.exists():
        print(f" | size={p.stat().st_size / (1024**2):.2f} MB")
    else:
        print()

print("\n" + "=" * 70)
print("4. TRAINING SUMMARY")
print("=" * 70)
summary_path = paths["Training summary"]
if summary_path.exists():
    try:
        summary = json.loads(summary_path.read_text())
        for k in ["model", "status", "num_epochs", "global_step",
                  "best_val", "best_checkpoint", "last_checkpoint"]:
            print(f"{k}: {summary.get(k)}")
    except Exception as e:
        print("Could not read summary:", repr(e))

print("\n" + "=" * 70)
print("5. MANIFEST INTEGRITY")
print("=" * 70)
manifest_path = paths["V4 case manifest"]
if manifest_path.exists():
    try:
        df = pd.read_csv(manifest_path, dtype={"case_id": str})
        print("Shape:", df.shape)
        print("Unique case IDs:", df["case_id"].nunique())
        print("Split counts:", df["split"].value_counts(dropna=False).to_dict())
        print("Required vector columns present:", {
            c: c in df.columns for c in [
                "concept_vector_str",
                "negative_vector_str",
                "attribute_vector_str"
            ]
        })
    except Exception as e:
        print("Could not read manifest:", repr(e))

print("\nR21A COMPLETE")

Mounted at /content/drive
======================================================================
1. RUNTIME
======================================================================
PyTorch: 2.11.0+cu130
CUDA available: True
GPU: NVIDIA A100-SXM4-80GB
Fresh notebook objects:
  model_v5: not initialized
  V5Model: not initialized
  test_loader: not initialized
  tokenizer: not initialized
  image_processor: not initialized
  test_dataset: not initialized

======================================================================
2. CHECKPOINTS
======================================================================
best.pt: exists=True
  Size: 4.321 GiB
last.pt: exists=True
  Size: 4.321 GiB

======================================================================
3. DATA FILES
======================================================================
V4 case manifest: exists=True | size=1.83 MB
Image manifest: exists=True | size=51.84 MB
Structured targets: exists=True | size=5.94 MB
Ontology mapping: exists=True | size=0.00 MB
Training summary: exists=True | size=0.00 MB

======================================================================
4. TRAINING SUMMARY
======================================================================
model: V5
status: TRAINING_COMPLETE
num_epochs: 5
global_step: 1920
best_val: 0.424518172663671
best_checkpoint: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/best.pt
last_checkpoint: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/last.pt

======================================================================
5. MANIFEST INTEGRITY
======================================================================
Shape: (7606, 15)
Unique case IDs: 7606
Split counts: {'train': 6138, 'val': 756, 'test': 712}
Required vector columns present: {'concept_vector_str': True, 'negative_vector_str': True, 'attribute_vector_str': True}

R21A COMPLETE

In [2]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
import torch

ckpt_path = Path(
    "/content/drive/MyDrive/NoiSoi_Matching/"
    "baseline_model_v5/checkpoints/best.pt"
)

print("Checkpoint exists:", ckpt_path.exists())
print("Checkpoint size (GiB):", round(ckpt_path.stat().st_size / 1024**3, 3))
print("PyTorch:", torch.__version__)

print("\nLoading checkpoint metadata with mmap=True, weights_only=True...")
try:
    checkpoint = torch.load(
        ckpt_path,
        map_location="cpu",
        weights_only=True,
        mmap=True,
    )

    print("Checkpoint object type:", type(checkpoint).__name__)

    if isinstance(checkpoint, dict):
        print("\nTop-level keys:")
        for key, value in checkpoint.items():
            if isinstance(value, dict):
                print(f"  {key}: dict, {len(value)} entries")
            elif torch.is_tensor(value):
                print(f"  {key}: tensor, shape={tuple(value.shape)}")
            else:
                print(f"  {key}: {type(value).__name__}")

        # Find a likely model state dictionary.
        state_candidates = []
        for key, value in checkpoint.items():
            if isinstance(value, dict) and value:
                tensor_count = sum(torch.is_tensor(v) for v in value.values())
                if tensor_count:
                    state_candidates.append((key, value, tensor_count))

        if all(torch.is_tensor(v) for v in checkpoint.values()):
            state_candidates.insert(0, ("<top-level state_dict>", checkpoint,
                                        len(checkpoint)))

        print("\nPotential state dictionaries:")
        for name, state, tensor_count in state_candidates:
            print(f"\n--- {name}: {tensor_count} direct tensor entries ---")
            shown = 0
            for key, value in state.items():
                if torch.is_tensor(value):
                    print(f"  {key}: {tuple(value.shape)} | {value.dtype}")
                    shown += 1
                    if shown >= 35:
                        print("  ... truncated")
                        break

    else:
        print("Unexpected checkpoint format; no model reconstruction attempted.")

except Exception as e:
    print("CHECKPOINT INSPECTION FAILED")
    print(type(e).__name__ + ":", str(e)[:1500])
    print("No training or checkpoint modification was performed.")

print("\nR21B COMPLETE")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Checkpoint exists: True
Checkpoint size (GiB): 4.321
PyTorch: 2.11.0+cu130

Loading checkpoint metadata with mmap=True, weights_only=True...
CHECKPOINT INSPECTION FAILED
UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, do those steps only if you trust the source of the checkpoint.
	(1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL numpy._core.multiarray._reconstruct was not an allowed global by default. Please use `torch.serialization.add_safe_globals([numpy._core.multiarray._reconstruct])` or the `torch.serialization.safe_globals([numpy._core.multiarray._reconstruct])` context manager to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
No training or checkpoint modification was performed.

R21B COMPLETE

In [3]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
import torch
import numpy as np

ckpt_path = Path(
    "/content/drive/MyDrive/NoiSoi_Matching/"
    "baseline_model_v5/checkpoints/best.pt"
)

# Allowlist only the NumPy reconstruction function named in the error.
try:
    reconstruct = np._core.multiarray._reconstruct
except AttributeError:
    reconstruct = np.core.multiarray._reconstruct

print("Checkpoint exists:", ckpt_path.exists())
print("PyTorch:", torch.__version__)
print("NumPy:", np.__version__)

try:
    with torch.serialization.safe_globals([reconstruct]):
        checkpoint = torch.load(
            ckpt_path,
            map_location="cpu",
            weights_only=True,
            mmap=True,
        )

    print("\nLOAD PASS")
    print("Checkpoint type:", type(checkpoint).__name__)

    if isinstance(checkpoint, dict):
        print("\nTop-level keys:")
        for key, value in checkpoint.items():
            if isinstance(value, dict):
                print(f"  {key}: dict ({len(value)} entries)")
            elif torch.is_tensor(value):
                print(f"  {key}: tensor {tuple(value.shape)}")
            else:
                print(f"  {key}: {type(value).__name__}")

        print("\nLikely model state dictionaries:")
        for name, value in checkpoint.items():
            if isinstance(value, dict):
                tensor_items = [
                    (k, v) for k, v in value.items()
                    if torch.is_tensor(v)
                ]
                if tensor_items:
                    print(f"\n[{name}] tensor entries: {len(tensor_items)}")
                    for key, tensor in tensor_items[:30]:
                        print(f"  {key}: {tuple(tensor.shape)}")
                    if len(tensor_items) > 30:
                        print("  ... truncated")
    else:
        print("Unexpected checkpoint format; stop for inspection.")

except Exception as e:
    print("\nLOAD BLOCKED")
    print(type(e).__name__ + ":", str(e)[:2500])
    print("No training or checkpoint modification was performed.")

print("\nR21C COMPLETE")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Checkpoint exists: True
PyTorch: 2.11.0+cu130
NumPy: 2.1.3

LOAD BLOCKED
UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, do those steps only if you trust the source of the checkpoint.
	(1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL numpy.ndarray was not an allowed global by default. Please use `torch.serialization.add_safe_globals([numpy.ndarray])` or the `torch.serialization.safe_globals([numpy.ndarray])` context manager to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
No training or checkpoint modification was performed.

R21C COMPLETE

In [4]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
import torch
import numpy as np

ckpt_path = Path(
    "/content/drive/MyDrive/NoiSoi_Matching/"
    "baseline_model_v5/checkpoints/best.pt"
)

try:
    reconstruct = np._core.multiarray._reconstruct
except AttributeError:
    reconstruct = np.core.multiarray._reconstruct

safe_types = [reconstruct, np.ndarray]

print("Checkpoint exists:", ckpt_path.exists())
print("Using weights_only=True and mmap=True")

try:
    with torch.serialization.safe_globals(safe_types):
        checkpoint = torch.load(
            ckpt_path,
            map_location="cpu",
            weights_only=True,
            mmap=True,
        )

    print("\nLOAD PASS")
    print("Object type:", type(checkpoint).__name__)

    if isinstance(checkpoint, dict):
        print("Top-level keys:")
        for key, value in checkpoint.items():
            if isinstance(value, dict):
                print(f"  {key}: dict ({len(value)} entries)")
            elif torch.is_tensor(value):
                print(f"  {key}: tensor {tuple(value.shape)}")
            else:
                print(f"  {key}: {type(value).__name__}")

        for name, value in checkpoint.items():
            if isinstance(value, dict):
                tensors = [(k, v) for k, v in value.items()
                           if torch.is_tensor(v)]
                if tensors:
                    print(f"\nState candidate: {name}, {len(tensors)} tensors")
                    for key, tensor in tensors[:40]:
                        print(f"  {key}: {tuple(tensor.shape)}")
                    if len(tensors) > 40:
                        print("  ... truncated")
    else:
        print("Unexpected checkpoint format; stop for inspection.")

except Exception as e:
    print("\nLOAD BLOCKED")
    print(type(e).__name__ + ":", str(e)[:2500])
    print("No training or checkpoint modification was performed.")

print("\nR21D COMPLETE")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Checkpoint exists: True
Using weights_only=True and mmap=True

LOAD BLOCKED
UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, do those steps only if you trust the source of the checkpoint.
	(1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL numpy.dtype was not an allowed global by default. Please use `torch.serialization.add_safe_globals([numpy.dtype])` or the `torch.serialization.safe_globals([numpy.dtype])` context manager to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
No training or checkpoint modification was performed.

R21D COMPLETE

In [5]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
import torch
import numpy as np

ckpt_path = Path(
    "/content/drive/MyDrive/NoiSoi_Matching/"
    "baseline_model_v5/checkpoints/best.pt"
)

try:
    reconstruct = np._core.multiarray._reconstruct
except AttributeError:
    reconstruct = np.core.multiarray._reconstruct

safe_types = [reconstruct, np.ndarray, np.dtype]

try:
    with torch.serialization.safe_globals(safe_types):
        checkpoint = torch.load(
            ckpt_path,
            map_location="cpu",
            weights_only=True,
            mmap=True,
        )

    print("LOAD PASS")
    print("Checkpoint type:", type(checkpoint).__name__)

    if isinstance(checkpoint, dict):
        print("\nTop-level keys:")
        for key, value in checkpoint.items():
            if isinstance(value, dict):
                print(f"\n{key}: dict ({len(value)} entries)")
                tensors = [
                    (k, v) for k, v in value.items()
                    if torch.is_tensor(v)
                ]
                for k, v in tensors[:25]:
                    print(f"  {k}: {tuple(v.shape)}")
                if len(tensors) > 25:
                    print("  ... truncated")
            elif torch.is_tensor(value):
                print(f"{key}: tensor {tuple(value.shape)}")
            else:
                print(f"{key}: {type(value).__name__}")
    else:
        print("Unexpected checkpoint format; stop for inspection.")

except Exception as e:
    print("\nLOAD BLOCKED")
    print(type(e).__name__ + ":", str(e)[:2500])
    print("Checkpoint was not modified.")

print("\nR21E COMPLETE")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

LOAD BLOCKED
UnpicklingError: Weights only load failed. In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
Please file an issue with the following so that we can make `weights_only=True` compatible with your use case: WeightsUnpickler error:

Can only build Tensor, Parameter, OrderedDict or types allowlisted via `add_safe_globals`, but got <class 'numpy.dtypes.UInt32DType'>

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
Checkpoint was not modified.

R21E COMPLETE

In [6]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
import torch

ckpt_path = Path(
    "/content/drive/MyDrive/NoiSoi_Matching/"
    "baseline_model_v5/checkpoints/best.pt"
)

# Chỉ dùng với checkpoint nội bộ đáng tin cậy do dự án của bạn tạo.
checkpoint = torch.load(
    ckpt_path,
    map_location="cpu",
    weights_only=False,
    mmap=True,
)

print("Checkpoint loaded for inspection.")
print("Type:", type(checkpoint).__name__)

if isinstance(checkpoint, dict):
    print("\nTop-level keys:")
    for key, value in checkpoint.items():
        if isinstance(value, dict):
            print(f"{key}: dict, {len(value)} entries")
            tensor_items = [
                (k, v) for k, v in value.items()
                if torch.is_tensor(v)
            ]
            for k, tensor in tensor_items[:12]:
                print(f"  {k}: {tuple(tensor.shape)}")
        elif torch.is_tensor(value):
            print(f"{key}: tensor {tuple(value.shape)}")
        else:
            print(f"{key}: {type(value).__name__}")
else:
    print("Unexpected checkpoint format.")

print("\nInspection complete.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Checkpoint loaded for inspection.
Type: dict

Top-level keys:
epoch: int
batch_idx: int
global_step: int
model_state: dict, 403 entries
  vision.embeddings.cls_token: (1, 1, 768)
  vision.embeddings.position_embeddings: (1, 197, 768)
  vision.embeddings.patch_embeddings.projection.weight: (768, 3, 16, 16)
  vision.embeddings.patch_embeddings.projection.bias: (768,)
  vision.layers.0.attention.q_proj.weight: (768, 768)
  vision.layers.0.attention.q_proj.bias: (768,)
  vision.layers.0.attention.k_proj.weight: (768, 768)
  vision.layers.0.attention.k_proj.bias: (768,)
  vision.layers.0.attention.v_proj.weight: (768, 768)
  vision.layers.0.attention.v_proj.bias: (768,)
  vision.layers.0.attention.o_proj.weight: (768, 768)
  vision.layers.0.attention.o_proj.bias: (768,)
optimizer_state: dict, 2 entries
scheduler_state: dict, 7 entries
best_val: float
history: dict, 2 entries
rng_state: tensor (5056,)
cuda_rng_state: list
python_rng_state: tuple
numpy_rng_state: tuple

Inspection complete.

In [7]:

from collections import Counter, defaultdict
import torch

assert "checkpoint" in globals(), "Checkpoint chưa có trong RAM; hãy chạy lại cell đọc checkpoint."
assert isinstance(checkpoint, dict) and "model_state" in checkpoint

state = checkpoint["model_state"]

print("=" * 75)
print("R21F-A — TRAINING STATE")
print("=" * 75)
for key in ["epoch", "batch_idx", "global_step", "best_val"]:
    print(f"{key}: {checkpoint.get(key)}")
print("Total model state entries:", len(state))
print("Tensor entries:", sum(torch.is_tensor(v) for v in state.values()))

print("\n" + "=" * 75)
print("R21F-B — PARAMETER PREFIX COUNTS")
print("=" * 75)

prefix_counts = Counter(
    key.split(".")[0] for key in state
)
for prefix, count in prefix_counts.most_common():
    print(f"{prefix}: {count}")

print("\n" + "=" * 75)
print("R21F-C — ALL NON-mT5 PARAMETER NAMES AND SHAPES")
print("=" * 75)

for key, value in state.items():
    if not key.startswith("mt5."):
        shape = tuple(value.shape) if torch.is_tensor(value) else type(value).__name__
        print(f"{key}: {shape}")

print("\n" + "=" * 75)
print("R21F-D — mT5 PARAMETER SUMMARY")
print("=" * 75)

mt5_keys = [(k, v) for k, v in state.items() if k.startswith("mt5.")]
print("mT5 entries:", len(mt5_keys))

mt5_prefix_counts = Counter(
    ".".join(k.split(".")[:3]) for k, _ in mt5_keys
)
print("mT5 top-level groups:")
for prefix, count in mt5_prefix_counts.most_common(30):
    print(f"  {prefix}: {count}")

print("\nFirst 20 mT5 keys:")
for key, value in mt5_keys[:20]:
    shape = tuple(value.shape) if torch.is_tensor(value) else type(value).__name__
    print(f"  {key}: {shape}")

print("\nLast 20 mT5 keys:")
for key, value in mt5_keys[-20:]:
    shape = tuple(value.shape) if torch.is_tensor(value) else type(value).__name__
    print(f"  {key}: {shape}")

print("\nR21F COMPLETE")

===========================================================================
R21F-A — TRAINING STATE
===========================================================================
epoch: 5
batch_idx: 0
global_step: 1920
best_val: 0.424518172663671
Total model state entries: 403
Tensor entries: 403

===========================================================================
R21F-B — PARAMETER PREFIX COUNTS
===========================================================================
vision: 200
mt5: 192
conditioner: 3
projector: 2
concept_head: 2
negative_head: 2
attribute_head: 2

===========================================================================
R21F-C — ALL NON-mT5 PARAMETER NAMES AND SHAPES
===========================================================================
vision.embeddings.cls_token: (1, 1, 768)
vision.embeddings.position_embeddings: (1, 197, 768)
vision.embeddings.patch_embeddings.projection.weight: (768, 3, 16, 16)
vision.embeddings.patch_embeddings.projection.bias: (768,)
vision.layers.0.attention.q_proj.weight: (768, 768)
vision.layers.0.attention.q_proj.bias: (768,)
vision.layers.0.attention.k_proj.weight: (768, 768)
vision.layers.0.attention.k_proj.bias: (768,)
vision.layers.0.attention.v_proj.weight: (768, 768)
vision.layers.0.attention.v_proj.bias: (768,)
vision.layers.0.attention.o_proj.weight: (768, 768)
vision.layers.0.attention.o_proj.bias: (768,)
vision.layers.0.layernorm_before.weight: (768,)
vision.layers.0.layernorm_before.bias: (768,)
vision.layers.0.layernorm_after.weight: (768,)
vision.layers.0.layernorm_after.bias: (768,)
vision.layers.0.mlp.fc1.weight: (3072, 768)
vision.layers.0.mlp.fc1.bias: (3072,)
vision.layers.0.mlp.fc2.weight: (768, 3072)
vision.layers.0.mlp.fc2.bias: (768,)
vision.layers.1.attention.q_proj.weight: (768, 768)
vision.layers.1.attention.q_proj.bias: (768,)
vision.layers.1.attention.k_proj.weight: (768, 768)
vision.layers.1.attention.k_proj.bias: (768,)
vision.layers.1.attention.v_proj.weight: (768, 768)
vision.layers.1.attention.v_proj.bias: (768,)
vision.layers.1.attention.o_proj.weight: (768, 768)
vision.layers.1.attention.o_proj.bias: (768,)
vision.layers.1.layernorm_before.weight: (768,)
vision.layers.1.layernorm_before.bias: (768,)
vision.layers.1.layernorm_after.weight: (768,)
vision.layers.1.layernorm_after.bias: (768,)
vision.layers.1.mlp.fc1.weight: (3072, 768)
vision.layers.1.mlp.fc1.bias: (3072,)
vision.layers.1.mlp.fc2.weight: (768, 3072)
vision.layers.1.mlp.fc2.bias: (768,)
vision.layers.2.attention.q_proj.weight: (768, 768)
vision.layers.2.attention.q_proj.bias: (768,)
vision.layers.2.attention.k_proj.weight: (768, 768)
vision.layers.2.attention.k_proj.bias: (768,)
vision.layers.2.attention.v_proj.weight: (768, 768)
vision.layers.2.attention.v_proj.bias: (768,)
vision.layers.2.attention.o_proj.weight: (768, 768)
vision.layers.2.attention.o_proj.bias: (768,)
vision.layers.2.layernorm_before.weight: (768,)
vision.layers.2.layernorm_before.bias: (768,)
vision.layers.2.layernorm_after.weight: (768,)
vision.layers.2.layernorm_after.bias: (768,)
vision.layers.2.mlp.fc1.weight: (3072, 768)
vision.layers.2.mlp.fc1.bias: (3072,)
vision.layers.2.mlp.fc2.weight: (768, 3072)
vision.layers.2.mlp.fc2.bias: (768,)
vision.layers.3.attention.q_proj.weight: (768, 768)
vision.layers.3.attention.q_proj.bias: (768,)
vision.layers.3.attention.k_proj.weight: (768, 768)
vision.layers.3.attention.k_proj.bias: (768,)
vision.layers.3.attention.v_proj.weight: (768, 768)
vision.layers.3.attention.v_proj.bias: (768,)
vision.layers.3.attention.o_proj.weight: (768, 768)
vision.layers.3.attention.o_proj.bias: (768,)
vision.layers.3.layernorm_before.weight: (768,)
vision.layers.3.layernorm_before.bias: (768,)
vision.layers.3.layernorm_after.weight: (768,)
vision.layers.3.layernorm_after.bias: (768,)
vision.layers.3.mlp.fc1.weight: (3072, 768)
vision.layers.3.mlp.fc1.bias: (3072,)
vision.layers.3.mlp.fc2.weight: (768, 3072)
vision.layers.3.mlp.fc2.bias: (768,)
vision.layers.4.attention.q_proj.weight: (768, 768)
vision.layers.4.attention.q_proj.bias: (768,)
vision.layers.4.attention.k_proj.weight: (768, 768)
vision.layers.4.attention.k_proj.bias: (768,)
vision.layers.4.attention.v_proj.weight: (768, 768)
vision.layers.4.attention.v_proj.bias: (768,)
vision.layers.4.attention.o_proj.weight: (768, 768)
vision.layers.4.attention.o_proj.bias: (768,)
vision.layers.4.layernorm_before.weight: (768,)
vision.layers.4.layernorm_before.bias: (768,)
vision.layers.4.layernorm_after.weight: (768,)
vision.layers.4.layernorm_after.bias: (768,)
vision.layers.4.mlp.fc1.weight: (3072, 768)
vision.layers.4.mlp.fc1.bias: (3072,)
vision.layers.4.mlp.fc2.weight: (768, 3072)
vision.layers.4.mlp.fc2.bias: (768,)
vision.layers.5.attention.q_proj.weight: (768, 768)
vision.layers.5.attention.q_proj.bias: (768,)
vision.layers.5.attention.k_proj.weight: (768, 768)
vision.layers.5.attention.k_proj.bias: (768,)
vision.layers.5.attention.v_proj.weight: (768, 768)
vision.layers.5.attention.v_proj.bias: (768,)
vision.layers.5.attention.o_proj.weight: (768, 768)
vision.layers.5.attention.o_proj.bias: (768,)
vision.layers.5.layernorm_before.weight: (768,)
vision.layers.5.layernorm_before.bias: (768,)
vision.layers.5.layernorm_after.weight: (768,)
vision.layers.5.layernorm_after.bias: (768,)
vision.layers.5.mlp.fc1.weight: (3072, 768)
vision.layers.5.mlp.fc1.bias: (3072,)
vision.layers.5.mlp.fc2.weight: (768, 3072)
vision.layers.5.mlp.fc2.bias: (768,)
vision.layers.6.attention.q_proj.weight: (768, 768)
vision.layers.6.attention.q_proj.bias: (768,)
vision.layers.6.attention.k_proj.weight: (768, 768)
vision.layers.6.attention.k_proj.bias: (768,)
vision.layers.6.attention.v_proj.weight: (768, 768)
vision.layers.6.attention.v_proj.bias: (768,)
vision.layers.6.attention.o_proj.weight: (768, 768)
vision.layers.6.attention.o_proj.bias: (768,)
vision.layers.6.layernorm_before.weight: (768,)
vision.layers.6.layernorm_before.bias: (768,)
vision.layers.6.layernorm_after.weight: (768,)
vision.layers.6.layernorm_after.bias: (768,)
vision.layers.6.mlp.fc1.weight: (3072, 768)
vision.layers.6.mlp.fc1.bias: (3072,)
vision.layers.6.mlp.fc2.weight: (768, 3072)
vision.layers.6.mlp.fc2.bias: (768,)
vision.layers.7.attention.q_proj.weight: (768, 768)
vision.layers.7.attention.q_proj.bias: (768,)
vision.layers.7.attention.k_proj.weight: (768, 768)
vision.layers.7.attention.k_proj.bias: (768,)
vision.layers.7.attention.v_proj.weight: (768, 768)
vision.layers.7.attention.v_proj.bias: (768,)
vision.layers.7.attention.o_proj.weight: (768, 768)
vision.layers.7.attention.o_proj.bias: (768,)
vision.layers.7.layernorm_before.weight: (768,)
vision.layers.7.layernorm_before.bias: (768,)
vision.layers.7.layernorm_after.weight: (768,)
vision.layers.7.layernorm_after.bias: (768,)
vision.layers.7.mlp.fc1.weight: (3072, 768)
vision.layers.7.mlp.fc1.bias: (3072,)
vision.layers.7.mlp.fc2.weight: (768, 3072)
vision.layers.7.mlp.fc2.bias: (768,)
vision.layers.8.attention.q_proj.weight: (768, 768)
vision.layers.8.attention.q_proj.bias: (768,)
vision.layers.8.attention.k_proj.weight: (768, 768)
vision.layers.8.attention.k_proj.bias: (768,)
vision.layers.8.attention.v_proj.weight: (768, 768)
vision.layers.8.attention.v_proj.bias: (768,)
vision.layers.8.attention.o_proj.weight: (768, 768)
vision.layers.8.attention.o_proj.bias: (768,)
vision.layers.8.layernorm_before.weight: (768,)
vision.layers.8.layernorm_before.bias: (768,)
vision.layers.8.layernorm_after.weight: (768,)
vision.layers.8.layernorm_after.bias: (768,)
vision.layers.8.mlp.fc1.weight: (3072, 768)
vision.layers.8.mlp.fc1.bias: (3072,)
vision.layers.8.mlp.fc2.weight: (768, 3072)
vision.layers.8.mlp.fc2.bias: (768,)
vision.layers.9.attention.q_proj.weight: (768, 768)
vision.layers.9.attention.q_proj.bias: (768,)
vision.layers.9.attention.k_proj.weight: (768, 768)
vision.layers.9.attention.k_proj.bias: (768,)
vision.layers.9.attention.v_proj.weight: (768, 768)
vision.layers.9.attention.v_proj.bias: (768,)
vision.layers.9.attention.o_proj.weight: (768, 768)
vision.layers.9.attention.o_proj.bias: (768,)
vision.layers.9.layernorm_before.weight: (768,)
vision.layers.9.layernorm_before.bias: (768,)
vision.layers.9.layernorm_after.weight: (768,)
vision.layers.9.layernorm_after.bias: (768,)
vision.layers.9.mlp.fc1.weight: (3072, 768)
vision.layers.9.mlp.fc1.bias: (3072,)
vision.layers.9.mlp.fc2.weight: (768, 3072)
vision.layers.9.mlp.fc2.bias: (768,)
vision.layers.10.attention.q_proj.weight: (768, 768)
vision.layers.10.attention.q_proj.bias: (768,)
vision.layers.10.attention.k_proj.weight: (768, 768)
vision.layers.10.attention.k_proj.bias: (768,)
vision.layers.10.attention.v_proj.weight: (768, 768)
vision.layers.10.attention.v_proj.bias: (768,)
vision.layers.10.attention.o_proj.weight: (768, 768)
vision.layers.10.attention.o_proj.bias: (768,)
vision.layers.10.layernorm_before.weight: (768,)
vision.layers.10.layernorm_before.bias: (768,)
vision.layers.10.layernorm_after.weight: (768,)
vision.layers.10.layernorm_after.bias: (768,)
vision.layers.10.mlp.fc1.weight: (3072, 768)
vision.layers.10.mlp.fc1.bias: (3072,)
vision.layers.10.mlp.fc2.weight: (768, 3072)
vision.layers.10.mlp.fc2.bias: (768,)
vision.layers.11.attention.q_proj.weight: (768, 768)
vision.layers.11.attention.q_proj.bias: (768,)
vision.layers.11.attention.k_proj.weight: (768, 768)
vision.layers.11.attention.k_proj.bias: (768,)
vision.layers.11.attention.v_proj.weight: (768, 768)
vision.layers.11.attention.v_proj.bias: (768,)
vision.layers.11.attention.o_proj.weight: (768, 768)
vision.layers.11.attention.o_proj.bias: (768,)
vision.layers.11.layernorm_before.weight: (768,)
vision.layers.11.layernorm_before.bias: (768,)
vision.layers.11.layernorm_after.weight: (768,)
vision.layers.11.layernorm_after.bias: (768,)
vision.layers.11.mlp.fc1.weight: (3072, 768)
vision.layers.11.mlp.fc1.bias: (3072,)
vision.layers.11.mlp.fc2.weight: (768, 3072)
vision.layers.11.mlp.fc2.bias: (768,)
vision.layernorm.weight: (768,)
vision.layernorm.bias: (768,)
vision.pooler.dense.weight: (768, 768)
vision.pooler.dense.bias: (768,)
projector.weight: (512, 768)
projector.bias: (512,)
conditioner.concept_embeddings: (48, 512)
conditioner.negative_embeddings: (5, 512)
conditioner.attribute_embeddings: (6, 512)
concept_head.weight: (48, 512)
concept_head.bias: (48,)
negative_head.weight: (5, 512)
negative_head.bias: (5,)
attribute_head.weight: (6, 512)
attribute_head.bias: (6,)

===========================================================================
R21F-D — mT5 PARAMETER SUMMARY
===========================================================================
mT5 entries: 192
mT5 top-level groups:
  mt5.decoder.block: 113
  mt5.encoder.block: 73
  mt5.shared.weight: 1
  mt5.encoder.embed_tokens: 1
  mt5.encoder.final_layer_norm: 1
  mt5.decoder.embed_tokens: 1
  mt5.decoder.final_layer_norm: 1
  mt5.lm_head.weight: 1

First 20 mT5 keys:
  mt5.shared.weight: (250112, 512)
  mt5.encoder.embed_tokens.weight: (250112, 512)
  mt5.encoder.block.0.layer.0.SelfAttention.q.weight: (384, 512)
  mt5.encoder.block.0.layer.0.SelfAttention.k.weight: (384, 512)
  mt5.encoder.block.0.layer.0.SelfAttention.v.weight: (384, 512)
  mt5.encoder.block.0.layer.0.SelfAttention.o.weight: (512, 384)
  mt5.encoder.block.0.layer.0.SelfAttention.relative_attention_bias.weight: (32, 6)
  mt5.encoder.block.0.layer.0.layer_norm.weight: (512,)
  mt5.encoder.block.0.layer.1.DenseReluDense.wi_0.weight: (1024, 512)
  mt5.encoder.block.0.layer.1.DenseReluDense.wi_1.weight: (1024, 512)
  mt5.encoder.block.0.layer.1.DenseReluDense.wo.weight: (512, 1024)
  mt5.encoder.block.0.layer.1.layer_norm.weight: (512,)
  mt5.encoder.block.1.layer.0.SelfAttention.q.weight: (384, 512)
  mt5.encoder.block.1.layer.0.SelfAttention.k.weight: (384, 512)
  mt5.encoder.block.1.layer.0.SelfAttention.v.weight: (384, 512)
  mt5.encoder.block.1.layer.0.SelfAttention.o.weight: (512, 384)
  mt5.encoder.block.1.layer.0.layer_norm.weight: (512,)
  mt5.encoder.block.1.layer.1.DenseReluDense.wi_0.weight: (1024, 512)
  mt5.encoder.block.1.layer.1.DenseReluDense.wi_1.weight: (1024, 512)
  mt5.encoder.block.1.layer.1.DenseReluDense.wo.weight: (512, 1024)

Last 20 mT5 keys:
  mt5.decoder.block.6.layer.2.DenseReluDense.wi_0.weight: (1024, 512)
  mt5.decoder.block.6.layer.2.DenseReluDense.wi_1.weight: (1024, 512)
  mt5.decoder.block.6.layer.2.DenseReluDense.wo.weight: (512, 1024)
  mt5.decoder.block.6.layer.2.layer_norm.weight: (512,)
  mt5.decoder.block.7.layer.0.SelfAttention.q.weight: (384, 512)
  mt5.decoder.block.7.layer.0.SelfAttention.k.weight: (384, 512)
  mt5.decoder.block.7.layer.0.SelfAttention.v.weight: (384, 512)
  mt5.decoder.block.7.layer.0.SelfAttention.o.weight: (512, 384)
  mt5.decoder.block.7.layer.0.layer_norm.weight: (512,)
  mt5.decoder.block.7.layer.1.EncDecAttention.q.weight: (384, 512)
  mt5.decoder.block.7.layer.1.EncDecAttention.k.weight: (384, 512)
  mt5.decoder.block.7.layer.1.EncDecAttention.v.weight: (384, 512)
  mt5.decoder.block.7.layer.1.EncDecAttention.o.weight: (512, 384)
  mt5.decoder.block.7.layer.1.layer_norm.weight: (512,)
  mt5.decoder.block.7.layer.2.DenseReluDense.wi_0.weight: (1024, 512)
  mt5.decoder.block.7.layer.2.DenseReluDense.wi_1.weight: (1024, 512)
  mt5.decoder.block.7.layer.2.DenseReluDense.wo.weight: (512, 1024)
  mt5.decoder.block.7.layer.2.layer_norm.weight: (512,)
  mt5.decoder.final_layer_norm.weight: (512,)
  mt5.lm_head.weight: (250112, 512)

R21F COMPLETE

In [8]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import ast
import json
import torch
from pathlib import Path

# ------------------------------------------------------------
# 1. Locate the original notebook and saved checkpoint
# ------------------------------------------------------------
notebook_path = Path(
    "/content/drive/MyDrive/Colab Notebooks/25sep.ipynb"
)
checkpoint_path = Path(
    "/content/drive/MyDrive/NoiSoi_Matching/"
    "baseline_model_v5/checkpoints/best.pt"
)

assert notebook_path.exists(), f"Original notebook not found: {notebook_path}"
assert checkpoint_path.exists(), f"Checkpoint not found: {checkpoint_path}"

with open(notebook_path, "r", encoding="utf-8") as f:
    notebook = json.load(f)

cells = notebook.get("cells", [])
sources = [
    "".join(cell.get("source", []))
    for cell in cells
    if cell.get("cell_type") == "code"
]

# Find the latest definitions to avoid the older V5 implementation.
class_nodes = {}
class_cell_indices = {}

for idx, source in enumerate(sources):
    try:
        tree = ast.parse(source)
    except SyntaxError:
        continue

    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name in {
            "SoftStructuredConditioner", "V5Model"
        }:
            class_nodes[node.name] = node
            class_cell_indices[node.name] = idx

required = {"SoftStructuredConditioner", "V5Model"}
missing = required - set(class_nodes)

print("Notebook:", notebook_path.name)
print("Code cells:", len(sources))
print("Found class definitions:", class_cell_indices)

assert not missing, (
    f"Could not find classes: {sorted(missing)}. "
    "Stop rather than reconstructing a guessed architecture."
)

# ------------------------------------------------------------
# 2. Execute only relevant imports from the original notebook
#    and the exact latest class definitions.
# ------------------------------------------------------------
allowed_roots = {
    "torch", "transformers", "typing", "math",
    "numpy", "collections"
}
import_nodes = {}
for source in sources:
    try:
        tree = ast.parse(source)
    except SyntaxError:
        continue

    for node in tree.body:
        if isinstance(node, ast.Import):
            roots = [alias.name.split(".")[0] for alias in node.names]
        elif isinstance(node, ast.ImportFrom):
            roots = [(node.module or "").split(".")[0]]
        else:
            continue

        if roots and all(root in allowed_roots for root in roots):
            import_nodes[ast.dump(node)] = node

# Import statements first; then execute the two original class definitions.
body = list(import_nodes.values()) + [
    class_nodes["SoftStructuredConditioner"],
    class_nodes["V5Model"],
]
module = ast.Module(body=body, type_ignores=[])
exec(compile(module, str(notebook_path), "exec"), globals())

print("PASS: original V5 classes loaded from notebook source.")

# ------------------------------------------------------------
# 3. Load checkpoint if not already present in memory
#    This is the trusted checkpoint created by this project.
# ------------------------------------------------------------
if "checkpoint" not in globals() or not isinstance(checkpoint, dict):
    checkpoint = torch.load(
        checkpoint_path,
        map_location="cpu",
        weights_only=False,
        mmap=True,
    )

assert "model_state" in checkpoint, (
    f"Expected 'model_state'; found keys: {list(checkpoint.keys())}"
)

# ------------------------------------------------------------
# 4. Instantiate exact architecture and restore all weights
# ------------------------------------------------------------
model_v5 = V5Model()
result = model_v5.load_state_dict(
    checkpoint["model_state"],
    strict=True,
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_v5 = model_v5.to(device)
model_v5.eval()

print("\n" + "=" * 70)
print("R21G — RESTORATION RESULT")
print("=" * 70)
print("load_state_dict:", result)
print("Checkpoint epoch:", checkpoint.get("epoch"))
print("Global step:", checkpoint.get("global_step"))
print("Best validation loss:", checkpoint.get("best_val"))
print("Device:", device)
print("Model parameters:", sum(p.numel() for p in model_v5.parameters()))
print("Model in eval mode:", not model_v5.training)
print("PASS: V5 restored with strict=True; no training performed.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Notebook: 25sep.ipynb
Code cells: 162
Found class definitions: {'SoftStructuredConditioner': 131, 'V5Model': 131}

ImportError: cannot import name 'MT5Tokenizer' from 'transformers' (/usr/local/lib/python3.13/dist-packages/transformers/__init__.py)

In [9]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import ast
import json
import torch
from pathlib import Path

notebook_path = Path("/content/drive/MyDrive/Colab Notebooks/25sep.ipynb")
checkpoint_path = Path(
    "/content/drive/MyDrive/NoiSoi_Matching/"
    "baseline_model_v5/checkpoints/best.pt"
)

with open(notebook_path, "r", encoding="utf-8") as f:
    notebook = json.load(f)

cells = notebook.get("cells", [])
code_cells = [
    "".join(c.get("source", []))
    for c in cells if c.get("cell_type") == "code"
]

# Locate the cell containing both original V5 class definitions.
target_source = None
target_index = None

for i, source in enumerate(code_cells):
    try:
        tree = ast.parse(source)
    except SyntaxError:
        continue

    class_names = {
        node.name for node in tree.body
        if isinstance(node, ast.ClassDef)
    }
    if {"SoftStructuredConditioner", "V5Model"}.issubset(class_names):
        target_source = source
        target_index = i

assert target_source is not None, "Could not find both original V5 classes."

tree = ast.parse(target_source)
imports = []
definitions = []

for node in tree.body:
    if isinstance(node, (ast.Import, ast.ImportFrom)):
        # Preserve imports from the original class cell, but remove
        # the incompatible tokenizer import.
        if isinstance(node, ast.ImportFrom) and node.module == "transformers":
            kept = [
                alias for alias in node.names
                if alias.name != "MT5Tokenizer"
            ]
            if kept:
                imports.append(
                    ast.ImportFrom(
                        module=node.module,
                        names=kept,
                        level=node.level,
                    )
                )
        else:
            imports.append(node)

    elif isinstance(node, ast.ClassDef) and node.name in {
        "SoftStructuredConditioner", "V5Model"
    }:
        definitions.append(node)

assert len(definitions) == 2, (
    f"Expected two class definitions, found {len(definitions)}"
)

module = ast.Module(body=imports + definitions, type_ignores=[])
exec(compile(ast.fix_missing_locations(module), str(notebook_path), "exec"), globals())

print(f"PASS: loaded original classes from notebook code cell {target_index}.")
print("V5Model:", V5Model)
print("SoftStructuredConditioner:", SoftStructuredConditioner)

# Load the trusted checkpoint only if it is not already in memory.
if not isinstance(globals().get("checkpoint"), dict):
    checkpoint = torch.load(
        checkpoint_path,
        map_location="cpu",
        weights_only=False,
        mmap=True,
    )

assert "model_state" in checkpoint, (
    f"Unexpected checkpoint keys: {list(checkpoint.keys())}"
)

model_v5 = V5Model()
load_result = model_v5.load_state_dict(
    checkpoint["model_state"],
    strict=True,
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_v5 = model_v5.to(device)
model_v5.eval()

print("\n" + "=" * 65)
print("R21G — RESTORATION RESULT")
print("=" * 65)
print("Strict loading:", load_result)
print("Checkpoint epoch:", checkpoint.get("epoch"))
print("Global step:", checkpoint.get("global_step"))
print("Best validation loss:", checkpoint.get("best_val"))
print("Device:", device)
print("Parameter count:", sum(p.numel() for p in model_v5.parameters()))
print("Eval mode:", not model_v5.training)
print("PASS: restored without training.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
PASS: loaded original classes from notebook code cell 131.
V5Model: <class '__main__.V5Model'>
SoftStructuredConditioner: <class '__main__.SoftStructuredConditioner'>

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/502 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  346MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/200 [00:00<?, ?it/s]

config.json:   0%|          | 0.00/553 [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B / 1.20GB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/192 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.20GB

model.safetensors: downloading bytes:           |  0.00B

=================================================================
R21G — RESTORATION RESULT
=================================================================
Strict loading: <All keys matched successfully>
Checkpoint epoch: 5
Global step: 1920
Best validation loss: 0.424518172663671
Device: cuda
Parameter count: 387020219
Eval mode: True
PASS: restored without training.

In [11]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import json
from pathlib import Path

notebook_path = Path("/content/drive/MyDrive/Colab Notebooks/25sep.ipynb")
with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

code_cells = [
    "".join(cell.get("source", []))
    for cell in nb.get("cells", [])
    if cell.get("cell_type") == "code"
]

search_terms = [
    "test_loader",
    "class V5Dataset",
    "class",
    "AutoImageProcessor",
    "AutoTokenizer",
    "image_processor",
    "case_to_images",
    "pixel_values",
    "image_mask",
    "image_status",
    "v4_training_manifest.csv",
]

print("=" * 75)
print("R21H — ORIGINAL TEST PIPELINE SEARCH")
print("=" * 75)

for term in search_terms:
    matches = []
    for idx, source in enumerate(code_cells):
        if term.lower() in source.lower():
            matches.append(idx)
    print(f"{term}: {matches[-12:]}")

print("\n" + "=" * 75)
print("RELEVANT CELL CONTENTS")
print("=" * 75)

selected = set()
for idx, source in enumerate(code_cells):
    low = source.lower()
    score = sum(term.lower() in low for term in [
        "test_loader",
        "class V5Dataset",
        "AutoImageProcessor",
        "AutoTokenizer",
        "case_to_images",
        "image_status",
        "pixel_values",
        "image_mask",
    ])
    if score >= 2 or "test_loader" in low:
        selected.add(idx)

for idx in sorted(selected):
    source = code_cells[idx]
    print(f"\n{'=' * 25} CODE CELL {idx} {'=' * 25}")
    print(source[:9000])
    if len(source) > 9000:
        print("\n... CELL TRUNCATED ...")

print("\nR21H COMPLETE")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
===========================================================================
R21H — ORIGINAL TEST PIPELINE SEARCH
===========================================================================
test_loader: [25, 123, 139]
class V5Dataset: [139]
class: [104, 106, 115, 116, 119, 120, 122, 125, 131, 139, 144, 156]
AutoImageProcessor: [0, 1, 141, 142]
AutoTokenizer: [0, 1, 68, 120, 139, 141, 142]
image_processor: [60, 68, 69, 73, 119, 120, 122, 141, 142, 144, 156, 161]
case_to_images: [60, 65, 67, 69, 73, 119, 120, 122, 139, 144, 156, 161]
pixel_values: [120, 122, 123, 124, 126, 127, 131, 139, 140, 143, 144, 156]
image_mask: [119, 120, 122, 123, 124, 126, 127, 131, 139, 140, 143, 156]
image_status: [46, 66, 67, 69, 73, 113, 114, 119, 120, 139, 144, 156]
v4_training_manifest.csv: [119, 120, 139, 144, 145, 146, 147, 149, 153, 155, 156, 161]

===========================================================================
RELEVANT CELL CONTENTS
===========================================================================

========================= CODE CELL 0 =========================
import os
import json
import math
import random
from pathlib import Path
from collections import Counter

import numpy as np
import pandas as pd
from PIL import Image

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from transformers import (
    ViTModel,
    MT5ForConditionalGeneration,
    AutoTokenizer,
    AutoImageProcessor,
)

print("=" * 70)
print("V4 NEW-NOTEBOOK BOOTSTRAP")
print("=" * 70)

# ================================================================
# 0. GOOGLE DRIVE
# ================================================================

from google.colab import drive

if not os.path.exists("/content/drive/MyDrive"):
    drive.mount("/content/drive")
else:
    print("Google Drive: already mounted")

# ================================================================
# 1. PATHS
# ================================================================

BASE = "/content/drive/MyDrive/NoiSoi_Matching"

V4_DIR = f"{BASE}/baseline_model_v4"

V4_MANIFEST = (
    f"{V4_DIR}/v4_training_manifest.csv"
)

STRUCTURED_CSV = (
    f"{BASE}/v3_ontology_v2/"
    f"v3_structured_targets_v2_2.csv"
)

IMAGE_MANIFEST = (
    f"{BASE}/final_manifest/"
    f"final_dataset_manifest.csv"
)

CONFIG_PATH = (
    f"{V4_DIR}/v4_config.json"
)

E2_CKPT = (
    f"{V4_DIR}/checkpoints/epoch_02.pt"
)

E3_CKPT = (
    f"{V4_DIR}/checkpoints/epoch_03.pt"
)

BEST_CKPT = (
    f"{V4_DIR}/checkpoints/best.pt"
)

========================= CODE CELL 1 =========================
# ================================================================
# V4 NEW-NOTEBOOK BOOTSTRAP + EXACT CONDITIONING ABLATION
# ================================================================
#
# PURPOSE:
#   Rebuild everything after Colab runtime disconnect
#   then run the EXACT V4 conditioning ablation.
#
# NO:
#   - training
#   - backward
#   - optimizer step
#   - scheduler step
#   - checkpoint save
#
# ================================================================

import os
import json
import math
import random
from pathlib import Path
from collections import Counter

import numpy as np
import pandas as pd
from PIL import Image

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from transformers import (
    ViTModel,
    MT5ForConditionalGeneration,
    AutoTokenizer,
    AutoImageProcessor,
)

print("=" * 70)
print("V4 NEW-NOTEBOOK BOOTSTRAP")
print("=" * 70)

# ================================================================
# 0. GOOGLE DRIVE
# ================================================================

from google.colab import drive

if not os.path.exists("/content/drive/MyDrive"):
    drive.mount("/content/drive")
else:
    print("Google Drive: already mounted")

# ================================================================
# 1. PATHS
# ================================================================

BASE = "/content/drive/MyDrive/NoiSoi_Matching"

V4_DIR = f"{BASE}/baseline_model_v4"

V4_MANIFEST = (
    f"{V4_DIR}/v4_training_manifest.csv"
)

STRUCTURED_CSV = (
    f"{BASE}/v3_ontology_v2/"
    f"v3_structured_targets_v2_2.csv"
)

IMAGE_MANIFEST = (
    f"{BASE}/final_manifest/"
    f"final_dataset_manifest.csv"
)

CONFIG_PATH = (
    f"{V4_DIR}/v4_config.json"
)

E2_CKPT = (
    f"{V4_DIR}/checkpoints/epoch_02.pt"
)

E3_CKPT = (
    f"{V4_DIR}/checkpoints/epoch_03.pt"
)

BEST_CKPT = (
    f"{V4_DIR}/checkpoints/best.pt"
)

# ------------------------------------------------
# Path checks
# ------------------------------------------------

required_paths = {
    "V4 manifest": V4_MANIFEST,
    "Structured targets": STRUCTURED_CSV,
    "Image manifest": IMAGE_MANIFEST,
    "V4 config": CONFIG_PATH,
    "E2 checkpoint": E2_CKPT,
    "E3 checkpoint": E3_CKPT,
    "Best checkpoint": BEST_CKPT,
}

print("\nPATH CHECK")

for name, path in required_paths.items():

    exists = os.path.exists(path)

    print(
        f"  {name:22s}:",
        "PASS" if exists else "FAIL",
        "->",
        path
    )

    assert exists, f"Missing: {path}"


# ================================================================
# 2. ENVIRONMENT
# ================================================================

print("\nENVIRONMENT")

print("PyTorch       :", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

assert torch.cuda.is_available(), "CUDA is required"

device = torch.device("cuda")

gpu_name = torch.cuda.get_device_name(0)

print("GPU           :", gpu_name)

if torch.cuda.is_bf16_supported():
    print("BF16          : supported")
else:
    print("BF16          : not supported")


# ================================================================
# 3. LOAD CONFIG
# ================================================================

with open(CONFIG_PATH, "r") as f:
    config = json.load(f)

print("\nV4 CONFIG")

for k, v in config.items():
    print(f"  {k}: {v}")


assert config["num_concepts"] == 48
assert config["num_negative_findings"] == 5
assert config["num_attributes"] == 6
assert config["max_images_per_case"] == 8

print("\nOntology dimensions: PASS")


# ================================================================
# 4. TOKENIZER + IMAGE PROCESSOR
# ================================================================

print("\nLOADING TOKENIZER")

tokenizer = AutoTokenizer.from_pretrained(
    "google/mt5-small"
)

print(
    "Tokenizer:",
    type(tokenizer).__name__
)

print(
    "Vocab size:",
    tokenizer.vocab_size
)

print(
    "pad_token_id:",
    tokenizer.pad_token_id
)

print(
    "eos_token_id:",
    tokenizer.eos_token_id
)

print("\nLOADING IMAGE PROCESSOR")

image_processor = AutoImageProcessor.from_pretrained(
    "google/vit-base-patch16-224"
)

print(
    "Image processor:",
    type(image_processor).__name__
)

print(
    "Image size:",
    image_processor.size
)

print(
    "Image mean:",
    image_processor.image_mean
)

print(
    "Image std:",
    image_processor.image_std
)


# ================================================================
# 5. LOAD MANIFESTS
# ================================================================

print("\nLOADING MANIFESTS")

v4_df = pd.read_csv(
    V4_MANIFEST,
    dtype=str,
)

structured_df = pd.read_csv(
    STRUCTURED_CSV,
    dtype=str,
)

image_df = pd.read_csv(
    IMAGE_MANIFEST,
    dtype=str,
)

print(
    "V4 manifest:",
    v4_df.shape
)

print(
    "Structured:",
    structured_df.shape
)

print(
    "Image manifest:",
    image_df.shape
)

assert v4_df.shape[0] == 7606
assert structured_df.shape[0] == 7606
assert image_df.shape[0] == 76405

print("Manifest shapes: PASS")


# ================================================================
# 6. COLUMN AUDIT
# ================================================================

print("\nCOLUMN AUDIT")

print(
    "V4 columns:",
    v4_df.columns.tolist()
)

print(
    "\nImage columns:",
    image_df.columns.tolist()
)


# ------------------------------------------------
# Resolve required columns
# ------------------------------------------------

def resolve_column(
    df,
    candidates,
    name,
):

    for c in candidates:
        if c in df.columns:
            print(
                f"{name:22s}: {c}"
            )
            return c

    raise KeyError(
        f"Cannot resolve {name}. "
        f"Tried {candidates}"
    )


v4_case_col = resolve_column(
    v4_df,
    ["case_id"],
    "V4 case_id",
)

v4_split_col = resolve_column(
    v4_df,
    ["split"],
    "V4 split",
)

v4_report_col = resolve_column(
    v4_df,
    ["ket_luan"],
    "V4 report",
)

image_case_col = resolve_column(
    image_df,
    ["case_id"],
    "Image case_id",
)

image_path_col = resolve_column(
    image_df,
    ["image_path"],
    "Image path",
)

# status column may have different naming
image_status_col = None

for c in [
    "image_status",
    "status",
    "mapping_status",
    "quality_status",
]:

    if c in image_df.columns:
        image_status_col = c
        break

print(
    "Image status column:",
    image_status_col
)


# ================================================================
# 7. VALIDATION MANIFEST
# ================================================================

val_manifest = v4_df[
    v4_df[v4_split_col].astype(str).str.lower() == "val"
].copy()

print("\nVALIDATION")

print(
    "Validation cases:",
    len(val_manifest)
)

assert len(val_manifest) == 756

val_case_ids = set(
    val_manifest[v4_case_col].astype(str)
)

print(
    "Unique validation cases:",
    len(val_case_ids)
)

assert len(val_case_ids) == 756


# ================================================================
# 8. IMAGE FILTERING
# ================================================================

val_images = image_df[
    image_df[image_case_col].astype(str).isin(
        val_case_ids
    )
].copy()

# ------------------------------------------------
# Keep only NORMAL if status exists
# ------------------------------------------------

if image_status_col is not None:

    status_norm = (
        val_images[image_status_col]
        .astype(str)
        .str.upper()
        .str.strip()
    )

    before = len(val_images)

    val_images = val_images[
        status_norm == "NORMAL"
    ].copy()

    print(
        "\nNORMAL image filtering:",
        before,
        "->",
        len(val_images)
    )

else:

    print(
        "\nWARNING: no image status column found."
    )

# ------------------------------------------------
# Remove missing paths
# ------------------------------------------------

val_images[image_path_col] = (
    val_images[image_path_col]
    .astype(str)
)

missing_path = (
    ~val_images[image_path_col].map(
        os.path.exists
    )
)

print(
    "Missing image paths:",
    int(missing_path.sum())
)

assert missing_path.sum() == 0

# ------------------------------------------------
# Group by case
# ------------------------------------------------

case_to_images = {}

for case_id, g in val_images.groupby(
    image_case_col
):

    paths = (
        g[image_path_col]
        .astype(str)
        .tolist()
    )

    # deterministic order
    paths = sorted(paths)

    # V4 cap
    paths = paths[:8]

    case_to_images[str(case_id)] = paths


print(
    "Cases with NORMAL images:",
    len(case_to_images)
)

missing_cases = [
    c for c in val_case_ids
    if c not in case_to_images
]

print(
    "Validation cases without NORMAL image:",
    len(missing_cases)
)

assert len(missing_cases) == 0


# =====

... CELL TRUNCATED ...

========================= CODE CELL 5 =========================
# ============================================================
# V4 EXACT CONDITIONING ABLATION
# E2 / E3 × FULL / ZERO_STRUCT / ZERO_VISUAL / ZERO_BOTH
# ============================================================

import torch
import torch.nn.functional as F
import numpy as np
import pandas as pd
from collections import Counter

model.eval()


# ============================================================
# 1. EXACT V4 CONDITIONING
# ============================================================

@torch.no_grad()
def build_v4_conditioning(
    batch,
    zero_struct=False,
    zero_visual=False,
):
    pixel_values = batch["pixel_values"].to(device)
    image_mask = batch["image_mask"].to(device)

    B, N, C, H, W = pixel_values.shape

    # --------------------------------------------------------
    # Vision
    # --------------------------------------------------------
    x = pixel_values.reshape(B * N, C, H, W)

    vision_out = model.vision(
        pixel_values=x
    ).last_hidden_state[:, 0]

    vision_out = vision_out.reshape(B, N, 768)

    # --------------------------------------------------------
    # EXACT checkpoint projector
    # --------------------------------------------------------
    visual_tokens = model.projector(vision_out)

    visual_tokens = visual_tokens * image_mask[:, :, None]

    # --------------------------------------------------------
    # ZERO_VISUAL:
    # must zero AFTER projector so projector bias is removed
    # --------------------------------------------------------
    if zero_visual:
        visual_tokens = torch.zeros_like(visual_tokens)

    # --------------------------------------------------------
    # Pool visual representation
    # --------------------------------------------------------
    denom = image_mask.sum(
        dim=1,
        keepdim=True
    ).clamp(min=1)

    pooled = (
        visual_tokens.sum(dim=1) / denom
    )

    # --------------------------------------------------------
    # Structured heads
    # --------------------------------------------------------
    concept_logits = model.structured_heads["concept"](pooled)
    negative_logits = model.structured_heads["negative"](pooled)
    attribute_logits = model.structured_heads["attribute"](pooled)

    concept_pred = (
        torch.sigmoid(concept_logits) >= 0.5
    ).float()

    negative_pred = (
        torch.sigmoid(negative_logits) >= 0.5
    ).float()

    attribute_pred = (
        torch.sigmoid(attribute_logits) >= 0.5
    ).float()

    # --------------------------------------------------------
    # ZERO_STRUCT
    # Keep conditioner architecture intact, but force all
    # structured values to 0.
    # --------------------------------------------------------
    if zero_struct:
        concept_pred = torch.zeros_like(concept_pred)
        negative_pred = torch.zeros_like(negative_pred)
        attribute_pred = torch.zeros_like(attribute_pred)

    # --------------------------------------------------------
    # Structured conditioner
    # --------------------------------------------------------
    structured_tokens, structured_attention = (
        model.conditioner(
            concept_pred,
            negative_pred,
            attribute_pred,
        )
    )

    # --------------------------------------------------------
    # Combine visual + structured prefix
    # --------------------------------------------------------
    visual_attention = image_mask.long()

    prefix = torch.cat(
        [
            visual_tokens,
            structured_tokens,
        ],
        dim=1,
    )

    attention_mask = torch.cat(
        [
            visual_attention,
            structured_attention,
        ],
        dim=1,
    )

    # --------------------------------------------------------
    # EXACT mT5 prefix construction
    # --------------------------------------------------------
    zero_ids = torch.zeros(
        B,
        prefix.shape[1],
        dtype=torch.long,
        device=prefix.device,
    )

    base_embeddings = model.mt5.encoder.embed_tokens(
        zero_ids
    )

    inputs_embeds = base_embeddings + prefix

    return {
        "inputs_embeds": inputs_embeds,
        "attention_mask": attention_mask,

        "concept_pred": concept_pred,
        "negative_pred": negative_pred,
        "attribute_pred": attribute_pred,

        "concept_logits": concept_logits,
        "negative_logits": negative_logits,
        "attribute_logits": attribute_logits,

        "visual_tokens": visual_tokens,
        "structured_tokens": structured_tokens,
    }


# ============================================================
# 2. TEACHER-FORCED LOSS
# ============================================================

@torch.no_grad()
def teacher_forced_eval(cond, labels):
    encoder_outputs = model.mt5.encoder(
        inputs_embeds=cond["inputs_embeds"],
        attention_mask=cond["attention_mask"],
        return_dict=True,
    )

    out = model.mt5(
        encoder_outputs=encoder_outputs,
        attention_mask=cond["attention_mask"],
        labels=labels,
        return_dict=True,
    )

    return float(out.loss.item())


# ============================================================
# 3. AUTOREGRESSIVE GENERATION
# ============================================================

@torch.no_grad()
def generate_one(cond, max_new_tokens=20):

    encoder_outputs = model.mt5.encoder(
        inputs_embeds=cond["inputs_embeds"],
        attention_mask=cond["attention_mask"],
        return_dict=True,
    )

    decoder_ids = torch.full(
        (1, 1),
        tokenizer.pad_token_id,
        dtype=torch.long,
        device=device,
    )

    generated = []

    for _ in range(max_new_tokens):

        out = model.mt5(
            encoder_outputs=encoder_outputs,
            attention_mask=cond["attention_mask"],
            decoder_input_ids=decoder_ids,
            return_dict=True,
        )

        next_token = torch.argmax(
            out.logits[:, -1, :],
            dim=-1,
            keepdim=True,
        )

        token_id = int(next_token.item())

        if token_id == tokenizer.eos_token_id:
            break

        generated.append(token_id)

        decoder_ids = torch.cat(
            [decoder_ids, next_token],
            dim=1,
        )

    return safe_decode(generated)


# ============================================================
# 4. PREPARE AUDIT BATCHES
# ============================================================

def case_to_batch(case):
    """
    Convert one Dataset item to a batch of size 1.
    """

    batch = {}

    for k, v in case.items():

        if torch.is_tensor(v):
            if k in ["pixel_values"]:
                # Dataset item: [N,C,H,W]
                batch[k] = v.unsqueeze(0)
            elif k in ["image_mask"]:
                # Dataset item: [N]
                batch[k] = v.unsqueeze(0)
            elif k in ["labels"]:
                # Dataset item: [T]
                batch[k] = v.unsqueeze(0)
            else:
                batch[k] = v.unsqueeze(0)

        else:
            batch[k] = v

    return batch


# ============================================================
# 5. RUN ONE CHECKPOINT
# ============================================================

def run_ablation_for_checkpoint(
    ckpt,
    epoch_name,
):

    print("\n" + "=" * 70)
    print(f"CHECKPOINT: {epoch_name}")
    print("=" * 70)

    model.load_state_dict(
        ckpt["model_state"],
        strict=True,
    )

    model.eval()

    conditions = {
        "FULL": {
            "zero_struct": False,
            "zero_visual": False,
        },
        "ZERO_STRUCT": {
            "zero_struct": True,
            "zero_visual": False,
        },
        "ZERO_VISUAL": {
            "zero_struct": False,
            "zero_visual": True,
        },
        "ZERO_BOTH": {
            "zero_struct": True,
            "zero_visual": True,
        },
    }

    rows = []

    for condition_name, flags in conditions.items():

        print(
            f"\n--- {condition_name} ---"
        )

        losses = []
        outputs = []

In [13]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import json
from pathlib import Path

nb_path = Path("/content/drive/MyDrive/Colab Notebooks/25sep.ipynb")
assert nb_path.exists(), f"Không tìm thấy notebook: {nb_path}"

with nb_path.open("r", encoding="utf-8") as f:
    nb = json.load(f)

cells = nb.get("cells", [])
print("Notebook cells:", len(cells))

# In đúng các cell R21H đã xác định có test pipeline.
for idx in [25, 123, 139]:
    if idx >= len(cells):
        print(f"\nCELL {idx}: ngoài phạm vi notebook hiện tại")
        continue

    cell = cells[idx]
    src = cell.get("source", [])
    src = "".join(src) if isinstance(src, list) else str(src)

    print("\n" + "=" * 90)
    print(f"CELL INDEX {idx} | TYPE={cell.get('cell_type')} | CHARS={len(src)}")
    print("=" * 90)
    print(src)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Notebook cells: 162

==========================================================================================
CELL INDEX 25 | TYPE=code | CHARS=1266
==========================================================================================
# ============================================================
# AUDIT: CURRENT COLAB RUNTIME OBJECTS
# DO NOT MODIFY ANYTHING
# ============================================================

print("========== LOADER RUNTIME AUDIT ==========")

candidate_names = [
    "train_loader",
    "val_loader",
    "test_loader",
    "train_dataset",
    "val_dataset",
    "test_dataset",
    "train_dl",
    "val_dl",
    "dataset",
    "loader",
]

for name in candidate_names:
    if name in globals():
        obj = globals()[name]

        print(f"\n{name}")
        print(f"  type = {type(obj)}")

        try:
            print(f"  len  = {len(obj)}")
        except Exception:
            print("  len  = <not available>")


print("\n========== ALL *_LOADER / *_DATASET OBJECTS ==========")

for name, obj in globals().items():
    if (
        "loader" in name.lower()
        or "dataloader" in name.lower()
        or "dataset" in name.lower()
    ):
        if not name.startswith("_"):
            print(f"{name:30s} {type(obj)}")


print("\n========== MODEL OBJECTS ==========")

for name in ["v5", "model", "optimizer", "scheduler"]:
    if name in globals():
        print(f"{name:15s} {type(globals()[name])}")
    else:
        print(f"{name:15s} MISSING")

==========================================================================================
CELL INDEX 123 | TYPE=code | CHARS=8979
==========================================================================================
# ============================================================
# V5 RESTORE — CELL 9H
# DataLoaders + Exact V4 Structured Targets
# ============================================================

import ast
import numpy as np
import torch
from torch.utils.data import DataLoader

print("=" * 70)
print("V5 RESTORE — DATALOADER + STRUCTURED TARGET AUDIT")
print("=" * 70)


# ------------------------------------------------------------
# 1. Exact V4 vocabularies
# ------------------------------------------------------------

NEGATIVE_VOCAB = [
    "no_abnormal_ent",
    "no_abnormal_external_middle_ear",
    "no_abnormal_nose_sinus",
    "no_bleeding",
    "no_foreign_body",
]

ATTRIBUTE_VOCAB = [
    "acute",
    "bilateral",
    "chronic",
    "left",
    "post_surgery",
    "right",
]

print("\n[VOCABULARY]")
print("Negative:", NEGATIVE_VOCAB)
print("Attribute:", ATTRIBUTE_VOCAB)

assert len(NEGATIVE_VOCAB) == 5
assert len(ATTRIBUTE_VOCAB) == 6


# ------------------------------------------------------------
# 2. Parse persisted V4 vector strings
# ------------------------------------------------------------

def parse_binary_vector(value, expected_len, name):

    if not isinstance(value, str):
        raise ValueError(
            f"{name}: expected string, got {type(value)}"
        )

    parts = value.split(",")

    if len(parts) != expected_len:
        raise ValueError(
            f"{name}: expected {expected_len}, got {len(parts)}"
        )

    vector = np.array(
        [int(x) for x in parts],
        dtype=np.float32
    )

    if not np.isin(vector, [0, 1]).all():
        raise ValueError(
            f"{name}: non-binary values found"
        )

    return vector


# ------------------------------------------------------------
# 3. Build exact structured target dictionaries
# ------------------------------------------------------------

def build_structured_targets(df):

    result = {}

    for _, row in df.iterrows():

        case_id = row["case_id"]

        concept = parse_binary_vector(
            row["concept_vector_str"],
            48,
            "concept_vector_str"
        )

        negative = parse_binary_vector(
            row["negative_vector_str"],
            5,
            "negative_vector_str"
        )

        attribute = parse_binary_vector(
            row["attribute_vector_str"],
            6,
            "attribute_vector_str"
        )

        result[case_id] = {
            "concept_targets": torch.tensor(
                concept,
                dtype=torch.float32
            ),
            "negative_targets": torch.tensor(
                negative,
                dtype=torch.float32
            ),
            "attribute_targets": torch.tensor(
                attribute,
                dtype=torch.float32
            ),
            "structured_loss_mask": float(
                row["structured_loss_mask"]
            ),
        }

    return result


structured_targets_v5 = build_structured_targets(v4_df)


# ------------------------------------------------------------
# 4. Exact target count audit
# ------------------------------------------------------------

print("\n[STRUCTURED TARGETS]")

print(
    "Cases:",
    len(structured_targets_v5)
)

assert len(structured_targets_v5) == 7606

for case_id, target in list(
    structured_targets_v5.items()
)[:3]:

    print(
        case_id,
        "concept=",
        tuple(target["concept_targets"].shape),
        "negative=",
        tuple(target["negative_targets"].shape),
        "attribute=",
        tuple(target["attribute_targets"].shape),
        "mask=",
        target["structured_loss_mask"]
    )

    assert target["concept_targets"].shape == (48,)
    assert target["negative_targets"].shape == (5,)
    assert target["attribute_targets"].shape == (6,)


# ------------------------------------------------------------
# 5. Verify structured labels against persisted counts
# ------------------------------------------------------------

concept_counts = []
negative_counts = []
attribute_counts = []

for _, row in v4_df.iterrows():

    concept = parse_binary_vector(
        row["concept_vector_str"],
        48,
        "concept_vector_str"
    )

    negative = parse_binary_vector(
        row["negative_vector_str"],
        5,
        "negative_vector_str"
    )

    attribute = parse_binary_vector(
        row["attribute_vector_str"],
        6,
        "attribute_vector_str"
    )

    concept_counts.append(int(concept.sum()))
    negative_counts.append(int(negative.sum()))
    attribute_counts.append(int(attribute.sum()))

assert np.array_equal(
    concept_counts,
    v4_df["num_concepts_v2"].to_numpy()
)

assert np.array_equal(
    negative_counts,
    v4_df["num_negative_findings"].to_numpy()
)

assert np.array_equal(
    attribute_counts,
    v4_df["num_attributes_v2"].to_numpy()
)

print("\n[COUNT CONSISTENCY]")
print("PASS: concept vectors match num_concepts_v2.")
print("PASS: negative vectors match num_negative_findings.")
print("PASS: attribute vectors match num_attributes_v2.")


# ------------------------------------------------------------
# 6. DataLoader
# ------------------------------------------------------------

train_loader_v5 = DataLoader(
    train_dataset_v5,
    batch_size=4,
    shuffle=True,
    num_workers=2,
    pin_memory=True,
    collate_fn=collate_v4,
    drop_last=False
)

val_loader_v5 = DataLoader(
    val_dataset_v5,
    batch_size=4,
    shuffle=False,
    num_workers=2,
    pin_memory=True,
    collate_fn=collate_v4,
    drop_last=False
)

test_loader_v5 = DataLoader(
    test_dataset_v5,
    batch_size=4,
    shuffle=False,
    num_workers=2,
    pin_memory=True,
    collate_fn=collate_v4,
    drop_last=False
)


# ------------------------------------------------------------
# 7. Loader size audit
# ------------------------------------------------------------

print("\n[LOADERS]")

print(
    "Train batches:",
    len(train_loader_v5)
)

print(
    "Val batches:",
    len(val_loader_v5)
)

print(
    "Test batches:",
    len(test_loader_v5)
)

assert len(train_loader_v5) == 1535
assert len(val_loader_v5) == 189
assert len(test_loader_v5) == 178


# ------------------------------------------------------------
# 8. Build one real training batch
# ------------------------------------------------------------

print("\n[REAL BATCH AUDIT]")

real_batch = next(iter(train_loader_v5))

print(
    "case_id:",
    real_batch["case_id"]
)

print(
    "pixel_values:",
    tuple(real_batch["pixel_values"].shape),
    real_batch["pixel_values"].dtype
)

print(
    "image_mask:",
    tuple(real_batch["image_mask"].shape),
    real_batch["image_mask"].dtype
)

print(
    "labels:",
    tuple(real_batch["labels"].shape),
    real_batch["labels"].dtype
)

assert real_batch["pixel_values"].shape[0] == 4
assert real_batch["pixel_values"].shape[1] <= 8
assert real_batch["pixel_values"].shape[2:] == (
    3, 224, 224
)

assert real_batch["image_mask"].shape[:2] == (
    4,
    real_batch["pixel_values"].shape[1]
)

assert real_batch["labels"].shape == (4, 96)


# ------------------------------------------------------------
# 9. Structured target lookup audit
# ------------------------------------------------------------

print("\n[STRUCTURED BATCH LOOKUP]")

batch_case_ids = real_batch["case_id"]

concept_targets = torch.stack([
    structured_targets_v5[c]["concept_targets"]
    for c in batch_case_ids
])

negative_targets = torch.stack([
    structured_targets_v5[c]["negative_targets"]
    for c in batch_case_ids
])

attribute_targets = torch.stack([
    structured_targets_v5[c]["attribute_targets"]
    for c in batch_case_ids
])

structured_masks = torch.tensor([
    structured_targets_v5[c]["structured_loss_mask"]
    for c in batch_case_ids
], dtype=torch.float32)


print(
    "concept_targets:",
    tuple(concept_targets.shape)
)

print(
    "negative_targets:",
    tuple(negative_targets.shape)
)

print(
    "attribute_targets:",
    tuple(attribute_targets.shape)
)

print(
    "structured_masks:",
    tuple(structured_masks.shape)
)

assert concept_targets.shape == (4, 48)
assert negative_targets.shape == (4, 5)
assert attribute_targets.shape == (4, 6)
assert structured_masks.shape == (4,)


# ------------------------------------------------------------
# 10. Safety
# ------------------------------------------------------------

print("\n[SAFETY]")
print("PASS: Exact V4 structured vectors used.")
print("PASS: 48 concept targets.")
print("PASS: 5 negative targets.")
print("PASS: 6 attribute targets.")
print("PASS: Vector/count consistency verified.")
print("PASS: Train loader = 1535 batches.")
print("PASS: Val loader = 189 batches.")
print("PASS: Test loader = 178 batches.")
print("PASS: Real batch schema valid.")
print("PASS: No optimizer.")
print("PASS: No backward.")
print("PASS: No training.")

print("\n" + "=" * 70)
print("CELL 9H PASS — send me this output.")
print("=" * 70)

==========================================================================================
CELL INDEX 139 | TYPE=code | CHARS=37922
==========================================================================================
# ============================================================
# V5 — FULL TRAINING FROM PRETRAINED VIT + mT5
# NO V4 WARM START
#
# ONE-CELL:
#   Drive
#   ↓
#   manifests
#   ↓
#   dataset / loaders
#   ↓
#   structured targets
#   ↓
#   optimizer / scheduler
#   ↓
#   checkpoint resume
#   ↓
#   V5 training
#
# CHECKPOINT:
#   every 48 optimizer steps
#   2 rolling checkpoints
#   epoch checkpoints
#   best.pt
#   last.pt
# ============================================================

import os
import gc
import ast
import json
import math
import random
import time
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image

import torch
import torch.nn.functional as F

from torch.utils.data import Dataset, DataLoader, Subset
from transformers import ViTImageProcessor, AutoTokenizer
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR
from tqdm.auto import tqdm


# ============================================================
# 0. DRIVE
# ============================================================

print("=" * 80)
print("V5 — FULL TRAINING")
print("=" * 80)

from google.colab import drive

if not Path("/content/drive/MyDrive").exists():
    drive.mount(
        "/content/drive",
        force_remount=False
    )

DRIVE = Path(
    "/content/drive/MyDrive"
)

assert DRIVE.exists()

print("PASS: Drive mounted.")


# ============================================================
# 1. CONFIG
# ============================================================

SEED = 42

EPOCHS = 5
BATCH_SIZE = 4
GRAD_ACCUM = 4

TRAIN_CASES = 6138
VAL_CASES = 756
TEST_CASES = 712

MAX_IMAGES = 8
IMAGE_SIZE = 224
MAX_TARGET_LENGTH = 96

OPT_STEPS_PER_EPOCH = 384
TOTAL_OPT_STEPS = 1920
WARMUP_STEPS = 96

CHECKPOINT_EVERY = 48

BF16 = True

REPORT_W = 1.0
CONCEPT_W = 0.5
NEGATIVE_W = 0.5
ATTRIBUTE_W = 0.25

device = torch.device("cuda")

assert torch.cuda.is_available()

print(
    "GPU:",
    torch.cuda.get_device_name(0)
)


# ============================================================
# 2. PATHS
# ============================================================

ROOT = (
    DRIVE /
    "NoiSoi_Matching"
)

V4_MANIFEST = (
    ROOT /
    "baseline_model_v4" /
    "v4_training_manifest.csv"
)

IMAGE_MANIFEST = (
    ROOT /
    "final_manifest" /
    "final_dataset_manifest.csv"
)

STRUCTURED_CSV = (
    ROOT /
    "v3_ontology_v2" /
    "v3_structured_targets_v2_2.csv"
)

V5_ROOT = (
    ROOT /
    "baseline_model_v5"
)

CKPT_DIR = (
    V5_ROOT /
    "checkpoints"
)

CKPT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

LAST_CKPT = (
    CKPT_DIR /
    "last.pt"
)

BEST_CKPT = (
    CKPT_DIR /
    "best.pt"
)

ROLLING = [
    CKPT_DIR / "resume_0.pt",
    CKPT_DIR / "resume_1.pt",
]


# ============================================================
# 3. MANIFEST AUDIT
# ============================================================

print("\n" + "=" * 80)
print("[1] MANIFESTS")
print("=" * 80)

assert V4_MANIFEST.exists(), V4_MANIFEST
assert IMAGE_MANIFEST.exists(), IMAGE_MANIFEST
assert STRUCTURED_CSV.exists(), STRUCTURED_CSV

v4_df = pd.read_csv(
    V4_MANIFEST
)

image_df = pd.read_csv(
    IMAGE_MANIFEST
)

structured_df = pd.read_csv(
    STRUCTURED_CSV
)

print(
    "V4 manifest:",
    v4_df.shape
)

print(
    "Image manifest:",
    image_df.shape
)

print(
    "Structured:",
    structured_df.shape
)

assert v4_df.shape[0] == 7606
assert structured_df.shape[0] == 7606


# ============================================================
# 4. EXACT V4 SPLITS
# ============================================================

train_cases = (
    v4_df.loc[
        v4_df["split"] == "train",
        "case_id"
    ]
    .astype(str)
    .tolist()
)

val_cases = (
    v4_df.loc[
        v4_df["split"] == "val",
        "case_id"
    ]
    .astype(str)
    .tolist()
)

test_cases = (
    v4_df.loc[
        v4_df["split"] == "test",
        "case_id"
    ]
    .astype(str)
    .tolist()
)

assert len(train_cases) == 6138
assert len(val_cases) == 756
assert len(test_cases) == 712

train_set = set(train_cases)
val_set = set(val_cases)
test_set = set(test_cases)

print(
    "PASS: Exact V4 split counts:"
)

print(
    " train:",
    len(train_cases)
)

print(
    " val  :",
    len(val_cases)
)

print(
    " test :",
    len(test_cases)
)


# ============================================================
# 5. IMAGE PATH COLUMN
# ============================================================

if "image_path" in image_df.columns:
    IMAGE_COL = "image_path"
elif "pdf_path" in image_df.columns:
    IMAGE_COL = "pdf_path"
else:
    raise RuntimeError(
        "No image_path/pdf_path column."
    )

assert "case_id" in image_df.columns

print(
    "Image column:",
    IMAGE_COL
)


# ============================================================
# 6. NORMAL IMAGE FILTER
# ============================================================

if "image_status" in image_df.columns:

    normal_df = image_df[
        image_df["image_status"]
        .astype(str)
        .str.upper()
        .eq("NORMAL")
    ].copy()

else:

    normal_df = image_df.copy()

print(
    "NORMAL images:",
    len(normal_df)
)


# ============================================================
# 7. BUILD CASE → IMAGES
# EXACT V4 SELECTION POLICY
# ============================================================

case_to_images = {}

for case_id, group in normal_df.groupby(
    "case_id",
    sort=False
):

    case_id = str(case_id)

    rows = group.copy()

    if "image_order" in rows.columns:

        def numeric_order(x):

            try:
                return float(x)
            except Exception:
                return 0

        rows = rows.assign(
            _order=rows["image_order"]
            .map(numeric_order)
        )

        rows = rows.sort_values(
            "_order"
        )

    paths = (
        rows[IMAGE_COL]
        .dropna()
        .astype(str)
        .tolist()
    )

    # Resolve paths if relative
    resolved_paths = []

    for p in paths:

        pp = Path(p)

        if pp.exists():

            resolved_paths.append(
                str(pp)
            )

        else:

            candidates = [
                Path("/content") / p,
                ROOT / p,
            ]

            found = None

            for c in candidates:

                if c.exists():
                    found = c
                    break

            if found is not None:
                resolved_paths.append(
                    str(found)
                )

    # V4 validation/test: first 8
    # Training: random selection >8
    case_to_images[
        case_id
    ] = resolved_paths


# ============================================================
# 8. APPLY V4 SPLIT IMAGE POLICY
# ============================================================

def select_images(
    case_id,
    split,
):

    paths = case_to_images.get(
        str(case_id),
        []
    )

    if len(paths) <= MAX_IMAGES:
        return paths

    if split == "train":

        # Deterministic random selection
        rng = random.Random(
            SEED +
            hash(str(case_id))
            % 1_000_000
        )

        return rng.sample(
            paths,
            MAX_IMAGES
        )

    return paths[:MAX_IMAGES]


selected_train = {
    c: select_images(c, "train")
    for c in train_cases
}

selected_val = {
    c: select_images(c, "val")
    for c in val_cases
}

selected_test = {
    c: select_images(c, "test")
    for c in test_cases
}


assert max(
    len(v)
    for v in selected_train.values()
) <= 8

assert max(
    len(v)
    for v in selected_val.values()
) <= 8

assert max(
    len(v)
    for v in selected_test.values()
) <= 8


print(
    "PASS: max images <= 8."
)


# ============================================================
# 9. PROCESSOR / TOKENIZER
# ============================================================

print("\n" + "=" * 80)
print("[2] PROCESSOR / TOKENIZER")
print("=" * 80)

processor = (
    ViTImageProcessor.from_pretrained(
        "google/vit-base-patch16-224-in21k"
    )
)

tokenizer = (
    AutoTokenizer.from_pretrained(
        "google/mt5-small"
    )
)

print(
    "PASS: ViT processor."
)

print(
    "PASS: mT5 tokenizer."
)


# ============================================================
# 10. TARGET TEXT
# ============================================================

assert "ket_luan" in v4_df.columns

report_map = dict(
    zip(
        v4_df["case_id"].astype(str),
        v4_df["ket_luan"].fillna("").astype(str)
    )
)

assert len(report_map) == 7606

print(
    "PASS: Report target = ket_luan."
)


# ============================================================
# 11. VECTOR PARSER
# ============================================================

def parse_vector(value):

    if value is None:
        return []

    if isinstance(value, float):

In [14]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import inspect
import json
from pathlib import Path

print("=" * 80)
print("V5 — FORWARD PATH AUDIT (READ-ONLY)")
print("=" * 80)

# 1. Find the restored model without assuming its variable name.
model = None
model_name = None

for name in ["model_v5", "v5", "model"]:
    obj = globals().get(name)
    if obj is not None and hasattr(obj, "state_dict"):
        model = obj
        model_name = name
        break

if model is None:
    print("MODEL: No restored model found under model_v5 / v5 / model")
else:
    print("MODEL variable:", model_name)
    print("MODEL class:", type(model).__name__)
    print("MODEL device:", next(model.parameters()).device)
    print("\n--- Exact runtime forward() ---")
    try:
        print(inspect.getsource(type(model).forward))
    except Exception as e:
        print("Runtime source unavailable:", repr(e))

# 2. Report existing test pipeline objects, without creating them.
print("\n--- Existing runtime objects ---")
for name in [
    "test_loader_v5", "test_dataset_v5",
    "test_cases", "selected_test",
    "structured_targets_v5", "processor", "tokenizer"
]:
    obj = globals().get(name)
    if obj is None:
        print(f"{name}: MISSING")
    else:
        try:
            detail = f"type={type(obj).__name__}, len={len(obj)}"
        except Exception:
            detail = f"type={type(obj).__name__}"
        print(f"{name}: {detail}")

# 3. Confirm relevant model modules.
if model is not None:
    print("\n--- Model modules ---")
    for name in [
        "vision", "projector", "conditioner",
        "concept_head", "negative_head",
        "attribute_head", "mt5"
    ]:
        obj = getattr(model, name, None)
        print(f"{name}: {type(obj).__name__ if obj is not None else 'MISSING'}")

print("\nREAD-ONLY AUDIT COMPLETE — no training or checkpoint writes.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
================================================================================
V5 — FORWARD PATH AUDIT (READ-ONLY)
================================================================================
MODEL variable: model_v5
MODEL class: V5Model
MODEL device: cuda:0

--- Exact runtime forward() ---
Runtime source unavailable: OSError('lineno is out of bounds')

--- Existing runtime objects ---
test_loader_v5: MISSING
test_dataset_v5: MISSING
test_cases: MISSING
selected_test: MISSING
structured_targets_v5: MISSING
processor: MISSING
tokenizer: MISSING

--- Model modules ---
vision: ViTModel
projector: Linear
conditioner: SoftStructuredConditioner
concept_head: Linear
negative_head: Linear
attribute_head: Linear
mt5: MT5ForConditionalGeneration

READ-ONLY AUDIT COMPLETE — no training or checkpoint writes.

In [15]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import ast
from pathlib import Path

nb_path = Path("/content/drive/MyDrive/Colab Notebooks/25sep.ipynb")
assert nb_path.exists(), f"Notebook not found: {nb_path}"

import json
with nb_path.open("r", encoding="utf-8") as f:
    nb = json.load(f)

found = False

for idx, cell in enumerate(nb.get("cells", [])):
    if cell.get("cell_type") != "code":
        continue

    src = cell.get("source", [])
    src = "".join(src) if isinstance(src, list) else str(src)

    try:
        tree = ast.parse(src)
    except SyntaxError:
        continue

    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == "V5Model":
            methods = [
                n for n in node.body
                if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))
                and n.name == "forward"
            ]

            if methods:
                method = methods[0]
                print("=" * 80)
                print(f"V5Model.forward() — notebook cell {idx}")
                print("=" * 80)
                print(ast.get_source_segment(src, method))
                found = True
                break

    if found:
        break

assert found, "Could not locate V5Model.forward() in the original notebook."
print("\nREAD-ONLY: no model execution, training, or checkpoint writes.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
================================================================================
V5Model.forward() — notebook cell 81
================================================================================
def forward(
        self,
        pixel_values,
        image_mask,
        labels=None,
        concept_targets=None,
        negative_targets=None,
        attribute_targets=None,
    ):
        B, N, C, H, W = pixel_values.shape

        # ----------------------------------------------------------
        # Flatten images for ViT
        # ----------------------------------------------------------
        x = pixel_values.view(
            B * N,
            C,
            H,
            W
        )

        vision_outputs = self.vision(
            pixel_values=x
        )

        cls = vision_outputs.last_hidden_state[:, 0]
        cls = cls.view(B, N, -1)

        # ----------------------------------------------------------
        # Mask padded images
        # ----------------------------------------------------------
        mask = image_mask.unsqueeze(-1)

        cls = cls * mask

        pooled = cls.sum(dim=1) / mask.sum(
            dim=1
        ).clamp(min=1.0)

        # ----------------------------------------------------------
        # Project visual representation
        # ----------------------------------------------------------
        visual_hidden = self.projector(pooled)

        # ----------------------------------------------------------
        # Structured prediction
        # ----------------------------------------------------------
        concept_logits = self.concept_head(
            visual_hidden
        )

        negative_logits = self.negative_head(
            visual_hidden
        )

        attribute_logits = self.attribute_head(
            visual_hidden
        )

        # ----------------------------------------------------------
        # Soft structured conditioning
        # ----------------------------------------------------------
        structured_tokens = self.conditioner(
            concept_logits,
            negative_logits,
            attribute_logits,
        )

        # ----------------------------------------------------------
        # Visual token
        # ----------------------------------------------------------
        visual_tokens = visual_hidden.unsqueeze(1)

        # ----------------------------------------------------------
        # Decoder conditioning
        # ----------------------------------------------------------
        inputs_embeds = torch.cat(
            [
                visual_tokens,
                structured_tokens,
            ],
            dim=1,
        )

        # ----------------------------------------------------------
        # mT5 decoder
        # ----------------------------------------------------------
        outputs = self.mt5(
            inputs_embeds=inputs_embeds,
            labels=labels,
        )

        return {
            "report_loss": outputs.loss,
            "concept_logits": concept_logits,
            "negative_logits": negative_logits,
            "attribute_logits": attribute_logits,
            "logits": outputs.logits,
            "inputs_embeds": inputs_embeds,
        }

READ-ONLY: no model execution, training, or checkpoint writes.

In [16]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import ast
import json
import numpy as np
import pandas as pd
import torch

from pathlib import Path
from PIL import Image
from torch.utils.data import Dataset, DataLoader
from transformers import ViTImageProcessor

print("=" * 80)
print("V5 STRUCTURED-HEAD TEST EVALUATION — READ ONLY")
print("=" * 80)

# ------------------------------------------------------------
# 1. Validate restored model; do not reload or modify checkpoint
# ------------------------------------------------------------
assert "model_v5" in globals(), "model_v5 is missing."
model = model_v5

for name in [
    "vision", "projector", "concept_head",
    "negative_head", "attribute_head"
]:
    assert hasattr(model, name), f"Missing model module: {name}"

device = next(model.parameters()).device
assert device.type == "cuda", f"Expected CUDA model, got {device}"

model.eval()
print("Model:", type(model).__name__)
print("Device:", device)
print("Mode: eval; no optimizer; no training")

# ------------------------------------------------------------
# 2. Load the exact persisted manifests and structured targets
# ------------------------------------------------------------
ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")

V4_MANIFEST = ROOT / "baseline_model_v4/v4_training_manifest.csv"
IMAGE_MANIFEST = ROOT / "final_manifest/final_dataset_manifest.csv"
STRUCTURED_CSV = ROOT / "v3_ontology_v2/v3_structured_targets_v2_2.csv"
ONTOLOGY_CSV = ROOT / "baseline_model_v4/diagnostics/frozen_concept_ontology_mapping.csv"

for p in [V4_MANIFEST, IMAGE_MANIFEST, STRUCTURED_CSV]:
    assert p.exists(), f"Required file missing: {p}"

v4_df = pd.read_csv(V4_MANIFEST)
image_df = pd.read_csv(IMAGE_MANIFEST)
structured_df = pd.read_csv(STRUCTURED_CSV)

assert len(v4_df) == 7606
assert len(structured_df) == 7606

test_cases = (
    v4_df.loc[v4_df["split"].astype(str).eq("test"), "case_id"]
    .astype(str).tolist()
)
assert len(test_cases) == 712
assert len(set(test_cases)) == 712

print("\nManifest rows:", len(v4_df))
print("Test cases:", len(test_cases))
print("Image manifest rows:", len(image_df))

# ------------------------------------------------------------
# 3. Reproduce original NORMAL-image selection for test
# ------------------------------------------------------------
assert "case_id" in image_df.columns

IMAGE_COL = (
    "image_path" if "image_path" in image_df.columns
    else "pdf_path" if "pdf_path" in image_df.columns
    else None
)
assert IMAGE_COL is not None, "No image_path/pdf_path column."

if "image_status" in image_df.columns:
    normal_df = image_df[
        image_df["image_status"].astype(str).str.upper().eq("NORMAL")
    ].copy()
else:
    normal_df = image_df.copy()

def numeric_order(x):
    try:
        return float(x)
    except Exception:
        return 0.0

case_to_images = {}

for case_id, group in normal_df.groupby("case_id", sort=False):
    case_id = str(case_id)
    rows = group.copy()

    if "image_order" in rows.columns:
        rows["_order"] = rows["image_order"].map(numeric_order)
        rows = rows.sort_values("_order")

    paths = rows[IMAGE_COL].dropna().astype(str).tolist()
    resolved = []

    for p in paths:
        pp = Path(p)

        if pp.exists():
            resolved.append(str(pp))
            continue

        candidates = [Path("/content") / p, ROOT / p]
        match = next((c for c in candidates if c.exists()), None)

        if match is not None:
            resolved.append(str(match))

    case_to_images[case_id] = resolved[:8]

missing_images = [
    c for c in test_cases
    if not case_to_images.get(c)
]

print("\nNORMAL images:", len(normal_df))
print("Test cases without usable image paths:", len(missing_images))

if missing_images:
    print("Examples:", missing_images[:10])
    raise RuntimeError(
        "Some test cases have no resolved NORMAL images. "
        "Stopping rather than silently changing the test set."
    )

# ------------------------------------------------------------
# 4. Load the same ViT image processor used by training
# ------------------------------------------------------------
processor = ViTImageProcessor.from_pretrained(
    "google/vit-base-patch16-224-in21k"
)

class StructuredTestDataset(Dataset):
    def __init__(self, case_ids, image_map, processor):
        self.case_ids = list(case_ids)
        self.image_map = image_map
        self.processor = processor

    def __len__(self):
        return len(self.case_ids)

    def __getitem__(self, idx):
        case_id = self.case_ids[idx]
        images = []

        for path in self.image_map[case_id]:
            try:
                with Image.open(path) as im:
                    images.append(im.convert("RGB").copy())
            except Exception as e:
                raise RuntimeError(
                    f"Image read failed for case={case_id}, "
                    f"path={path}: {e}"
                )

        if not images:
            raise RuntimeError(f"No images for case {case_id}")

        pixels = self.processor(
            images=images,
            return_tensors="pt"
        )["pixel_values"]

        return {"case_id": case_id, "pixel_values": pixels}

def collate_test(batch):
    B = len(batch)
    max_n = max(item["pixel_values"].shape[0] for item in batch)

    pixels = torch.zeros(B, max_n, 3, 224, 224, dtype=torch.float32)
    mask = torch.zeros(B, max_n, dtype=torch.float32)
    case_ids = []

    for i, item in enumerate(batch):
        n = item["pixel_values"].shape[0]
        pixels[i, :n] = item["pixel_values"]
        mask[i, :n] = 1.0
        case_ids.append(item["case_id"])

    return {
        "case_id": case_ids,
        "pixel_values": pixels,
        "image_mask": mask
    }

test_dataset = StructuredTestDataset(test_cases, case_to_images, processor)
test_loader = DataLoader(
    test_dataset,
    batch_size=4,
    shuffle=False,
    num_workers=2,
    pin_memory=True,
    collate_fn=collate_test
)

assert len(test_dataset) == 712
assert len(test_loader) == 178

print("Test dataset:", len(test_dataset))
print("Test batches:", len(test_loader))

# ------------------------------------------------------------
# 5. Parse structured ground truth in persisted vector order
# ------------------------------------------------------------
def parse_vector(value):
    if value is None:
        return []

    if isinstance(value, float) and np.isnan(value):
        return []

    s = str(value).strip()
    if not s:
        return []

    try:
        obj = ast.literal_eval(s)
        if isinstance(obj, (list, tuple, np.ndarray)):
            return [float(x) for x in obj]
    except Exception:
        pass

    try:
        obj = json.loads(s)
        if isinstance(obj, list):
            return [float(x) for x in obj]
    except Exception:
        pass

    s = s.replace("[", "").replace("]", "")
    try:
        return [float(x.strip()) for x in s.split(",") if x.strip()]
    except Exception:
        return []

required = [
    "case_id", "concept_vector_str",
    "negative_vector_str", "attribute_vector_str"
]
assert all(c in structured_df.columns for c in required)

structured_df["case_id"] = structured_df["case_id"].astype(str)
assert structured_df["case_id"].is_unique

target_map = {}
for _, row in structured_df.iterrows():
    c = row["case_id"]
    concept = parse_vector(row["concept_vector_str"])
    negative = parse_vector(row["negative_vector_str"])
    attribute = parse_vector(row["attribute_vector_str"])

    if (len(concept), len(negative), len(attribute)) != (48, 5, 6):
        raise ValueError(
            f"Invalid target dimensions for {c}: "
            f"{len(concept)}, {len(negative)}, {len(attribute)}"
        )

    target_map[c] = (
        np.asarray(concept, dtype=np.float32),
        np.asarray(negative, dtype=np.float32),
        np.asarray(attribute, dtype=np.float32)
    )

assert all(c in target_map for c in test_cases)

y_concept = np.stack([target_map[c][0] for c in test_cases])
y_negative = np.stack([target_map[c][1] for c in test_cases])
y_attribute = np.stack([target_map[c][2] for c in test_cases])

assert y_concept.shape == (712, 48)
assert y_negative.shape == (712, 5)
assert y_attribute.shape == (712, 6)

# ------------------------------------------------------------
# 6. Exact structured path from V5Model.forward()
#    Deliberately bypass mT5; no labels/decoder required.
# ------------------------------------------------------------
pred_concept, pred_negative, pred_attribute = [], [], []
evaluated_ids = []

with torch.inference_mode():
    for batch_idx, batch in enumerate(test_loader):
        pixels = batch["pixel_values"].to(device, non_blocking=True)
        image_mask = batch["image_mask"].to(device, non_blocking=True)

        B, N, C, H, W = pixels.shape
        flat = pixels.reshape(B * N, C, H, W)

        with torch.autocast(
            device_type="cuda",
            dtype=torch.bfloat16,
            enabled=(device.type == "cuda")
        ):
            vision_outputs = model.vision(pixel_values=flat)
            cls = vision_outputs.last_hidden_state[:, 0]
            cls = cls.reshape(B, N, -1)

            mask = image_mask.unsqueeze(-1)
            cls = cls * mask
            pooled = cls.sum(dim=1) / mask.sum(dim=1).clamp(min=1.0)

            visual_hidden = model.projector(pooled)

            concept_logits = model.concept_head(visual_hidden)
            negative_logits = model.negative_head(visual_hidden)
            attribute_logits = model.attribute_head(visual_hidden)

        pred_concept.append(torch.sigmoid(concept_logits.float()).cpu().numpy())
        pred_negative.append(torch.sigmoid(negative_logits.float()).cpu().numpy())
        pred_attribute.append(torch.sigmoid(attribute_logits.float()).cpu().numpy())
        evaluated_ids.extend(batch["case_id"])

        if (batch_idx + 1) % 25 == 0 or (batch_idx + 1) == len(test_loader):
            print(f"Evaluated batches: {batch_idx + 1}/{len(test_loader)}")

p_concept = np.concatenate(pred_concept)
p_negative = np.concatenate(pred_negative)
p_attribute = np.concatenate(pred_attribute)

assert evaluated_ids == test_cases, "Test case order/identity mismatch."
assert p_concept.shape == (712, 48)
assert p_negative.shape == (712, 5)
assert p_attribute.shape == (712, 6)

# ------------------------------------------------------------
# 7. Threshold 0.5 metrics: per-label + group summaries
# ------------------------------------------------------------
def metrics_for_group(y, p, names, group_name, threshold=0.5):
    y = y.astype(np.int32)
    pred = (p >= threshold).astype(np.int32)

    tp = ((y == 1) & (pred == 1)).sum(axis=0)
    fp = ((y == 0) & (pred == 1)).sum(axis=0)
    fn = ((y == 1) & (pred == 0)).sum(axis=0)
    support = y.sum(axis=0)

    precision = np.divide(
        tp, tp + fp, out=np.zeros_like(tp, dtype=float), where=(tp + fp) > 0
    )
    recall = np.divide(
        tp, tp + fn, out=np.zeros_like(tp, dtype=float), where=(tp + fn) > 0
    )
    f1 = np.divide(
        2 * precision * recall,
        precision + recall,
        out=np.zeros_like(precision),
        where=(precision + recall) > 0
    )

    total_tp, total_fp, total_fn = tp.sum(), fp.sum(), fn.sum()
    micro_p = total_tp / (total_tp + total_fp) if total_tp + total_fp else 0.0
    micro_r = total_tp / (total_tp + total_fn) if total_tp + total_fn else 0.0
    micro_f1 = (
        2 * micro_p * micro_r / (micro_p + micro_r)
        if micro_p + micro_r else 0.0
    )

    active = support > 0
    summary = {
        "group": group_name,
        "labels": y.shape[1],
        "positive_label_count": int(active.sum()),
        "micro_precision": micro_p,
        "micro_recall": micro_r,
        "micro_f1": micro_f1,
        "macro_f1_all_labels": float(f1.mean()),
        "macro_f1_labels_with_positives": (
            float(f1[active].mean()) if active.any() else 0.0
        ),
        "ground_truth_positives": int(y.sum()),
        "predicted_positives": int(pred.sum()),
    }

    per_label = pd.DataFrame({
        "group": group_name,
        "label_index": np.arange(y.shape[1]),
        "ground_truth_positives": support,
        "predicted_positives": pred.sum(axis=0),
        "TP": tp,
        "FP": fp,
        "FN": fn,
        "precision": precision,
        "recall": recall,
        "F1": f1,
    })

    return summary, per_label

# Keep vector indices explicit; ontology mapping is audited separately below.
concept_names = [f"concept_{i:02d}" for i in range(48)]
negative_names = [
    "no_abnormal_ent",
    "no_abnormal_external_middle_ear",
    "no_abnormal_nose_sinus",
    "no_bleeding",
    "no_foreign_body",
]
attribute_names = [
    "acute", "bilateral", "chronic", "left", "post_surgery", "right"
]

summaries, per_label_tables = [], []

for group_name, y, p, names in [
    ("concept", y_concept, p_concept, concept_names),
    ("negative", y_negative, p_negative, negative_names),
    ("attribute", y_attribute, p_attribute, attribute_names),
]:
    summary, per_label = metrics_for_group(y, p, names, group_name)
    summaries.append(summary)
    per_label["label"] = [names[i] for i in per_label["label_index"]]
    per_label_tables.append(per_label)

print("\n" + "=" * 80)
print("GROUP SUMMARY — threshold = 0.50")
print("=" * 80)
print(pd.DataFrame(summaries).round(4).to_string(index=False))

print("\n" + "=" * 80)
print("PER-LABEL METRICS")
print("=" * 80)
all_per_label = pd.concat(per_label_tables, ignore_index=True)
print(
    all_per_label[
        ["group", "label", "ground_truth_positives", "predicted_positives",
         "TP", "FP", "FN", "precision", "recall", "F1"]
    ].round(4).to_string(index=False)
)

# Show mapping schema so concept indices can be translated safely later.
if ONTOLOGY_CSV.exists():
    ontology = pd.read_csv(ONTOLOGY_CSV)
    print("\n" + "=" * 80)
    print("FROZEN ONTOLOGY MAPPING — schema/sample only")
    print("=" * 80)
    print("Shape:", ontology.shape)
    print("Columns:", ontology.columns.tolist())
    print(ontology.head(8).to_string(index=False))
else:
    print("\nOntology mapping file not found; concept labels remain indexed.")

print("\nPASS: 712 test cases evaluated.")
print("PASS: 48 concept + 5 negative + 6 attribute logits evaluated.")
print("PASS: No training, optimizer step, or checkpoint write.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
================================================================================
V5 STRUCTURED-HEAD TEST EVALUATION — READ ONLY
================================================================================
Model: V5Model
Device: cuda:0
Mode: eval; no optimizer; no training

/tmp/ipykernel_694/1696204890.py:53: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  image_df = pd.read_csv(IMAGE_MANIFEST)

Manifest rows: 7606
Test cases: 712
Image manifest rows: 76405

NORMAL images: 76216
Test cases without usable image paths: 0

preprocessor_config.json:   0%|          | 0.00/160 [00:00<?, ?B/s]

Test dataset: 712
Test batches: 178

AssertionError:

In [17]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import os
import pandas as pd

print("=" * 80)
print("STRUCTURED TARGET SCHEMA CHECK — READ ONLY")
print("=" * 80)

print("STRUCTURED_CSV:", STRUCTURED_CSV)
print("File exists:", os.path.isfile(STRUCTURED_CSV))

if os.path.isfile(STRUCTURED_CSV):
    schema_df = pd.read_csv(STRUCTURED_CSV, nrows=5, low_memory=False)

    print("\nColumns actually present:")
    for i, col in enumerate(schema_df.columns):
        print(f"{i:02d}. {col!r}")

    print("\nColumns required by the evaluation cell:")
    required = [
        "case_id",
        "concept_vector_str",
        "negative_vector_str",
        "attribute_vector_str",
    ]
    for col in required:
        print(f"{col}: {'FOUND' if col in schema_df.columns else 'MISSING'}")

    print("\nFirst 3 rows:")
    display(schema_df.head(3))

    print("\nExisting structured_df in memory:")
    if "structured_df" in globals():
        print("Shape:", structured_df.shape)
        print("Columns:", structured_df.columns.tolist())
    else:
        print("No structured_df variable currently exists.")
else:
    print("ERROR: The configured structured-target CSV path does not exist.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
================================================================================
STRUCTURED TARGET SCHEMA CHECK — READ ONLY
================================================================================
STRUCTURED_CSV: /content/drive/MyDrive/NoiSoi_Matching/v3_ontology_v2/v3_structured_targets_v2_2.csv
File exists: True

Columns actually present:
00. 'case_id'
01. 'patient_group_id'
02. 'split'
03. 'pdf_path'
04. 'ho_ten'
05. 'nam_sinh'
06. 'gioi_tinh_clean'
07. 'ly_do_noi_soi'
08. 'tai'
09. 'hoc_mui'
10. 'hong_mui'
11. 'hong_thanh_quan'
12. 'hong_mieng'
13. 'ket_luan'
14. 'phan_biet'
15. 'de_nghi'
16. 'target_norm'
17. 'concepts'
18. 'attributes'
19. 'num_concepts'
20. 'num_attributes'
21. 'concept__viem_ong_tai_ngoai'
22. 'concept__nhot_ong_tai_ngoai'
23. 'concept__chan_thuong_ong_tai_ngoai'
24. 'concept__viem_tai_giua'
25. 'concept__viem_mang_nhi'
26. 'concept__thung_mang_nhi'
27. 'concept__xep_mang_nhi'
28. 'concept__ray_tai'
29. 'concept__viem_tai_xuong_chum'
30. 'concept__hau_phau_va_nhi'
31. 'concept__di_vat_tai'
32. 'concept__viem_mui'
33. 'concept__viem_mui_xoang'
34. 'concept__viem_xoang'
35. 'concept__polyp_mui'
36. 'concept__chay_mau_mui'
37. 'concept__dich_vat_mui'
38. 'concept__hoc_xuong_ca'
39. 'concept__di_vat_hong_thanh_quan'
40. 'concept__di_vat'
41. 'concept__hau_phau_mui_xoang'
42. 'concept__tien_dinh_mui'
43. 'concept__lech_vach_ngan'
44. 'concept__viem_va'
45. 'concept__qua_phat_va'
46. 'concept__viem_amidan'
47. 'concept__amidan_qua_phat'
48. 'concept__viem_hong'
49. 'concept__viem_mieng'
50. 'concept__viem_luoi'
51. 'concept__ap_to_mieng'
52. 'concept__viem_thanh_quan'
53. 'concept__hat_day_thanh'
54. 'concept__polyp_day_thanh'
55. 'concept__liet_day_thanh'
56. 'concept__theo_doi_trao_nguoc'
57. 'concept__khong_thay_benh_ly_tai'
58. 'concept__khong_thay_benh_ly'
59. 'concept__khong_thay_diem_chay_mau'
60. 'concept__khong_thay_di_vat'
61. 'attribute__acute'
62. 'attribute__chronic'
63. 'attribute__right'
64. 'attribute__left'
65. 'attribute__bilateral'
66. 'attribute__post_surgery'
67. 'has_concept'
68. 'has_attribute'
69. 'ambiguity_reason'
70. 'concept_signature'
71. 'concepts_str'
72. 'attributes_str'
73. 'concepts_v2'
74. 'negative_findings'
75. 'attributes_v2'
76. 'concept__hep_ong_tai_ngoai'
77. 'concept__polyp_ong_tai_ngoai'
78. 'concept__chan_thuong_mang_nhi'
79. 'concept__viem_vanh_tai'
80. 'concept__tu_dich_vanh_tai'
81. 'concept__ro_luan_nhi'
82. 'concept__not_vanh_tai'
83. 'concept__u_hoc_mui'
84. 'concept__u_nhu_hoc_mui'
85. 'concept__u_nhu_cuon_mui'
86. 'concept__u_xoang'
87. 'concept__seo_hoc_mui'
88. 'concept__nang_day_thanh'
89. 'concept__di_vat_hong'
90. 'negative__no_abnormal_external_middle_ear'
91. 'negative__no_abnormal_nose_sinus'
92. 'negative__no_abnormal_ent'
93. 'negative__no_bleeding'
94. 'negative__no_foreign_body'
95. 'concepts_v2_str'
96. 'negative_findings_str'
97. 'attributes_v2_str'
98. 'num_concepts_v2'
99. 'num_negative_findings'
100. 'num_attributes_v2'
101. 'has_structured_label'

Columns required by the evaluation cell:
case_id: FOUND
concept_vector_str: MISSING
negative_vector_str: MISSING
attribute_vector_str: MISSING

First 3 rows:

,case_id,patient_group_id,split,pdf_path,ho_ten,nam_sinh,gioi_tinh_clean,ly_do_noi_soi,tai,hoc_mui,...,negative__no_abnormal_ent,negative__no_bleeding,negative__no_foreign_body,concepts_v2_str,negative_findings_str,attributes_v2_str,num_concepts_v2,num_negative_findings,num_attributes_v2,has_structured_label
0,10000.10000.0.10014,NGUYEN TRUONG TAN SANG_2015,train,/content/drive/MyDrive/Hồ sơ bệnh/Hình nội soi...,NGUYỄN TRƯƠNG TẤN SANG,2015,NAM,HỈ MŨI LỎNG,NaN,"Cuốn mũi: hồng, xuất tiết nhầy trong. Khe mũi:...",...,0,0,0,viem_mui,NaN,chronic,1,0,1,True
1,10001.10001.0.10015,INARI ANH TUAN_2014,train,/content/drive/MyDrive/Hồ sơ bệnh/Hình nội soi...,INARI ANH TUẤN,2014,NAM,ĐAU TAI BÊN TRÁI,P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.,Cuốn mũi: xuất tiết nhầy trắng Khe mũi: thoáng...,...,0,0,0,viem_mui,NaN,NaN,1,0,0,True
2,10002.10002.0.10016,BUI NGOC BAO CHAU_2016,train,/content/drive/MyDrive/Hồ sơ bệnh/Hình nội soi...,BÙI NGỌC BẢO CHÂU,2016,NỮ,CHẢY MŨI LỎNG,NaN,"Cuốn mũi: nhợt, gồ ghề nhẹ, xuất tiết nhầy trắ...",...,0,0,0,viem_mui,NaN,chronic,1,0,1,True

Existing structured_df in memory:
Shape: (7606, 102)
Columns: ['case_id', 'patient_group_id', 'split', 'pdf_path', 'ho_ten', 'nam_sinh', 'gioi_tinh_clean', 'ly_do_noi_soi', 'tai', 'hoc_mui', 'hong_mui', 'hong_thanh_quan', 'hong_mieng', 'ket_luan', 'phan_biet', 'de_nghi', 'target_norm', 'concepts', 'attributes', 'num_concepts', 'num_attributes', 'concept__viem_ong_tai_ngoai', 'concept__nhot_ong_tai_ngoai', 'concept__chan_thuong_ong_tai_ngoai', 'concept__viem_tai_giua', 'concept__viem_mang_nhi', 'concept__thung_mang_nhi', 'concept__xep_mang_nhi', 'concept__ray_tai', 'concept__viem_tai_xuong_chum', 'concept__hau_phau_va_nhi', 'concept__di_vat_tai', 'concept__viem_mui', 'concept__viem_mui_xoang', 'concept__viem_xoang', 'concept__polyp_mui', 'concept__chay_mau_mui', 'concept__dich_vat_mui', 'concept__hoc_xuong_ca', 'concept__di_vat_hong_thanh_quan', 'concept__di_vat', 'concept__hau_phau_mui_xoang', 'concept__tien_dinh_mui', 'concept__lech_vach_ngan', 'concept__viem_va', 'concept__qua_phat_va', 'concept__viem_amidan', 'concept__amidan_qua_phat', 'concept__viem_hong', 'concept__viem_mieng', 'concept__viem_luoi', 'concept__ap_to_mieng', 'concept__viem_thanh_quan', 'concept__hat_day_thanh', 'concept__polyp_day_thanh', 'concept__liet_day_thanh', 'concept__theo_doi_trao_nguoc', 'concept__khong_thay_benh_ly_tai', 'concept__khong_thay_benh_ly', 'concept__khong_thay_diem_chay_mau', 'concept__khong_thay_di_vat', 'attribute__acute', 'attribute__chronic', 'attribute__right', 'attribute__left', 'attribute__bilateral', 'attribute__post_surgery', 'has_concept', 'has_attribute', 'ambiguity_reason', 'concept_signature', 'concepts_str', 'attributes_str', 'concepts_v2', 'negative_findings', 'attributes_v2', 'concept__hep_ong_tai_ngoai', 'concept__polyp_ong_tai_ngoai', 'concept__chan_thuong_mang_nhi', 'concept__viem_vanh_tai', 'concept__tu_dich_vanh_tai', 'concept__ro_luan_nhi', 'concept__not_vanh_tai', 'concept__u_hoc_mui', 'concept__u_nhu_hoc_mui', 'concept__u_nhu_cuon_mui', 'concept__u_xoang', 'concept__seo_hoc_mui', 'concept__nang_day_thanh', 'concept__di_vat_hong', 'negative__no_abnormal_external_middle_ear', 'negative__no_abnormal_nose_sinus', 'negative__no_abnormal_ent', 'negative__no_bleeding', 'negative__no_foreign_body', 'concepts_v2_str', 'negative_findings_str', 'attributes_v2_str', 'num_concepts_v2', 'num_negative_findings', 'num_attributes_v2', 'has_structured_label']

In [18]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import json, os, re

print("=" * 80)
print("V5 LABEL-ORDER AUDIT — READ ONLY")
print("=" * 80)

# 1. Actual head dimensions
for name in ["concept_head", "negative_head", "attribute_head"]:
    head = getattr(model_v5, name, None)
    if head is None:
        print(f"{name}: NOT FOUND on model_v5")
    else:
        print(f"{name}: out_features={getattr(head, 'out_features', 'unknown')}")

# 2. Candidate labels in the structured target CSV
for prefix in ["concept__", "negative__", "attribute__"]:
    cols = [c for c in structured_df.columns if c.startswith(prefix)]
    print(f"\n{prefix} ({len(cols)} columns):")
    print(cols)

# 3. Check whether the training label-order variables remain in memory
print("\n" + "=" * 80)
print("LABEL VARIABLES STILL IN MEMORY")
print("=" * 80)

for name in sorted(globals()):
    if re.search(r"(concept|negative|attribute).*(cols|columns|vocab|labels|names|keys|targets)", name, re.I):
        value = globals()[name]
        if isinstance(value, (list, tuple)):
            print(f"{name}: length={len(value)}; values={list(value)[:70]}")
        elif hasattr(value, "shape"):
            print(f"{name}: shape={value.shape}")
        else:
            print(f"{name}: type={type(value).__name__}")

# 4. Inspect the original notebook cell containing V5 training code
notebook_path = "/content/drive/MyDrive/Colab Notebooks/25sep.ipynb"
print("\nNotebook exists:", os.path.isfile(notebook_path))

if os.path.isfile(notebook_path):
    with open(notebook_path, "r", encoding="utf-8") as f:
        nb = json.load(f)

    for idx, cell in enumerate(nb.get("cells", [])):
        src = "".join(cell.get("source", []))
        if cell.get("cell_type") == "code" and (
            "class V5Dataset" in src or "class V5Model" in src
        ):
            print(f"\n--- Notebook cell {idx}: relevant label/target lines ---")
            lines = src.splitlines()
            patterns = re.compile(
                r"concept.*(col|vocab|label|target|vector)|"
                r"negative.*(col|vocab|label|target|vector)|"
                r"attribute.*(col|vocab|label|target|vector)|"
                r"structured_df|parse_vector|concept_head|negative_head|attribute_head",
                re.I
            )
            hits = [i for i, line in enumerate(lines) if patterns.search(line)]
            shown = set()
            for i in hits:
                for j in range(max(0, i-2), min(len(lines), i+3)):
                    if j not in shown:
                        print(f"{j+1:04d}: {lines[j]}")
                        shown.add(j)
                print("...")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
================================================================================
V5 LABEL-ORDER AUDIT — READ ONLY
================================================================================
concept_head: out_features=48
negative_head: out_features=5
attribute_head: out_features=6

concept__ (54 columns):
['concept__viem_ong_tai_ngoai', 'concept__nhot_ong_tai_ngoai', 'concept__chan_thuong_ong_tai_ngoai', 'concept__viem_tai_giua', 'concept__viem_mang_nhi', 'concept__thung_mang_nhi', 'concept__xep_mang_nhi', 'concept__ray_tai', 'concept__viem_tai_xuong_chum', 'concept__hau_phau_va_nhi', 'concept__di_vat_tai', 'concept__viem_mui', 'concept__viem_mui_xoang', 'concept__viem_xoang', 'concept__polyp_mui', 'concept__chay_mau_mui', 'concept__dich_vat_mui', 'concept__hoc_xuong_ca', 'concept__di_vat_hong_thanh_quan', 'concept__di_vat', 'concept__hau_phau_mui_xoang', 'concept__tien_dinh_mui', 'concept__lech_vach_ngan', 'concept__viem_va', 'concept__qua_phat_va', 'concept__viem_amidan', 'concept__amidan_qua_phat', 'concept__viem_hong', 'concept__viem_mieng', 'concept__viem_luoi', 'concept__ap_to_mieng', 'concept__viem_thanh_quan', 'concept__hat_day_thanh', 'concept__polyp_day_thanh', 'concept__liet_day_thanh', 'concept__theo_doi_trao_nguoc', 'concept__khong_thay_benh_ly_tai', 'concept__khong_thay_benh_ly', 'concept__khong_thay_diem_chay_mau', 'concept__khong_thay_di_vat', 'concept__hep_ong_tai_ngoai', 'concept__polyp_ong_tai_ngoai', 'concept__chan_thuong_mang_nhi', 'concept__viem_vanh_tai', 'concept__tu_dich_vanh_tai', 'concept__ro_luan_nhi', 'concept__not_vanh_tai', 'concept__u_hoc_mui', 'concept__u_nhu_hoc_mui', 'concept__u_nhu_cuon_mui', 'concept__u_xoang', 'concept__seo_hoc_mui', 'concept__nang_day_thanh', 'concept__di_vat_hong']

negative__ (5 columns):
['negative__no_abnormal_external_middle_ear', 'negative__no_abnormal_nose_sinus', 'negative__no_abnormal_ent', 'negative__no_bleeding', 'negative__no_foreign_body']

attribute__ (6 columns):
['attribute__acute', 'attribute__chronic', 'attribute__right', 'attribute__left', 'attribute__bilateral', 'attribute__post_surgery']

================================================================================
LABEL VARIABLES STILL IN MEMORY
================================================================================

Notebook exists: True

--- Notebook cell 8: relevant label/target lines ---
0059:         )
0060:
0061:         self.concept_label = nn.Embedding(
0062:             num_concepts, d_model
0063:         )
...
0064:
0065:         self.negative_label = nn.Embedding(
0066:             num_negative, d_model
0067:         )
...
0068:
0069:         self.attribute_label = nn.Embedding(
0070:             num_attributes, d_model
0071:         )
...
0127:         )
0128:
0129:         concept_label = self.concept_label(
0130:             concept_idx
0131:         )[None, :, :]
...
0141:         concept_tokens = (
0142:             concept_value
0143:             + concept_label
0144:             + concept_type
0145:         )
...
0159:         )
0160:
0161:         negative_label = self.negative_label(
0162:             negative_idx
0163:         )[None, :, :]
...
0173:         negative_tokens = (
0174:             negative_value
0175:             + negative_label
0176:             + negative_type
0177:         )
...
0191:         )
0192:
0193:         attribute_label = self.attribute_label(
0194:             attribute_idx
0195:         )[None, :, :]
...
0206:         attribute_tokens = (
0207:             attribute_value
0208:             + attribute_label
0209:             + attribute_type
0210:         )
...

--- Notebook cell 76: relevant label/target lines ---

--- Notebook cell 77: relevant label/target lines ---

--- Notebook cell 78: relevant label/target lines ---

--- Notebook cell 81: relevant label/target lines ---
0120:
0121:         # Structured prediction heads
0122:         self.concept_head = nn.Linear(512, 48)
0123:         self.negative_head = nn.Linear(512, 5)
0124:         self.attribute_head = nn.Linear(512, 6)
...
0125:
...
0126:         # Soft structured conditioning
...
0137:         image_mask,
0138:         labels=None,
0139:         concept_targets=None,
0140:         negative_targets=None,
0141:         attribute_targets=None,
...
0142:     ):
...
0143:         B, N, C, H, W = pixel_values.shape
...
0179:         # Structured prediction
0180:         # ----------------------------------------------------------
0181:         concept_logits = self.concept_head(
0182:             visual_hidden
0183:         )
...
0184:
0185:         negative_logits = self.negative_head(
0186:             visual_hidden
0187:         )
...
0188:
0189:         attribute_logits = self.attribute_head(
0190:             visual_hidden
0191:         )
...
0261:     "projector": hasattr(v5, "projector"),
0262:     "conditioner": hasattr(v5, "conditioner"),
0263:     "concept_head": hasattr(v5, "concept_head"),
0264:     "negative_head": hasattr(v5, "negative_head"),
0265:     "attribute_head": hasattr(v5, "attribute_head"),
...
0266: }
...
0267:
...
0287: print(
0288:     "concept:",
0289:     tuple(v5.concept_head.weight.shape)
0290: )
0291: print(
...
0292:     "negative:",
0293:     tuple(v5.negative_head.weight.shape)
0294: )
0295: print(
...
0296:     "attribute:",
0297:     tuple(v5.attribute_head.weight.shape)
0298: )
0299:
...
0300: assert tuple(v5.concept_head.weight.shape) == (48, 512)
0301: assert tuple(v5.negative_head.weight.shape) == (5, 512)
0302: assert tuple(v5.attribute_head.weight.shape) == (6, 512)
...
0303:
...
0304: # Conditioner
...

--- Notebook cell 98: relevant label/target lines ---
0332:     "projector",
0333:     "conditioner",
0334:     "concept_head",
0335:     "negative_head",
0336:     "attribute_head",
...
0337: ]
...
0338:
...

--- Notebook cell 99: relevant label/target lines ---
0069:     "self.projector = Projector",
0070:     "self.conditioner = SoftStructuredConditioner",
0071:     "self.concept_head",
0072:     "self.negative_head",
0073:     "self.attribute_head",
...
0074: ]
...
0075:
...
0107:
0108: head_markers = [
0109:     "self.concept_head",
0110:     "self.negative_head",
0111:     "self.attribute_head",
...
0112: ]
...
0113:
...
0259:     "projector",
0260:     "conditioner",
0261:     "concept_head",
0262:     "negative_head",
0263:     "attribute_head",
...
0264: ]
...
0265:
...
0301:
0302: print(
0303:     "concept_head:",
0304:     tuple(
0305:         v5.concept_head.weight.shape
...
0306:     )
0307: )
...
0308:
0309: print(
0310:     "negative_head:",
0311:     tuple(
0312:         v5.negative_head.weight.shape
...
0313:     )
0314: )
...
0315:
0316: print(
0317:     "attribute_head:",
0318:     tuple(
0319:         v5.attribute_head.weight.shape
...
0320:     )
0321: )
...
0330:
0331: if tuple(
0332:     v5.concept_head.weight.shape
0333: ) != (48, 512):
0334:
...
0338:
0339: if tuple(
0340:     v5.negative_head.weight.shape
0341: ) != (5, 512):
0342:
...
0346:
0347: if tuple(
0348:     v5.attribute_head.weight.shape
0349: ) != (6, 512):
0350:
...

--- Notebook cell 100: relevant label/target lines ---
0027:
0028: patterns = [
0029:     "concept_head",
0030:     "negative_head",
0031:     "attribute_head",
...
0032:     "structured_heads",
...
0033: ]
...
0081: candidate_cells = sorted(
0082:     set(
0083:         matches["concept_head"]
0084:         + matches["negative_head"]
0085:         + matches["attribute_head"]
...
0086:         + matches["structured_heads"]
...
0087:     )
...

--- Notebook cell 101: relevant label/target lines ---
0048:     "self.mt5 = MT5ForConditionalGeneration.from_pretrained",
0049:     "self.projector = Projector",
0050:     "self.concept_head = nn.Linear(512, 48)",
0051:     "self.negative_head = nn.Linear(512, 5)",
0052:     "self.attribute_head = nn.Linear(512, 6)",
...
0053:     "self.conditioner = SoftStructuredConditioner",
...
0054:     "def forward(",
...
0138:
0139: print(
0140:     "Contains concept_head:",
0141:     "self.concept_head = nn.Linear(512, 48)"
0142:     in v5_class_source
...
0143: )
...
0144:
0145: print(
0146:     "Contains negative_head:",
0147:     "self.negative_head = nn.Linear(512, 5)"
0148:     in v5_class_source
...
0149: )
...
0150:
0151: print(
0152:     "Contains attribute_head:",
0153:     "self.attribute_head = nn.Linear(512, 6)"
0154:     in v5_class_source
...
0155: )
...
0241:     "mt5": hasattr(v5, "mt5"),
0242:     "projector": hasattr(v5, "projector"),
0243:     "concept_head": hasattr(v5, "concept_head"),
0244:     "negative_head": hasattr(v5, "negative_head"),
0245:     "attribute_head": hasattr(v5, "attribute_head"),
...
0246:     "conditioner": hasattr(v5, "conditioner"),
...
0247: }
...
0271:
0272: concept_shape = tuple(
0273:     v5.concept_head.weight.shape
0274: )
0275:
...
0276: negative_shape = tuple(
0277:     v5.negative_head.weight.shape
0278: )
0279:
...
0280: attribute_shape = tuple(
0281:     v5.attribute_head.weight.shape
0282: )
0283:
...
0416:
0417: print("PASS: Exact V5Model restored from Cell 81")
0418: print("PASS: concept_head / negative_head / attribute_head present")
0419: print("PASS: Projector = 768 -> 512")
0420: print("PASS: Structured heads = 48 / 5 / 6")
...

--- Notebook cell 103: relevant label/target lines ---
0052:     "self.attribute_embeddings",
0053:     "class V5Model",
0054:     "self.concept_head = nn.Linear(512, 48)",
0055:     "self.negative_head = nn.Linear(512, 5)",
0056:     "self.attribute_head = nn.Linear(512, 6)",
...
0057:     "self.conditioner = SoftStructuredConditioner",
...
0058: ]
...
0290:     "projector",
0291:     "conditioner",
0292:     "concept_head",
0293:     "negative_head",
0294:     "attribute_head",
...
0295: ]
...
0296:
...
0326:         ),
0327:
0328:     "concept_head":
0329:         tuple(
0330:             v5.concept_head.weight.shape
...
0331:         ),
0332:
...
0333:     "negative_head":
0334:         tuple(
0335:             v5.negative_head.weight.shape
...
0336:         ),
0337:
...
0338:     "attribute_head":
0339:         tuple(
0340:             v5.attribute_head.weight.shape
...
0341:         ),
0342:
...
0364: expected_shapes = {
0365:     "projector": (512, 768),
0366:     "concept_head": (48, 512),
0367:     "negative_head": (5, 512),
0368:     "attribute_head": (6, 512),
...
0369:     "concept_embeddings": (48, 512),
...
0370:     "negative_embeddings": (5, 512),
...
0471:
0472: print(
0473:     "PASS: concept_head / negative_head / attribute_head present"
0474: )
0475:
...

--- Notebook cell 106: relevant label/target lines ---
0158:     "projector",
0159:     "conditioner",
0160:     "concept_head",
0161:     "negative_head",
0162:     "attribute_head",
...
0163: ]
...
0164:
...

--- Notebook cell 115: relevant label/target lines ---
0140:         )
0141:
0142:         self.concept_head = nn.Linear(
0143:             hidden_dim,
0144:             n_concepts
...
0145:         )
0146:
0147:         self.negative_head = nn.Linear(
0148:             hidden_dim,
0149:             n_negative
...
0150:         )
0151:
0152:         self.attribute_head = nn.Linear(
0153:             hidden_dim,
0154:             n_attributes
...
0160:         image_mask,
0161:         labels=None,
0162:         concept_targets=None,
0163:         negative_targets=None,
0164:         attribute_targets=None
...
0165:     ):
...
0166:
...
0198:         )
0199:
0200:         concept_logits = self.concept_head(
0201:             visual_hidden
0202:         )
...
0203:
0204:         negative_logits = self.negative_head(
0205:             visual_hidden
0206:         )
...
0207:
0208:         attribute_logits = self.attribute_head(
0209:             visual_hidden
0210:         )
...
0278:     "projector",
0279:     "conditioner",
0280:     "concept_head",
0281:     "negative_head",
0282:     "attribute_head",
...
0283: ]:
...
0284:
...
0313:
0314: assert tuple(
0315:     v5.concept_head.weight.shape
0316: ) == (48, 512)
0317:
...
0318: assert tuple(
0319:     v5.negative_head.weight.shape
0320: ) == (5, 512)
0321:
...
0322: assert tuple(
0323:     v5.attribute_head.weight.shape
0324: ) == (6, 512)
0325:
...
0338: print("\n[SHAPES]")
0339: print("PASS: projector         = (512, 768)")
0340: print("PASS: concept_head      = (48, 512)")
0341: print("PASS: negative_head     = (5, 512)")
0342: print("PASS: attribute_head    = (6, 512)")
...
0343: print("PASS: concept_embedding = (48, 512)")
...
0344: print("PASS: negative_embedding= (5, 512)")
...

--- Notebook cell 131: relevant label/target lines ---
0154:         # ----------------------------------------------------
0155:
0156:         self.concept_head = nn.Linear(
0157:             512,
0158:             48,
...
0159:         )
0160:
0161:         self.negative_head = nn.Linear(
0162:             512,
0163:             5,
...
0164:         )
0165:
0166:         self.attribute_head = nn.Linear(
0167:             512,
0168:             6,
...
0188:         image_mask,
0189:         labels=None,
0190:         concept_targets=None,
0191:         negative_targets=None,
0192:         attribute_targets=None,
...
0193:     ):
...
0194:
...
0252:
0253:         concept_logits = (
0254:             self.concept_head(
0255:                 visual_hidden
0256:             )
...
0258:
0259:         negative_logits = (
0260:             self.negative_head(
0261:                 visual_hidden
0262:             )
...
0264:
0265:         attribute_logits = (
0266:             self.attribute_head(
0267:                 visual_hidden
0268:             )
...
0370:     "Concept head:",
0371:     tuple(
0372:         v5.concept_head.weight.shape
0373:     )
0374: )
...
0377:     "Negative head:",
0378:     tuple(
0379:         v5.negative_head.weight.shape
0380:     )
0381: )
...
0384:     "Attribute head:",
0385:     tuple(
0386:         v5.attribute_head.weight.shape
0387:     )
0388: )
...

--- Notebook cell 139: relevant label/target lines ---
0193: )
0194:
0195: structured_df = pd.read_csv(
0196:     STRUCTURED_CSV
0197: )
...
0209: print(
0210:     "Structured:",
0211:     structured_df.shape
0212: )
0213:
...
0214: assert v4_df.shape[0] == 7606
0215: assert structured_df.shape[0] == 7606
0216:
0217:
...
0524: # ============================================================
0525:
0526: def parse_vector(value):
0527:
0528:     if value is None:
...
0591: required_structured_cols = [
0592:     "case_id",
0593:     "concept_vector_str",
0594:     "negative_vector_str",
0595:     "attribute_vector_str",
...
0596: ]
...
0597:
...
0598: for col in required_structured_cols:
0599:     assert col in structured_df.columns, col
0600:
0601:
...
0602: structured_targets_v5 = {}
0603:
0604: for _, row in structured_df.iterrows():
0605:
0606:     case_id = str(
...
0608:     )
0609:
0610:     concept = parse_vector(
0611:         row["concept_vector_str"]
0612:     )
...
0613:
...
0614:     negative = parse_vector(
0615:         row["negative_vector_str"]
0616:     )
...
0617:
...
0618:     attribute = parse_vector(
0619:         row["attribute_vector_str"]
0620:     )
...
0621:
...
0642:     ] = {
0643:
0644:         "concept_targets":
0645:             torch.tensor(
0646:                 concept,
...
0648:             ),
0649:
0650:         "negative_targets":
0651:             torch.tensor(
0652:                 negative,
...
0654:             ),
0655:
0656:         "attribute_targets":
0657:             torch.tensor(
0658:                 attribute,
...
1115:                 (
1116:                     list(
1117:                         v5.concept_head.parameters()
1118:                     )
1119:                     +
...
1120:                     list(
1121:                         v5.negative_head.parameters()
1122:                     )
1123:                     +
...
1124:                     list(
1125:                         v5.attribute_head.parameters()
1126:                     )
1127:                 ),
...
1457: def compute_total_loss(
1458:     outputs,
1459:     concept_targets,
1460:     negative_targets,
1461:     attribute_targets,
...
1462: ):
...
1463:
...
1471:                 "concept_logits"
1472:             ],
1473:             concept_targets,
1474:         )
1475:     )
...
1480:                 "negative_logits"
1481:             ],
1482:             negative_targets,
1483:         )
1484:     )
...
1489:                 "attribute_logits"
1490:             ],
1491:             attribute_targets,
1492:         )
1493:     )
...
1606:         )
1607:
1608:         concept_targets = torch.stack([
1609:             structured_targets_v5[
1610:                 c
...
1611:             ][
1612:                 "concept_targets"
1613:             ]
1614:             for c in case_ids
...
1618:         )
1619:
1620:         negative_targets = torch.stack([
1621:             structured_targets_v5[
1622:                 c
...
1623:             ][
1624:                 "negative_targets"
1625:             ]
1626:             for c in case_ids
...
1630:         )
1631:
1632:         attribute_targets = torch.stack([
1633:             structured_targets_v5[
1634:                 c
...
1635:             ][
1636:                 "attribute_targets"
1637:             ]
1638:             for c in case_ids
...
1662:             ) = compute_total_loss(
1663:                 outputs,
1664:                 concept_targets,
1665:                 negative_targets,
1666:                 attribute_targets,
...
1667:             )
...
1668:
...
1808:         del image_mask
1809:         del labels
1810:         del concept_targets
1811:         del negative_targets
1812:         del attribute_targets
...
1813:
...
1814:
...
1855:             )
1856:
1857:             concept_targets = torch.stack([
1858:                 structured_targets_v5[
1859:                     c
...
1860:                 ][
1861:                     "concept_targets"
1862:                 ]
1863:                 for c in case_ids
...
1867:             )
1868:
1869:             negative_targets = torch.stack([
1870:                 structured_targets_v5[
1871:                     c
...
1872:                 ][
1873:                     "negative_targets"
1874:                 ]
1875:                 for c in case_ids
...
1879:             )
1880:
1881:             attribute_targets = torch.stack([
1882:                 structured_targets_v5[
1883:                     c
...
1884:                 ][
1885:                     "attribute_targets"
1886:                 ]
1887:                 for c in case_ids
...
1911:                 ) = compute_total_loss(
1912:                     outputs,
1913:                     concept_targets,
1914:                     negative_targets,
1915:                     attribute_targets,
...
1916:                 )
...
1917:
...

In [19]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import json, re, os
import pandas as pd

NB_PATH = "/content/drive/MyDrive/Colab Notebooks/25sep.ipynb"
CSV_PATH = STRUCTURED_CSV

print("=" * 80)
print("TRACE V5 TARGET GENERATION — READ ONLY")
print("=" * 80)

with open(NB_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

# Search every code cell for vector creation, label ordering, and target construction.
patterns = re.compile(
    r"concept_vector_str|negative_vector_str|attribute_vector_str|"
    r"structured_targets_v5|required_structured_cols|"
    r"concept_cols|negative_cols|attribute_cols|"
    r"concept_targets|negative_targets|attribute_targets|"
    r"concepts_v2_str|negative_findings_str|attributes_v2_str|"
    r"concept__viem_ong_tai_ngoai",
    re.I
)

for idx, cell in enumerate(nb.get("cells", [])):
    if cell.get("cell_type") != "code":
        continue
    src = "".join(cell.get("source", []))
    lines = src.splitlines()
    hits = [i for i, line in enumerate(lines) if patterns.search(line)]
    if hits:
        print(f"\n{'='*25} CELL {idx} {'='*25}")
        shown = set()
        for i in hits:
            for j in range(max(0, i-3), min(len(lines), i+4)):
                if j not in shown:
                    print(f"{j+1:04d}: {lines[j]}")
                    shown.add(j)
            print("...")

# Check whether the CSV's existing structured columns can support the expected dimensions.
df = pd.read_csv(CSV_PATH, nrows=5, low_memory=False)
concept_cols = [c for c in df.columns if c.startswith("concept__")]
negative_cols = [c for c in df.columns if c.startswith("negative__")]
attribute_cols = [c for c in df.columns if c.startswith("attribute__")]

print("\n" + "=" * 80)
print("CURRENT CSV COUNTS")
print("=" * 80)
print("Concept columns:", len(concept_cols))
print("Negative columns:", len(negative_cols))
print("Attribute columns:", len(attribute_cols))
print("Model head dimensions: 48 / 5 / 6")
print("\nExisting serialized fields:")
for c in ["concepts_v2_str", "negative_findings_str", "attributes_v2_str"]:
    print(f"\n{c}:")
    if c in df.columns:
        print(df[c].head(5).tolist())
    else:
        print("MISSING")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
================================================================================
TRACE V5 TARGET GENERATION — READ ONLY
================================================================================

========================= CELL 1 =========================
0742:
0743:     def forward(
0744:         self,
0745:         concept_targets,
0746:         negative_targets,
0747:         attribute_targets,
0748:     ):
...
0749:
...
0750:         device = concept_targets.device
...
0751:
0752:         concept_ids = (
0753:             concept_targets
...
0754:             .long()
0755:             .clamp(0, 1)
0756:         )
...
0757:
0758:         negative_ids = (
0759:             negative_targets
0760:             .long()
0761:             .clamp(0, 1)
0762:         )
...
0763:
0764:         attribute_ids = (
0765:             attribute_targets
0766:             .long()
0767:             .clamp(0, 1)
0768:         )
...
0850:             structured_tokens
0851:         )
0852:
0853:         B = concept_targets.shape[0]
0854:
0855:         structured_attention = torch.ones(
0856:             B,
...

========================= CELL 10 =========================
0032: image_mask = batch["image_mask"].to(device)
0033: labels = batch["labels"].to(device)
0034:
0035: concept_targets = batch["concept_targets"].to(device).float()
0036: negative_targets = batch["negative_targets"].to(device).float()
0037: attribute_targets = batch["attribute_targets"].to(device).float()
0038:
...
0039: B, N, C, H, W = pixel_values.shape
...
0040:
...
0041: print(f"Batch size: {B}")
0042: print(f"Images/case: {N}")
0043: print(f"Labels: {tuple(labels.shape)}")
0044: print(f"Concept targets: {tuple(concept_targets.shape)}")
0045: print(f"Negative targets: {tuple(negative_targets.shape)}")
0046: print(f"Attribute targets: {tuple(attribute_targets.shape)}")
0047:
...
0048:
...
0049: # ============================================================
...
0186:
0187: L_concept = F.binary_cross_entropy_with_logits(
0188:     concept_logits,
0189:     concept_targets,
0190: )
0191:
0192: L_negative = F.binary_cross_entropy_with_logits(
...
0193:     negative_logits,
0194:     negative_targets,
0195: )
0196:
0197: L_attribute = F.binary_cross_entropy_with_logits(
...
0198:     attribute_logits,
0199:     attribute_targets,
0200: )
0201:
0202: print("\nRaw losses:")
...

========================= CELL 12 =========================
0027: # ------------------------------------------------------------
0028: # 2. Frozen structured columns
0029: # ------------------------------------------------------------
0030: concept_cols = [
0031:     "concept__amidan_qua_phat",
0032:     "concept__chan_thuong_mang_nhi",
0033:     "concept__chan_thuong_ong_tai_ngoai",
...
0068:     "concept__viem_mieng",
0069:     "concept__viem_mui",
0070:     "concept__viem_mui_xoang",
0071:     "concept__viem_ong_tai_ngoai",
0072:     "concept__viem_tai_giua",
0073:     "concept__viem_tai_xuong_chum",
0074:     "concept__viem_thanh_quan",
...
0078:     "concept__xep_mang_nhi",
0079: ]
0080:
0081: negative_cols = [
0082:     "negative__no_abnormal_external_middle_ear",
0083:     "negative__no_abnormal_nose_sinus",
0084:     "negative__no_abnormal_ent",
...
0086:     "negative__no_foreign_body",
0087: ]
0088:
0089: attribute_cols = [
0090:     "attribute__acute",
0091:     "attribute__chronic",
0092:     "attribute__right",
...
0100: # ------------------------------------------------------------
0101: required = (
0102:     ["case_id"]
0103:     + concept_cols
0104:     + negative_cols
0105:     + attribute_cols
0106: )
...
0107:
...
0108: missing = [c for c in required if c not in manifest_audit.columns]
...
0119: manifest_lookup = (
0120:     manifest_audit[
0121:         ["case_id"]
0122:         + concept_cols
0123:         + negative_cols
0124:         + attribute_cols
0125:     ]
...
0126:     .set_index("case_id")
...
0127: )
...
0145: # ------------------------------------------------------------
0146: target_rows = manifest_lookup.loc[list(batch_case_ids)]
0147:
0148: concept_targets = torch.tensor(
0149:     target_rows[concept_cols].values,
0150:     dtype=torch.float32,
0151:     device=device,
...
0152: )
...
0153:
0154: negative_targets = torch.tensor(
0155:     target_rows[negative_cols].values,
0156:     dtype=torch.float32,
0157:     device=device,
...
0158: )
...
0159:
0160: attribute_targets = torch.tensor(
0161:     target_rows[attribute_cols].values,
0162:     dtype=torch.float32,
0163:     device=device,
...
0164: )
...
0165:
0166: print("\nTarget shapes:")
0167: print("  concept :", tuple(concept_targets.shape))
0168: print("  negative:", tuple(negative_targets.shape))
0169: print("  attribute:", tuple(attribute_targets.shape))
0170:
...
0171: assert concept_targets.shape == (len(batch_case_ids), 48)
...
0172: assert negative_targets.shape == (len(batch_case_ids), 5)
...
0173: assert attribute_targets.shape == (len(batch_case_ids), 6)
0174:
...
0175: # ------------------------------------------------------------
...
0176: # 6. Forward V5
...
0188:     pixel_values=pixel_values,
0189:     image_mask=image_mask,
0190:     labels=labels,
0191:     concept_targets=concept_targets,
0192:     negative_targets=negative_targets,
0193:     attribute_targets=attribute_targets,
0194: )
...
0195:
...
0196: # ------------------------------------------------------------
...

========================= CELL 13 =========================
0029: # ------------------------------------------------------------
0030: # 2. Exact frozen ontology order
0031: # ------------------------------------------------------------
0032: concept_cols = [
0033:     "concept__amidan_qua_phat",
0034:     "concept__chan_thuong_mang_nhi",
0035:     "concept__chan_thuong_ong_tai_ngoai",
...
0070:     "concept__viem_mieng",
0071:     "concept__viem_mui",
0072:     "concept__viem_mui_xoang",
0073:     "concept__viem_ong_tai_ngoai",
0074:     "concept__viem_tai_giua",
0075:     "concept__viem_tai_xuong_chum",
0076:     "concept__viem_thanh_quan",
...
0080:     "concept__xep_mang_nhi",
0081: ]
0082:
0083: negative_cols = [
0084:     "negative__no_abnormal_external_middle_ear",
0085:     "negative__no_abnormal_nose_sinus",
0086:     "negative__no_abnormal_ent",
...
0088:     "negative__no_foreign_body",
0089: ]
0090:
0091: attribute_cols = [
0092:     "attribute__acute",
0093:     "attribute__chronic",
0094:     "attribute__right",
...
0102: # ------------------------------------------------------------
0103: required_cols = (
0104:     ["case_id"]
0105:     + concept_cols
0106:     + negative_cols
0107:     + attribute_cols
0108: )
...
0109:
...
0110: missing = [
...
0157: # ------------------------------------------------------------
0158: # 6. Convert to tensors
0159: # ------------------------------------------------------------
0160: concept_targets = torch.tensor(
0161:     target_rows[concept_cols].to_numpy(),
0162:     dtype=torch.float32,
0163:     device=device,
...
0164: )
...
0165:
0166: negative_targets = torch.tensor(
0167:     target_rows[negative_cols].to_numpy(),
0168:     dtype=torch.float32,
0169:     device=device,
...
0170: )
...
0171:
0172: attribute_targets = torch.tensor(
0173:     target_rows[attribute_cols].to_numpy(),
0174:     dtype=torch.float32,
0175:     device=device,
...
0176: )
...
0177:
0178: print("\nTarget tensor shapes:")
0179: print("  concept   :", tuple(concept_targets.shape))
0180: print("  negative  :", tuple(negative_targets.shape))
0181: print("  attribute :", tuple(attribute_targets.shape))
0182:
...
0183: assert concept_targets.shape == (len(batch_case_ids), 48)
...
0184: assert negative_targets.shape == (len(batch_case_ids), 5)
...
0185: assert attribute_targets.shape == (len(batch_case_ids), 6)
0186:
...
0187: # ------------------------------------------------------------
...
0188: # 7. Value sanity
...
0191:
0192: print(
0193:     "  concept   :",
0194:     torch.unique(concept_targets).detach().cpu().tolist()
0195: )
0196:
0197: print(
...
0198:     "  negative  :",
0199:     torch.unique(negative_targets).detach().cpu().tolist()
0200: )
0201:
0202: print(
...
0203:     "  attribute :",
0204:     torch.unique(attribute_targets).detach().cpu().tolist()
0205: )
0206:
0207: assert torch.isfinite(concept_targets).all()
...
0208: assert torch.isfinite(negative_targets).all()
0209: assert torch.isfinite(attribute_targets).all()
0210:
...
0211: assert set(torch.unique(concept_targets).cpu().tolist()).issubset({0.0, 1.0})
...
0212: assert set(torch.unique(negative_targets).cpu().tolist()).issubset({0.0, 1.0})
...
0213: assert set(torch.unique(attribute_targets).cpu().tolist()).issubset({0.0, 1.0})
0214:
...
0215: print("\n" + "=" * 70)
...
0216: print("PASS — STRUCTURED TARGETS READY FOR V5 LOSS AUDIT")
...

========================= CELL 14 =========================
0025: # ------------------------------------------------------------
0026: target_rows = target_index.loc[list(batch_case_ids)]
0027:
0028: concept_targets = torch.tensor(
0029:     target_rows[concept_cols].to_numpy(),
0030:     dtype=torch.float32,
0031:     device=device,
...
0032: )
...
0033:
0034: negative_targets = torch.tensor(
0035:     target_rows[negative_cols].to_numpy(),
0036:     dtype=torch.float32,
0037:     device=device,
...
0038: )
...
0039:
0040: attribute_targets = torch.tensor(
0041:     target_rows[attribute_cols].to_numpy(),
0042:     dtype=torch.float32,
0043:     device=device,
...
0044: )
...
0052:     pixel_values=pixel_values,
0053:     image_mask=image_mask,
0054:     labels=labels,
0055:     concept_targets=concept_targets,
0056:     negative_targets=negative_targets,
0057:     attribute_targets=attribute_targets,
0058: )
...
0059:
...
0060: # ------------------------------------------------------------
...
0072:     concept_logits = out.concept_logits
0073:     L_concept = F.binary_cross_entropy_with_logits(
0074:         concept_logits,
0075:         concept_targets,
0076:     )
0077:
0078: if hasattr(out, "negative_loss"):
...
0081:     negative_logits = out.negative_logits
0082:     L_negative = F.binary_cross_entropy_with_logits(
0083:         negative_logits,
0084:         negative_targets,
0085:     )
0086:
0087: if hasattr(out, "attribute_loss"):
...
0090:     attribute_logits = out.attribute_logits
0091:     L_attribute = F.binary_cross_entropy_with_logits(
0092:         attribute_logits,
0093:         attribute_targets,
0094:     )
0095:
0096: # V4-equivalent weighting
...

========================= CELL 16 =========================
0009:     pixel_values,
0010:     image_mask,
0011:     labels=None,
0012:     concept_targets=None,
0013:     negative_targets=None,
0014:     attribute_targets=None,
0015: ):
...
0016:
...
0017:     B, N, C, H, W = pixel_values.shape
...
0151:         "attention_mask": attention_mask,
0152:     }
0153:
0154:     if concept_targets is not None:
0155:         result["concept_loss"] = (
0156:             F.binary_cross_entropy_with_logits(
0157:                 concept_logits,
...
0158:                 concept_targets,
0159:             )
0160:         )
0161:
...
0162:     if negative_targets is not None:
0163:         result["negative_loss"] = (
0164:             F.binary_cross_entropy_with_logits(
0165:                 negative_logits,
...
0166:                 negative_targets,
0167:             )
0168:         )
0169:
...
0170:     if attribute_targets is not None:
0171:         result["attribute_loss"] = (
0172:             F.binary_cross_entropy_with_logits(
0173:                 attribute_logits,
...
0174:                 attribute_targets,
0175:             )
0176:         )
0177:
...

========================= CELL 17 =========================
0011:         pixel_values=pixel_values,
0012:         image_mask=image_mask,
0013:         labels=labels,
0014:         concept_targets=concept_targets,
0015:         negative_targets=negative_targets,
0016:         attribute_targets=attribute_targets,
0017:     )
...
0018:
...
0019: print("=" * 70)
...

========================= CELL 19 =========================
0019:     pixel_values=pixel_values,
0020:     image_mask=image_mask,
0021:     labels=labels,
0022:     concept_targets=concept_targets,
0023:     negative_targets=negative_targets,
0024:     attribute_targets=attribute_targets,
0025: )
...
0026:
...
0027: L_report = out_grad["report_loss"]
...

========================= CELL 74 =========================
0120: # -----------------------------------------------------------------------------
0121: print("\n[STRUCTURED COLUMNS]")
0122:
0123: required_structured_cols = [
0124:     "concept_vector_str",
0125:     "negative_vector_str",
0126:     "attribute_vector_str",
...
0127: ]
...
0128:
...
0129: for c in required_structured_cols:
...
0130:     print(
0131:         f"{c:25s}:",
0132:         "FOUND" if c in structured_df.columns else "MISSING"
...
0133:     )
0134:
0135: if not all(c in structured_df.columns for c in required_structured_cols):
0136:     raise RuntimeError(
0137:         "Structured target columns are missing. "
0138:         "Do NOT train."
...
0240:     case_id = str(row["case_id"])
0241:
0242:     concept = parse_vector(
0243:         row["concept_vector_str"]
0244:     )
0245:
0246:     negative = parse_vector(
...
0247:         row["negative_vector_str"]
0248:     )
0249:
0250:     attribute = parse_vector(
...
0251:         row["attribute_vector_str"]
0252:     )
0253:
0254:     structured_lookup[case_id] = {
...
0419:
0420:     source_concept = torch.tensor(
0421:         parse_vector(
0422:             source_row["concept_vector_str"]
0423:         ),
0424:         dtype=torch.float32,
0425:         device=device,
...
0427:
0428:     source_negative = torch.tensor(
0429:         parse_vector(
0430:             source_row["negative_vector_str"]
0431:         ),
0432:         dtype=torch.float32,
0433:         device=device,
...
0435:
0436:     source_attribute = torch.tensor(
0437:         parse_vector(
0438:             source_row["attribute_vector_str"]
0439:         ),
0440:         dtype=torch.float32,
0441:         device=device,
...
0526:         pixel_values=pixel_values,
0527:         image_mask=image_mask,
0528:         labels=labels,
0529:         concept_targets=concept_gt,
0530:         negative_targets=negative_gt,
0531:         attribute_targets=attribute_gt,
0532:     )
...
0533:
...
0534: print(
...

========================= CELL 81 =========================
0136:         pixel_values,
0137:         image_mask,
0138:         labels=None,
0139:         concept_targets=None,
0140:         negative_targets=None,
0141:         attribute_targets=None,
0142:     ):
...
0143:         B, N, C, H, W = pixel_values.shape
...
0144:
...

========================= CELL 85 =========================
0081:
0082: required_target_columns = [
0083:     "case_id",
0084:     "concept_vector_str",
0085:     "negative_vector_str",
0086:     "attribute_vector_str",
0087: ]
...
0088:
...
0089: missing_target_columns = [
...
0099:     )
0100:
0101: print("PASS: case_id found")
0102: print("PASS: concept_vector_str found")
0103: print("PASS: negative_vector_str found")
0104: print("PASS: attribute_vector_str found")
0105:
...
0106: # ================================================================================
...
0107: # 4. CASE-ID UNIQUENESS
...
0191:     case_id = str(row["case_id"])
0192:
0193:     concept = parse_vector(
0194:         row["concept_vector_str"],
0195:         48,
0196:         "concept_vector",
0197:         case_id,
...
0198:     )
0199:
0200:     negative = parse_vector(
0201:         row["negative_vector_str"],
0202:         5,
0203:         "negative_vector",
0204:         case_id,
...
0205:     )
0206:
0207:     attribute = parse_vector(
0208:         row["attribute_vector_str"],
0209:         6,
0210:         "attribute_vector",
0211:         case_id,
...
0322:         "one or more train-batch case_ids."
0323:     )
0324:
0325: concept_targets = torch.tensor(
0326:     np.stack([
0327:         target_lookup[c]["concept"]
0328:         for c in case_ids
...
0330:     dtype=torch.float32,
0331: )
0332:
0333: negative_targets = torch.tensor(
0334:     np.stack([
0335:         target_lookup[c]["negative"]
0336:         for c in case_ids
...
0338:     dtype=torch.float32,
0339: )
0340:
0341: attribute_targets = torch.tensor(
0342:     np.stack([
0343:         target_lookup[c]["attribute"]
0344:         for c in case_ids
...
0347: )
0348:
0349: print(
0350:     "concept_targets:",
0351:     tuple(concept_targets.shape)
0352: )
0353:
...
0354: print(
...
0355:     "negative_targets:",
0356:     tuple(negative_targets.shape)
0357: )
0358:
...
0359: print(
...
0360:     "attribute_targets:",
0361:     tuple(attribute_targets.shape)
0362: )
0363:
...
0364: # ================================================================================
...
0368: print("\n[TARGET VALUE AUDIT]")
0369:
0370: for name, tensor in [
0371:     ("concept", concept_targets),
0372:     ("negative", negative_targets),
0373:     ("attribute", attribute_targets),
0374: ]:
...
0375:
...
0376:     unique_values = torch.unique(tensor).cpu().tolist()
...
0422:     non_blocking=True
0423: )
0424:
0425: concept_targets_device = concept_targets.to(
0426:     device,
0427:     non_blocking=True
0428: )
...
0429:
0430: negative_targets_device = negative_targets.to(
0431:     device,
0432:     non_blocking=True
0433: )
...
0434:
0435: attribute_targets_device = attribute_targets.to(
0436:     device,
0437:     non_blocking=True
0438: )
...
0462:         pixel_values=pixel_values_device,
0463:         image_mask=image_mask_device,
0464:         labels=labels_device,
0465:         concept_targets=concept_targets_device,
0466:         negative_targets=negative_targets_device,
0467:         attribute_targets=attribute_targets_device,
0468:     )
...
0469:
...
0470: print(
...
0592:
0593: concept_loss = torch.nn.functional.binary_cross_entropy_with_logits(
0594:     outputs["concept_logits"],
0595:     concept_targets_device,
0596: )
0597:
0598: negative_loss = torch.nn.functional.binary_cross_entropy_with_logits(
...
0599:     outputs["negative_logits"],
0600:     negative_targets_device,
0601: )
0602:
0603: attribute_loss = torch.nn.functional.binary_cross_entropy_with_logits(
...
0604:     outputs["attribute_logits"],
0605:     attribute_targets_device,
0606: )
0607:
0608: total_audit_loss = (
...

========================= CELL 87 =========================
0104: print("=" * 80)
0105:
0106: vector_cols = [
0107:     "concept_vector_str",
0108:     "negative_vector_str",
0109:     "attribute_vector_str",
0110: ]
...
0111:
...
0112: for col in vector_cols:
...
0266: print("=" * 80)
0267:
0268: expected_dims = {
0269:     "concept_vector_str": 48,
0270:     "negative_vector_str": 5,
0271:     "attribute_vector_str": 6,
0272: }
...
0273:
...
0274: dimension_failures = []
...

========================= CELL 88 =========================
0223: actual_concept = np.stack(
0224:     [
0225:         parse_vector(value)
0226:         for value in v4_df["concept_vector_str"]
0227:     ]
0228: )
0229:
...
0316: actual_negative = np.stack(
0317:     [
0318:         parse_vector(value)
0319:         for value in v4_df["negative_vector_str"]
0320:     ]
0321: )
0322:
...
0398: actual_attribute = np.stack(
0399:     [
0400:         parse_vector(value)
0401:         for value in v4_df["attribute_vector_str"]
0402:     ]
0403: )
0404:
...

========================= CELL 89 =========================
0108: actual_negative = np.stack(
0109:     [
0110:         parse_vector(x)
0111:         for x in v4_df["negative_vector_str"]
0112:     ]
0113: )
0114:
...
0208: # ================================================================================
0209:
0210: print("\n" + "=" * 80)

In [20]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
import pandas as pd

ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
V4_PATH = ROOT / "baseline_model_v4/v4_training_manifest.csv"
STRUCT_PATH = ROOT / "v3_ontology_v2/v3_structured_targets_v2_2.csv"
CKPT_PATH = ROOT / "baseline_model_v5/checkpoints/best.pt"

v4 = pd.read_csv(V4_PATH)
structured = pd.read_csv(STRUCT_PATH)

for name, df in [("V4 manifest", v4), ("Structured CSV", structured)]:
    print(f"\n===== {name} =====")
    print("Shape:", df.shape)
    print("Case IDs unique:", df["case_id"].nunique() if "case_id" in df else "MISSING")
    for col in ["concept_vector_str", "negative_vector_str",
                "attribute_vector_str", "structured_loss_mask"]:
        print(f"{col}: {'FOUND' if col in df.columns else 'MISSING'}")
    print("Concept columns:", sum(c.startswith("concept__") for c in df.columns))
    print("Negative columns:", sum(c.startswith("negative__") for c in df.columns))
    print("Attribute columns:", sum(c.startswith("attribute__") for c in df.columns))

print("\n===== CASE-ID OVERLAP =====")
if "case_id" in v4 and "case_id" in structured:
    a = set(v4["case_id"].astype(str))
    b = set(structured["case_id"].astype(str))
    print("V4 cases:", len(a))
    print("Structured cases:", len(b))
    print("Overlap:", len(a & b))
    print("Only V4:", len(a - b))
    print("Only Structured:", len(b - a))

print("\n===== CHECKPOINT FILE =====")
print("Exists:", CKPT_PATH.exists())
if CKPT_PATH.exists():
    print("Size (MB):", round(CKPT_PATH.stat().st_size / 1024**2, 2))
    print("Modified:", pd.Timestamp(CKPT_PATH.stat().st_mtime, unit="s"))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

===== V4 manifest =====
Shape: (7606, 15)
Case IDs unique: 7606
concept_vector_str: FOUND
negative_vector_str: FOUND
attribute_vector_str: FOUND
structured_loss_mask: FOUND
Concept columns: 0
Negative columns: 0
Attribute columns: 0

===== Structured CSV =====
Shape: (7606, 102)
Case IDs unique: 7606
concept_vector_str: MISSING
negative_vector_str: MISSING
attribute_vector_str: MISSING
structured_loss_mask: MISSING
Concept columns: 54
Negative columns: 5
Attribute columns: 6

===== CASE-ID OVERLAP =====
V4 cases: 7606
Structured cases: 7606
Overlap: 7606
Only V4: 0
Only Structured: 0

===== CHECKPOINT FILE =====
Exists: True
Size (MB): 4425.08
Modified: 2026-09-29 04:20:44

In [21]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import json
from pathlib import Path

nb_path = Path("/content/drive/MyDrive/Colab Notebooks/25sep.ipynb")
print("Notebook exists:", nb_path.exists())

if nb_path.exists():
    nb = json.loads(nb_path.read_text(encoding="utf-8"))
    cells = nb.get("cells", [])
    print("Total cells:", len(cells))

    for idx in [123, 139]:
        if idx >= len(cells):
            print(f"\nCell {idx}: OUT OF RANGE")
            continue

        cell = cells[idx]
        source = "".join(cell.get("source", []))
        outputs = cell.get("outputs", [])

        print(f"\n{'=' * 70}")
        print(f"CELL {idx}")
        print("Execution count:", cell.get("execution_count"))
        print("Output count:", len(outputs))
        print("--- Relevant source lines ---")

        for line_no, line in enumerate(source.splitlines(), start=1):
            if any(term in line.lower() for term in [
                "read_csv", "structured_df", "v4_df",
                "concept_vector_str", "structured_targets_v5",
                "assert col in", "epoch", "best.pt",
                "checkpoint", "training"
            ]):
                print(f"{line_no:04d}: {line[:240]}")

        print("--- Saved outputs (truncated) ---")
        for out_idx, out in enumerate(outputs):
            data = out.get("data", {})
            text_out = out.get("text", [])

            if "text/plain" in data:
                payload = data["text/plain"]
                text_out = payload if isinstance(payload, list) else [payload]

            text_out = "".join(text_out)
            if text_out.strip():
                print(f"[Output {out_idx}]")
                print(text_out[:2500])

            if out.get("output_type") == "error":
                print("ERROR:", out.get("ename"), out.get("evalue"))
else:
    print("Không tìm thấy notebook ở đường dẫn trên.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Notebook exists: True
Total cells: 162

======================================================================
CELL 123
Execution count: 15
Output count: 1
--- Relevant source lines ---
0089:             row["concept_vector_str"],
0091:             "concept_vector_str"
0127: structured_targets_v5 = build_structured_targets(v4_df)
0138:     len(structured_targets_v5)
0141: assert len(structured_targets_v5) == 7606
0144:     structured_targets_v5.items()
0172: for _, row in v4_df.iterrows():
0175:         row["concept_vector_str"],
0177:         "concept_vector_str"
0198:     v4_df["num_concepts_v2"].to_numpy()
0203:     v4_df["num_negative_findings"].to_numpy()
0208:     v4_df["num_attributes_v2"].to_numpy()
0279: # 8. Build one real training batch
0332:     structured_targets_v5[c]["concept_targets"]
0337:     structured_targets_v5[c]["negative_targets"]
0342:     structured_targets_v5[c]["attribute_targets"]
0347:     structured_targets_v5[c]["structured_loss_mask"]
0394: print("PASS: No training.")
--- Saved outputs (truncated) ---
[Output 0]
======================================================================
V5 RESTORE — DATALOADER + STRUCTURED TARGET AUDIT
======================================================================

[VOCABULARY]
Negative: ['no_abnormal_ent', 'no_abnormal_external_middle_ear', 'no_abnormal_nose_sinus', 'no_bleeding', 'no_foreign_body']
Attribute: ['acute', 'bilateral', 'chronic', 'left', 'post_surgery', 'right']

[STRUCTURED TARGETS]
Cases: 7606
10000.10000.0.10014 concept= (48,) negative= (5,) attribute= (6,) mask= 1.0
10001.10001.0.10015 concept= (48,) negative= (5,) attribute= (6,) mask= 1.0
10002.10002.0.10016 concept= (48,) negative= (5,) attribute= (6,) mask= 1.0

[COUNT CONSISTENCY]
PASS: concept vectors match num_concepts_v2.
PASS: negative vectors match num_negative_findings.
PASS: attribute vectors match num_attributes_v2.

[LOADERS]
Train batches: 1535
Val batches: 189
Test batches: 178

[REAL BATCH AUDIT]
case_id: ['13931.13931.0.13950', '15080.15080.0.15099', '14286.14286.0.14305', '15667.15667.0.15688']
pixel_values: (4, 8, 3, 224, 224) torch.float32
image_mask: (4, 8) torch.float32
labels: (4, 96) torch.int64

[STRUCTURED BATCH LOOKUP]
concept_targets: (4, 48)
negative_targets: (4, 5)
attribute_targets: (4, 6)
structured_masks: (4,)

[SAFETY]
PASS: Exact V4 structured vectors used.
PASS: 48 concept targets.
PASS: 5 negative targets.
PASS: 6 attribute targets.
PASS: Vector/count consistency verified.
PASS: Train loader = 1535 batches.
PASS: Val loader = 189 batches.
PASS: Test loader = 178 batches.
PASS: Real batch schema valid.
PASS: No optimizer.
PASS: No backward.
PASS: No training.

======================================================================
CELL 9H PASS — send me this output.
======================================================================


======================================================================
CELL 139
Execution count: 15
Output count: 2
--- Relevant source lines ---
0002: # V5 — FULL TRAINING FROM PRETRAINED VIT + mT5
0016: #   checkpoint resume
0018: #   V5 training
0020: # CHECKPOINT:
0022: #   2 rolling checkpoints
0023: #   epoch checkpoints
0024: #   best.pt
0056: print("V5 — FULL TRAINING")
0082: EPOCHS = 5
0094: OPT_STEPS_PER_EPOCH = 384
0098: CHECKPOINT_EVERY = 48
0129:     "v4_training_manifest.csv"
0151:     "checkpoints"
0166:     "best.pt"
0187: v4_df = pd.read_csv(
0191: image_df = pd.read_csv(
0195: structured_df = pd.read_csv(
0201:     v4_df.shape
0211:     structured_df.shape
0214: assert v4_df.shape[0] == 7606
0215: assert structured_df.shape[0] == 7606
0223:     v4_df.loc[
0224:         v4_df["split"] == "train",
0232:     v4_df.loc[
0233:         v4_df["split"] == "val",
0241:     v4_df.loc[
0242:         v4_df["split"] == "test",
0396:     # Training: random selection >8
0506: assert "ket_luan" in v4_df.columns
0510:         v4_df["case_id"].astype(str),
0511:         v4_df["ket_luan"].fillna("").astype(str)
0593:     "concept_vector_str",
0599:     assert col in structured_df.columns, col
0602: structured_targets_v5 = {}
0604: for _, row in structured_df.iterrows():
0611:         row["concept_vector_str"]
0640:     structured_targets_v5[
0668:     len(structured_targets_v5)
0905: # Deterministic epoch permutation.
0906: # This makes mid-epoch resume possible.
0910:     epoch,
0917:         SEED + epoch
0978:     epoch=1,
1167: # 22. CHECKPOINT FUNCTIONS
1171:     "epoch",
1184:     epoch,
1194:         "epoch":
1195:             int(epoch),
1240: # 23. FIND RESUME CHECKPOINT
1243: def checkpoint_step(path):
1257:                 "last_epoch"
1274:         step = checkpoint_step(
1302: start_epoch = 1
1321:     print("RESUMING CHECKPOINT")
1325:         "Checkpoint:",
1367:         scheduler_v5.last_epoch
1378:         start_epoch = int(
1380:                 "epoch"
1392:         # Old epoch-level checkpoint
1395:             % OPT_STEPS_PER_EPOCH
1399:             start_epoch = (
1401:                 // OPT_STEPS_PER_EPOCH
1410:                 "Checkpoint is mid-epoch but "
1428:         "Start epoch:",
1429:         start_epoch
1445:     print("NO V5 CHECKPOINT")
1515: # 27. TRAINING
1519: print("V5 TRAINING")
1523:     "Epochs:",
1524:     EPOCHS
1533:     "Checkpoint interval:",
1534:     CHECKPOINT_EVERY,
1539: for epoch in range(
1540:     start_epoch,
1541:     EPOCHS + 1
1546:     epoch_start = time.time()
1549:         epoch=epoch,
1552:             if epoch == start_epoch
1559:         if epoch == start_epoch
1573:         desc=f"Train {epoch}/{EPOCHS}",
1609:             structured_targets_v5[
1621:             structured_targets_v5[
1633:             structured_targets_v5[
1733:             # FREQUENT CHECKPOINT
1738:                 % CHECKPOINT_EVERY
1745:                         // CHECKPOINT_EVERY
1760:                     "epoch":
1761:                         epoch,
1772:                     epoch,
1781:                     f"\nCHECKPOINT PASS | "
1783:                     f"epoch={epoch} | "
1829:             desc=f"Val {epoch}/{EPOCHS}",
1858:                 structured_targets_v5[
1870:                 structured_targets_v5[
1882:                 structured_targets_v5[
1964:     # EPOCH RESUME STATE
1971:         "epoch":
1972:             epoch + 1,
1992:             epoch,
2008:     # EPOCH CHECKPOINT
2011:     epoch_ckpt = (
2013:         f"epoch_{epoch:02d}.pt"
2017:         epoch_ckpt,
2018:         epoch,
2028:         epoch,
2039:         f"EPOCH {epoch}/{EPOCHS} COMPLETE"
2064:         f"Checkpoint : {epoch_ckpt.name}"
2069:         f"{(time.time()-epoch_start)/60:.1f} min"
2073:     # Reset resume batch after first epoch
2082: print("V5 TRAINING FINISHED")
2106:     "best.pt:",
2118: print("\nPASS: V5 TRAINING COMPLETE.")
2119: print("PASS: Checkpoints saved.")
--- Saved outputs (truncated) ---
[Output 0]
================================================================================
V5 — FULL TRAINING
================================================================================
PASS: Drive mounted.
GPU: NVIDIA A100-SXM4-80GB

================================================================================
[1] MANIFESTS
================================================================================

ERROR: AssertionError /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv

In [22]:
from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import json
from pathlib import Path
import torch

nb_path = Path("/content/drive/MyDrive/Colab Notebooks/25sep.ipynb")
ckpt_path = Path(
    "/content/drive/MyDrive/NoiSoi_Matching/"
    "baseline_model_v5/checkpoints/best.pt"
)

# 1. In đầy đủ loại và nội dung output của Cell 139
nb = json.loads(nb_path.read_text(encoding="utf-8"))
cell = nb["cells"][139]

print("=" * 70)
print("CELL 139")
print("Execution count:", cell.get("execution_count"))

for i, out in enumerate(cell.get("outputs", [])):
    print(f"\n--- OUTPUT {i}: {out.get('output_type')} ---")

    if out.get("output_type") == "error":
        print("Error:", out.get("ename"), out.get("evalue"))
        print("\n".join(out.get("traceback", []))[-5000:])

    data = out.get("data", {})
    for mime, content in data.items():
        if mime in ("text/plain", "text/html"):
            print(f"[{mime}]")
            print("".join(content) if isinstance(content, list) else content)

    if "text" in out:
        print("".join(out["text"]))

# 2. Đọc metadata checkpoint — không load model vào GPU
print("\n" + "=" * 70)
print("CHECKPOINT METADATA")

if not ckpt_path.exists():
    print("Checkpoint không tồn tại:", ckpt_path)
else:
    print("Exists:", True)
    print("Size (GB):", round(ckpt_path.stat().st_size / 1024**3, 3))
    print("Modified:", __import__("datetime").datetime.fromtimestamp(
        ckpt_path.stat().st_mtime
    ).isoformat())

    try:
        ckpt = torch.load(
            ckpt_path,
            map_location="cpu",
            weights_only=False
        )
        if isinstance(ckpt, dict):
            print("Top-level keys:", list(ckpt.keys()))
            for key in (
                "epoch", "global_step", "best_val_loss",
                "val_loss", "step", "last_epoch"
            ):
                if key in ckpt:
                    print(f"{key}:", ckpt[key])
        else:
            print("Checkpoint object type:", type(ckpt))
        del ckpt
    except Exception as e:
        print("Metadata read error:", repr(e))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
======================================================================
CELL 139
Execution count: 15

--- OUTPUT 0: stream ---
================================================================================
V5 — FULL TRAINING
================================================================================
PASS: Drive mounted.
GPU: NVIDIA A100-SXM4-80GB

================================================================================
[1] MANIFESTS
================================================================================


--- OUTPUT 1: error ---
Error: AssertionError /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_6136/1670025182.py in <cell line: 0>()
    181 print("=" * 80)
    182
--> 183 assert V4_MANIFEST.exists(), V4_MANIFEST
    184 assert IMAGE_MANIFEST.exists(), IMAGE_MANIFEST
    185 assert STRUCTURED_CSV.exists(), STRUCTURED_CSV

AssertionError: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv

======================================================================
CHECKPOINT METADATA
Exists: True
Size (GB): 4.321
Modified: 2026-09-29T04:20:44
Top-level keys: ['epoch', 'batch_idx', 'global_step', 'model_state', 'optimizer_state', 'scheduler_state', 'best_val', 'history', 'rng_state', 'cuda_rng_state', 'python_rng_state', 'numpy_rng_state']
epoch: 5
global_step: 1920

In [23]:
from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
from datetime import datetime
import torch

ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
CKPT = ROOT / "baseline_model_v5/checkpoints/best.pt"

print("=" * 70)
print("1. KIỂM TRA CÁC ĐƯỜNG DẪN MANIFEST")
print("=" * 70)

expected_paths = [
    ROOT / "baseline_model_v4/v4_training_manifest.csv",
    ROOT / "final_manifest/final_dataset_manifest.csv",
    ROOT / "v3_ontology_v2/v3_structured_targets_v2_2.csv",
]

for p in expected_paths:
    print(f"{p}")
    print("  exists:", p.exists())
    if p.exists():
        print("  size (MB):", round(p.stat().st_size / 1024**2, 2))
        print("  modified:", datetime.fromtimestamp(p.stat().st_mtime).isoformat())

print("\n" + "=" * 70)
print("2. TÌM CÁC FILE MANIFEST LIÊN QUAN")
print("=" * 70)

for pattern in [
    "*training*manifest*.csv",
    "*dataset*manifest*.csv",
    "*structured*target*.csv",
    "*ontology*.csv",
]:
    print(f"\nPattern: {pattern}")
    matches = list(ROOT.rglob(pattern))
    if not matches:
        print("  Không tìm thấy.")
    for p in matches[:40]:
        print(
            p.relative_to(ROOT),
            "| modified:",
            datetime.fromtimestamp(p.stat().st_mtime).isoformat(),
            "| MB:",
            round(p.stat().st_size / 1024**2, 2),
        )

print("\n" + "=" * 70)
print("3. LỊCH SỬ HUẤN LUYỆN TRONG CHECKPOINT")
print("=" * 70)

if not CKPT.exists():
    print("Không tìm thấy checkpoint:", CKPT)
else:
    ckpt = torch.load(CKPT, map_location="cpu", weights_only=False)

    print("epoch:", ckpt.get("epoch"))
    print("global_step:", ckpt.get("global_step"))
    print("best_val:", ckpt.get("best_val"))

    history = ckpt.get("history")
    print("history type:", type(history).__name__)

    if isinstance(history, dict):
        for key, value in history.items():
            print(f"\nHistory key: {key}")
            print("Value:", repr(value)[:4000])
    elif isinstance(history, (list, tuple)):
        print("History entries:", len(history))
        for item in history[-10:]:
            print(repr(item)[:1000])
    else:
        print("History:", repr(history)[:4000])

    del ckpt

print("\nHOÀN TẤT — chỉ đọc, không huấn luyện, không lưu thay đổi.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
======================================================================
1. KIỂM TRA CÁC ĐƯỜNG DẪN MANIFEST
======================================================================
/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv
  exists: True
  size (MB): 1.83
  modified: 2026-09-22T16:26:41
/content/drive/MyDrive/NoiSoi_Matching/final_manifest/final_dataset_manifest.csv
  exists: True
  size (MB): 51.84
  modified: 2026-09-18T02:08:30
/content/drive/MyDrive/NoiSoi_Matching/v3_ontology_v2/v3_structured_targets_v2_2.csv
  exists: True
  size (MB): 5.94
  modified: 2026-09-21T16:51:22

======================================================================
2. TÌM CÁC FILE MANIFEST LIÊN QUAN
======================================================================

Pattern: *training*manifest*.csv
baseline_model_v3/v3_training_manifest.csv | modified: 2026-09-21T16:52:13 | MB: 1.83
baseline_model_v4/v4_training_manifest.csv | modified: 2026-09-22T16:26:41 | MB: 1.83

Pattern: *dataset*manifest*.csv
final_manifest/final_dataset_manifest.csv | modified: 2026-09-18T02:08:30 | MB: 51.84

Pattern: *structured*target*.csv
v3_ontology_v1/v3_structured_targets.csv | modified: 2026-09-21T16:47:19 | MB: 5.09
v3_ontology_v1/v3_structured_targets_v1_1_audit.csv | modified: 2026-09-21T16:48:50 | MB: 5.36
v3_ontology_v2/v3_structured_targets_v2.csv | modified: 2026-09-21T16:50:06 | MB: 5.93
v3_ontology_v2/v3_structured_targets_v2_1.csv | modified: 2026-09-21T16:50:47 | MB: 5.94
v3_ontology_v2/v3_structured_targets_v2_2.csv | modified: 2026-09-21T16:51:22 | MB: 5.94

Pattern: *ontology*.csv
v3_ontology_v1/ontology_v1_1_audit_summary.csv | modified: 2026-09-21T16:48:50 | MB: 0.0
baseline_model_v4/diagnostics/frozen_concept_ontology_mapping.csv | modified: 2026-09-22T16:26:41 | MB: 0.0

======================================================================
3. LỊCH SỬ HUẤN LUYỆN TRONG CHECKPOINT
======================================================================
epoch: 5
global_step: 1920
best_val: 0.424518172663671
history type: dict

History key: train_loss
Value: [0.5731708970967303, 0.5046075203082849, 0.47171955251829634, 0.45422747778290645, 0.44715843725379206]

History key: val_loss
Value: [0.46700948011622856, 0.44155955633946825, 0.42823387978095856, 0.4258775923539091, 0.424518172663671]

HOÀN TẤT — chỉ đọc, không huấn luyện, không lưu thay đổi.

In [24]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
from datetime import datetime
import pandas as pd
import json

ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
V4_PATH = ROOT / "baseline_model_v4/v4_training_manifest.csv"
IMG_PATH = ROOT / "final_manifest/final_dataset_manifest.csv"
STRUCT_PATH = ROOT / "v3_ontology_v2/v3_structured_targets_v2_2.csv"
MAP_PATH = ROOT / "baseline_model_v4/diagnostics/frozen_concept_ontology_mapping.csv"
PRED_PATH = ROOT / "baseline_model_v5/test_predictions_712.csv"
OUT = ROOT / "baseline_model_v5/diagnostics/audit_20261015"
OUT.mkdir(parents=True, exist_ok=True)

report = []

def log(s=""):
    print(s)
    report.append(str(s))

def inspect_csv(path, name):
    log(f"\n{'=' * 75}\n{name}\n{'=' * 75}")
    log(f"Path: {path}")
    log(f"Exists: {path.exists()}")
    if not path.exists():
        return None
    log(f"Size MB: {path.stat().st_size / 1024**2:.3f}")
    log(f"Modified: {datetime.fromtimestamp(path.stat().st_mtime).isoformat()}")
    df = pd.read_csv(path, low_memory=False)
    log(f"Shape: {df.shape}")
    log(f"Columns ({len(df.columns)}): {df.columns.tolist()}")
    if "case_id" in df.columns:
        ids = df["case_id"].astype(str)
        log(f"Unique case_id: {ids.nunique()} / {len(df)}")
        log(f"Duplicate case_id rows: {int(ids.duplicated().sum())}")
    return df

v4 = inspect_csv(V4_PATH, "V4 TRAINING MANIFEST")
img = inspect_csv(IMG_PATH, "IMAGE MANIFEST")
st = inspect_csv(STRUCT_PATH, "STRUCTURED TARGET CSV")
mapping = inspect_csv(MAP_PATH, "FROZEN ONTOLOGY MAPPING")
pred = inspect_csv(PRED_PATH, "TEST PREDICTIONS")

if v4 is not None:
    log("\n[V4 vector/count/mask columns]")
    for c in v4.columns:
        if any(k in c.lower() for k in [
            "concept", "negative", "attribute", "structured", "split"
        ]):
            log(f"{c}: {v4[c].head(3).tolist()}")

if st is not None:
    log("\n[Structured CSV: column groups]")
    for prefix in ("concept__", "negative__", "attribute__"):
        cols = [c for c in st.columns if c.startswith(prefix)]
        log(f"{prefix}: {len(cols)}")
        log(f"Names: {cols}")

    log("\n[Potential serialized label columns]")
    for c in st.columns:
        if any(k in c.lower() for k in [
            "concept", "negative", "attribute", "finding"
        ]) and not c.startswith(("concept__", "negative__", "attribute__")):
            log(f"{c}: {st[c].head(3).tolist()}")

if mapping is not None:
    log("\n[Mapping table preview]")
    log(mapping.head(20).to_string(index=False))

if v4 is not None and st is not None:
    a, b = set(v4["case_id"].astype(str)), set(st["case_id"].astype(str))
    log("\n[CASE ID OVERLAP]")
    log(f"V4 IDs: {len(a)} | Structured IDs: {len(b)}")
    log(f"Overlap: {len(a & b)}")
    log(f"Only V4: {len(a - b)}")
    log(f"Only Structured: {len(b - a)}")

report_path = OUT / "cell1_schema_ontology_audit.txt"
report_path.write_text("\n".join(report), encoding="utf-8")
print("\nSaved report:", report_path)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

===========================================================================
V4 TRAINING MANIFEST
===========================================================================
Path: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv
Exists: True
Size MB: 1.833
Modified: 2026-09-22T16:26:41
Shape: (7606, 15)
Columns (15): ['case_id', 'patient_group_id', 'split', 'ket_luan', 'concepts_v2_str', 'negative_findings_str', 'attributes_v2_str', 'concept_vector_str', 'negative_vector_str', 'attribute_vector_str', 'has_structured_label', 'structured_loss_mask', 'num_concepts_v2', 'num_negative_findings', 'num_attributes_v2']
Unique case_id: 7606 / 7606
Duplicate case_id rows: 0

===========================================================================
IMAGE MANIFEST
===========================================================================
Path: /content/drive/MyDrive/NoiSoi_Matching/final_manifest/final_dataset_manifest.csv
Exists: True
Size MB: 51.841
Modified: 2026-09-18T02:08:30
Shape: (76405, 26)
Columns (26): ['case_id', 'image_order', 'image_path', 'image_name', 'record_id', 'datetime', 'date', 'image_index', 'n_images_case', 'is_no_signal_v3', 'image_status', 'patient_group_id', 'split', 'pdf_path', 'ho_ten', 'nam_sinh', 'gioi_tinh_clean', 'ly_do_noi_soi', 'tai', 'hoc_mui', 'hong_mui', 'hong_thanh_quan', 'hong_mieng', 'ket_luan', 'phan_biet', 'de_nghi']
Unique case_id: 7607 / 76405
Duplicate case_id rows: 68798

===========================================================================
STRUCTURED TARGET CSV
===========================================================================
Path: /content/drive/MyDrive/NoiSoi_Matching/v3_ontology_v2/v3_structured_targets_v2_2.csv
Exists: True
Size MB: 5.945
Modified: 2026-09-21T16:51:22
Shape: (7606, 102)
Columns (102): ['case_id', 'patient_group_id', 'split', 'pdf_path', 'ho_ten', 'nam_sinh', 'gioi_tinh_clean', 'ly_do_noi_soi', 'tai', 'hoc_mui', 'hong_mui', 'hong_thanh_quan', 'hong_mieng', 'ket_luan', 'phan_biet', 'de_nghi', 'target_norm', 'concepts', 'attributes', 'num_concepts', 'num_attributes', 'concept__viem_ong_tai_ngoai', 'concept__nhot_ong_tai_ngoai', 'concept__chan_thuong_ong_tai_ngoai', 'concept__viem_tai_giua', 'concept__viem_mang_nhi', 'concept__thung_mang_nhi', 'concept__xep_mang_nhi', 'concept__ray_tai', 'concept__viem_tai_xuong_chum', 'concept__hau_phau_va_nhi', 'concept__di_vat_tai', 'concept__viem_mui', 'concept__viem_mui_xoang', 'concept__viem_xoang', 'concept__polyp_mui', 'concept__chay_mau_mui', 'concept__dich_vat_mui', 'concept__hoc_xuong_ca', 'concept__di_vat_hong_thanh_quan', 'concept__di_vat', 'concept__hau_phau_mui_xoang', 'concept__tien_dinh_mui', 'concept__lech_vach_ngan', 'concept__viem_va', 'concept__qua_phat_va', 'concept__viem_amidan', 'concept__amidan_qua_phat', 'concept__viem_hong', 'concept__viem_mieng', 'concept__viem_luoi', 'concept__ap_to_mieng', 'concept__viem_thanh_quan', 'concept__hat_day_thanh', 'concept__polyp_day_thanh', 'concept__liet_day_thanh', 'concept__theo_doi_trao_nguoc', 'concept__khong_thay_benh_ly_tai', 'concept__khong_thay_benh_ly', 'concept__khong_thay_diem_chay_mau', 'concept__khong_thay_di_vat', 'attribute__acute', 'attribute__chronic', 'attribute__right', 'attribute__left', 'attribute__bilateral', 'attribute__post_surgery', 'has_concept', 'has_attribute', 'ambiguity_reason', 'concept_signature', 'concepts_str', 'attributes_str', 'concepts_v2', 'negative_findings', 'attributes_v2', 'concept__hep_ong_tai_ngoai', 'concept__polyp_ong_tai_ngoai', 'concept__chan_thuong_mang_nhi', 'concept__viem_vanh_tai', 'concept__tu_dich_vanh_tai', 'concept__ro_luan_nhi', 'concept__not_vanh_tai', 'concept__u_hoc_mui', 'concept__u_nhu_hoc_mui', 'concept__u_nhu_cuon_mui', 'concept__u_xoang', 'concept__seo_hoc_mui', 'concept__nang_day_thanh', 'concept__di_vat_hong', 'negative__no_abnormal_external_middle_ear', 'negative__no_abnormal_nose_sinus', 'negative__no_abnormal_ent', 'negative__no_bleeding', 'negative__no_foreign_body', 'concepts_v2_str', 'negative_findings_str', 'attributes_v2_str', 'num_concepts_v2', 'num_negative_findings', 'num_attributes_v2', 'has_structured_label']
Unique case_id: 7606 / 7606
Duplicate case_id rows: 0

===========================================================================
FROZEN ONTOLOGY MAPPING
===========================================================================
Path: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/diagnostics/frozen_concept_ontology_mapping.csv
Exists: True
Size MB: 0.002
Modified: 2026-09-22T16:26:41
Shape: (48, 3)
Columns (3): ['dimension', 'column', 'label']

===========================================================================
TEST PREDICTIONS
===========================================================================
Path: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/test_predictions_712.csv
Exists: True
Size MB: 0.060
Modified: 2026-09-30T16:34:27
Shape: (712, 3)
Columns (3): ['case_id', 'prediction', 'ground_truth']
Unique case_id: 712 / 712
Duplicate case_id rows: 0

[V4 vector/count/mask columns]
split: ['train', 'train', 'train']
concepts_v2_str: ['viem_mui', 'viem_mui', 'viem_mui']
negative_findings_str: [nan, nan, nan]
attributes_v2_str: ['chronic', nan, 'chronic']
concept_vector_str: ['0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0', '0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0', '0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0']
negative_vector_str: ['0,0,0,0,0', '0,0,0,0,0', '0,0,0,0,0']
attribute_vector_str: ['0,0,1,0,0,0', '0,0,0,0,0,0', '0,0,1,0,0,0']
has_structured_label: [True, True, True]
structured_loss_mask: [1.0, 1.0, 1.0]
num_concepts_v2: [1, 1, 1]
num_negative_findings: [0, 0, 0]
num_attributes_v2: [1, 0, 1]

[Structured CSV: column groups]
concept__: 54
Names: ['concept__viem_ong_tai_ngoai', 'concept__nhot_ong_tai_ngoai', 'concept__chan_thuong_ong_tai_ngoai', 'concept__viem_tai_giua', 'concept__viem_mang_nhi', 'concept__thung_mang_nhi', 'concept__xep_mang_nhi', 'concept__ray_tai', 'concept__viem_tai_xuong_chum', 'concept__hau_phau_va_nhi', 'concept__di_vat_tai', 'concept__viem_mui', 'concept__viem_mui_xoang', 'concept__viem_xoang', 'concept__polyp_mui', 'concept__chay_mau_mui', 'concept__dich_vat_mui', 'concept__hoc_xuong_ca', 'concept__di_vat_hong_thanh_quan', 'concept__di_vat', 'concept__hau_phau_mui_xoang', 'concept__tien_dinh_mui', 'concept__lech_vach_ngan', 'concept__viem_va', 'concept__qua_phat_va', 'concept__viem_amidan', 'concept__amidan_qua_phat', 'concept__viem_hong', 'concept__viem_mieng', 'concept__viem_luoi', 'concept__ap_to_mieng', 'concept__viem_thanh_quan', 'concept__hat_day_thanh', 'concept__polyp_day_thanh', 'concept__liet_day_thanh', 'concept__theo_doi_trao_nguoc', 'concept__khong_thay_benh_ly_tai', 'concept__khong_thay_benh_ly', 'concept__khong_thay_diem_chay_mau', 'concept__khong_thay_di_vat', 'concept__hep_ong_tai_ngoai', 'concept__polyp_ong_tai_ngoai', 'concept__chan_thuong_mang_nhi', 'concept__viem_vanh_tai', 'concept__tu_dich_vanh_tai', 'concept__ro_luan_nhi', 'concept__not_vanh_tai', 'concept__u_hoc_mui', 'concept__u_nhu_hoc_mui', 'concept__u_nhu_cuon_mui', 'concept__u_xoang', 'concept__seo_hoc_mui', 'concept__nang_day_thanh', 'concept__di_vat_hong']
negative__: 5
Names: ['negative__no_abnormal_external_middle_ear', 'negative__no_abnormal_nose_sinus', 'negative__no_abnormal_ent', 'negative__no_bleeding', 'negative__no_foreign_body']
attribute__: 6
Names: ['attribute__acute', 'attribute__chronic', 'attribute__right', 'attribute__left', 'attribute__bilateral', 'attribute__post_surgery']

[Potential serialized label columns]
concepts: ["['viem_mui']", "['viem_mui']", "['viem_mui']"]
attributes: ["['chronic']", '[]', "['chronic']"]
num_concepts: [1, 1, 1]
num_attributes: [1, 0, 1]
has_concept: [True, True, True]
has_attribute: [True, False, True]
concept_signature: ['viem_mui', 'viem_mui', 'viem_mui']
concepts_str: ['viem_mui', 'viem_mui', 'viem_mui']
attributes_str: ['chronic', nan, 'chronic']
concepts_v2: ["['viem_mui']", "['viem_mui']", "['viem_mui']"]
negative_findings: ['[]', '[]', '[]']
attributes_v2: ["['chronic']", '[]', "['chronic']"]
concepts_v2_str: ['viem_mui', 'viem_mui', 'viem_mui']
negative_findings_str: [nan, nan, nan]
attributes_v2_str: ['chronic', nan, 'chronic']
num_concepts_v2: [1, 1, 1]
num_negative_findings: [0, 0, 0]
num_attributes_v2: [1, 0, 1]

[Mapping table preview]
 dimension                             column                     label
         0           concept__amidan_qua_phat           amidan_qua_phat
         1      concept__chan_thuong_mang_nhi      chan_thuong_mang_nhi
         2 concept__chan_thuong_ong_tai_ngoai chan_thuong_ong_tai_ngoai
         3              concept__chay_mau_mui              chay_mau_mui
         4               concept__di_vat_hong               di_vat_hong
         5    concept__di_vat_hong_thanh_quan    di_vat_hong_thanh_quan
         6                concept__di_vat_tai                di_vat_tai
         7              concept__dich_vat_mui              dich_vat_mui
         8             concept__hat_day_thanh             hat_day_thanh
         9        concept__hau_phau_mui_xoang        hau_phau_mui_xoang
        10           concept__hau_phau_va_nhi           hau_phau_va_nhi
        11         concept__hep_ong_tai_ngoai         hep_ong_tai_ngoai
        12              concept__hoc_xuong_ca              hoc_xuong_ca
        13            concept__lech_vach_ngan            lech_vach_ngan
        14            concept__liet_day_thanh            liet_day_thanh
        15            concept__nang_day_thanh            nang_day_thanh
        16        concept__nhot_ong_tai_ngoai        nhot_ong_tai_ngoai
        17              concept__not_vanh_tai              not_vanh_tai
        18           concept__polyp_day_thanh           polyp_day_thanh
        19                 concept__polyp_mui                 polyp_mui

[CASE ID OVERLAP]
V4 IDs: 7606 | Structured IDs: 7606
Overlap: 7606
Only V4: 0
Only Structured: 0

Saved report: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell1_schema_ontology_audit.txt

In [25]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
import pandas as pd
import numpy as np
import ast, json, re

ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
V4_PATH = ROOT / "baseline_model_v4/v4_training_manifest.csv"
OUT = ROOT / "baseline_model_v5/diagnostics/audit_20261015"
OUT.mkdir(parents=True, exist_ok=True)

df = pd.read_csv(V4_PATH, low_memory=False)
print("Rows:", len(df), "| Columns:", len(df.columns))

def parse_vector(value):
    if pd.isna(value):
        return None
    if isinstance(value, (list, tuple, np.ndarray)):
        return np.asarray(value, dtype=float).reshape(-1)
    s = str(value).strip()
    if not s:
        return None
    for parser in (ast.literal_eval, json.loads):
        try:
            obj = parser(s)
            if isinstance(obj, (list, tuple, np.ndarray)):
                return np.asarray(obj, dtype=float).reshape(-1)
        except Exception:
            pass
    # Fallback only for simple numeric vectors.
    if s.startswith("[") and s.endswith("]"):
        vals = re.findall(r"[-+]?(?:\d*\.)?\d+(?:[eE][-+]?\d+)?", s)
        if vals:
            return np.asarray(vals, dtype=float)
    return None

expected = {
    "concept_vector_str": 48,
    "negative_vector_str": 5,
    "attribute_vector_str": 6,
}
count_cols = {
    "concept_vector_str": "num_concepts_v2",
    "negative_vector_str": "num_negative_findings",
    "attribute_vector_str": "num_attributes_v2",
}

issues = []
summary = []

for _, row in df.iterrows():
    cid = str(row.get("case_id", ""))
    record = {"case_id": cid, "split": row.get("split", None)}
    for col, dim in expected.items():
        if col not in df.columns:
            record[col + "_issue"] = "MISSING_COLUMN"
            continue

        vec = parse_vector(row[col])
        if vec is None:
            record[col + "_issue"] = "PARSE_FAILED_OR_NULL"
            continue

        record[col + "_length"] = len(vec)
        record[col + "_sum"] = float(np.nansum(vec))
        if len(vec) != dim:
            record[col + "_issue"] = f"WRONG_LENGTH_{len(vec)}_EXPECTED_{dim}"
        elif not np.isfinite(vec).all():
            record[col + "_issue"] = "NONFINITE_VALUE"
        elif not np.isin(vec, [0, 1]).all():
            record[col + "_issue"] = "NON_BINARY_VALUE"
        else:
            record[col + "_issue"] = ""

        cnt_col = count_cols[col]
        if cnt_col in df.columns and len(vec) == dim:
            try:
                count_value = float(row[cnt_col])
                if np.isfinite(count_value) and int(vec.sum()) != int(count_value):
                    record[col + "_count_issue"] = (
                        f"VECTOR_SUM_{int(vec.sum())}_COUNT_COL_{int(count_value)}"
                    )
                else:
                    record[col + "_count_issue"] = ""
            except Exception:
                record[col + "_count_issue"] = "COUNT_PARSE_FAILED"

    mask = row.get("structured_loss_mask", np.nan)
    try:
        mask = float(mask)
        record["mask_issue"] = "" if mask in (0.0, 1.0) else f"UNEXPECTED_MASK_{mask}"
    except Exception:
        record["mask_issue"] = "MASK_MISSING_OR_INVALID"

    all_issues = [
        (k, v) for k, v in record.items()
        if k.endswith("_issue") and v
    ]
    if all_issues:
        record["issue_details"] = "; ".join(f"{k}={v}" for k, v in all_issues)
        issues.append(record)

print("\n===== VECTOR AUDIT SUMMARY =====")
print("Cases:", len(df))
print("Cases with at least one issue:", len(issues))
print("Split counts:")
if "split" in df.columns:
    print(df["split"].value_counts(dropna=False).to_string())

for col, dim in expected.items():
    print(f"\n{col}: expected dimension {dim}")
    if col not in df.columns:
        print("  MISSING COLUMN")
        continue
    parsed = df[col].map(parse_vector)
    lengths = parsed.map(lambda x: len(x) if x is not None else -1)
    print("  Length distribution:", lengths.value_counts().sort_index().to_dict())
    valid = parsed[parsed.map(lambda x: x is not None and len(x) == dim)]
    if len(valid):
        sums = valid.map(lambda x: int(np.sum(x)))
        print("  Vector-sum distribution:", sums.value_counts().sort_index().to_dict())

issue_path = OUT / "cell2_vector_issues.csv"
summary_path = OUT / "cell2_split_summary.csv"
pd.DataFrame(issues).to_csv(issue_path, index=False)

if "split" in df.columns:
    split_rows = []
    for split, part in df.groupby("split", dropna=False):
        item = {"split": split, "cases": len(part)}
        for col in expected:
            if col in part.columns:
                parsed = part[col].map(parse_vector)
                item[col + "_parse_failures"] = int(parsed.isna().sum())
                item[col + "_expected_length"] = expected[col]
                item[col + "_wrong_length"] = int(
                    parsed.map(lambda x: x is None or len(x) != expected[col]).sum()
                )
        split_rows.append(item)
    pd.DataFrame(split_rows).to_csv(summary_path, index=False)

print("\nSaved issue file:", issue_path)
print("Saved split summary:", summary_path)
print("Read-only audit complete; no model or checkpoint changed.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Rows: 7606 | Columns: 15

===== VECTOR AUDIT SUMMARY =====
Cases: 7606
Cases with at least one issue: 0
Split counts:
split
train    6138
val       756
test      712

concept_vector_str: expected dimension 48
  Length distribution: {48: 7606}
  Vector-sum distribution: {0: 419, 1: 4708, 2: 2163, 3: 294, 4: 21, 5: 1}

negative_vector_str: expected dimension 5
  Length distribution: {5: 7606}
  Vector-sum distribution: {0: 6806, 1: 730, 2: 70}

attribute_vector_str: expected dimension 6
  Length distribution: {6: 7606}
  Vector-sum distribution: {0: 2337, 1: 3202, 2: 1669, 3: 316, 4: 70, 5: 12}

Saved issue file: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell2_vector_issues.csv
Saved split summary: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell2_split_summary.csv
Read-only audit complete; no model or checkpoint changed.

In [26]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
from collections import Counter
import pandas as pd
import numpy as np
import re, unicodedata

ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
PRED_PATH = ROOT / "baseline_model_v5/test_predictions_712.csv"
OUT = ROOT / "baseline_model_v5/diagnostics/audit_20261015"
OUT.mkdir(parents=True, exist_ok=True)

df = pd.read_csv(PRED_PATH, low_memory=False)
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print(df.head(5).to_string(index=False))

def norm_text(x):
    if pd.isna(x):
        return ""
    s = unicodedata.normalize("NFKC", str(x)).lower().strip()
    s = re.sub(r"[^\w\s]", " ", s, flags=re.UNICODE)
    return re.sub(r"\s+", " ", s).strip()

def choose_col(columns, candidates):
    lower = {str(c).lower(): c for c in columns}
    for name in candidates:
        if name in lower:
            return lower[name]
    for c in columns:
        cl = str(c).lower()
        if any(name in cl for name in candidates):
            return c
    return None

id_col = choose_col(df.columns, ["case_id"])
pred_col = choose_col(df.columns, [
    "prediction", "predicted_text", "pred_text",
    "generated_text", "y_pred", "predicted", "pred"
])
true_col = choose_col(df.columns, [
    "ground_truth", "true_label", "target_text",
    "y_true", "ket_luan", "reference", "label", "target"
])

print("\nDetected case ID:", id_col)
print("Detected prediction:", pred_col)
print("Detected ground truth:", true_col)

lines = [
    f"Rows: {len(df)}",
    f"Columns: {df.columns.tolist()}",
    f"Detected ID: {id_col}",
    f"Detected prediction: {pred_col}",
    f"Detected ground truth: {true_col}",
]
case_report = []

if pred_col is None or true_col is None:
    lines.append(
        "Metrics not calculated because prediction/ground-truth columns "
        "could not be identified safely."
    )
else:
    d = df.copy()
    d["_pred_norm"] = d[pred_col].map(norm_text)
    d["_true_norm"] = d[true_col].map(norm_text)
    d["_exact_match"] = d["_pred_norm"] == d["_true_norm"]

    def token_f1(p, t):
        pt, tt = p.split(), t.split()
        if not pt or not tt:
            return float(pt == tt)
        pc, tc = Counter(pt), Counter(tt)
        overlap = sum((pc & tc).values())
        if overlap == 0:
            return 0.0
        precision = overlap / len(pt)
        recall = overlap / len(tt)
        return 2 * precision * recall / (precision + recall)

    d["_token_f1"] = [
        token_f1(p, t) for p, t in zip(d["_pred_norm"], d["_true_norm"])
    ]

    pred_counts = d["_pred_norm"].value_counts(dropna=False)
    lines.extend([
        f"Rows evaluated: {len(d)}",
        f"Unique normalized predictions: {d['_pred_norm'].nunique()}",
        f"Unique normalized ground truths: {d['_true_norm'].nunique()}",
        f"Exact match: {d['_exact_match'].mean():.4f}",
        f"Mean token F1: {d['_token_f1'].mean():.4f}",
        f"Top prediction share: {pred_counts.iloc[0] / len(d):.4f}",
        "\nTop 20 predictions:",
        pred_counts.head(20).to_string(),
        "\nTop 20 ground-truth labels:",
        d["_true_norm"].value_counts().head(20).to_string(),
    ])

    # Cases with mismatch, longest/shortest labels and case ID if available.
    mismatch = d.loc[~d["_exact_match"]].copy()
    cols = [c for c in [id_col, true_col, pred_col, "_token_f1"] if c is not None]
    mismatch[cols].to_csv(OUT / "cell3_prediction_mismatches.csv", index=False)

    d[cols + ["_exact_match"]].to_csv(
        OUT / "cell3_prediction_case_metrics.csv", index=False
    )

    print("\n===== PREDICTION METRICS =====")
    print("\n".join(lines))

report_path = OUT / "cell3_prediction_audit.txt"
report_path.write_text("\n".join(lines), encoding="utf-8")

print("\nSaved report:", report_path)
print("Saved mismatch CSV:", OUT / "cell3_prediction_mismatches.csv")
print("Saved per-case CSV:", OUT / "cell3_prediction_case_metrics.csv")
print("\nAudit complete. No training, no checkpoint overwrite.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Shape: (712, 3)
Columns: ['case_id', 'prediction', 'ground_truth']
            case_id                                   prediction                                         ground_truth
10017.10017.0.10031          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP      VIÊM MÀNG NHĨ CẤP BÓNG NƯỚC P - NHIỀU RÁY TAI T
10057.10057.0.10071          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP       VIÊM ỐNG TAI NGOÀI (T) MẠN / VIÊM MŨI ĐỢT CẤP.
10116.10116.0.10130          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                    VIÊM ỐNG TAI NGOÀI MÀNG NHĨ P CẤP
10125.10125.0.10139                                 VIÊM MŨI MẠN VIÊM MŨI MẠN VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ 2 BÊN MẠN
10126.10126.0.10140 VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.                                       VIÊM A-MI-ĐAN.

Detected case ID: case_id
Detected prediction: prediction
Detected ground truth: ground_truth

===== PREDICTION METRICS =====
Rows: 712
Columns: ['case_id', 'prediction', 'ground_truth']
Detected ID: case_id
Detected prediction: prediction
Detected ground truth: ground_truth
Rows evaluated: 712
Unique normalized predictions: 16
Unique normalized ground truths: 243
Exact match: 0.1896
Mean token F1: 0.6097
Top prediction share: 0.4551

Top 20 predictions:
_pred_norm
viêm mũi mạn                                 324
viêm ống tai ngoài màng nhĩ t cấp            126
viêm họng mạn theo dõi trào ngược dịch vị     81
viêm mũi xoang                                52
viêm mũi va                                   47
viêm tai giữa p mạn                           46
viêm tai giữa t cấp viêm mũi                  10
viêm ống tai ngoài màng nhĩ t                  8
viêm mũi xoang mạn polyp mũi                   6
viêm ống tai ngoài 2 bên mạn                   4
viêm ống tai ngoài p cấp                       2
viêm tai giữa t mạn                            2
viêm tai giữa t cấp viêm mũi xoang             1
viêm tai giữa 2 bên viêm mũi                   1
viêm mũi                                       1
viêm mũi xoang va                              1

Top 20 ground-truth labels:
_true_norm
viêm mũi mạn                                                                  83
viêm mũi                                                                      67
viêm họng mạn theo dõi trào ngược dịch vị                                     51
viêm mũi xoang                                                                36
hiện không thấy hình ảnh bệnh lý tai ngoài tai giữa trên nội soi              23
viêm mũi đợt cấp                                                              18
viêm mũi va                                                                   14
viêm ống tai ngoài màng nhĩ p cấp                                             12
viêm mũi mạn va                                                               12
viêm ống tai ngoài màng nhĩ p                                                 10
hiện không thấy hình ảnh bệnh lý tai ngoài tai giữa trên nội soi viêm mũi     10
viêm tai giữa t mạn                                                           10
viêm mũi xoang mạn polyp mũi                                                   9
viêm tai giữa t mạn viêm mũi xoang mạn đã ptns mũi xoang                       9
viêm mũi xoang mạn đã pt                                                       7
viêm mũi xoang viêm va                                                         7
viêm mũi mạn viêm va                                                           6
viêm ống tai ngoài màng nhĩ t cấp                                              6
hiện không thấy hình ảnh bệnh lý mũi xoang tai ngoài tai giữa trên nội soi     6
viêm mũi viêm xoang p                                                          5

Saved report: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell3_prediction_audit.txt
Saved mismatch CSV: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell3_prediction_mismatches.csv
Saved per-case CSV: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell3_prediction_case_metrics.csv

Audit complete. No training, no checkpoint overwrite.

In [27]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
import pandas as pd
import numpy as np
import ast, json

ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
V4_PATH = ROOT / "baseline_model_v4/v4_training_manifest.csv"
STRUCT_PATH = ROOT / "v3_ontology_v2/v3_structured_targets_v2_2.csv"
MAP_PATH = ROOT / "baseline_model_v4/diagnostics/frozen_concept_ontology_mapping.csv"
OUT = ROOT / "baseline_model_v5/diagnostics/audit_20261015"
OUT.mkdir(parents=True, exist_ok=True)

v4 = pd.read_csv(V4_PATH, low_memory=False)
st = pd.read_csv(STRUCT_PATH, low_memory=False)
mp = pd.read_csv(MAP_PATH, low_memory=False)

def parse_vec(x):
    if pd.isna(x):
        return []
    s = str(x).strip()
    try:
        z = ast.literal_eval(s)
        if isinstance(z, (list, tuple)):
            return [int(float(v)) for v in z]
    except Exception:
        pass
    try:
        return [int(float(v.strip())) for v in s.split(",")]
    except Exception:
        return []

# Sort mapping by explicit dimension, never by current CSV column order.
mp["dimension"] = pd.to_numeric(mp["dimension"], errors="coerce")
mp = mp.sort_values("dimension").reset_index(drop=True)

print("Mapping rows:", len(mp))
print("Dimensions:", mp["dimension"].tolist())
print("Unique dimensions:", mp["dimension"].nunique())
print("Unique mapping columns:", mp["column"].nunique())
print("\nFull frozen mapping:")
print(mp.to_string(index=False))

mapping_labels = mp["label"].astype(str).tolist()
mapping_columns = mp["column"].astype(str).tolist()

# Structured wide columns are only a comparison source; don't assume their order.
wide_cols = [c for c in st.columns if c.startswith("concept__")]
wide_labels = {c.removeprefix("concept__"): c for c in wide_cols}

# Match each V4 serialized concept list against mapping labels.
# A one-hot vector should point to the corresponding serialized concept if
# the mapping and V4 vectors use the same ontology/order.
merged = v4[[
    "case_id", "split", "concepts_v2_str",
    "concept_vector_str", "num_concepts_v2"
]].merge(
    st[["case_id"] + wide_cols],
    on="case_id", how="left", validate="one_to_one",
    suffixes=("_v4", "_wide")
)

issues = []
dimension_rows = []

for _, row in merged.iterrows():
    vec = parse_vec(row["concept_vector_str"])
    if len(vec) != 48:
        issues.append({
            "case_id": row["case_id"],
            "split": row["split"],
            "issue": f"vector length {len(vec)}",
        })
        continue

    serialized = str(row["concepts_v2_str"])
    try:
        parsed = ast.literal_eval(serialized)
        if isinstance(parsed, list):
            source_labels = [str(x) for x in parsed if str(x) != "nan"]
        else:
            source_labels = [x.strip() for x in serialized.split(",") if x.strip()]
    except Exception:
        source_labels = [x.strip() for x in serialized.split(",") if x.strip()]

    active_dims = [i for i, val in enumerate(vec) if val == 1]
    mapped_labels = [mapping_labels[i] for i in active_dims if i < len(mapping_labels)]

    # Compare vector-active labels against serialized source labels.
    source_set = set(source_labels)
    mapped_set = set(mapped_labels)

    if source_set != mapped_set:
        issues.append({
            "case_id": row["case_id"],
            "split": row["split"],
            "issue": "vector labels differ from concepts_v2_str",
            "source_labels": "|".join(sorted(source_set)),
            "mapped_labels": "|".join(sorted(mapped_set)),
            "active_dims": "|".join(map(str, active_dims)),
        })

    for i, col in enumerate(mapping_columns):
        if i >= len(vec):
            continue
        label = mapping_labels[i]
        wide_col = wide_labels.get(label)
        if wide_col is None:
            continue
        expected = pd.to_numeric(pd.Series([row[wide_col]]), errors="coerce").iloc[0]
        if pd.notna(expected) and int(expected) != int(vec[i]):
            dimension_rows.append({
                "case_id": row["case_id"],
                "split": row["split"],
                "dimension": i,
                "label": label,
                "vector_value": int(vec[i]),
                "wide_csv_value": int(expected),
                "wide_column": wide_col,
            })

issues_df = pd.DataFrame(issues)
dim_df = pd.DataFrame(dimension_rows)

issues_path = OUT / "cell4_vector_vs_serialized_labels.csv"
dims_path = OUT / "cell4_vector_vs_wide_columns.csv"
issues_df.to_csv(issues_path, index=False)
dim_df.to_csv(dims_path, index=False)

print("\n===== RESULT =====")
print("Cases compared:", len(merged))
print("Cases with vector vs serialized-label discrepancy:", len(issues_df))
print("Per-dimension wide-column discrepancies:", len(dim_df))
print("Cases with any wide-column discrepancy:",
      dim_df["case_id"].nunique() if len(dim_df) else 0)

if len(issues_df):
    print("\nExamples of serialized-label discrepancies:")
    print(issues_df.head(20).to_string(index=False))

if len(dim_df):
    print("\nExamples of wide-column discrepancies:")
    print(dim_df.head(30).to_string(index=False))

print("\nSaved:")
print(issues_path)
print(dims_path)
print("\nRead-only audit completed. Checkpoint untouched.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Mapping rows: 48
Dimensions: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]
Unique dimensions: 48
Unique mapping columns: 48

Full frozen mapping:
 dimension                             column                     label
         0           concept__amidan_qua_phat           amidan_qua_phat
         1      concept__chan_thuong_mang_nhi      chan_thuong_mang_nhi
         2 concept__chan_thuong_ong_tai_ngoai chan_thuong_ong_tai_ngoai
         3              concept__chay_mau_mui              chay_mau_mui
         4               concept__di_vat_hong               di_vat_hong
         5    concept__di_vat_hong_thanh_quan    di_vat_hong_thanh_quan
         6                concept__di_vat_tai                di_vat_tai
         7              concept__dich_vat_mui              dich_vat_mui
         8             concept__hat_day_thanh             hat_day_thanh
         9        concept__hau_phau_mui_xoang        hau_phau_mui_xoang
        10           concept__hau_phau_va_nhi           hau_phau_va_nhi
        11         concept__hep_ong_tai_ngoai         hep_ong_tai_ngoai
        12              concept__hoc_xuong_ca              hoc_xuong_ca
        13            concept__lech_vach_ngan            lech_vach_ngan
        14            concept__liet_day_thanh            liet_day_thanh
        15            concept__nang_day_thanh            nang_day_thanh
        16        concept__nhot_ong_tai_ngoai        nhot_ong_tai_ngoai
        17              concept__not_vanh_tai              not_vanh_tai
        18           concept__polyp_day_thanh           polyp_day_thanh
        19                 concept__polyp_mui                 polyp_mui
        20       concept__polyp_ong_tai_ngoai       polyp_ong_tai_ngoai
        21               concept__qua_phat_va               qua_phat_va
        22                   concept__ray_tai                   ray_tai
        23               concept__ro_luan_nhi               ro_luan_nhi
        24               concept__seo_hoc_mui               seo_hoc_mui
        25       concept__theo_doi_trao_nguoc       theo_doi_trao_nguoc
        26            concept__thung_mang_nhi            thung_mang_nhi
        27             concept__tien_dinh_mui             tien_dinh_mui
        28          concept__tu_dich_vanh_tai          tu_dich_vanh_tai
        29                 concept__u_hoc_mui                 u_hoc_mui
        30            concept__u_nhu_cuon_mui            u_nhu_cuon_mui
        31             concept__u_nhu_hoc_mui             u_nhu_hoc_mui
        32                   concept__u_xoang                   u_xoang
        33               concept__viem_amidan               viem_amidan
        34                 concept__viem_hong                 viem_hong
        35                 concept__viem_luoi                 viem_luoi
        36             concept__viem_mang_nhi             viem_mang_nhi
        37                concept__viem_mieng                viem_mieng
        38                  concept__viem_mui                  viem_mui
        39            concept__viem_mui_xoang            viem_mui_xoang
        40        concept__viem_ong_tai_ngoai        viem_ong_tai_ngoai
        41             concept__viem_tai_giua             viem_tai_giua
        42       concept__viem_tai_xuong_chum       viem_tai_xuong_chum
        43           concept__viem_thanh_quan           viem_thanh_quan
        44                   concept__viem_va                   viem_va
        45             concept__viem_vanh_tai             viem_vanh_tai
        46                concept__viem_xoang                viem_xoang
        47              concept__xep_mang_nhi              xep_mang_nhi

===== RESULT =====
Cases compared: 7606
Cases with vector vs serialized-label discrepancy: 2898
Per-dimension wide-column discrepancies: 0
Cases with any wide-column discrepancy: 0

Examples of serialized-label discrepancies:
            case_id split                                     issue                 source_labels                 mapped_labels active_dims
10010.10010.0.10024 train vector labels differ from concepts_v2_str theo_doi_trao_nguoc|viem_hong theo_doi_trao_nguoc|viem_hong       25|34
10012.10012.0.10026 train vector labels differ from concepts_v2_str        viem_mui|viem_tai_giua        viem_mui|viem_tai_giua       38|41
10013.10013.0.10027 train vector labels differ from concepts_v2_str        viem_mui|viem_tai_giua        viem_mui|viem_tai_giua       38|41
10014.10014.0.10028 train vector labels differ from concepts_v2_str theo_doi_trao_nguoc|viem_hong theo_doi_trao_nguoc|viem_hong       25|34
10016.10016.0.10030 train vector labels differ from concepts_v2_str  viem_mui_xoang|viem_tai_giua  viem_mui_xoang|viem_tai_giua       39|41
10017.10017.0.10031  test vector labels differ from concepts_v2_str         ray_tai|viem_mang_nhi         ray_tai|viem_mang_nhi       22|36
10021.10021.0.10035 train vector labels differ from concepts_v2_str   viem_mui|viem_ong_tai_ngoai   viem_mui|viem_ong_tai_ngoai       38|40
10022.10022.0.10036 train vector labels differ from concepts_v2_str  thung_mang_nhi|viem_tai_giua  thung_mang_nhi|viem_tai_giua       26|41
10023.10023.0.10037 train vector labels differ from concepts_v2_str                           nan
10025.10025.0.10039 train vector labels differ from concepts_v2_str           viem_mui|viem_xoang           viem_mui|viem_xoang       38|46
10026.10026.0.10040 train vector labels differ from concepts_v2_str           viem_mui|viem_xoang           viem_mui|viem_xoang       38|46
10028.10028.0.10042 train vector labels differ from concepts_v2_str                           nan
10031.10031.0.10045 train vector labels differ from concepts_v2_str theo_doi_trao_nguoc|viem_hong theo_doi_trao_nguoc|viem_hong       25|34
10036.10036.0.10050 train vector labels differ from concepts_v2_str      amidan_qua_phat|viem_mui      amidan_qua_phat|viem_mui        0|38
10039.10039.0.10053   val vector labels differ from concepts_v2_str theo_doi_trao_nguoc|viem_hong theo_doi_trao_nguoc|viem_hong       25|34
10041.10041.0.10055 train vector labels differ from concepts_v2_str        tien_dinh_mui|viem_mui        tien_dinh_mui|viem_mui       27|38
10044.10044.0.10058 train vector labels differ from concepts_v2_str  viem_mui_xoang|viem_tai_giua  viem_mui_xoang|viem_tai_giua       39|41
10049.10049.0.10063 train vector labels differ from concepts_v2_str        viem_mui|viem_tai_giua        viem_mui|viem_tai_giua       38|41
10051.10051.0.10065 train vector labels differ from concepts_v2_str              viem_mui|viem_va              viem_mui|viem_va       38|44
10057.10057.0.10071  test vector labels differ from concepts_v2_str   viem_mui|viem_ong_tai_ngoai   viem_mui|viem_ong_tai_ngoai       38|40

Saved:
/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell4_vector_vs_serialized_labels.csv
/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell4_vector_vs_wide_columns.csv

Read-only audit completed. Checkpoint untouched.

In [28]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
import pandas as pd
import numpy as np
import ast

ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
V4_PATH = ROOT / "baseline_model_v4/v4_training_manifest.csv"
OUT = ROOT / "baseline_model_v5/diagnostics/audit_20261015"
OUT.mkdir(parents=True, exist_ok=True)

df = pd.read_csv(V4_PATH, low_memory=False)

def parse_vector(x):
    if pd.isna(x):
        return []
    s = str(x).strip()
    try:
        value = ast.literal_eval(s)
        if isinstance(value, (list, tuple)):
            return [int(float(v)) for v in value]
    except (ValueError, SyntaxError, TypeError):
        pass
    try:
        return [int(float(v.strip())) for v in s.split(",")]
    except (ValueError, TypeError):
        return []

def parse_labels(x):
    if pd.isna(x):
        return set()
    s = str(x).strip()
    if not s or s.lower() in {"nan", "none", "null"}:
        return set()
    try:
        value = ast.literal_eval(s)
        if isinstance(value, (list, tuple, set)):
            return {
                str(v).strip()
                for v in value
                if str(v).strip() and str(v).strip().lower() not in {"nan", "none", "null"}
            }
    except (ValueError, SyntaxError, TypeError):
        pass
    return {
        part.strip()
        for part in s.split("|")
        if part.strip() and part.strip().lower() not in {"nan", "none", "null"}
    }

mapping_path = ROOT / "baseline_model_v4/diagnostics/frozen_concept_ontology_mapping.csv"
mapping = pd.read_csv(mapping_path).sort_values("dimension")
labels = mapping["label"].astype(str).tolist()

rows = []
for _, r in df.iterrows():
    vec = parse_vector(r["concept_vector_str"])
    source = parse_labels(r["concepts_v2_str"])

    if len(vec) != len(labels):
        rows.append({
            "case_id": r["case_id"],
            "split": r["split"],
            "issue": "wrong_vector_length",
            "source_labels": "|".join(sorted(source)),
            "vector_labels": "",
        })
        continue

    vector_labels = {
        labels[i] for i, value in enumerate(vec)
        if value == 1
    }
    if source != vector_labels:
        rows.append({
            "case_id": r["case_id"],
            "split": r["split"],
            "issue": "label_set_mismatch",
            "source_labels": "|".join(sorted(source)),
            "vector_labels": "|".join(sorted(vector_labels)),
        })

audit = pd.DataFrame(rows)
audit_path = OUT / "cell5_normalized_label_comparison.csv"
audit.to_csv(audit_path, index=False)

print("Total cases:", len(df))
print("Cases with normalized discrepancies:", len(audit))
if len(audit):
    print("\nIssue types:")
    print(audit["issue"].value_counts().to_string())
    print("\nFirst 20 discrepancies:")
    print(audit.head(20).to_string(index=False))
else:
    print("PASS: All serialized label sets match their vectors.")

print("\nSaved:", audit_path)
print("Read-only audit; no model training or checkpoint modification.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Total cases: 7606
Cases with normalized discrepancies: 0
PASS: All serialized label sets match their vectors.

Saved: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell5_normalized_label_comparison.csv
Read-only audit; no model training or checkpoint modification.

In [29]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
import json
import hashlib

ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
NB_PATH = Path("/content/drive/MyDrive/Colab Notebooks/25sep.ipynb")
OUT = ROOT / "baseline_model_v5/diagnostics/audit_20261015"
OUT.mkdir(parents=True, exist_ok=True)

assert NB_PATH.exists(), f"Notebook not found: {NB_PATH}"

with open(NB_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

cells = nb.get("cells", [])
print("Notebook:", NB_PATH.name)
print("Total cells:", len(cells))

keywords = [
    "def build_structured_targets",
    "V5 — FULL TRAINING",
    "V5 FULL TRAINING",
    "concept_vector_str",
    "negative_vector_str",
    "attribute_vector_str",
    "BCEWithLogitsLoss",
    "optimizer.step",
    "loss.backward",
    "best.pt",
    "load_state_dict",
]

report = []
for i, cell in enumerate(cells):
    source = "".join(cell.get("source", []))
    if any(k.lower() in source.lower() for k in keywords):
        report.append({
            "cell_index": i,
            "execution_count": cell.get("execution_count"),
            "source": source,
        })

for item in report:
    print("\n" + "=" * 90)
    print(
        f"CELL INDEX: {item['cell_index']} | "
        f"EXECUTION COUNT: {item['execution_count']}"
    )
    print("=" * 90)
    lines = item["source"].splitlines()
    hits = [
        j for j, line in enumerate(lines)
        if any(k.lower() in line.lower() for k in keywords)
    ]
    shown = set()
    for j in hits:
        for k in range(max(0, j - 3), min(len(lines), j + 5)):
            if k not in shown:
                print(f"{k+1:4}: {lines[k]}")
                shown.add(k)
        print("    ...")

out_path = OUT / "cell6_training_source_audit.txt"
with open(out_path, "w", encoding="utf-8") as f:
    for item in report:
        f.write(
            f"\n{'='*90}\nCELL INDEX: {item['cell_index']} | "
            f"EXECUTION COUNT: {item['execution_count']}\n"
        )
        f.write(item["source"])
        f.write("\n")

print("\nCells matched:", len(report))
print("Report saved:", out_path)
print("READ-ONLY: no training, no optimizer, no checkpoint writes.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Notebook: 25sep.ipynb
Total cells: 162

==========================================================================================
CELL INDEX: 0 | EXECUTION COUNT: None
==========================================================================================
  70: )
  71:
  72: BEST_CKPT = (
  73:     f"{V4_DIR}/checkpoints/best.pt"
  74: )
    ...

==========================================================================================
CELL INDEX: 1 | EXECUTION COUNT: None
==========================================================================================
  87: )
  88:
  89: BEST_CKPT = (
  90:     f"{V4_DIR}/checkpoints/best.pt"
  91: )
  92:
  93: # ------------------------------------------------
  94: # Path checks
    ...
1014: # Strict load
1015: # ------------------------------------------------
1016:
1017: load_result = model.load_state_dict(
1018:     E2["model_state"],
1019:     strict=True,
1020: )
1021:
    ...
1028:     E2["best_val"]
1029: )
1030:
1031: model.load_state_dict(
1032:     E3["model_state"],
1033:     strict=True,
1034: )
1035:
    ...
1099: # 14. SNAPSHOT
1100: # ================================================================
1101:
1102: model.load_state_dict(
1103:     E2["model_state"],
1104:     strict=True,
1105: )
1106:
    ...
1504:     print(checkpoint_name)
1505:     print("=" * 70)
1506:
1507:     model.load_state_dict(
1508:         checkpoint["model_state"],
1509:         strict=True,
1510:     )
1511:
    ...
1899: # RESTORE MODEL TO ORIGINAL E2 STATE
1900: # ================================================================
1901:
1902: model.load_state_dict(
1903:     model_snapshot,
1904:     strict=True,
1905: )
1906:
    ...

==========================================================================================
CELL INDEX: 2 | EXECUTION COUNT: None
==========================================================================================
  85: # ------------------------------------------------------------
  86: # STRICT LOAD E2
  87: # ------------------------------------------------------------
  88: model.load_state_dict(E2["model_state"], strict=True)
  89:
  90: print("\n✓ E2 STRICT LOAD PASSED")
  91:
  92: # ------------------------------------------------------------
    ...
  93: # STRICT LOAD E3
  94: # ------------------------------------------------------------
  95: model.load_state_dict(E3["model_state"], strict=True)
  96:
  97: print("✓ E3 STRICT LOAD PASSED")
  98:
  99: print("\n" + "=" * 70)
    ...

==========================================================================================
CELL INDEX: 5 | EXECUTION COUNT: None
==========================================================================================
 277:     print(f"CHECKPOINT: {epoch_name}")
 278:     print("=" * 70)
 279:
 280:     model.load_state_dict(
 281:         ckpt["model_state"],
 282:         strict=True,
 283:     )
 284:
    ...

==========================================================================================
CELL INDEX: 6 | EXECUTION COUNT: None
==========================================================================================
  56:     print(f"LOGIT INTERVENTION — {epoch_name}")
  57:     print("=" * 70)
  58:
  59:     model.load_state_dict(
  60:         ckpt["model_state"],
  61:         strict=True,
  62:     )
  63:
    ...

==========================================================================================
CELL INDEX: 7 | EXECUTION COUNT: None
==========================================================================================
  37:     f"found {len(val_loader.dataset)}"
  38: )
  39:
  40: model.load_state_dict(E3["model_state"], strict=True)
  41: model.to(device)
  42: model.eval()
  43:
  44: print("=" * 70)
    ...

==========================================================================================
CELL INDEX: 8 | EXECUTION COUNT: None
==========================================================================================
 381:     test_tokens.float().pow(2).mean()
 382: )
 383:
 384: dummy_loss.backward()
 385:
 386: print("\nGradient-path test:")
 387:
 388: print(
    ...
 549: # Clear previous grads
 550: v5.zero_grad(set_to_none=True)
 551:
 552: report_loss.backward()
 553:
 554: # ------------------------------------------------------------
 555: # Inspect structured-head gradients
 556: # ------------------------------------------------------------
    ...

==========================================================================================
CELL INDEX: 9 | EXECUTION COUNT: None
==========================================================================================
  11: # 1. Load V4 E3 into reference model
  12: # ------------------------------------------------------------
  13:
  14: model.load_state_dict(
  15:     E3["model_state"],
  16:     strict=True,
  17: )
  18:
    ...

==========================================================================================
CELL INDEX: 10 | EXECUTION COUNT: None
==========================================================================================
  15: # 0. Restore V4 E3 reference + V5 warm-start
  16: # ------------------------------------------------------------
  17:
  18: model.load_state_dict(
  19:     E3["model_state"],
  20:     strict=True,
  21: )
  22: model.eval()
    ...
 214:
 215:     v5.zero_grad(set_to_none=True)
 216:
 217:     loss.backward(
 218:         retain_graph=True
 219:     )
 220:
 221:     norms = {}
    ...

==========================================================================================
CELL INDEX: 14 | EXECUTION COUNT: None
==========================================================================================
 115: def grad_norm_for_loss(loss, module):
 116:     v5.zero_grad(set_to_none=True)
 117:
 118:     loss.backward(
 119:         retain_graph=True
 120:     )
 121:
 122:     total_sq = 0.0
    ...
 253:
 254: print("\n" + "=" * 70)
 255: print("V5 LOSS / GRADIENT AUDIT COMPLETE")
 256: print("NO optimizer.step()")
 257: print("NO scheduler.step()")
 258: print("NO checkpoint write")
 259: print("=" * 70)
    ...

==========================================================================================
CELL INDEX: 17 | EXECUTION COUNT: None
==========================================================================================
  78: print("\n" + "=" * 70)
  79: print("PASS — V5 FORWARD IS EXECUTABLE AND FINITE")
  80: print("NO backward")
  81: print("NO optimizer.step()")
  82: print("NO scheduler.step()")
  83: print("NO checkpoint write")
  84: print("=" * 70)
    ...

==========================================================================================
CELL INDEX: 18 | EXECUTION COUNT: None
==========================================================================================
   1: # ============================================================
   2: # V5 REPORT → STRUCTURED GRADIENT AUDIT
   3: # READ-ONLY
   4: # NO optimizer.step()
   5: # NO scheduler.step()
   6: # NO checkpoint
   7: # ============================================================
   8:
    ...
 144:
 145:     v5.zero_grad(set_to_none=True)
 146:
 147:     loss.backward(
 148:         retain_graph=True
 149:     )
 150:
 151:     norm = module_grad_norm(
    ...

==========================================================================================
CELL INDEX: 19 | EXECUTION COUNT: None
==========================================================================================
 156:
 157:     v5.zero_grad(set_to_none=True)
 158:
 159:     loss.backward(
 160:         retain_graph=True
 161:     )
 162:
 163:     g = grad_norm(
    ...
 250: v5.zero_grad(set_to_none=True)
 251:
 252: print(
 253:     "\nNO optimizer.step()"
 254:     "\nNO scheduler.step()"
 255:     "\nNO checkpoint write"
 256: )
    ...

==========================================================================================
CELL INDEX: 20 | EXECUTION COUNT: None
==========================================================================================
   2: # V5 OPTIMIZER PARAMETER-GROUP AUDIT
   3: # READ-ONLY
   4: # NO optimizer creation
   5: # NO optimizer.step()
   6: # NO scheduler
   7: # NO checkpoint
   8: # ============================================================
   9:
    ...

==========================================================================================
CELL INDEX: 23 | EXECUTION COUNT: None
==========================================================================================
 202:
 203: v5_restore = V5Model()
 204:
 205: v5_restore.load_state_dict(
 206:     loaded["model_state"],
 207:     strict=True,
 208: )
 209:
    ...
 243:     eta_min=0,
 244: )
 245:
 246: optimizer_restore.load_state_dict(
 247:     loaded["optimizer_state"]
 248: )
 249:
 250: scheduler_restore.load_state_dict(
    ...
 251:     loaded["scheduler_state"]
 252: )
 253:
 254: # ------------------------------------------------------------
    ...

==========================================================================================
CELL INDEX: 24 | EXECUTION COUNT: None
==========================================================================================
 260: }
 261:
 262: checkpoint_paths["last"] = os.path.join(CKPT_DIR, "last.pt")
 263: checkpoint_paths["best"] = os.path.join(CKPT_DIR, "best.pt")
 264:
 265: print()
 266: print("Checkpoint directory:")
 267: print(CKPT_DIR)
    ...
 324: print("V5 TRAINING PRE-FLIGHT: PASS")
 325: print("=" * 55)
 326:
 327: print("NO optimizer.step() executed")
 328: print("NO scheduler.step() executed")
 329: print("NO checkpoint written")
 330: print("V4 remains untouched")
 331: print()
    ...

==========================================================================================
CELL INDEX: 74 | EXECUTION COUNT: None
==========================================================================================
 121: print("\n[STRUCTURED COLUMNS]")
 122:
 123: required_structured_cols = [
 124:     "concept_vector_str",
 125:     "negative_vector_str",
 126:     "attribute_vector_str",
 127: ]
 128:
    ...
 129: for c in required_structured_cols:
    ...
 130:     print(
    ...
 240:     case_id = str(row["case_id"])
 241:
 242:     concept = parse_vector(
 243:         row["concept_vector_str"]
 244:     )
 245:
 246:     negative = parse_vector(
 247:         row["negative_vector_str"]
    ...
 248:     )
 249:
 250:     attribute = parse_vector(
 251:         row["attribute_vector_str"]
    ...
 252:     )
 253:
 254:     structured_lookup[case_id] = {
 255:         "concept": concept,
    ...
 419:
 420:     source_concept = torch.tensor(
 421:         parse_vector(
 422:             source_row["concept_vector_str"]
 423:         ),
 424:         dtype=torch.float32,
 425:         device=device,
 426:     )
    ...
 427:
 428:     source_negative = torch.tensor(
 429:         parse_vector(
 430:             source_row["negative_vector_str"]
 431:         ),
 432:         dtype=torch.float32,
 433:         device=device,
 434:     )
    ...
 435:
 436:     source_attribute = torch.tensor(
 437:         parse_vector(
 438:             source_row["attribute_vector_str"]
 439:         ),
 440:         dtype=torch.float32,
 441:         device=device,
 442:     )
    ...

==========================================================================================
CELL INDEX: 75 | EXECUTION COUNT: None
==========================================================================================
  32: candidates = [
  33:     os.path.join(V4_CKPT_DIR, "epoch_03.pt"),
  34:     os.path.join(V4_CKPT_DIR, "epoch_03.pth"),
  35:     os.path.join(V4_CKPT_DIR, "best.pt"),
  36: ]
  37:
  38: existing = [p for p in candidates if os.path.exists(p)]
  39:
    ...
 136: # -------------------------------------------------------------------------
 137: # 5. Load compatible weights
 138: # -------------------------------------------------------------------------
 139: load_result = v5.load_state_dict(
 140:     compatible,
 141:     strict=False,
 142: )
 143:
    ...

==========================================================================================
CELL INDEX: 82 | EXECUTION COUNT: None
==========================================================================================
 207: # ------------------------------------------------------------------
 208: # 9. Load only compatible weights
 209: # ------------------------------------------------------------------
 210: load_result = v5.load_state_dict(
 211:     compatible,
 212:     strict=False,
 213: )
 214:
    ...

==========================================================================================
CELL INDEX: 84 | EXECUTION COUNT: None
==========================================================================================
  92: # ------------------------------------------------------------------
  93: print("\n[LOAD V4 -> V5]")
  94:
  95: load_result = v5.load_state_dict(
  96:     fresh_compatible,
  97:     strict=False,
  98: )
  99:
    ...

==========================================================================================
CELL INDEX: 85 | EXECUTION COUNT: None
==========================================================================================
  81:
  82: required_target_columns = [
  83:     "case_id",
  84:     "concept_vector_str",
  85:     "negative_vector_str",
  86:     "attribute_vector_str",
  87: ]
  88:
    ...
  89: missing_target_columns = [
    ...
  90:     c
    ...
  99:     )
 100:
 101: print("PASS: case_id found")
 102: print("PASS: concept_vector_str found")
 103: print("PASS: negative_vector_str found")
 104: print("PASS: attribute_vector_str found")
 105:
 106: # ================================================================================
    ...
 107: # 4. CASE-ID UNIQUENESS
    ...
 108: # ================================================================================
    ...
 191:     case_id = str(row["case_id"])
 192:
 193:     concept = parse_vector(
 194:         row["concept_vector_str"],
 195:         48,
 196:         "concept_vector",
 197:         case_id,
 198:     )
    ...
 199:
 200:     negative = parse_vector(
 201:         row["negative_vector_str"],
 202:         5,
 203:         "negative_vector",
 204:         case_id,
 205:     )
    ...
 206:
 207:     attribute = parse_vector(
 208:         row["attribute_vector_str"],
 209:         6,
 210:         "attribute_vector",
 211:         case_id,
 212:     )
    ...

==========================================================================================
CELL INDEX: 87 | EXECUTION COUNT: None
==========================================================================================
 104: print("=" * 80)
 105:
 106: vector_cols = [
 107:     "concept_vector_str",
 108:     "negative_vector_str",
 109:     "attribute_vector_str",
 110: ]
 111:
    ...
 112: for col in vector_cols:
    ...
 113:
    ...
 266: print("=" * 80)
 267:
 268: expected_dims = {
 269:     "concept_vector_str": 48,
 270:     "negative_vector_str": 5,
 271:     "attribute_vector_str": 6,
 272: }
 273:
    ...
 274: dimension_failures = []
    ...
 275:
    ...

==========================================================================================
CELL INDEX: 88 | EXECUTION COUNT: None
==========================================================================================
 223: actual_concept = np.stack(
 224:     [
 225:         parse_vector(value)
 226:         for value in v4_df["concept_vector_str"]
 227:     ]
 228: )
 229:
 230: print(
    ...
 316: actual_negative = np.stack(
 317:     [
 318:         parse_vector(value)
 319:         for value in v4_df["negative_vector_str"]
 320:     ]
 321: )
 322:
 323: print("\n[NEGATIVE VECTOR VERIFICATION]")
    ...
 398: actual_attribute = np.stack(
 399:     [
 400:         parse_vector(value)
 401:         for value in v4_df["attribute_vector_str"]
 402:     ]
 403: )
 404:
 405: print("\n[ATTRIBUTE VECTOR VERIFICATION]")
    ...

==========================================================================================
CELL INDEX: 89 | EXECUTION COUNT: None
==========================================================================================
 108: actual_negative = np.stack(
 109:     [
 110:         parse_vector(x)
 111:         for x in v4_df["negative_vector_str"]
 112:     ]
 113: )
 114:
 115: print("\n[V4 NEGATIVE VECTOR]")
    ...
 265: #
 266: # The only thing we can safely inspect here is whether the serialized
 267: # negative_findings_str corresponds to the positive dimensions of
 268: # negative_vector_str.
 269:
 270: unique_labels = set()
 271:
 272: for value in v4_df["negative_findings_str"]:
    ...

==========================================================================================
CELL INDEX: 90 | EXECUTION COUNT: None
==========================================================================================
 127: actual_v4 = np.stack(
 128:     [
 129:         parse_vector(x)
 130:         for x in v4_df["negative_vector_str"]
 131:     ]
 132: )
 133:
 134: print("\n[VECTOR SHAPES]")
    ...
 206:         )
 207:
 208:     raise RuntimeError(
 209:         "V4 negative_vector_str does NOT match "
 210:         "V4 negative_findings_str."
 211:     )
 212:
 213: print(
    ...

==========================================================================================
CELL INDEX: 91 | EXECUTION COUNT: None
==========================================================================================
 202: actual_v4 = np.stack(
 203:     [
 204:         parse_vector(x)
 205:         for x in v4_df["attribute_vector_str"]
 206:     ]
 207: )
 208:
 209: print("\n[VECTOR SHAPES]")
    ...
 291:         )
 292:
 293:     raise RuntimeError(
 294:         "V4 attribute_vector_str does NOT match "
 295:         "attributes_v2_str."
 296:     )
 297:
 298: print(
    ...

==========================================================================================
CELL INDEX: 92 | EXECUTION COUNT: None
==========================================================================================
  55:
  56: required_target_cols = [
  57:     "case_id",
  58:     "concept_vector_str",
  59:     "negative_vector_str",
  60:     "attribute_vector_str",
  61: ]
  62:
    ...
  63: missing_target_cols = [
    ...
  64:     c for c in required_target_cols
    ...
 137:
 138: concept_matrix = parse_column(
 139:     v4_df,
 140:     "concept_vector_str",
 141:     48,
 142: )
 143:
 144: negative_matrix = parse_column(
    ...
 145:     v4_df,
 146:     "negative_vector_str",
 147:     5,
 148: )
 149:
 150: attribute_matrix = parse_column(
    ...
 151:     v4_df,
 152:     "attribute_vector_str",
 153:     6,
 154: )
 155:
 156: print("\n[CANONICAL TARGET MATRICES]")
    ...

==========================================================================================
CELL INDEX: 94 | EXECUTION COUNT: None
==========================================================================================
  89:
  90: concept_matrix = parse_column(
  91:     v4_df,
  92:     "concept_vector_str",
  93:     48,
  94: )
  95:
  96: negative_matrix = parse_column(
    ...
  97:     v4_df,
  98:     "negative_vector_str",
  99:     5,
 100: )
 101:
 102: attribute_matrix = parse_column(
    ...
 103:     v4_df,
 104:     "attribute_vector_str",
 105:     6,
 106: )
 107:
 108: target_lookup = {
    ...
 337:
 338: print("\n[BACKWARD]")
 339:
 340: total_loss.backward()
 341:
 342: print(
 343:     "PASS: total_loss.backward() completed"
 344: )
    ...
 345:
 346: # ------------------------------------------------------------------------------
 347: # 8. GRADIENT SUMMARY
    ...


In [30]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import json
from pathlib import Path

NB_PATH = Path("/content/drive/MyDrive/Colab Notebooks/25sep.ipynb")
OUT_DIR = Path(
    "/content/drive/MyDrive/NoiSoi_Matching/"
    "baseline_model_v5/diagnostics/audit_20261015"
)
OUT_DIR.mkdir(parents=True, exist_ok=True)

with open(NB_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

matches = []
for idx, cell in enumerate(nb.get("cells", [])):
    source = "".join(cell.get("source", []))
    if "V5 — FULL TRAINING" in source or "V5 - FULL TRAINING" in source:
        matches.append((idx, source))

assert matches, "Không tìm thấy cell huấn luyện V5 trong notebook."

idx, source = matches[-1]
lines = source.splitlines()

print("Training cell index:", idx)
print("Total source lines:", len(lines))

# In các đoạn then chốt để xác định nguồn nhãn, loss và checkpoint.
needles = [
    "V4_MANIFEST",
    "STRUCTURED_CSV",
    "pd.read_csv",
    "required_structured_cols",
    "structured_df",
    "structured_lookup",
    "train_df",
    "build_structured_targets",
    "backward_loss",
    "loss.backward",
    "optimizer.step",
    "torch.save",
    "BEST_CKPT",
]

ranges = []
for i, line in enumerate(lines):
    if any(key.lower() in line.lower() for key in needles):
        ranges.append((max(0, i - 5), min(len(lines), i + 9)))

# Gộp các đoạn bị chồng lấn.
merged = []
for start, end in sorted(ranges):
    if merged and start <= merged[-1][1]:
        merged[-1] = (merged[-1][0], max(merged[-1][1], end))
    else:
        merged.append((start, end))

output = []
for start, end in merged:
    output.append(f"\n{'=' * 72}\nLINES {start+1}-{end}\n{'=' * 72}")
    output.extend(
        f"{i+1:4}: {lines[i]}"
        for i in range(start, end)
    )

text = "\n".join(output)
print(text)

report_path = OUT_DIR / "cell7_v5_training_flow.txt"
report_path.write_text(text, encoding="utf-8")
print("\nSaved:", report_path)
print("READ-ONLY: không train, không optimizer step, không ghi checkpoint.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Training cell index: 139
Total source lines: 2121

========================================================================
LINES 121-146
========================================================================
 121: ROOT = (
 122:     DRIVE /
 123:     "NoiSoi_Matching"
 124: )
 125:
 126: V4_MANIFEST = (
 127:     ROOT /
 128:     "baseline_model_v4" /
 129:     "v4_training_manifest.csv"
 130: )
 131:
 132: IMAGE_MANIFEST = (
 133:     ROOT /
 134:     "final_manifest" /
 135:     "final_dataset_manifest.csv"
 136: )
 137:
 138: STRUCTURED_CSV = (
 139:     ROOT /
 140:     "v3_ontology_v2" /
 141:     "v3_structured_targets_v2_2.csv"
 142: )
 143:
 144: V5_ROOT = (
 145:     ROOT /
 146:     "baseline_model_v5"

========================================================================
LINES 159-172
========================================================================
 159: LAST_CKPT = (
 160:     CKPT_DIR /
 161:     "last.pt"
 162: )
 163:
 164: BEST_CKPT = (
 165:     CKPT_DIR /
 166:     "best.pt"
 167: )
 168:
 169: ROLLING = [
 170:     CKPT_DIR / "resume_0.pt",
 171:     CKPT_DIR / "resume_1.pt",
 172: ]

========================================================================
LINES 178-204
========================================================================
 178:
 179: print("\n" + "=" * 80)
 180: print("[1] MANIFESTS")
 181: print("=" * 80)
 182:
 183: assert V4_MANIFEST.exists(), V4_MANIFEST
 184: assert IMAGE_MANIFEST.exists(), IMAGE_MANIFEST
 185: assert STRUCTURED_CSV.exists(), STRUCTURED_CSV
 186:
 187: v4_df = pd.read_csv(
 188:     V4_MANIFEST
 189: )
 190:
 191: image_df = pd.read_csv(
 192:     IMAGE_MANIFEST
 193: )
 194:
 195: structured_df = pd.read_csv(
 196:     STRUCTURED_CSV
 197: )
 198:
 199: print(
 200:     "V4 manifest:",
 201:     v4_df.shape
 202: )
 203:
 204: print(

========================================================================
LINES 206-223
========================================================================
 206:     image_df.shape
 207: )
 208:
 209: print(
 210:     "Structured:",
 211:     structured_df.shape
 212: )
 213:
 214: assert v4_df.shape[0] == 7606
 215: assert structured_df.shape[0] == 7606
 216:
 217:
 218: # ============================================================
 219: # 4. EXACT V4 SPLITS
 220: # ============================================================
 221:
 222: train_cases = (
 223:     v4_df.loc[

========================================================================
LINES 586-612
========================================================================
 586:
 587: # ============================================================
 588: # 12. STRUCTURED TARGETS
 589: # ============================================================
 590:
 591: required_structured_cols = [
 592:     "case_id",
 593:     "concept_vector_str",
 594:     "negative_vector_str",
 595:     "attribute_vector_str",
 596: ]
 597:
 598: for col in required_structured_cols:
 599:     assert col in structured_df.columns, col
 600:
 601:
 602: structured_targets_v5 = {}
 603:
 604: for _, row in structured_df.iterrows():
 605:
 606:     case_id = str(
 607:         row["case_id"]
 608:     )
 609:
 610:     concept = parse_vector(
 611:         row["concept_vector_str"]
 612:     )

========================================================================
LINES 1223-1236
========================================================================
1223:
1224:     tmp = Path(
1225:         str(path) + ".tmp"
1226:     )
1227:
1228:     torch.save(
1229:         payload,
1230:         tmp
1231:     )
1232:
1233:     os.replace(
1234:         tmp,
1235:         path
1236:     )

========================================================================
LINES 1986-1999
========================================================================
1986:     if val_loss < best_val:
1987:
1988:         best_val = val_loss
1989:
1990:         save_ckpt(
1991:             BEST_CKPT,
1992:             epoch,
1993:             v5,
1994:             optimizer_v5,
1995:             scheduler_v5,
1996:             best_val,
1997:             history,
1998:         )
1999:

========================================================================
LINES 2102-2121
========================================================================
2102:     LAST_CKPT.exists()
2103: )
2104:
2105: print(
2106:     "best.pt:",
2107:     BEST_CKPT.exists()
2108: )
2109:
2110: assert (
2111:     global_step
2112:     == TOTAL_OPT_STEPS
2113: )
2114:
2115: assert LAST_CKPT.exists()
2116: assert BEST_CKPT.exists()
2117:
2118: print("\nPASS: V5 TRAINING COMPLETE.")
2119: print("PASS: Checkpoints saved.")
2120: print("PASS: V4 was not required.")
2121: print("=" * 80)

Saved: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell7_v5_training_flow.txt
READ-ONLY: không train, không optimizer step, không ghi checkpoint.

In [31]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import json
from pathlib import Path
from datetime import datetime

NB_PATH = Path("/content/drive/MyDrive/Colab Notebooks/25sep.ipynb")
ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
CKPT = ROOT / "baseline_model_v5/checkpoints/best.pt"
OUT_DIR = ROOT / "baseline_model_v5/diagnostics/audit_20261015"
OUT_DIR.mkdir(parents=True, exist_ok=True)

with open(NB_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

lines = []
for idx in [123, 126, 127, 139, 140]:
    if idx >= len(nb["cells"]):
        continue

    cell = nb["cells"][idx]
    source = "".join(cell.get("source", []))
    outputs = cell.get("outputs", [])

    lines.append("\n" + "=" * 85)
    lines.append(
        f"CELL {idx} | execution_count={cell.get('execution_count')} "
        f"| output_count={len(outputs)}"
    )
    lines.append("=" * 85)

    # Hiển thị các đoạn source liên quan đến dữ liệu và checkpoint.
    src = source.splitlines()
    keys = [
        "V4_MANIFEST", "STRUCTURED_CSV", "structured_df",
        "v4_df", "structured_targets", "save_ckpt",
        "BEST_CKPT", "backward_loss.backward",
        "optimizer.step", "PASS: V5 TRAINING COMPLETE",
    ]
    hit = [
        i for i, line in enumerate(src)
        if any(k.lower() in line.lower() for k in keys)
    ]
    shown = set()
    for i in hit:
        for j in range(max(0, i - 2), min(len(src), i + 4)):
            if j not in shown:
                lines.append(f"SOURCE {j+1:4}: {src[j]}")
                shown.add(j)

    # Chỉ trích xuất output văn bản đã lưu; không thực thi cell.
    for oi, out in enumerate(outputs):
        text_parts = []
        data = out.get("data", {})
        for mime in ("text/plain", "text/markdown"):
            value = data.get(mime)
            if value:
                text_parts.extend(value if isinstance(value, list) else [str(value)])
        if out.get("output_type") == "error":
            text_parts.append(
                f"ERROR: {out.get('ename')}: {out.get('evalue')}"
            )
        if text_parts:
            out_text = "\n".join(text_parts)
            lines.append(f"\nSAVED OUTPUT {oi}:\n{out_text[:5000]}")

if CKPT.exists():
    stat = CKPT.stat()
    lines.extend([
        "\n" + "=" * 85,
        "CHECKPOINT FILE METADATA",
        "=" * 85,
        f"Path: {CKPT}",
        f"Size (GB): {stat.st_size / (1024**3):.3f}",
        f"Modified: {datetime.fromtimestamp(stat.st_mtime).isoformat()}",
    ])
else:
    lines.append(f"\nCHECKPOINT NOT FOUND: {CKPT}")

report = "\n".join(lines)
print(report)

report_path = OUT_DIR / "cell8_saved_training_history.txt"
report_path.write_text(report, encoding="utf-8")
print("\nReport saved:", report_path)
print("READ-ONLY: không chạy cell trong notebook, không load model, không sửa checkpoint.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

=====================================================================================
CELL 123 | execution_count=15 | output_count=1
=====================================================================================
SOURCE   78: # ------------------------------------------------------------
SOURCE   79:
SOURCE   80: def build_structured_targets(df):
SOURCE   81:
SOURCE   82:     result = {}
SOURCE   83:
SOURCE  125:
SOURCE  126:
SOURCE  127: structured_targets_v5 = build_structured_targets(v4_df)
SOURCE  128:
SOURCE  129:
SOURCE  130: # ------------------------------------------------------------
SOURCE  136: print(
SOURCE  137:     "Cases:",
SOURCE  138:     len(structured_targets_v5)
SOURCE  139: )
SOURCE  140:
SOURCE  141: assert len(structured_targets_v5) == 7606
SOURCE  142:
SOURCE  143: for case_id, target in list(
SOURCE  144:     structured_targets_v5.items()
SOURCE  145: )[:3]:
SOURCE  146:
SOURCE  147:     print(
SOURCE  170: attribute_counts = []
SOURCE  171:
SOURCE  172: for _, row in v4_df.iterrows():
SOURCE  173:
SOURCE  174:     concept = parse_binary_vector(
SOURCE  175:         row["concept_vector_str"],
SOURCE  196: assert np.array_equal(
SOURCE  197:     concept_counts,
SOURCE  198:     v4_df["num_concepts_v2"].to_numpy()
SOURCE  199: )
SOURCE  200:
SOURCE  201: assert np.array_equal(
SOURCE  202:     negative_counts,
SOURCE  203:     v4_df["num_negative_findings"].to_numpy()
SOURCE  204: )
SOURCE  205:
SOURCE  206: assert np.array_equal(
SOURCE  207:     attribute_counts,
SOURCE  208:     v4_df["num_attributes_v2"].to_numpy()
SOURCE  209: )
SOURCE  210:
SOURCE  211: print("\n[COUNT CONSISTENCY]")
SOURCE  330:
SOURCE  331: concept_targets = torch.stack([
SOURCE  332:     structured_targets_v5[c]["concept_targets"]
SOURCE  333:     for c in batch_case_ids
SOURCE  334: ])
SOURCE  335:
SOURCE  336: negative_targets = torch.stack([
SOURCE  337:     structured_targets_v5[c]["negative_targets"]
SOURCE  338:     for c in batch_case_ids
SOURCE  339: ])
SOURCE  340:
SOURCE  341: attribute_targets = torch.stack([
SOURCE  342:     structured_targets_v5[c]["attribute_targets"]
SOURCE  343:     for c in batch_case_ids
SOURCE  344: ])
SOURCE  345:
SOURCE  346: structured_masks = torch.tensor([
SOURCE  347:     structured_targets_v5[c]["structured_loss_mask"]
SOURCE  348:     for c in batch_case_ids
SOURCE  349: ], dtype=torch.float32)
SOURCE  350:

=====================================================================================
CELL 126 | execution_count=1 | output_count=2
=====================================================================================
SOURCE   15: #   train_loader_v5
SOURCE   16: #   val_loader_v5
SOURCE   17: #   structured_targets_v5
SOURCE   18: #   optimizer/scheduler dependencies
SOURCE   19: # ============================================================
SOURCE   20:
SOURCE   93: )
SOURCE   94:
SOURCE   95: BEST_CKPT = (
SOURCE   96:     V5_CKPT_DIR / "best.pt"
SOURCE   97: )
SOURCE   98:
SOURCE  720:
SOURCE  721:         concept_targets = torch.stack([
SOURCE  722:             structured_targets_v5[c][
SOURCE  723:                 "concept_targets"
SOURCE  724:             ]
SOURCE  725:             for c in case_ids
SOURCE  730:
SOURCE  731:         negative_targets = torch.stack([
SOURCE  732:             structured_targets_v5[c][
SOURCE  733:                 "negative_targets"
SOURCE  734:             ]
SOURCE  735:             for c in case_ids
SOURCE  740:
SOURCE  741:         attribute_targets = torch.stack([
SOURCE  742:             structured_targets_v5[c][
SOURCE  743:                 "attribute_targets"
SOURCE  744:             ]
SOURCE  745:             for c in case_ids
SOURCE  750:
SOURCE  751:         masks = torch.tensor([
SOURCE  752:             structured_targets_v5[c][
SOURCE  753:                 "structured_loss_mask"
SOURCE  754:             ]
SOURCE  755:             for c in case_ids
SOURCE  801:         # ----------------------------------------------------
SOURCE  802:
SOURCE  803:         backward_loss.backward()
SOURCE  804:
SOURCE  805:         # ----------------------------------------------------
SOURCE  806:         # Optimizer step
SOURCE 1004:
SOURCE 1005:             concept_targets = torch.stack([
SOURCE 1006:                 structured_targets_v5[c][
SOURCE 1007:                     "concept_targets"
SOURCE 1008:                 ]
SOURCE 1009:                 for c in case_ids
SOURCE 1014:
SOURCE 1015:             negative_targets = torch.stack([
SOURCE 1016:                 structured_targets_v5[c][
SOURCE 1017:                     "negative_targets"
SOURCE 1018:                 ]
SOURCE 1019:                 for c in case_ids
SOURCE 1024:
SOURCE 1025:             attribute_targets = torch.stack([
SOURCE 1026:                 structured_targets_v5[c][
SOURCE 1027:                     "attribute_targets"
SOURCE 1028:                 ]
SOURCE 1029:                 for c in case_ids
SOURCE 1034:
SOURCE 1035:             masks = torch.tensor([
SOURCE 1036:                 structured_targets_v5[c][
SOURCE 1037:                     "structured_loss_mask"
SOURCE 1038:                 ]
SOURCE 1039:                 for c in case_ids
SOURCE 1167:
SOURCE 1168:         save_checkpoint(
SOURCE 1169:             BEST_CKPT,
SOURCE 1170:             epoch,
SOURCE 1171:             v5,
SOURCE 1172:             optimizer_v5,
SOURCE 1282:
SOURCE 1283:     print(
SOURCE 1284:         f"best.pt exists  : {BEST_CKPT.exists()}"
SOURCE 1285:     )
SOURCE 1286:
SOURCE 1287:     assert epoch_path.exists()
SOURCE 1289:
SOURCE 1290:     if improved:
SOURCE 1291:         assert BEST_CKPT.exists()
SOURCE 1292:
SOURCE 1293:     print(
SOURCE 1294:         "CHECKPOINT STATUS: PASS"
SOURCE 1331: print(
SOURCE 1332:     "best.pt:",
SOURCE 1333:     BEST_CKPT.exists()
SOURCE 1334: )
SOURCE 1335:
SOURCE 1336: assert global_step == TOTAL_OPTIMIZER_STEPS
SOURCE 1337: assert scheduler_v5.last_epoch == TOTAL_OPTIMIZER_STEPS
SOURCE 1338: assert LAST_CKPT.exists()
SOURCE 1339: assert BEST_CKPT.exists()
SOURCE 1340:
SOURCE 1341: print("\nPASS: V5 training completed.")
SOURCE 1342: print("PASS: Frequent resume checkpoints enabled.")
SOURCE 1343: print("PASS: last.pt maintained.")
SOURCE 1344: print("PASS: best.pt maintained.")

SAVED OUTPUT 1:
ERROR: NameError: name 'train_loader_v5' is not defined

=====================================================================================
CELL 127 | execution_count=3 | output_count=2
=====================================================================================
SOURCE  104: )
SOURCE  105:
SOURCE  106: BEST_CKPT = (
SOURCE  107:     V5_CKPT_DIR / "best.pt"
SOURCE  108: )
SOURCE  109:
SOURCE  181:     "train_loader_v5",
SOURCE  182:     "val_loader_v5",
SOURCE  183:     "structured_targets_v5",
SOURCE  184: ]
SOURCE  185:
SOURCE  186: missing_objects = [
SOURCE  200:         "\nRuntime was disconnected/reset.\n"
SOURCE  201:         "Drive is mounted, but the Python objects "
SOURCE  202:         "v5 / loaders / structured_targets_v5 "
SOURCE  203:         "must be restored first.\n\n"
SOURCE  204:         "Run the V5 restore/data cells, then rerun "
SOURCE  205:         "this training cell."
SOURCE  877:
SOURCE  878:         concept_targets = torch.stack([
SOURCE  879:             structured_targets_v5[c][
SOURCE  880:                 "concept_targets"
SOURCE  881:             ]
SOURCE  882:             for c in case_ids
SOURCE  887:
SOURCE  888:         negative_targets = torch.stack([
SOURCE  889:             structured_targets_v5[c][
SOURCE  890:                 "negative_targets"
SOURCE  891:             ]
SOURCE  892:             for c in case_ids
SOURCE  897:
SOURCE  898:         attribute_targets = torch.stack([
SOURCE  899:             structured_targets_v5[c][
SOURCE  900:                 "attribute_targets"
SOURCE  901:             ]
SOURCE  902:             for c in case_ids
SOURCE  907:
SOURCE  908:         masks = torch.tensor([
SOURCE  909:             structured_targets_v5[c][
SOURCE  910:                 "structured_loss_mask"
SOURCE  911:             ]
SOURCE  912:             for c in case_ids
SOURCE  958:         # ----------------------------------------------------
SOURCE  959:
SOURCE  960:         backward_loss.backward()
SOURCE  961:
SOURCE  962:         # ----------------------------------------------------
SOURCE  963:         # Step
SOURCE 1135:
SOURCE 1136:             concept_targets = torch.stack([
SOURCE 1137:                 structured_targets_v5[c][
SOURCE 1138:                     "concept_targets"
SOURCE 1139:                 ]
SOURCE 1140:                 for c in case_ids
SOURCE 1145:
SOURCE 1146:             negative_targets = torch.stack([
SOURCE 1147:                 structured_targets_v5[c][
SOURCE 1148:                     "negative_targets"
SOURCE 1149:                 ]
SOURCE 1150:                 for c in case_ids
SOURCE 1155:
SOURCE 1156:             attribute_targets = torch.stack([
SOURCE 1157:                 structured_targets_v5[c][
SOURCE 1158:                     "attribute_targets"
SOURCE 1159:                 ]
SOURCE 1160:                 for c in case_ids
SOURCE 1165:
SOURCE 1166:             masks = torch.tensor([
SOURCE 1167:                 structured_targets_v5[c][
SOURCE 1168:                     "structured_loss_mask"
SOURCE 1169:                 ]
SOURCE 1170:                 for c in case_ids
SOURCE 1258:
SOURCE 1259:         save_checkpoint(
SOURCE 1260:             BEST_CKPT,
SOURCE 1261:             epoch,
SOURCE 1262:             v5,
SOURCE 1263:             optimizer_v5,
SOURCE 1403: print(
SOURCE 1404:     "best.pt:",
SOURCE 1405:     BEST_CKPT.exists()
SOURCE 1406: )
SOURCE 1407:
SOURCE 1408: assert (
SOURCE 1417:
SOURCE 1418: assert LAST_CKPT.exists()
SOURCE 1419: assert BEST_CKPT.exists()
SOURCE 1420:
SOURCE 1421: print("\nPASS: V5 training complete.")
SOURCE 1422: print("PASS: Frequent checkpointing.")
SOURCE 1423: print("PASS: Resume-safe.")
SOURCE 1424: print("PASS: V4 untouched.")

SAVED OUTPUT 1:
ERROR: ValueError: Mountpoint must not already contain files

=====================================================================================
CELL 139 | execution_count=15 | output_count=2
=====================================================================================
SOURCE  124: )
SOURCE  125:
SOURCE  126: V4_MANIFEST = (
SOURCE  127:     ROOT /
SOURCE  128:     "baseline_model_v4" /
SOURCE  129:     "v4_training_manifest.csv"
SOURCE  136: )
SOURCE  137:
SOURCE  138: STRUCTURED_CSV = (
SOURCE  139:     ROOT /
SOURCE  140:     "v3_ontology_v2" /
SOURCE  141:     "v3_structured_targets_v2_2.csv"
SOURCE  142: )
SOURCE  143:
SOURCE  144: V5_ROOT = (
SOURCE  162: )
SOURCE  163:
SOURCE  164: BEST_CKPT = (
SOURCE  165:     CKPT_DIR /
SOURCE  166:     "best.pt"
SOURCE  167: )
SOURCE  181: print("=" * 80)
SOURCE  182:
SOURCE  183: assert V4_MANIFEST.exists(), V4_MANIFEST
SOURCE  184: assert IMAGE_MANIFEST.exists(), IMAGE_MANIFEST
SOURCE  185: assert STRUCTURED_CSV.exists(), STRUCTURED_CSV
SOURCE  186:
SOURCE  187: v4_df = pd.read_csv(
SOURCE  188:     V4_MANIFEST
SOURCE  189: )
SOURCE  190:
SOURCE  191: image_df = pd.read_csv(
SOURCE  193: )
SOURCE  194:
SOURCE  195: structured_df = pd.read_csv(
SOURCE  196:     STRUCTURED_CSV
SOURCE  197: )
SOURCE  198:
SOURCE  199: print(
SOURCE  200:     "V4 manifest:",
SOURCE  201:     v4_df.shape
SOURCE  202: )
SOURCE  203:
SOURCE  204: print(
SOURCE  209: print(
SOURCE  210:     "Structured:",
SOURCE  211:     structured_df.shape
SOURCE  212: )
SOURCE  213:
SOURCE  214: assert v4_df.shape[0] == 7606
SOURCE  215: assert structured_df.shape[0] == 7606
SOURCE  216:
SOURCE  217:
SOURCE  218: # ============================================================
SOURCE  221:
SOURCE  222: train_cases = (
SOURCE  223:     v4_df.loc[
SOURCE  224:         v4_df["split"] == "train",
SOURCE  225:         "case_id"
SOURCE  226:     ]
SOURCE  227:     .astype(str)
SOURCE  230:
SOURCE  231: val_cases = (
SOURCE  232:     v4_df.loc[
SOURCE  233:         v4_df["split"] == "val",
SOURCE  234:         "case_id"
SOURCE  235:     ]
SOURCE  236:     .astype(str)
SOURCE  239:
SOURCE  240: test_cases = (
SOURCE  241:     v4_df.loc[
SOURCE  242:         v4_df["split"] == "test",
SOURCE  243:         "case_id"
SOURCE  244:     ]
SOURCE  245:     .astype(str)
SOURCE  504: # ============================================================
SOURCE  505:
SOURCE  506: assert "ket_luan" in v4_df.columns
SOURCE  507:
SOURCE  508: report_map = dict(
SOURCE  509:     zip(
SOURCE  510:         v4_df["case_id"].astype(str),
SOURCE  511:         v4_df["ket_luan"].fillna("").astype(str)
SOURCE  512:     )
SOURCE  513: )
SOURCE  514:
SOURCE  597:
SOURCE  598: for col in required_structured_cols:
SOURCE  599:     assert col in structured_df.columns, col
SOURCE  600:
SOURCE  601:
SOURCE  602: structured_targets_v5 = {}
SOURCE  603:
SOURCE  604: for _, row in structured_df.iterrows():
SOURCE  605:
SOURCE  606:     case_id = str(
SOURCE  607:         row["case_id"]
SOURCE  638:         )
SOURCE  639:
SOURCE  640:     structured_targets_v5[
SOURCE  641:         case_id
SOURCE  642:     ] = {
SOURCE  643:
SOURCE  666:
SOURCE  667: assert (
SOURCE  668:     len(structured_targets_v5)
SOURCE  669:     == 7606
SOURCE  670: )
SOURCE  671:
SOURCE 1180:
SOURCE 1181:
SOURCE 1182: def save_ckpt(
SOURCE 1183:     path,
SOURCE 1184:     epoch,
SOURCE 1185:     model,
SOURCE 1607:
SOURCE 1608:         concept_targets = torch.stack([
SOURCE 1609:             structured_targets_v5[
SOURCE 1610:                 c
SOURCE 1611:             ][
SOURCE 1612:                 "concept_targets"
SOURCE 1619:
SOURCE 1620:         negative_targets = torch.stack([
SOURCE 1621:             structured_targets_v5[
SOURCE 1622:                 c
SOURCE 1623:             ][
SOURCE 1624:                 "negative_targets"
SOURCE 1631:
SOURCE 1632:         attribute_targets = torch.stack([
SOURCE 1633:             structured_targets_v5[
SOURCE 1634:                 c
SOURCE 1635:             ][
SOURCE 1636:                 "attribute_targets"
SOURCE 1768:                 }
SOURCE 1769:
SOURCE 1770:                 save_ckpt(
SOURCE 1771:                     rolling_path,
SOURCE 1772:                     epoch,
SOURCE 1773:                     v5,
SOURCE 1856:
SOURCE 1857:             concept_targets = torch.stack([
SOURCE 1858:                 structured_targets_v5[
SOURCE 1859:                     c
SOURCE 1860:                 ][
SOURCE 1861:                     "concept_targets"
SOURCE 1868:
SOURCE 1869:             negative_targets = torch.stack([
SOURCE 1870:                 structured_targets_v5[
SOURCE 1871:                     c
SOURCE 1872:                 ][
SOURCE 1873:                     "negative_targets"
SOURCE 1880:
SOURCE 1881:             attribute_targets = torch.stack([
SOURCE 1882:                 structured_targets_v5[
SOURCE 1883:                     c
SOURCE 1884:                 ][
SOURCE 1885:                     "attribute_targets"
SOURCE 1988:         best_val = val_loss
SOURCE 1989:
SOURCE 1990:         save_ckpt(
SOURCE 1991:             BEST_CKPT,
SOURCE 1992:             epoch,
SOURCE 1993:             v5,
SOURCE 1994:             optimizer_v5,
SOURCE 2014:     )
SOURCE 2015:
SOURCE 2016:     save_ckpt(
SOURCE 2017:         epoch_ckpt,
SOURCE 2018:         epoch,
SOURCE 2019:         v5,
SOURCE 2024:     )
SOURCE 2025:
SOURCE 2026:     save_ckpt(
SOURCE 2027:         LAST_CKPT,
SOURCE 2028:         epoch,
SOURCE 2029:         v5,
SOURCE 2105: print(
SOURCE 2106:     "best.pt:",
SOURCE 2107:     BEST_CKPT.exists()
SOURCE 2108: )
SOURCE 2109:
SOURCE 2110: assert (
SOURCE 2114:
SOURCE 2115: assert LAST_CKPT.exists()
SOURCE 2116: assert BEST_CKPT.exists()
SOURCE 2117:
SOURCE 2118: print("\nPASS: V5 TRAINING COMPLETE.")
SOURCE 2119: print("PASS: Checkpoints saved.")
SOURCE 2120: print("PASS: V4 was not required.")
SOURCE 2121: print("=" * 80)

SAVED OUTPUT 1:
ERROR: AssertionError: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv

=====================================================================================
CELL 140 | execution_count=16 | output_count=2
=====================================================================================
SOURCE   50:
SOURCE   51: LAST_CKPT = V5_CKPT_DIR / "last.pt"
SOURCE   52: BEST_CKPT = V5_CKPT_DIR / "best.pt"
SOURCE   53:
SOURCE   54:
SOURCE   55: # ============================================================
SOURCE  389:     print(
SOURCE  390:         "best.pt exists:",
SOURCE  391:         BEST_CKPT.exists()
SOURCE  392:     )
SOURCE  393:
SOURCE  394:     print(
SOURCE  529:
SOURCE  530:         concept_targets_gpu = torch.stack([
SOURCE  531:             structured_targets_v5[c][
SOURCE  532:                 "concept_targets"
SOURCE  533:             ]
SOURCE  534:             for c in batch_case_ids
SOURCE  539:
SOURCE  540:         negative_targets_gpu = torch.stack([
SOURCE  541:             structured_targets_v5[c][
SOURCE  542:                 "negative_targets"
SOURCE  543:             ]
SOURCE  544:             for c in batch_case_ids
SOURCE  549:
SOURCE  550:         attribute_targets_gpu = torch.stack([
SOURCE  551:             structured_targets_v5[c][
SOURCE  552:                 "attribute_targets"
SOURCE  553:             ]
SOURCE  554:             for c in batch_case_ids
SOURCE  559:
SOURCE  560:         structured_masks_gpu = torch.tensor([
SOURCE  561:             structured_targets_v5[c][
SOURCE  562:                 "structured_loss_mask"
SOURCE  563:             ]
SOURCE  564:             for c in batch_case_ids
SOURCE  778:
SOURCE  779:             concept_targets_gpu = torch.stack([
SOURCE  780:                 structured_targets_v5[c][
SOURCE  781:                     "concept_targets"
SOURCE  782:                 ]
SOURCE  783:                 for c in batch_case_ids
SOURCE  788:
SOURCE  789:             negative_targets_gpu = torch.stack([
SOURCE  790:                 structured_targets_v5[c][
SOURCE  791:                     "negative_targets"
SOURCE  792:                 ]
SOURCE  793:                 for c in batch_case_ids
SOURCE  798:
SOURCE  799:             attribute_targets_gpu = torch.stack([
SOURCE  800:                 structured_targets_v5[c][
SOURCE  801:                     "attribute_targets"
SOURCE  802:                 ]
SOURCE  803:                 for c in batch_case_ids
SOURCE  808:
SOURCE  809:             structured_masks_gpu = torch.tensor([
SOURCE  810:                 structured_targets_v5[c][
SOURCE  811:                     "structured_loss_mask"
SOURCE  812:                 ]
SOURCE  813:                 for c in batch_case_ids
SOURCE  946:
SOURCE  947:         save_v5_checkpoint(
SOURCE  948:             BEST_CKPT,
SOURCE  949:             epoch,
SOURCE  950:             v5,
SOURCE  951:             optimizer_v5,
SOURCE 1078:
SOURCE 1079:     if improved:
SOURCE 1080:         assert BEST_CKPT.exists()
SOURCE 1081:
SOURCE 1082:     print("\nCHECKPOINT STATUS: PASS")
SOURCE 1083:
SOURCE 1128: print(
SOURCE 1129:     "best.pt exists:",
SOURCE 1130:     BEST_CKPT.exists()
SOURCE 1131: )
SOURCE 1132:
SOURCE 1133: print(
SOURCE 1139: assert scheduler_v5.last_epoch == 1920
SOURCE 1140: assert LAST_CKPT.exists()
SOURCE 1141: assert BEST_CKPT.exists()
SOURCE 1142:
SOURCE 1143: print("\n[FINAL SAFETY]")
SOURCE 1144: print("PASS: 1920 optimizer steps completed.")

SAVED OUTPUT 1:
ERROR: NameError: name 'train_loader_v5' is not defined

=====================================================================================
CHECKPOINT FILE METADATA
=====================================================================================
Path: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/best.pt

In [32]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
from datetime import datetime
import torch

CKPT_DIR = Path(
    "/content/drive/MyDrive/NoiSoi_Matching/"
    "baseline_model_v5/checkpoints"
)

if not CKPT_DIR.exists():
    print("Không tìm thấy thư mục:", CKPT_DIR)
else:
    files = sorted(
        p for p in CKPT_DIR.iterdir()
        if p.is_file() and p.suffix.lower() in {".pt", ".pth"}
    )

    print("Checkpoint directory:", CKPT_DIR)
    print("Số file checkpoint:", len(files))

    for p in files:
        stat = p.stat()
        print(
            f"\n{p.name}\n"
            f"  Size: {stat.st_size / (1024**3):.3f} GB\n"
            f"  Modified: "
            f"{datetime.fromtimestamp(stat.st_mtime).isoformat()}"
        )

    # Chỉ đọc metadata của best.pt; không load model_state vào GPU.
    best = CKPT_DIR / "best.pt"
    if best.exists():
        try:
            obj = torch.load(
                best,
                map_location="cpu",
                weights_only=False,
                mmap=True,
            )
            print("\nBEST.PT METADATA")
            if isinstance(obj, dict):
                for key in obj:
                    if key not in {
                        "model_state", "optimizer_state",
                        "scheduler_state", "rng_state",
                        "cuda_rng_state", "python_rng_state",
                        "numpy_rng_state"
                    }:
                        value = obj[key]
                        if key == "history":
                            print("history:", value)
                        elif isinstance(value, (str, int, float, bool, type(None))):
                            print(f"{key}: {value}")
                print("Top-level keys:", list(obj.keys()))
            del obj
        except Exception as e:
            print("Không đọc được metadata:", repr(e))

print("\nREAD-ONLY: không train, không cập nhật checkpoint.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Checkpoint directory: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints
Số file checkpoint: 2

best.pt
  Size: 4.321 GB
  Modified: 2026-09-29T04:20:44

last.pt
  Size: 4.321 GB
  Modified: 2026-09-29T04:25:51

BEST.PT METADATA
epoch: 5
batch_idx: 0
global_step: 1920
best_val: 0.424518172663671
history: {'train_loss': [0.5731708970967303, 0.5046075203082849, 0.47171955251829634, 0.45422747778290645, 0.44715843725379206], 'val_loss': [0.46700948011622856, 0.44155955633946825, 0.42823387978095856, 0.4258775923539091, 0.424518172663671]}
Top-level keys: ['epoch', 'batch_idx', 'global_step', 'model_state', 'optimizer_state', 'scheduler_state', 'best_val', 'history', 'rng_state', 'cuda_rng_state', 'python_rng_state', 'numpy_rng_state']

READ-ONLY: không train, không cập nhật checkpoint.

In [33]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import json
from pathlib import Path
import ast

ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
NB_PATH = Path("/content/drive/MyDrive/Colab Notebooks/25sep.ipynb")
V4_MANIFEST = ROOT / "baseline_model_v4/v4_training_manifest.csv"
STRUCTURED_CSV = ROOT / "v3_ontology_v2/v3_structured_targets_v2_2.csv"
MAPPING_CSV = ROOT / "baseline_model_v4/diagnostics/frozen_concept_ontology_mapping.csv"
CKPT_DIR = ROOT / "baseline_model_v5/checkpoints"
OUT_DIR = ROOT / "baseline_model_v5/diagnostics/audit_20261015"
OUT_DIR.mkdir(parents=True, exist_ok=True)

print("=== 1. INPUT FILES ===")
for p in [NB_PATH, V4_MANIFEST, STRUCTURED_CSV, MAPPING_CSV]:
    print(f"{p.name}: exists={p.exists()}")
    if p.exists():
        print(f"  bytes={p.stat().st_size}")

print("\n=== 2. CHECKPOINT FILES ===")
for p in sorted(CKPT_DIR.glob("*.pt")):
    print(f"{p.name}: {p.stat().st_size / (1024**3):.3f} GB")

print("\n=== 3. TRAINING-CELL HISTORY ===")
with open(NB_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

for idx, cell in enumerate(nb.get("cells", [])):
    src = "".join(cell.get("source", []))
    if not any(k in src for k in [
        "V5 — FULL TRAINING",
        "V5 - FULL TRAINING",
        "V5 training completed",
        "PASS: V5 TRAINING COMPLETE",
    ]):
        continue

    print(
        f"\nCell {idx}: execution_count={cell.get('execution_count')}, "
        f"source_lines={len(src.splitlines())}"
    )
    for out in cell.get("outputs", []):
        if out.get("output_type") == "error":
            print("Saved error:", out.get("ename"), out.get("evalue"))
        data = out.get("data", {})
        text = data.get("text/plain", [])
        if text:
            s = "".join(text) if isinstance(text, list) else str(text)
            print("Saved text output:", s[:1200])

print("\n=== 4. SOURCE-CODE CLUES ===")
# Chỉ tìm các dòng khai báo nguồn targets trong cell huấn luyện.
for idx, cell in enumerate(nb.get("cells", [])):
    src = "".join(cell.get("source", []))
    if "V5 — FULL TRAINING" not in src and "V5 - FULL TRAINING" not in src:
        continue

    for n, line in enumerate(src.splitlines(), start=1):
        if any(k in line for k in [
            "STRUCTURED_CSV", "structured_df =", "v4_df =",
            "structured_targets_v5 =", "required_structured_cols",
            "concept_vector_str", "negative_vector_str",
            "attribute_vector_str",
        ]):
            print(f"Cell {idx}, line {n}: {line.strip()}")

report_path = OUT_DIR / "cell9_source_provenance.txt"
report_path.write_text(
    "Cell 9 ran read-only checks. See notebook output for details.\n",
    encoding="utf-8",
)
print("\nRead-only audit completed.")
print("Report marker:", report_path)
print("No training or checkpoint modification.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
=== 1. INPUT FILES ===
25sep.ipynb: exists=True
  bytes=2978538
v4_training_manifest.csv: exists=True
  bytes=1921940
v3_structured_targets_v2_2.csv: exists=True
  bytes=6233626
frozen_concept_ontology_mapping.csv: exists=True
  bytes=1974

=== 2. CHECKPOINT FILES ===
best.pt: 4.321 GB
last.pt: 4.321 GB

=== 3. TRAINING-CELL HISTORY ===

Cell 126: execution_count=1, source_lines=1348
Saved error: NameError name 'train_loader_v5' is not defined

Cell 139: execution_count=15, source_lines=2121
Saved error: AssertionError /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv

=== 4. SOURCE-CODE CLUES ===
Cell 139, line 138: STRUCTURED_CSV = (
Cell 139, line 185: assert STRUCTURED_CSV.exists(), STRUCTURED_CSV
Cell 139, line 187: v4_df = pd.read_csv(
Cell 139, line 195: structured_df = pd.read_csv(
Cell 139, line 196: STRUCTURED_CSV
Cell 139, line 591: required_structured_cols = [
Cell 139, line 593: "concept_vector_str",
Cell 139, line 594: "negative_vector_str",
Cell 139, line 595: "attribute_vector_str",
Cell 139, line 598: for col in required_structured_cols:
Cell 139, line 602: structured_targets_v5 = {}
Cell 139, line 611: row["concept_vector_str"]
Cell 139, line 615: row["negative_vector_str"]
Cell 139, line 619: row["attribute_vector_str"]

Read-only audit completed.
Report marker: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell9_source_provenance.txt
No training or checkpoint modification.

In [34]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
import pandas as pd
import torch

ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
CKPT_DIR = ROOT / "baseline_model_v5/checkpoints"
PRED_CSV = ROOT / "baseline_model_v5/test_predictions_712.csv"

for name in ["best.pt", "last.pt"]:
    path = CKPT_DIR / name
    print(f"\n=== {name} ===")
    if not path.exists():
        print("MISSING")
        continue

    try:
        obj = torch.load(
            path,
            map_location="cpu",
            weights_only=False,
            mmap=True,
        )
        for key in ["epoch", "batch_idx", "global_step", "best_val", "history"]:
            if key in obj:
                print(f"{key}: {obj[key]}")
        del obj
    except Exception as e:
        print("Metadata read error:", repr(e))

print("\n=== TEST PREDICTIONS ===")
if PRED_CSV.exists():
    pred = pd.read_csv(PRED_CSV)
    print("Shape:", pred.shape)
    print("Columns:", pred.columns.tolist())
    print("Unique case IDs:", pred["case_id"].nunique())
    print("Null counts:")
    print(pred[["case_id", "prediction", "ground_truth"]].isna().sum())
    print("\nFirst 5 rows:")
    print(pred.head().to_string(index=False))
else:
    print("MISSING:", PRED_CSV)

print("\nREAD-ONLY: không train, không sửa checkpoint hay predictions.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

=== best.pt ===
epoch: 5
batch_idx: 0
global_step: 1920
best_val: 0.424518172663671
history: {'train_loss': [0.5731708970967303, 0.5046075203082849, 0.47171955251829634, 0.45422747778290645, 0.44715843725379206], 'val_loss': [0.46700948011622856, 0.44155955633946825, 0.42823387978095856, 0.4258775923539091, 0.424518172663671]}

=== last.pt ===
epoch: 5
batch_idx: 0
global_step: 1920
best_val: 0.424518172663671
history: {'train_loss': [0.5731708970967303, 0.5046075203082849, 0.47171955251829634, 0.45422747778290645, 0.44715843725379206], 'val_loss': [0.46700948011622856, 0.44155955633946825, 0.42823387978095856, 0.4258775923539091, 0.424518172663671]}

=== TEST PREDICTIONS ===
Shape: (712, 3)
Columns: ['case_id', 'prediction', 'ground_truth']
Unique case IDs: 712
Null counts:
case_id         0
prediction      0
ground_truth    0
dtype: int64

First 5 rows:
            case_id                                   prediction                                         ground_truth
10017.10017.0.10031          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP      VIÊM MÀNG NHĨ CẤP BÓNG NƯỚC P - NHIỀU RÁY TAI T
10057.10057.0.10071          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP       VIÊM ỐNG TAI NGOÀI (T) MẠN / VIÊM MŨI ĐỢT CẤP.
10116.10116.0.10130          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                    VIÊM ỐNG TAI NGOÀI MÀNG NHĨ P CẤP
10125.10125.0.10139                                 VIÊM MŨI MẠN VIÊM MŨI MẠN VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ 2 BÊN MẠN
10126.10126.0.10140 VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.                                       VIÊM A-MI-ĐAN.

READ-ONLY: không train, không sửa checkpoint hay predictions.

In [35]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
import pandas as pd
import numpy as np
import re
import unicodedata

ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
PRED_PATH = ROOT / "baseline_model_v5/test_predictions_712.csv"
V4_PATH = ROOT / "baseline_model_v4/v4_training_manifest.csv"
OUT_DIR = ROOT / "baseline_model_v5/diagnostics/audit_20261015"
OUT_DIR.mkdir(parents=True, exist_ok=True)

pred = pd.read_csv(PRED_PATH, dtype={"case_id": str})
v4 = pd.read_csv(V4_PATH, dtype={"case_id": str})

def norm_text(x):
    if pd.isna(x):
        return ""
    x = unicodedata.normalize("NFKC", str(x)).lower().strip()
    x = re.sub(r"[.,;:!?()\[\]{}]", " ", x)
    x = re.sub(r"\s+", " ", x)
    return x

pred["prediction_norm"] = pred["prediction"].map(norm_text)
pred["ground_truth_norm"] = pred["ground_truth"].map(norm_text)
pred["exact_match"] = (
    pred["prediction_norm"] == pred["ground_truth_norm"]
)

print("=== BASIC METRICS ===")
print("Prediction rows:", len(pred))
print("Unique prediction IDs:", pred["case_id"].nunique())
print("Exact normalized match:", round(pred["exact_match"].mean(), 4))
print("Unique normalized predictions:", pred["prediction_norm"].nunique())
print("Unique normalized ground truth:", pred["ground_truth_norm"].nunique())

print("\n=== PREDICTION DISTRIBUTION: TOP 15 ===")
print(pred["prediction_norm"].value_counts().head(15).to_string())

print("\n=== GROUND-TRUTH DISTRIBUTION: TOP 15 ===")
print(pred["ground_truth_norm"].value_counts().head(15).to_string())

print("\n=== TEST SPLIT CROSS-CHECK ===")
test_ids = set(
    v4.loc[v4["split"].astype(str).str.lower().eq("test"), "case_id"]
      .astype(str)
)
pred_ids = set(pred["case_id"].astype(str))

print("V4 test IDs:", len(test_ids))
print("Prediction IDs:", len(pred_ids))
print("Overlap:", len(test_ids & pred_ids))
print("Only in predictions:", len(pred_ids - test_ids))
print("Missing from predictions:", len(test_ids - pred_ids))

mismatch = pred.loc[
    ~pred["exact_match"],
    ["case_id", "prediction", "ground_truth"]
].copy()

out_path = OUT_DIR / "cell10_prediction_audit.csv"
mismatch.to_csv(out_path, index=False)

print("\nMismatch rows:", len(mismatch))
print("Saved mismatch audit:", out_path)
print("READ-ONLY: không train, không sửa checkpoint.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
=== BASIC METRICS ===
Prediction rows: 712
Unique prediction IDs: 712
Exact normalized match: 0.184
Unique normalized predictions: 16
Unique normalized ground truth: 263

=== PREDICTION DISTRIBUTION: TOP 15 ===
prediction_norm
viêm mũi mạn                                    324
viêm ống tai ngoài + màng nhĩ t cấp             126
viêm họng mạn - theo dõi trào ngược dịch vị      81
viêm mũi xoang                                   52
viêm mũi + va                                    47
viêm tai giữa p mạn                              46
viêm tai giữa t cấp viêm mũi                     10
viêm ống tai ngoài + màng nhĩ t                   8
viêm mũi xoang mạn - polyp mũi                    6
viêm ống tai ngoài 2 bên mạn                      4
viêm ống tai ngoài p cấp                          2
viêm tai giữa t mạn                               2
viêm tai giữa t cấp viêm mũi xoang                1
viêm tai giữa 2 bên viêm mũi                      1
viêm mũi                                          1

=== GROUND-TRUTH DISTRIBUTION: TOP 15 ===
ground_truth_norm
viêm mũi mạn                                                                 79
viêm mũi                                                                     66
viêm họng mạn - theo dõi trào ngược dịch vị                                  51
viêm mũi xoang                                                               35
hiện không thấy hình ảnh bệnh lý tai ngoài tai giữa trên nội soi             22
viêm mũi đợt cấp                                                             18
viêm mũi + va                                                                14
viêm tai giữa t mạn                                                          10
viêm mũi xoang mạn - polyp mũi                                                9
viêm tai giữa t mạn viêm mũi xoang mạn / đã ptns mũi xoang                    9
viêm mũi mạn + va                                                             9
viêm ống tai ngoài + màng nhĩ p cấp                                           9
hiện không thấy hình ảnh bệnh lý tai ngoài tai giữa trên nội soi viêm mũi     8
viêm mũi xoang + viêm va                                                      7
viêm mũi xoang mạn đã pt                                                      7

=== TEST SPLIT CROSS-CHECK ===
V4 test IDs: 712
Prediction IDs: 712
Overlap: 712
Only in predictions: 0
Missing from predictions: 0

Mismatch rows: 581
Saved mismatch audit: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell10_prediction_audit.csv
READ-ONLY: không train, không sửa checkpoint.

In [36]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import json
from pathlib import Path

NB_PATH = Path("/content/drive/MyDrive/Colab Notebooks/25sep.ipynb")
ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
OUT_DIR = ROOT / "baseline_model_v5/diagnostics/audit_20261015"
OUT_DIR.mkdir(parents=True, exist_ok=True)

with open(NB_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

keywords = [
    "test_predictions_712.csv",
    "ground_truth",
    "generate(",
    "generate_text",
    "decode(",
    "batch_decode",
    "argmax(",
    "prediction",
    "test_loader",
    "model.generate",
]

report = []
for idx, cell in enumerate(nb.get("cells", [])):
    src = "".join(cell.get("source", []))
    lines = src.splitlines()

    hits = [
        i for i, line in enumerate(lines)
        if any(k.lower() in line.lower() for k in keywords)
    ]
    if not hits:
        continue

    report.append(
        f"\n{'='*78}\n"
        f"CELL {idx} | execution_count={cell.get('execution_count')} "
        f"| lines={len(lines)}\n{'='*78}"
    )

    # In đoạn quanh các dòng liên quan, tránh in trùng.
    shown = set()
    for i in hits:
        for j in range(max(0, i - 3), min(len(lines), i + 5)):
            if j not in shown:
                report.append(f"{j+1:4}: {lines[j]}")
                shown.add(j)

text = "\n".join(report)
print(text[:30000])

path = OUT_DIR / "cell11_prediction_generation_source.txt"
path.write_text(text, encoding="utf-8")
print("\nSaved:", path)
print("READ-ONLY: không chạy inference, không train, không sửa checkpoint.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

==============================================================================
CELL 1 | execution_count=None | lines=1914
==============================================================================
1116: # SAFE DECODE
1117: # ================================================================
1118:
1119: def safe_decode(ids):
1120:
1121:     if torch.is_tensor(ids):
1122:         ids = ids.detach().cpu().tolist()
1123:
1128:         for x in ids
1129:     ]
1130:
1131:     return tokenizer.decode(
1132:         ids,
1133:         skip_special_tokens=True,
1134:     ).strip()
1135:
1278:     )
1279:
1280:     # ------------------------------------------------
1281:     # HARD PREDICTIONS
1282:     # EXACT
1283:     # ------------------------------------------------
1284:
1285:     concept_pred = (
1413: # ================================================================
1414:
1415: @torch.no_grad()
1416: def exact_generate(
1417:     cond,
1418:     max_new_tokens=20,
1419: ):
1420:
1456:             return_dict=True,
1457:         )
1458:
1459:         next_token = torch.argmax(
1460:             out.logits[:, -1, :],
1461:             dim=-1,
1462:             keepdim=True,
1463:         )
1484:             dim=1,
1485:         )
1486:
1487:     return safe_decode(
1488:         generated
1489:     )
1490:
1491:
1530:             zero_struct=False,
1531:         )
1532:
1533:         pred_full = exact_generate(
1534:             full
1535:         )
1536:
1537:         # ------------------------------------------------
1548:         )
1549:
1550:         pred_zero_struct = (
1551:             exact_generate(
1552:                 zero_struct
1553:             )
1554:         )
1555:
1567:         )
1568:
1569:         pred_zero_visual = (
1570:             exact_generate(
1571:                 zero_visual
1572:             )
1573:         )
1574:
1586:         )
1587:
1588:         pred_zero_both = (
1589:             exact_generate(
1590:                 zero_both
1591:             )
1592:         )
1593:
1597:                 case["case_id"],
1598:
1599:             "ref":
1600:                 safe_decode(
1601:                     case["labels"]
1602:                 ),
1603:
1604:             "full":
1669:             "condition":
1670:                 condition,
1671:
1672:             "unique_predictions":
1673:                 len(counts),
1674:
1675:             "dominant_prediction":
1676:                 dominant,
1677:
1678:             "dominant_count":
1679:                 dominant_count,

==============================================================================
CELL 4 | execution_count=None | lines=32
==============================================================================
   2: # RESTORE SAFE DECODE HELPER
   3: # ============================================================
   4:
   5: def safe_decode(token_ids):
   6:     """
   7:     Decode generated mT5 token IDs while removing
   8:     special / sentinel artifacts.
   9:     """
  13:     if isinstance(token_ids, int):
  14:         token_ids = [token_ids]
  15:
  16:     return tokenizer.decode(
  17:         token_ids,
  18:         skip_special_tokens=True,
  19:         clean_up_tokenization_spaces=True,
  20:     )
  24: print("=" * 70)
  25:
  26: # sanity check
  27: test_text = safe_decode([tokenizer.eos_token_id])
  28: print("Test decode:", repr(test_text))
  29:
  30: assert isinstance(test_text, str)
  31:

==============================================================================
CELL 5 | execution_count=None | lines=445
==============================================================================
 211:             return_dict=True,
 212:         )
 213:
 214:         next_token = torch.argmax(
 215:             out.logits[:, -1, :],
 216:             dim=-1,
 217:             keepdim=True,
 218:         )
 229:             dim=1,
 230:         )
 231:
 232:     return safe_decode(generated)
 233:
 234:
 235: # ============================================================
 236: # 4. PREPARE AUDIT BATCHES

==============================================================================
CELL 6 | execution_count=None | lines=233
==============================================================================
  34:     result = []
  35:
  36:     for p, token_id in zip(vals.tolist(), ids.tolist()):
  37:         token = tokenizer.decode(
  38:             [token_id],
  39:             skip_special_tokens=False,
  40:         )
  41:         result.append({
 125:             ).item()
 126:
 127:             # Does argmax change?
 128:             full_argmax = int(torch.argmax(full))
 129:             other_argmax = int(torch.argmax(other))
 130:
 131:             argmax_changed = (
 132:                 full_argmax != other_argmax
 133:             )
 140:                 "max_abs_logit_diff": max_abs_diff,
 141:                 "cosine_similarity": cosine,
 142:                 "argmax_changed": argmax_changed,
 143:                 "full_top_token": tokenizer.decode(
 144:                     [full_argmax],
 145:                     skip_special_tokens=False,
 146:                 ),
 147:                 "other_top_token": tokenizer.decode(
 148:                     [other_argmax],
 149:                     skip_special_tokens=False,
 150:                 ),
 151:             })

==============================================================================
CELL 7 | execution_count=None | lines=368
==============================================================================
  93:     full_probs = torch.softmax(full, dim=-1)
  94:     other_probs = torch.softmax(other, dim=-1)
  95:
  96:     full_top = full.argmax(dim=-1)
  97:     other_top = other.argmax(dim=-1)
  98:
  99:     # Probability assigned to FULL's preferred token
 100:     full_top_prob = full_probs.gather(
 101:         1, full_top[:, None]

==============================================================================
CELL 16 | execution_count=None | lines=203
==============================================================================
  53:     )
  54:
  55:     # --------------------------------------------------------
  56:     # 4. Structured prediction heads
  57:     # --------------------------------------------------------
  58:     concept_logits = self.structured_heads["concept"](pooled)
  59:     negative_logits = self.structured_heads["negative"](pooled)
  60:     attribute_logits = self.structured_heads["attribute"](pooled)

==============================================================================
CELL 25 | execution_count=None | lines=52
==============================================================================
   8: candidate_names = [
   9:     "train_loader",
  10:     "val_loader",
  11:     "test_loader",
  12:     "train_dataset",
  13:     "val_dataset",
  14:     "test_dataset",
  15:     "train_dl",

==============================================================================
CELL 81 | execution_count=None | lines=373
==============================================================================
 118:             out_dim=512
 119:         )
 120:
 121:         # Structured prediction heads
 122:         self.concept_head = nn.Linear(512, 48)
 123:         self.negative_head = nn.Linear(512, 5)
 124:         self.attribute_head = nn.Linear(512, 6)
 125:
 176:         visual_hidden = self.projector(pooled)
 177:
 178:         # ----------------------------------------------------------
 179:         # Structured prediction
 180:         # ----------------------------------------------------------
 181:         concept_logits = self.concept_head(
 182:             visual_hidden
 183:         )

==============================================================================
CELL 123 | execution_count=15 | lines=398
==============================================================================
 238:     drop_last=False
 239: )
 240:
 241: test_loader_v5 = DataLoader(
 242:     test_dataset_v5,
 243:     batch_size=4,
 244:     shuffle=False,
 245:     num_workers=2,
 267:
 268: print(
 269:     "Test batches:",
 270:     len(test_loader_v5)
 271: )
 272:
 273: assert len(train_loader_v5) == 1535
 274: assert len(val_loader_v5) == 189
 275: assert len(test_loader_v5) == 178
 276:
 277:
 278: # ------------------------------------------------------------
 279: # 8. Build one real training batch

==============================================================================
CELL 139 | execution_count=15 | lines=2121
==============================================================================
 889:     collate_fn=collate_v5,
 890: )
 891:
 892: test_loader_v5 = DataLoader(
 893:     test_dataset_v5,
 894:     batch_size=BATCH_SIZE,
 895:     shuffle=False,
 896:     num_workers=2,

Saved: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell11_prediction_generation_source.txt
READ-ONLY: không chạy inference, không train, không sửa checkpoint.

In [37]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import json
from pathlib import Path

NB_PATH = Path("/content/drive/MyDrive/Colab Notebooks/25sep.ipynb")
ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
PRED_PATH = ROOT / "baseline_model_v5/test_predictions_712.csv"
OUT_DIR = ROOT / "baseline_model_v5/diagnostics/audit_20261015"
OUT_DIR.mkdir(parents=True, exist_ok=True)

with open(NB_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

terms = [
    "test_predictions_712.csv",
    "to_csv(", "write_csv(", "csv.writer",
    "torch.load(", "load_state_dict(",
    "BEST_CKPT", "best.pt", "last.pt",
    "model.generate(", "exact_generate(",
]

report = []
for i, cell in enumerate(nb.get("cells", [])):
    src = "".join(cell.get("source", []))
    outputs = cell.get("outputs", [])
    matches = [
        (n, line.strip()[:240])
        for n, line in enumerate(src.splitlines(), start=1)
        if any(term.lower() in line.lower() for term in terms)
    ]

    # Chỉ in cell có thao tác lưu/nạp checkpoint hoặc ghi CSV,
    # và cell có cả inference lẫn xuất kết quả.
    relevant = [
        item for item in matches
        if any(t in item[1].lower() for t in [
            "test_predictions_712.csv", "to_csv(", "write_csv(",
            "csv.writer", "torch.load(", "load_state_dict(",
            "best_ckpt", "best.pt", "last.pt"
        ])
    ]
    if not relevant:
        continue

    report.append(
        f"\n=== CELL {i} | execution_count={cell.get('execution_count')} "
        f"| outputs={len(outputs)} ==="
    )
    for line_no, line in relevant:
        report.append(f"{line_no}: {line}")

    for j, output in enumerate(outputs):
        text_parts = []
        for key in ("text",):
            val = output.get(key)
            if val:
                text_parts.append(
                    "".join(val) if isinstance(val, list) else str(val)
                )
        data = output.get("data", {})
        if "text/plain" in data:
            val = data["text/plain"]
            text_parts.append(
                "".join(val) if isinstance(val, list) else str(val)
            )
        summary = " | ".join(text_parts)
        if summary:
            report.append(f"OUTPUT {j}: {summary[:500]}")

result = "\n".join(report)
print(result[:24000] if result else "Không tìm thấy các thao tác lưu/nạp checkpoint trong source cell.")

print("\n=== CSV FILE METADATA ===")
if PRED_PATH.exists():
    stat = PRED_PATH.stat()
    print("Path:", PRED_PATH)
    print("Size bytes:", stat.st_size)
    print("Modified timestamp:", __import__("datetime").datetime.fromtimestamp(
        stat.st_mtime
    ).isoformat())
else:
    print("Prediction CSV không tồn tại tại đường dẫn dự kiến.")

save_path = OUT_DIR / "cell12_checkpoint_and_prediction_source.txt"
save_path.write_text(result, encoding="utf-8")
print("\nSaved audit:", save_path)
print("READ-ONLY: không nạp model, không inference, không train, không sửa checkpoint.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

=== CELL 0 | execution_count=None | outputs=1 ===
72: BEST_CKPT = (
73: f"{V4_DIR}/checkpoints/best.pt"
OUTPUT 0: ======================================================================
V4 NEW-NOTEBOOK BOOTSTRAP
======================================================================
Mounted at /content/drive


=== CELL 1 | execution_count=None | outputs=24 ===
89: BEST_CKPT = (
90: f"{V4_DIR}/checkpoints/best.pt"
104: "Best checkpoint": BEST_CKPT,
988: E2 = torch.load(
994: E3 = torch.load(
1017: load_result = model.load_state_dict(
1031: model.load_state_dict(
1102: model.load_state_dict(
1507: model.load_state_dict(
1902: model.load_state_dict(
OUTPUT 0: ======================================================================
V4 NEW-NOTEBOOK BOOTSTRAP
======================================================================
Google Drive: already mounted

PATH CHECK
  V4 manifest           : PASS -> /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv
  Structured targets    : PASS -> /content/drive/MyDrive/NoiSoi_Matching/v3_ontology_v2/v3_structured_targets_v2_2.csv
  Image manifest        : PASS -> /content/drive/MyDriv
OUTPUT 1: config.json:   0%|          | 0.00/553 [00:00<?, ?B/s]
OUTPUT 2: Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

OUTPUT 3: tokenizer_config.json:   0%|          | 0.00/82.0 [00:00<?, ?B/s]
OUTPUT 4: spiece.model:   0%|          | 0.00/4.31M [00:00<?, ?B/s]
OUTPUT 5: special_tokens_map.json:   0%|          | 0.00/99.0 [00:00<?, ?B/s]
OUTPUT 6: Tokenizer: T5Tokenizer
Vocab size: 250100
pad_token_id: 0
eos_token_id: 1

LOADING IMAGE PROCESSOR

OUTPUT 7: preprocessor_config.json:   0%|          | 0.00/160 [00:00<?, ?B/s]
OUTPUT 8: config.json:   0%|          | 0.00/69.7k [00:00<?, ?B/s]
OUTPUT 9: Image processor: ViTImageProcessor
Image size: SizeDict(height=224, width=224, longest_edge=None, shortest_edge=None, max_height=None, max_width=None)
Image mean: (0.5, 0.5, 0.5)
Image std: (0.5, 0.5, 0.5)

LOADING MANIFESTS
V4 manifest: (7606, 15)
Structured: (7606, 102)
Image manifest: (76405, 26)
Manifest shapes: PASS

COLUMN AUDIT
V4 columns: ['case_id', 'patient_group_id', 'split', 'ket_luan', 'concepts_v2_str', 'negative_findings_str', 'attributes_v2_str', 'concept_vector_str', 'negative_v
OUTPUT 10: model.safetensors: reconstructing file:   0%|          |  0.00B /  346MB
OUTPUT 11: model.safetensors: downloading bytes:           |  0.00B
OUTPUT 12: Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]
OUTPUT 13: [transformers] ViTModel LOAD REPORT from: google/vit-base-patch16-224
Key                 | Status     |
--------------------+------------+-
classifier.bias     | UNEXPECTED |
classifier.weight   | UNEXPECTED |
pooler.dense.weight | MISSING    |
pooler.dense.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. C
OUTPUT 14: pytorch_model.bin: reconstructing file:   0%|          |  0.00B / 1.20GB
OUTPUT 15: pytorch_model.bin: downloading bytes:           |  0.00B
OUTPUT 16: Loading weights:   0%|          | 0/192 [00:00<?, ?it/s]
OUTPUT 17: [transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

OUTPUT 18: generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]
OUTPUT 19: Model device: cuda:0
Projector: (512, 768)
Concept head: (48, 512)
Negative head: (5, 512)
Attribute head: (6, 512)

LOADING CHECKPOINTS

OUTPUT 20: model.safetensors: reconstructing file:   0%|          |  0.00B / 1.20GB
OUTPUT 21: model.safetensors: downloading bytes:           |  0.00B
OUTPUT 22: E2 epoch: 2
E3 epoch: 3


=== CELL 2 | execution_count=None | outputs=6 ===
88: model.load_state_dict(E2["model_state"], strict=True)
95: model.load_state_dict(E3["model_state"], strict=True)
OUTPUT 0: ======================================================================
REBUILDING V4 WITH CHECKPOINT-EXACT PROJECTOR
======================================================================

OUTPUT 1: Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]
OUTPUT 2: [transformers] ViTModel LOAD REPORT from: google/vit-base-patch16-224
Key                 | Status     |
--------------------+------------+-
classifier.bias     | UNEXPECTED |
classifier.weight   | UNEXPECTED |
pooler.dense.weight | MISSING    |
pooler.dense.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. C
OUTPUT 3: Loading weights:   0%|          | 0/192 [00:00<?, ?it/s]
OUTPUT 4: [transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

OUTPUT 5:
Checkpoint projector keys:
  projector.proj.weight
  projector.proj.bias

✓ Checkpoint projector structure confirmed

Model projector keys:
  projector.proj.weight
  projector.proj.bias

✓ Model projector structure confirmed

✓ E2 STRICT LOAD PASSED
✓ E3 STRICT LOAD PASSED

======================================================================
V4 CHECKPOINT RESTORE: PASS
======================================================================


=== CELL 5 | execution_count=None | outputs=2 ===
280: model.load_state_dict(
OUTPUT 0:
======================================================================
CHECKPOINT: E2
======================================================================

--- FULL ---
TF loss: 9.486522
Unique AR outputs: 1/20
Top outputs:
  20x  'VI   ( <extra_id_33> <extra_id_33> <extra_id_33> <extra_id_33> <extra_id_33> <extra_id_33> <extra_id_33> <extra_id_33> <extra_id_33> <extra_id_33> <extra_id_33> <extra_id_33> <extra_id_33> <extra_id_33> <extra_id_33> <extra_id_33>'
Structured positives: concept=0.2
OUTPUT 1:   epoch    condition   tf_loss  unique_outputs  mean_concept_positive  \
0    E2         FULL  9.486522               1                   0.20
1    E2  ZERO_STRUCT  9.487007               1                   0.00
2    E2  ZERO_VISUAL  9.480780               1                  18.00
3    E2    ZERO_BOTH  9.504089               1                   0.00
4    E3         FULL  0.553457               1                   0.85
5    E3  ZERO_STRUCT  0.553450               1

=== CELL 6 | execution_count=None | outputs=2 ===
59: model.load_state_dict(
OUTPUT 0:
======================================================================
LOGIT INTERVENTION — E2
======================================================================

Case 0

FULL
  0.916296 'VI'
  0.070310 'HI'
  0.009968 'N'
  0.001754 'CH'
  0.000974 'H'

ZERO_STRUCT
  0.916296 'VI'
  0.070310 'HI'
  0.009968 'N'
  0.001754 'CH'
  0.000974 'H'

ZERO_VISUAL
  0.916996 'VI'
  0.069824 'HI'
  0.009845 'N'
  0.001687 'CH'
  0.000962 'H'

ZERO_BOTH
  0.917428 'VI'
  0.069163 'HI'
  0.010003 'N'

OUTPUT 1:   epoch   comparison  mean_abs_logit_diff  max_abs_logit_diff  mean_cosine  \
0    E2    ZERO_BOTH             0.051839            0.173743          1.0
1    E2  ZERO_STRUCT             0.000347            0.001819          1.0
2    E2  ZERO_VISUAL             0.056256            0.229733          1.0
3    E3    ZERO_BOTH             0.022536            0.049583          1.0
4    E3  ZERO_STRUCT             0.003002            0.005345          1.0
5    E3  ZERO_VISUAL

=== CELL 7 | execution_count=None | outputs=10 ===
40: model.load_state_dict(E3["model_state"], strict=True)
350: sensitivity_df.to_csv(
355: summary_df.to_csv(
OUTPUT 0: ======================================================================
V4 E3 — VALIDATION SENSITIVITY
======================================================================
Validation cases: 756
Validation batches: 189
Checkpoint epoch: 3
Device: cuda
Processed  80/756 cases | 6.1 min
Processed 160/756 cases | 14.2 min
Processed 240/756 cases | 22.4 min
Processed 320/756 cases | 30.6 min
Processed 400/756 cases | 38.8 min
Processed 480/756 cases | 47.3 min
Processed 560/756 cases | 55.6 min
Proc
OUTPUT 1: /tmp/ipykernel_1990/3742130145.py:280: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(summarize_sensitivity)

OUTPUT 2:     comparison  n_cases      mean    median       p75       p90       p95  \
0  ZERO_STRUCT    756.0  0.003535  0.002670  0.004258  0.008357  0.008804
1  ZERO_VISUAL    756.0  0.053310  0.051428  0.063169  0.075513  0.081973
2    ZERO_BOTH    756.0  0.023706  0.023918  0.032110  0.038836  0.042927

        max   mean_js  argmax_change_rate  mean_top_prob_change
0  0.014415  0.000000                 0.0              0.000020
1  0.104376  0.000002                 0.0              0.00
OUTPUT 3:
======================================================================
TOP 10 MOST SENSITIVE CASES PER INTERVENTION
======================================================================

--- ZERO_STRUCT ---

OUTPUT 4:       case_index  mean_abs_logit_diff  max_abs_logit_diff  js_divergence  \
553          185             0.014415            0.025520            0.0
1356         452             0.013796            0.024414           -0.0
926          310             0.013740            0.024315            0.0
1393         465             0.013720            0.024292            0.0
1417         473             0.013503            0.023891            0.0
975          327             0.013310
OUTPUT 5:
--- ZERO_VISUAL ---

OUTPUT 6:       case_index  mean_abs_logit_diff  max_abs_logit_diff  js_divergence  \
1444         480             0.104376            0.184214       0.000003
1829         609             0.102175            0.180183       0.000003
136           44             0.101544            0.178871       0.000005
1338         446             0.101277            0.179134       0.000005
1470         490             0.100210            0.176899       0.000003
1711         571             0.099975
OUTPUT 7:
--- ZERO_BOTH ---

OUTPUT 8:       case_index  mean_abs_logit_diff  max_abs_logit_diff  js_divergence  \
1006         334             0.054779            0.096903       0.000000
11             3             0.053261            0.094206       0.000000
1271         423             0.051806            0.092779       0.000001
500          164             0.051768            0.091898       0.000000
323          107             0.051490            0.091261       0.000000
455          151             0.049831
OUTPUT 9:
======================================================================
DIAGNOSTIC COMPLETE
======================================================================
Details: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/diagnostics/e3_val756_first_token_sensitivity.csv
Summary: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/diagnostics/e3_val756_first_token_sensitivity_summary.csv
Checkpoint unchanged.


=== CELL 9 | execution_count=None | outputs=1 ===
14: model.load_state_dict(
OUTPUT 0: ======================================================================
V5 WARM-START FROM V4 E3
======================================================================
Shared compatible keys: 409
✓ V4 E3 weights copied into V5
Maximum weight difference: 0.000e+00
✓ Exact V4 → V5 weight transfer confirmed
✓ 14 critical V4/V5 tensors match exactly
✓ V4 and V5 remain separate model objects

======================================================================
V5 WARM-START AUDIT: PASS
=============

=== CELL 10 | execution_count=None | outputs=2 ===
18: model.load_state_dict(
OUTPUT 0: ======================================================================
V5 LOSS / GRADIENT BALANCE AUDIT
======================================================================


=== CELL 23 | execution_count=None | outputs=6 ===
188: loaded = torch.load(
205: v5_restore.load_state_dict(
246: optimizer_restore.load_state_dict(
250: scheduler_restore.load_state_dict(
OUTPUT 0: ======================================================================
V5 CHECKPOINT / RESUME DRY-RUN
======================================================================

V5 checkpoint dir:
/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints

V4 checkpoint dir:
/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints

Checkpoint keys:
['epoch', 'model_state', 'optimizer_state', 'scheduler_state', 'best_val', 'rng_state', 'cuda_rng_state', 'history']

Dry-run check
OUTPUT 1: Loading weights:   0%|          | 0/198 [00:00<?, ?it/s]
OUTPUT 2: [transformers] ViTModel LOAD REPORT from: google/vit-base-patch16-224
Key                 | Status     |
--------------------+------------+-
classifier.bias     | UNEXPECTED |
classifier.weight   | UNEXPECTED |
pooler.dense.weight | MISSING    |
pooler.dense.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. C
OUTPUT 3: Loading weights:   0%|          | 0/192 [00:00<?, ?it/s]
OUTPUT 4: [transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

OUTPUT 5:
MODEL RESTORE
----------------------------------------------------------------------
Max weight difference: 0.000e+00
Tensor mismatches: 0

SCHEDULER RESTORE
----------------------------------------------------------------------
Original last_epoch: 0
Restored last_epoch: 0
Original step_count: 1
Restored step_count: 1

======================================================================
PASS — V5 CHECKPOINT / RESUME DRY-RUN
====================================================================

=== CELL 24 | execution_count=None | outputs=2 ===
262: checkpoint_paths["last"] = os.path.join(CKPT_DIR, "last.pt")
263: checkpoint_paths["best"] = os.path.join(CKPT_DIR, "best.pt")
OUTPUT 0: ========== V5 TRAINING PRE-FLIGHT ==========
Device       : NVIDIA A100-SXM4-40GB
Seed         : 42
Epochs       : 5
Batch        : 4
Grad accum   : 4
Effective    : 16
Steps/epoch  : 384
Total steps  : 1920
Warmup       : 96



=== CELL 54 | execution_count=None | outputs=1 ===
21: ckpt = torch.load(
OUTPUT 0: Checkpoint: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt
Size (MB): 4425.15

Top-level keys:
['epoch', 'model_state', 'optimizer_state', 'scheduler_state', 'best_val', 'rng_state', 'cuda_rng_state', 'history']

Metadata-like entries:
epoch: 3
model_state: <model_state_dict, 409 tensors>
optimizer_state: <optimizer_state_dict>
scheduler_state: <scheduler_state>
best_val: 0.6521643281140656
rng_state: tensor([42,  0,  0,  ...,  0,  0,  0], dtype=torch.uint8)
cud

=== CELL 75 | execution_count=None | outputs=2 ===
35: os.path.join(V4_CKPT_DIR, "best.pt"),
89: ckpt = torch.load(
139: load_result = v5.load_state_dict(
OUTPUT 0: ================================================================================
CELL 25A — RESTORE V5 MODEL OBJECT ONLY
================================================================================

[RUNTIME]
V5Model: MISSING


=== CELL 82 | execution_count=None | outputs=2 ===
105: checkpoint = torch.load(
210: load_result = v5.load_state_dict(
OUTPUT 0: ================================================================================
CELL 25A — WARM-START V5 FROM V4 EPOCH 3
================================================================================

[RUNTIME OBJECTS]
v5                  : FOUND
V4_MANIFEST         : FOUND

[V4 CHECKPOINT DIRECTORY]
/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints

[V4 EPOCH 3 CANDIDATES]
 - /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt

Selected checkpo

=== CELL 84 | execution_count=None | outputs=1 ===
95: load_result = v5.load_state_dict(
OUTPUT 0: ================================================================================
CELL 25B — OFFICIAL V5 WARM-START FROM V4 EPOCH 3
================================================================================

[RUNTIME]
v5                  : FOUND
v4_state            : FOUND
v5_state            : FOUND
exact_compatible    : FOUND
checkpoint_path     : FOUND

[COMPATIBLE WEIGHTS]
Exact V4 -> V5 compatible tensors: 394
PASS: Compatible set exactly matches audit

[LOAD V4 -> V5]
Missing V5 keys:

=== CELL 95 | execution_count=None | outputs=1 ===
426: test_optimizer.load_state_dict(
430: test_scheduler.load_state_dict(
OUTPUT 0: ================================================================================
CELL 26 — V5 OPTIMIZER + SCHEDULER AUDIT
================================================================================

[RUNTIME]
v5                  : FOUND

PASS: No previous optimizer_v5/scheduler_v5 reused

[PARAMETER GROUPS]
Optimizer: AdamW
Number of parameter groups: 5
0: vision               lr=1.00e-05 params=200
1: projector            lr=1.00e-04 params=2
2: conditioner          lr=1.00e-04 params=3
3:

=== CELL 96 | execution_count=None | outputs=2 ===
278: checkpoint = torch.load(
307: model.load_state_dict(
311: optimizer.load_state_dict(
315: scheduler.load_state_dict(
OUTPUT 0: ================================================================================
CELL 27 — V5 CHECKPOINT / RESUME AUDIT
================================================================================

[RUNTIME]
v5                  : MISSING
optimizer_v5        : MISSING
scheduler_v5        : MISSING


=== CELL 97 | execution_count=None | outputs=2 ===
165: checkpoint = torch.load(
OUTPUT 0: ================================================================================
CELL 27A — RESTORE V5 RUNTIME AFTER SESSION RESET
================================================================================

[DEVICE]
device: cuda

[DEPENDENCIES]
V5Model                       : MISSING
Projector                     : MISSING
ViTModel                      : MISSING
MT5ForConditionalGeneration   : MISSING


=== CELL 104 | execution_count=None | outputs=1 ===
66: v4_ckpt = torch.load(
493: v4_ckpt_after = torch.load(
OUTPUT 0: ================================================================================
CELL 28 — V4 EPOCH 3 → V5 WARM-START AUDIT
================================================================================

[PATH]
V4 checkpoint: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt
PASS: V4 Epoch 3 checkpoint exists

[V5]
Class: V5Model
Trainable parameters: 387,020,219
PASS: Correct V5 model is active

[LOAD V4 CHECKPOINT]
Checkpoint type: dict
Checkpoint keys: ['epoch

=== CELL 105 | execution_count=None | outputs=2 ===
7: v4_ckpt_after = torch.load(
OUTPUT 0:

In [38]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import json
from pathlib import Path

NB_PATH = Path("/content/drive/MyDrive/Colab Notebooks/25sep.ipynb")
OUT_DIR = Path(
    "/content/drive/MyDrive/NoiSoi_Matching/"
    "baseline_model_v5/diagnostics/audit_20261015"
)
OUT_DIR.mkdir(parents=True, exist_ok=True)

with open(NB_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

needles = [
    "test_predictions_712.csv",
    "to_csv(",
    "test_predictions",
    "predictions_712",
    "prediction_path",
    "pred_path",
    "save_checkpoint",
    "best.pt",
    "last.pt",
    "model.generate(",
    "exact_generate(",
]

report = []

for i, cell in enumerate(nb.get("cells", [])):
    src = "".join(cell.get("source", []))
    output_text = []

    for output in cell.get("outputs", []):
        if "text" in output:
            val = output["text"]
            output_text.append(
                "".join(val) if isinstance(val, list) else str(val)
            )

        for mime in ("text/plain", "text/html"):
            val = output.get("data", {}).get(mime)
            if val:
                output_text.append(
                    "".join(val) if isinstance(val, list) else str(val)
                )

    out = "\n".join(output_text)
    src_hits = [
        (n, line.strip())
        for n, line in enumerate(src.splitlines(), 1)
        if any(term in line.lower() for term in needles)
    ]
    out_hits = [
        (n, line.strip()[:220])
        for n, line in enumerate(out.splitlines(), 1)
        if any(term in line.lower() for term in needles)
    ]

    if src_hits or out_hits:
        report.append(
            f"\n=== CELL {i} | execution_count={cell.get('execution_count')} ==="
        )
        if src_hits:
            report.append("-- SOURCE MATCHES --")
            report.extend(f"{n}: {line[:240]}" for n, line in src_hits[:35])
        if out_hits:
            report.append("-- SAVED OUTPUT MATCHES --")
            report.extend(f"output line {n}: {line}" for n, line in out_hits[:20])

result = "\n".join(report)
print(result[:26000] if result else "Không tìm thấy dấu vết khớp.")

save_path = OUT_DIR / "cell13_full_notebook_prediction_trace.txt"
save_path.write_text(result, encoding="utf-8")
print("\nSaved:", save_path)
print("READ-ONLY: không nạp model, không inference, không train, không sửa checkpoint.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

=== CELL 0 | execution_count=None ===
-- SOURCE MATCHES --
73: f"{V4_DIR}/checkpoints/best.pt"

=== CELL 1 | execution_count=None ===
-- SOURCE MATCHES --
90: f"{V4_DIR}/checkpoints/best.pt"
1416: def exact_generate(
1533: pred_full = exact_generate(
1551: exact_generate(
1570: exact_generate(
1589: exact_generate(
-- SAVED OUTPUT MATCHES --
output line 13: Best checkpoint       : PASS -> /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt
output line 43: source_v3_checkpoint: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt

=== CELL 7 | execution_count=None ===
-- SOURCE MATCHES --
350: sensitivity_df.to_csv(
355: summary_df.to_csv(

=== CELL 24 | execution_count=None ===
-- SOURCE MATCHES --
262: checkpoint_paths["last"] = os.path.join(CKPT_DIR, "last.pt")
263: checkpoint_paths["best"] = os.path.join(CKPT_DIR, "best.pt")

=== CELL 44 | execution_count=None ===
-- SAVED OUTPUT MATCHES --
output line 11: checkpoint_best: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt
output line 14: checkpoint_last: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt
output line 45: source_v3_checkpoint: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt

=== CELL 52 | execution_count=None ===
-- SAVED OUTPUT MATCHES --
output line 10: best.pt
output line 14: last.pt

=== CELL 71 | execution_count=None ===
-- SAVED OUTPUT MATCHES --
output line 102: f"{V4_DIR}/checkpoints/best.pt"

=== CELL 72 | execution_count=None ===
-- SAVED OUTPUT MATCHES --
output line 102: f"{V4_DIR}/checkpoints/best.pt"

=== CELL 75 | execution_count=None ===
-- SOURCE MATCHES --
35: os.path.join(V4_CKPT_DIR, "best.pt"),

=== CELL 77 | execution_count=None ===
-- SAVED OUTPUT MATCHES --
output line 1074: os.path.join(V4_CKPT_DIR, "best.pt"),

=== CELL 79 | execution_count=None ===
-- SAVED OUTPUT MATCHES --
output line 99: f"{V4_DIR}/checkpoints/best.pt"
output line 194: f"{V4_DIR}/checkpoints/best.pt"
output line 1520: def exact_generate(
output line 1637: pred_full = exact_generate(
output line 1655: exact_generate(
output line 1674: exact_generate(
output line 1693: exact_generate(

=== CELL 126 | execution_count=1 ===
-- SOURCE MATCHES --
8: #   - last.pt
10: #   - best.pt
92: V5_CKPT_DIR / "last.pt"
96: V5_CKPT_DIR / "best.pt"
252: def save_checkpoint(
870: save_checkpoint(
880: # Also update last.pt
881: save_checkpoint(
1168: save_checkpoint(
1194: save_checkpoint(
1209: save_checkpoint(
1280: f"last.pt exists  : {LAST_CKPT.exists()}"
1284: f"best.pt exists  : {BEST_CKPT.exists()}"
1327: "last.pt:",
1332: "best.pt:",
1343: print("PASS: last.pt maintained.")
1344: print("PASS: best.pt maintained.")

=== CELL 127 | execution_count=3 ===
-- SOURCE MATCHES --
103: V5_CKPT_DIR / "last.pt"
107: V5_CKPT_DIR / "best.pt"
377: def save_checkpoint(
1040: save_checkpoint(
1050: save_checkpoint(
1259: save_checkpoint(
1289: save_checkpoint(
1304: save_checkpoint(
1399: "last.pt:",
1404: "best.pt:",

=== CELL 139 | execution_count=15 ===
-- SOURCE MATCHES --
24: #   best.pt
25: #   last.pt
161: "last.pt"
166: "best.pt"
2101: "last.pt:",
2106: "best.pt:",

=== CELL 140 | execution_count=16 ===
-- SOURCE MATCHES --
51: LAST_CKPT = V5_CKPT_DIR / "last.pt"
52: BEST_CKPT = V5_CKPT_DIR / "best.pt"
336: # 10. RESUME IF last.pt EXISTS
367: print("No last.pt found.")
385: "last.pt:",
390: "best.pt exists:",
1124: "last.pt exists:",
1129: "best.pt exists:",
1146: print("PASS: last.pt exists.")
1147: print("PASS: best.pt exists.")

=== CELL 146 | execution_count=26 ===
-- SOURCE MATCHES --
18: "best.pt",

=== CELL 147 | execution_count=29 ===
-- SOURCE MATCHES --
69: "best.pt",
70: "last.pt",

=== CELL 149 | execution_count=31 ===
-- SOURCE MATCHES --
22: "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",
23: "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt",
33: "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt",
34: "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/last.pt",
77: "best.pt",
78: "last.pt",
-- SAVED OUTPUT MATCHES --
output line 10: MISSING /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt
output line 11: MISSING /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt
output line 17: MISSING /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt
output line 18: MISSING /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/last.pt

=== CELL 153 | execution_count=35 ===
-- SOURCE MATCHES --
20: "NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",
21: "NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt",
-- SAVED OUTPUT MATCHES --
output line 7: FOUND       4425.07 MB    NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt
output line 8: FOUND       4425.07 MB    NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt

=== CELL 155 | execution_count=37 ===
-- SOURCE MATCHES --
22: f"{ROOT}/baseline_model_v4/checkpoints/best.pt",
25: f"{ROOT}/baseline_model_v4/checkpoints/last.pt",
-- SAVED OUTPUT MATCHES --
output line 7: PASS   | V4 best                | /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt
output line 8: PASS   | V4 last                | /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt

=== CELL 161 | execution_count=43 ===
-- SOURCE MATCHES --
62: f"{ROOT}/baseline_model_v4/checkpoints/best.pt",

Saved: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell13_full_notebook_prediction_trace.txt
READ-ONLY: không nạp model, không inference, không train, không sửa checkpoint.

In [39]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
import torch

ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
CKPT_DIR = ROOT / "baseline_model_v5/checkpoints"

for name in ["best.pt", "last.pt"]:
    path = CKPT_DIR / name
    print(f"\n{'='*65}\n{name}\n{'='*65}")

    if not path.exists():
        print("MISSING:", path)
        continue

    print("Size (GB):", round(path.stat().st_size / (1024**3), 3))
    print("Modified:", __import__("datetime").datetime.fromtimestamp(
        path.stat().st_mtime
    ).isoformat())

    # WARNING: checkpoint ~4.3 GB; reading it can take tens of seconds
    # and temporarily consume several GB of RAM.
    # weights_only=False is required for the checkpoint's optimizer/RNG metadata.
    ckpt = torch.load(
        path,
        map_location="cpu",
        weights_only=False
    )

    print("Epoch:", ckpt.get("epoch"))
    print("Global step:", ckpt.get("global_step", "not stored"))
    print("Best validation loss:", ckpt.get("best_val"))
    print("Top-level keys:", list(ckpt.keys()))

    state = ckpt.get("model_state", {})
    print("Model tensor count:", len(state))

    for prefix in [
        "concept_head", "negative_head", "attribute_head",
        "structured_heads", "lm_head", "mt5"
    ]:
        matches = [
            (k, tuple(v.shape))
            for k, v in state.items()
            if k.startswith(prefix)
        ]
        if matches:
            print(f"\n{prefix}:")
            for key, shape in matches[:12]:
                print(" ", key, shape)

    del state, ckpt

print("\nREAD-ONLY: không train, không optimizer step, không lưu checkpoint.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

=================================================================
best.pt
=================================================================
Size (GB): 4.321
Modified: 2026-09-29T04:20:44
Epoch: 5
Global step: 1920
Best validation loss: 0.424518172663671
Top-level keys: ['epoch', 'batch_idx', 'global_step', 'model_state', 'optimizer_state', 'scheduler_state', 'best_val', 'history', 'rng_state', 'cuda_rng_state', 'python_rng_state', 'numpy_rng_state']
Model tensor count: 403

concept_head:
  concept_head.weight (48, 512)
  concept_head.bias (48,)

negative_head:
  negative_head.weight (5, 512)
  negative_head.bias (5,)

attribute_head:
  attribute_head.weight (6, 512)
  attribute_head.bias (6,)

mt5:
  mt5.shared.weight (250112, 512)
  mt5.encoder.embed_tokens.weight (250112, 512)
  mt5.encoder.block.0.layer.0.SelfAttention.q.weight (384, 512)
  mt5.encoder.block.0.layer.0.SelfAttention.k.weight (384, 512)
  mt5.encoder.block.0.layer.0.SelfAttention.v.weight (384, 512)
  mt5.encoder.block.0.layer.0.SelfAttention.o.weight (512, 384)
  mt5.encoder.block.0.layer.0.SelfAttention.relative_attention_bias.weight (32, 6)
  mt5.encoder.block.0.layer.0.layer_norm.weight (512,)
  mt5.encoder.block.0.layer.1.DenseReluDense.wi_0.weight (1024, 512)
  mt5.encoder.block.0.layer.1.DenseReluDense.wi_1.weight (1024, 512)
  mt5.encoder.block.0.layer.1.DenseReluDense.wo.weight (512, 1024)
  mt5.encoder.block.0.layer.1.layer_norm.weight (512,)

=================================================================
last.pt
=================================================================
Size (GB): 4.321
Modified: 2026-09-29T04:25:51
Epoch: 5
Global step: 1920
Best validation loss: 0.424518172663671
Top-level keys: ['epoch', 'batch_idx', 'global_step', 'model_state', 'optimizer_state', 'scheduler_state', 'best_val', 'history', 'rng_state', 'cuda_rng_state', 'python_rng_state', 'numpy_rng_state']
Model tensor count: 403

concept_head:
  concept_head.weight (48, 512)
  concept_head.bias (48,)

negative_head:
  negative_head.weight (5, 512)
  negative_head.bias (5,)

attribute_head:
  attribute_head.weight (6, 512)
  attribute_head.bias (6,)

mt5:
  mt5.shared.weight (250112, 512)
  mt5.encoder.embed_tokens.weight (250112, 512)
  mt5.encoder.block.0.layer.0.SelfAttention.q.weight (384, 512)
  mt5.encoder.block.0.layer.0.SelfAttention.k.weight (384, 512)
  mt5.encoder.block.0.layer.0.SelfAttention.v.weight (384, 512)
  mt5.encoder.block.0.layer.0.SelfAttention.o.weight (512, 384)
  mt5.encoder.block.0.layer.0.SelfAttention.relative_attention_bias.weight (32, 6)
  mt5.encoder.block.0.layer.0.layer_norm.weight (512,)
  mt5.encoder.block.0.layer.1.DenseReluDense.wi_0.weight (1024, 512)
  mt5.encoder.block.0.layer.1.DenseReluDense.wi_1.weight (1024, 512)
  mt5.encoder.block.0.layer.1.DenseReluDense.wo.weight (512, 1024)
  mt5.encoder.block.0.layer.1.layer_norm.weight (512,)

READ-ONLY: không train, không optimizer step, không lưu checkpoint.

In [40]:
from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
import json

ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
V5_DIR = ROOT / "baseline_model_v5"
NOTEBOOK = Path("/content/drive/MyDrive/Colab Notebooks/25sep.ipynb")

TERMS = [
    "test_predictions_712.csv",
    "test_predictions",
    "prediction_path",
    "model.generate",
    "exact_generate",
    "argmax",
    "best.pt",
    "last.pt",
]

print("=== NOTEBOOK: prediction-related source lines ===")
if NOTEBOOK.exists():
    nb = json.loads(NOTEBOOK.read_text(encoding="utf-8"))
    hits = 0

    for i, cell in enumerate(nb.get("cells", [])):
        source = "".join(cell.get("source", []))
        matches = [
            (line_no, line.strip()[:240])
            for line_no, line in enumerate(source.splitlines(), 1)
            if any(term.lower() in line.lower() for term in TERMS)
        ]

        if matches:
            print(f"\nCell {i} | type={cell.get('cell_type')}")
            for line_no, line in matches[:12]:
                print(f"  L{line_no}: {line}")
            hits += len(matches)

    print(f"\nNotebook source matches: {hits}")
else:
    print("Notebook not found at the expected path.")

print("\n=== V5: small code/log/config files ===")
allowed = {".py", ".txt", ".log", ".json", ".yaml", ".yml", ".md"}
skip_dirs = {
    "checkpoints", "__pycache__", ".git",
    "images", "image_cache", "data", "datasets"
}
scanned = 0
found = 0

if V5_DIR.exists():
    for folder, dirs, files in __import__("os").walk(V5_DIR):
        dirs[:] = [d for d in dirs if d not in skip_dirs]

        for filename in files:
            path = Path(folder) / filename
            if path.suffix.lower() not in allowed:
                continue
            if scanned >= 500:
                print("Stopped at 500 files to keep the audit bounded.")
                break

            scanned += 1
            try:
                if path.stat().st_size > 2_000_000:
                    continue
                content = path.read_text(encoding="utf-8", errors="ignore")
                matches = [
                    (line_no, line.strip()[:220])
                    for line_no, line in enumerate(content.splitlines(), 1)
                    if any(term.lower() in line.lower() for term in TERMS)
                ]
                if matches:
                    found += 1
                    print(f"\nFILE: {path}")
                    for line_no, line in matches[:10]:
                        print(f"  L{line_no}: {line}")
            except Exception as e:
                print(f"Skipped {path.name}: {type(e).__name__}")

        if scanned >= 500:
            break

print(f"\nFiles scanned: {scanned} | Files with matches: {found}")
print("READ-ONLY audit complete.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
=== NOTEBOOK: prediction-related source lines ===

Cell 0 | type=code
  L73: f"{V4_DIR}/checkpoints/best.pt"

Cell 1 | type=code
  L90: f"{V4_DIR}/checkpoints/best.pt"
  L1416: def exact_generate(
  L1459: next_token = torch.argmax(
  L1533: pred_full = exact_generate(
  L1551: exact_generate(
  L1570: exact_generate(
  L1589: exact_generate(

Cell 5 | type=code
  L214: next_token = torch.argmax(

Cell 6 | type=code
  L127: # Does argmax change?
  L128: full_argmax = int(torch.argmax(full))
  L129: other_argmax = int(torch.argmax(other))
  L131: argmax_changed = (
  L132: full_argmax != other_argmax
  L142: "argmax_changed": argmax_changed,
  L144: [full_argmax],
  L148: [other_argmax],
  L228: argmax_change_rate=(
  L229: "argmax_changed",

Cell 7 | type=code
  L96: full_top = full.argmax(dim=-1)
  L97: other_top = other.argmax(dim=-1)
  L132: "argmax_changed": full_top.ne(other_top),
  L267: "argmax_change_rate": (
  L268: group["argmax_changed"].mean()
  L321: "argmax_changed",

Cell 24 | type=code
  L262: checkpoint_paths["last"] = os.path.join(CKPT_DIR, "last.pt")
  L263: checkpoint_paths["best"] = os.path.join(CKPT_DIR, "best.pt")

Cell 75 | type=code
  L35: os.path.join(V4_CKPT_DIR, "best.pt"),

Cell 126 | type=code
  L8: #   - last.pt
  L10: #   - best.pt
  L92: V5_CKPT_DIR / "last.pt"
  L96: V5_CKPT_DIR / "best.pt"
  L880: # Also update last.pt
  L1280: f"last.pt exists  : {LAST_CKPT.exists()}"
  L1284: f"best.pt exists  : {BEST_CKPT.exists()}"
  L1327: "last.pt:",
  L1332: "best.pt:",
  L1343: print("PASS: last.pt maintained.")
  L1344: print("PASS: best.pt maintained.")

Cell 127 | type=code
  L103: V5_CKPT_DIR / "last.pt"
  L107: V5_CKPT_DIR / "best.pt"
  L1399: "last.pt:",
  L1404: "best.pt:",

Cell 139 | type=code
  L24: #   best.pt
  L25: #   last.pt
  L161: "last.pt"
  L166: "best.pt"
  L2101: "last.pt:",
  L2106: "best.pt:",

Cell 140 | type=code
  L51: LAST_CKPT = V5_CKPT_DIR / "last.pt"
  L52: BEST_CKPT = V5_CKPT_DIR / "best.pt"
  L336: # 10. RESUME IF last.pt EXISTS
  L367: print("No last.pt found.")
  L385: "last.pt:",
  L390: "best.pt exists:",
  L1124: "last.pt exists:",
  L1129: "best.pt exists:",
  L1146: print("PASS: last.pt exists.")
  L1147: print("PASS: best.pt exists.")

Cell 146 | type=code
  L18: "best.pt",

Cell 147 | type=code
  L69: "best.pt",
  L70: "last.pt",

Cell 149 | type=code
  L22: "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",
  L23: "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt",
  L33: "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt",
  L34: "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/last.pt",
  L77: "best.pt",
  L78: "last.pt",

Cell 153 | type=code
  L20: "NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",
  L21: "NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt",

Cell 155 | type=code
  L22: f"{ROOT}/baseline_model_v4/checkpoints/best.pt",
  L25: f"{ROOT}/baseline_model_v4/checkpoints/last.pt",

Cell 161 | type=code
  L62: f"{ROOT}/baseline_model_v4/checkpoints/best.pt",

Notebook source matches: 73

=== V5: small code/log/config files ===

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/v5_final_training_summary.json
  L23: "last_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/last.pt",
  L24: "best_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/best.pt"

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell1_schema_ontology_audit.txt
  L51: Path: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/test_predictions_712.csv

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell6_training_source_audit.txt
  L76: f"{V4_DIR}/checkpoints/best.pt"
  L170: f"{V4_DIR}/checkpoints/best.pt"
  L1496: def exact_generate(
  L1539: next_token = torch.argmax(
  L1613: pred_full = exact_generate(
  L1631: exact_generate(
  L1650: exact_generate(
  L1669: exact_generate(
  L2315: next_token = torch.argmax(
  L2676: # Does argmax change?

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell7_v5_training_flow.txt
  L37: 161:     "last.pt"
  L42: 166:     "best.pt"
  L177: 2106:     "best.pt:",

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell8_saved_training_history.txt
  L85: SOURCE   96:     V5_CKPT_DIR / "best.pt"
  L150: SOURCE 1284:         f"best.pt exists  : {BEST_CKPT.exists()}"
  L161: SOURCE 1332:     "best.pt:",
  L172: SOURCE 1343: print("PASS: last.pt maintained.")
  L173: SOURCE 1344: print("PASS: best.pt maintained.")
  L184: SOURCE  107:     V5_CKPT_DIR / "best.pt"
  L260: SOURCE 1404:     "best.pt:",
  L299: SOURCE  166:     "best.pt"
  L457: SOURCE 2106:     "best.pt:",
  L478: SOURCE   51: LAST_CKPT = V5_CKPT_DIR / "last.pt"

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell11_prediction_generation_source.txt
  L32: 1416: def exact_generate(
  L40: 1459:         next_token = torch.argmax(
  L56: 1533:         pred_full = exact_generate(
  L64: 1551:             exact_generate(
  L72: 1570:             exact_generate(
  L80: 1589:             exact_generate(
  L139: 214:         next_token = torch.argmax(
  L166: 127:             # Does argmax change?
  L167: 128:             full_argmax = int(torch.argmax(full))
  L168: 129:             other_argmax = int(torch.argmax(other))

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell12_checkpoint_and_prediction_source.txt
  L4: 73: f"{V4_DIR}/checkpoints/best.pt"
  L13: 90: f"{V4_DIR}/checkpoints/best.pt"
  L228: max   mean_js  argmax_change_rate  mean_top_prob_change
  L349: 262: checkpoint_paths["last"] = os.path.join(CKPT_DIR, "last.pt")
  L350: 263: checkpoint_paths["best"] = os.path.join(CKPT_DIR, "best.pt")
  L382: 35: os.path.join(V4_CKPT_DIR, "best.pt"),
  L626: 8: #   - last.pt
  L627: 10: #   - best.pt
  L628: 92: V5_CKPT_DIR / "last.pt"
  L630: 96: V5_CKPT_DIR / "best.pt"

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell13_full_notebook_prediction_trace.txt
  L4: 73: f"{V4_DIR}/checkpoints/best.pt"
  L8: 90: f"{V4_DIR}/checkpoints/best.pt"
  L9: 1416: def exact_generate(
  L10: 1533: pred_full = exact_generate(
  L11: 1551: exact_generate(
  L12: 1570: exact_generate(
  L13: 1589: exact_generate(
  L15: output line 13: Best checkpoint       : PASS -> /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt
  L16: output line 43: source_v3_checkpoint: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt
  L25: 262: checkpoint_paths["last"] = os.path.join(CKPT_DIR, "last.pt")

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/runtime_state/paths.json
  L4: "v4_best": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",

Files scanned: 14 | Files with matches: 9
READ-ONLY audit complete.

In [41]:
from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
import json

ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
V5 = ROOT / "baseline_model_v5"

# 1. Training summary
summary_path = V5 / "diagnostics/v5_final_training_summary.json"
print("=" * 70)
print("1. V5 FINAL TRAINING SUMMARY")

if summary_path.exists():
    try:
        summary = json.loads(summary_path.read_text(encoding="utf-8"))
        print(json.dumps(summary, ensure_ascii=False, indent=2)[:12000])
    except Exception as e:
        print("Could not parse summary:", repr(e))
else:
    print("Summary file not found.")

# 2. Runtime paths
paths_path = V5 / "runtime_state/paths.json"
print("\n" + "=" * 70)
print("2. RUNTIME PATHS")

if paths_path.exists():
    try:
        paths = json.loads(paths_path.read_text(encoding="utf-8"))
        print(json.dumps(paths, ensure_ascii=False, indent=2))
    except Exception as e:
        print("Could not parse paths:", repr(e))
else:
    print("Runtime paths file not found.")

# 3. Relevant files in V5 (metadata only)
print("\n" + "=" * 70)
print("3. RELEVANT V5 FILES")

for folder in [V5, V5 / "diagnostics", V5 / "runtime_state",
               V5 / "checkpoints"]:
    print(f"\n[{folder}]")
    if not folder.exists():
        print("  Folder not found.")
        continue

    for p in sorted(folder.iterdir(), key=lambda x: x.name.lower()):
        if p.is_file():
            stat = p.stat()
            print(
                f"  FILE {p.name} | "
                f"{stat.st_size:,} bytes | "
                f"modified={__import__('datetime').datetime.fromtimestamp(stat.st_mtime).isoformat(timespec='seconds')}"
            )
        elif p.is_dir():
            print(f"  DIR  {p.name}/")

print("\nREAD-ONLY audit complete.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
======================================================================
1. V5 FINAL TRAINING SUMMARY
{
  "model": "V5",
  "status": "TRAINING_COMPLETE",
  "num_epochs": 5,
  "global_step": 1920,
  "epoch": 5,
  "next_batch": 0,
  "best_val": 0.424518172663671,
  "train_loss": [
    0.5731708970967303,
    0.5046075203082849,
    0.47171955251829634,
    0.45422747778290645,
    0.44715843725379206
  ],
  "val_loss": [
    0.46700948011622856,
    0.44155955633946825,
    0.42823387978095856,
    0.4258775923539091,
    0.424518172663671
  ],
  "last_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/last.pt",
  "best_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/best.pt"
}

======================================================================
2. RUNTIME PATHS
{
  "v4_manifest": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv",
  "v4_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt",
  "v4_best": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",
  "structured_targets": "/content/drive/MyDrive/NoiSoi_Matching/v3_ontology_v2/v3_structured_targets_v2_2.csv",
  "ontology_mapping": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/diagnostics/frozen_concept_ontology_mapping.csv",
  "final_manifest": "/content/drive/MyDrive/NoiSoi_Matching/final_manifest/final_dataset_manifest.csv",
  "v5_root": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5"
}

======================================================================
3. RELEVANT V5 FILES

[/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5]
  FILE anatomy_error_stratification.csv | 331,383 bytes | modified=2026-10-14T12:34:59
  DIR  checkpoints/
  DIR  diagnostics/
  FILE distribution_shift_audit.csv | 1,669 bytes | modified=2026-10-14T12:26:22
  FILE low_overlap_image_metadata.csv | 4,948 bytes | modified=2026-10-14T12:29:51
  FILE prediction_frequency_audit.csv | 710 bytes | modified=2026-10-14T12:14:15
  FILE prediction_quality_audit.csv | 79,960 bytes | modified=2026-10-14T12:19:52
  DIR  runtime_state/
  FILE test_predictions_712.csv | 62,941 bytes | modified=2026-09-30T16:34:27
  FILE text_overlap_audit.csv | 140,287 bytes | modified=2026-10-14T12:28:11
  FILE tympanic_membrane_cases.csv | 19,125 bytes | modified=2026-10-14T11:57:16

[/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics]
  DIR  audit_20261015/
  FILE v5_final_training_summary.json | 649 bytes | modified=2026-09-29T04:23:10

[/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/runtime_state]
  FILE environment.json | 182 bytes | modified=2026-09-28T08:24:55
  FILE gpu_state.json | 101 bytes | modified=2026-09-28T08:24:55
  FILE paths.json | 719 bytes | modified=2026-09-28T08:24:55
  FILE runtime_info.json | 310 bytes | modified=2026-09-28T08:24:55

[/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints]
  FILE best.pt | 4,640,037,647 bytes | modified=2026-09-29T04:20:44
  FILE last.pt | 4,640,037,647 bytes | modified=2026-09-29T04:25:51

READ-ONLY audit complete.

In [42]:
from google.colab import drive
drive.mount("/content/drive", force_remount=False)

from pathlib import Path
from collections import Counter
import pandas as pd
import json
import os
import re

ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
V5 = ROOT / "baseline_model_v5"
AUDIT = V5 / "diagnostics/audit_20261015"

def section(title):
    print("\n" + "=" * 88)
    print(title)
    print("=" * 88)

def norm_text(x):
    if pd.isna(x):
        return ""
    return re.sub(r"\s+", " ", str(x).strip().lower())

# ------------------------------------------------------------
# 1. ORIGINAL PREDICTIONS: distribution and direct comparison
# ------------------------------------------------------------
section("1. TEST PREDICTIONS — COUNTS, LABEL DISTRIBUTION, EXACT MATCH")

pred_path = V5 / "test_predictions_712.csv"

if pred_path.exists():
    pred = pd.read_csv(pred_path)
    print("Path:", pred_path)
    print("Shape:", pred.shape)
    print("Columns:", pred.columns.tolist())

    if "case_id" in pred.columns:
        print("Unique case_id:", pred["case_id"].nunique())
        print("Duplicate case_id rows:", int(pred["case_id"].duplicated().sum()))

    if {"prediction", "ground_truth"}.issubset(pred.columns):
        pred["_p_norm"] = pred["prediction"].map(norm_text)
        pred["_g_norm"] = pred["ground_truth"].map(norm_text)

        print("Unique predictions:", pred["_p_norm"].nunique())
        print("Unique ground truths:", pred["_g_norm"].nunique())
        print("Exact normalized match rate:",
              round(float((pred["_p_norm"] == pred["_g_norm"]).mean()), 4))

        print("\nTop 15 predictions:")
        print(pred["prediction"].value_counts(dropna=False).head(15).to_string())

        print("\nTop 15 ground truths:")
        print(pred["ground_truth"].value_counts(dropna=False).head(15).to_string())

        print("\nFirst 8 mismatches:")
        mismatch = pred[pred["_p_norm"] != pred["_g_norm"]]
        print(mismatch[["case_id", "prediction", "ground_truth"]]
              .head(8).to_string(index=False))

        print("\nPrediction frequency quantiles:")
        freq = pred["prediction"].value_counts()
        print(freq.describe(percentiles=[.25, .5, .75, .9, .95]).to_string())
else:
    print("Prediction CSV not found.")

# ------------------------------------------------------------
# 2. EXISTING AUDIT CSV REPORTS
# ------------------------------------------------------------
section("2. EXISTING AUDIT CSV FILES")

audit_files = [
    V5 / "prediction_frequency_audit.csv",
    V5 / "prediction_quality_audit.csv",
    V5 / "distribution_shift_audit.csv",
    V5 / "text_overlap_audit.csv",
    V5 / "low_overlap_image_metadata.csv",
    V5 / "anatomy_error_stratification.csv",
    V5 / "tympanic_membrane_cases.csv",
    AUDIT / "cell10_prediction_audit.csv",
]

for path in audit_files:
    if not path.exists():
        print(f"\nMISSING: {path.name}")
        continue

    try:
        df = pd.read_csv(path)
        print(f"\n--- {path.name} | shape={df.shape} ---")
        print("Columns:", df.columns.tolist())

        # Show a compact sample of existing audit results.
        if len(df):
            print(df.head(4).to_string(index=False, max_cols=12, max_colwidth=90))

        # Useful numeric summary without dumping the full table.
        numeric = df.select_dtypes(include="number")
        if not numeric.empty:
            print("Numeric summary:")
            print(numeric.describe().round(4).to_string(max_rows=8, max_cols=8))

    except Exception as e:
        print(f"Could not read {path.name}: {type(e).__name__}: {e}")

# ------------------------------------------------------------
# 3. CHECK AUDIT TEXT REPORTS FOR CONCLUSIONS / EVIDENCE
# ------------------------------------------------------------
section("3. EXISTING TEXT AUDITS — RELEVANT LINES")

text_files = [
    AUDIT / "cell1_schema_ontology_audit.txt",
    AUDIT / "cell6_training_source_audit.txt",
    AUDIT / "cell7_v5_training_flow.txt",
    AUDIT / "cell8_saved_training_history.txt",
    AUDIT / "cell11_prediction_generation_source.txt",
    AUDIT / "cell12_checkpoint_and_prediction_source.txt",
    AUDIT / "cell13_full_notebook_prediction_trace.txt",
]

keywords = [
    "test_predictions_712.csv", "to_csv(", "to_csv ",
    "prediction_quality_audit", "prediction_frequency_audit",
    "exact_generate", "model.generate", "argmax",
    "ground_truth", "prediction_path", "save_path",
    "checkpoint", "best.pt", "last.pt",
]

for path in text_files:
    if not path.exists():
        continue

    print(f"\n--- {path.name} ---")
    try:
        lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
        hits = [
            (i + 1, line.strip()[:240])
            for i, line in enumerate(lines)
            if any(k.lower() in line.lower() for k in keywords)
        ]
        if not hits:
            print("No matching lines.")
        else:
            for line_no, line in hits[:12]:
                print(f"L{line_no}: {line}")
            if len(hits) > 12:
                print(f"... {len(hits) - 12} additional matching lines omitted.")
    except Exception as e:
        print("Read error:", repr(e))

# ------------------------------------------------------------
# 4. PROJECT-LEVEL CODE / LOG SEARCH, EXCLUDING LARGE DATA
# ------------------------------------------------------------
section("4. PROJECT CODE/LOG SEARCH FOR CSV GENERATION")

search_terms = [
    "test_predictions_712.csv",
    "prediction_quality_audit.csv",
    "prediction_frequency_audit.csv",
    "to_csv(",
    "to_csv ",
]
extensions = {".py", ".ipynb", ".txt", ".log", ".json", ".yaml", ".yml", ".md"}
skip_dirs = {
    "checkpoints", "images", "image_cache", "data", "datasets",
    "__pycache__", ".git"
}

scanned = 0
hits_found = 0
MAX_FILES = 700
MAX_MATCHES_PER_FILE = 5

for folder, dirs, files in os.walk(ROOT):
    dirs[:] = [d for d in dirs if d not in skip_dirs]

    for filename in files:
        path = Path(folder) / filename
        if path.suffix.lower() not in extensions:
            continue
        if scanned >= MAX_FILES:
            break

        scanned += 1
        try:
            if path.stat().st_size > 3_000_000:
                continue
            content = path.read_text(encoding="utf-8", errors="ignore")
            matches = []
            for i, line in enumerate(content.splitlines(), 1):
                if any(term.lower() in line.lower() for term in search_terms):
                    matches.append((i, line.strip()[:220]))
                    if len(matches) >= MAX_MATCHES_PER_FILE:
                        break

            if matches:
                hits_found += 1
                print(f"\nFILE: {path}")
                for line_no, line in matches:
                    print(f"  L{line_no}: {line}")
        except Exception:
            pass

    if scanned >= MAX_FILES:
        print(f"\nSearch stopped at the safety limit of {MAX_FILES} files.")
        break

print(f"\nScanned files: {scanned}")
print(f"Files with matches: {hits_found}")

section("AUDIT COMPLETE")
print("READ-ONLY: no training, no optimizer step, no checkpoint writes.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

========================================================================================
1. TEST PREDICTIONS — COUNTS, LABEL DISTRIBUTION, EXACT MATCH
========================================================================================
Path: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/test_predictions_712.csv
Shape: (712, 3)
Columns: ['case_id', 'prediction', 'ground_truth']
Unique case_id: 712
Duplicate case_id rows: 0
Unique predictions: 16
Unique ground truths: 267
Exact normalized match rate: 0.184

Top 15 predictions:
prediction
VIÊM MŨI MẠN                                    324
VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP             126
VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.     81
VIÊM MŨI XOANG                                   52
VIÊM MŨI + VA                                    47
VIÊM TAI GIỮA P MẠN                              46
VIÊM TAI GIỮA T CẤP VIÊM MŨI                     10
VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T                   8
VIÊM MŨI XOANG MẠN - POLYP MŨI                    6
VIÊM ỐNG TAI NGOÀI 2 BÊN MẠN                      4
VIÊM ỐNG TAI NGOÀI P CẤP                          2
VIÊM TAI GIỮA T MẠN                               2
VIÊM TAI GIỮA T CẤP VIÊM MŨI XOANG                1
VIÊM TAI GIỮA 2 BÊN VIÊM MŨI                      1
VIÊM MŨI                                          1

Top 15 ground truths:
ground_truth
VIÊM MŨI MẠN                                                         79
VIÊM MŨI                                                             66
VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.                         51
VIÊM MŨI XOANG                                                       35
VIÊM MŨI ĐỢT CẤP                                                     18
VIÊM MŨI + VA                                                        14
HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TAI GIỮA TRÊN NỘI SOI    12
VIÊM TAI GIỮA T MẠN                                                  10
HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI GIỮA TRÊN NỘI SOI     10
VIÊM MŨI XOANG MẠN - POLYP MŨI                                        9
VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ P CẤP                                   9
VIÊM TAI GIỮA T MẠN VIÊM MŨI XOANG MẠN / ĐÃ PTNS MŨI XOANG            9
VIÊM MŨI MẠN + VA                                                     9
VIÊM MŨI XOANG MẠN (ĐÃ PT)                                            7
VIÊM MŨI XOANG + VIÊM VA                                              7

First 8 mismatches:
            case_id                                   prediction                                                                ground_truth
10017.10017.0.10031          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                             VIÊM MÀNG NHĨ CẤP BÓNG NƯỚC P - NHIỀU RÁY TAI T
10057.10057.0.10071          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                              VIÊM ỐNG TAI NGOÀI (T) MẠN / VIÊM MŨI ĐỢT CẤP.
10116.10116.0.10130          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                                           VIÊM ỐNG TAI NGOÀI MÀNG NHĨ P CẤP
10125.10125.0.10139                                 VIÊM MŨI MẠN                        VIÊM MŨI MẠN VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ 2 BÊN MẠN
10126.10126.0.10140 VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.                                                              VIÊM A-MI-ĐAN.
10153.10153.0.10167                               VIÊM MŨI XOANG HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI GIỮA TRÊN NỘI SOI / VIÊM MŨI
10156.10156.0.10170          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                                                    VIÊM ỐNG TAI NGOÀI P CẤP
10175.10175.0.10189                               VIÊM MŨI XOANG                                                                    VIÊM MŨI

Prediction frequency quantiles:
count     16.000000
mean      44.500000
std       82.859721
min        1.000000
25%        1.750000
50%        7.000000
75%       48.250000
90%      103.500000
95%      175.500000
max      324.000000

========================================================================================
2. EXISTING AUDIT CSV FILES
========================================================================================

--- prediction_frequency_audit.csv | shape=(16, 4) ---
Columns: ['prediction', 'case_count', 'ground_truth_unique', 'percent_of_test']
                                  prediction  case_count  ground_truth_unique  percent_of_test
                                VIÊM MŨI MẠN         324                  100            45.51
         VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP         126                   83            17.70
VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.          81                   28            11.38
                              VIÊM MŨI XOANG          52                   34             7.30
Numeric summary:
       case_count  ground_truth_unique  percent_of_test
count     16.0000              16.0000          16.0000
mean      44.5000              20.5000           6.2494
std       82.8597              30.0178          11.6394
min        1.0000               1.0000           0.1400
25%        1.7500               1.7500           0.2450
50%        7.0000               7.0000           0.9800
75%       48.2500              28.2500           6.7750
max      324.0000             100.0000          45.5100

--- prediction_quality_audit.csv | shape=(712, 6) ---
Columns: ['case_id', 'prediction', 'ground_truth', 'exact_match', 'token_f1', 'prediction_is_subset']
            case_id                          prediction                                         ground_truth  exact_match  token_f1  prediction_is_subset
10017.10017.0.10031 VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP      VIÊM MÀNG NHĨ CẤP BÓNG NƯỚC P - NHIỀU RÁY TAI T        False  0.631579                 False
10057.10057.0.10071 VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP       VIÊM ỐNG TAI NGOÀI (T) MẠN / VIÊM MŨI ĐỢT CẤP.        False  0.666667                 False
10116.10116.0.10130 VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                    VIÊM ỐNG TAI NGOÀI MÀNG NHĨ P CẤP        False  0.875000                 False
10125.10125.0.10139                        VIÊM MŨI MẠN VIÊM MŨI MẠN VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ 2 BÊN MẠN        False  0.400000                  True
Numeric summary:
       token_f1
count  712.0000
mean     0.6097
std      0.2842
min      0.0000
25%      0.3750
50%      0.6667
75%      0.8000
max      1.0000

--- distribution_shift_audit.csv | shape=(16, 10) ---
Columns: ['normalized_label', 'prediction', 'predicted_cases', 'test_GT_exact_label_cases', 'train_exact_label_cases', 'predicted_pct', 'test_GT_pct', 'train_pct', 'prediction_vs_GT_count_ratio', 'seen_exactly_in_train']
                         normalized_label                                   prediction  predicted_cases  test_GT_exact_label_cases  train_exact_label_cases  predicted_pct  test_GT_pct  train_pct  prediction_vs_GT_count_ratio  seen_exactly_in_train
                             VIÊM MŨI MẠN                                 VIÊM MŨI MẠN              324                         83                      618          45.51        11.66      10.07                          3.90                   True
        VIÊM ỐNG TAI NGOÀI MÀNG NHĨ T CẤP          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP              126                          6                       90          17.70         0.84       1.47                         21.00                   True
VIÊM HỌNG MẠN THEO DÕI TRÀO NGƯỢC DỊCH VỊ VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.               81                         51                      270          11.38         7.16       4.40                          1.59                   True
                           VIÊM MŨI XOANG                               VIÊM MŨI XOANG               52                         36                      302           7.30         5.06       4.92                          1.44                   True
Numeric summary:
       predicted_cases  test_GT_exact_label_cases  train_exact_label_cases  predicted_pct  test_GT_pct  train_pct  prediction_vs_GT_count_ratio
count          16.0000                    16.0000                  16.0000        16.0000      16.0000    16.0000                       16.0000
mean           44.5000                    18.5625                 160.5000         6.2494       2.6062     2.6162                        3.3456
std            82.8597                    26.1329                 209.6953        11.6394       3.6713     3.4167                        5.2382
min             1.0000                     1.0000                   5.0000         0.1400       0.1400     0.0800                        0.0100
25%             1.7500                     2.7500                  23.5000         0.2450       0.3850     0.3825                        0.6275
50%             7.0000                     5.5000                  62.5000         0.9800       0.7700     1.0200                        1.5150
75%            48.2500                    19.5000                 218.2500         6.7750       2.7425     3.5525                        3.4950
max           324.0000                    83.0000                 670.0000        45.5100      11.6600    10.9200                       21.0000

--- text_overlap_audit.csv | shape=(712, 11) ---
Columns: ['case_id', 'prediction', 'ground_truth', 'precision_tokens', 'recall_tokens', 'token_f1', 'pred_norm', 'gt_norm', 'exact_match', 'pred_token_count', 'gt_token_count']
            case_id                          prediction                                         ground_truth  precision_tokens  recall_tokens  token_f1                         pred_norm                                            gt_norm  exact_match  pred_token_count  gt_token_count
10017.10017.0.10031 VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP      VIÊM MÀNG NHĨ CẤP BÓNG NƯỚC P - NHIỀU RÁY TAI T             0.750       0.545455  0.631579 VIÊM ỐNG TAI NGOÀI MÀNG NHĨ T CẤP      VIÊM MÀNG NHĨ CẤP BÓNG NƯỚC P NHIỀU RÁY TAI T        False                 8              11
10057.10057.0.10071 VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP       VIÊM ỐNG TAI NGOÀI (T) MẠN / VIÊM MŨI ĐỢT CẤP.             0.750       0.600000  0.666667 VIÊM ỐNG TAI NGOÀI MÀNG NHĨ T CẤP          VIÊM ỐNG TAI NGOÀI T MẠN VIÊM MŨI ĐỢT CẤP        False                 8              10
10116.10116.0.10130 VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                    VIÊM ỐNG TAI NGOÀI MÀNG NHĨ P CẤP             0.875       0.875000  0.875000 VIÊM ỐNG TAI NGOÀI MÀNG NHĨ T CẤP                  VIÊM ỐNG TAI NGOÀI MÀNG NHĨ P CẤP        False                 8               8
10125.10125.0.10139                        VIÊM MŨI MẠN VIÊM MŨI MẠN VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ 2 BÊN MẠN             1.000       0.250000  0.400000                      VIÊM MŨI MẠN VIÊM MŨI MẠN VIÊM ỐNG TAI NGOÀI MÀNG NHĨ 2 BÊN MẠN        False                 3              12
Numeric summary:
       precision_tokens  recall_tokens  token_f1  pred_token_count  gt_token_count
count          712.0000       712.0000  712.0000          712.0000        712.0000
mean             0.7170         0.5885    0.6097            4.8722          7.1236
std              0.2756         0.3213    0.2842            2.4390          4.3334
min              0.0000         0.0000    0.0000            2.0000          1.0000
25%              0.6667         0.3333    0.3750            3.0000          3.0000
50%              0.6667         0.5394    0.6667            3.0000          6.0000
75%              1.0000         1.0000    0.8000            8.0000          9.0000
max              1.0000         1.0000    1.0000            9.0000         24.0000

--- low_overlap_image_metadata.csv | shape=(20, 11) ---
Columns: ['case_id', 'prediction', 'ground_truth', 'precision_tokens', 'recall_tokens', 'token_f1', 'pred_norm', 'gt_norm', 'exact_match', 'pred_token_count', 'gt_token_count']
            case_id                                   prediction                                                      ground_truth  precision_tokens  recall_tokens  token_f1                                 pred_norm                                                          gt_norm  exact_match  pred_token_count  gt_token_count
17557.17557.0.17582 VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.                                                    HÓC DỊ VẬT N1.               0.0            0.0       0.0 VIÊM HỌNG MẠN THEO DÕI TRÀO NGƯỢC DỊCH VỊ                                                    HÓC DỊ VẬT N1        False                 9               4
17686.17686.0.17711 VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.                                         HÓC XƯƠNG CÁ N1 (ĐÃ LẤY).               0.0            0.0       0.0 VIÊM HỌNG MẠN THEO DÕI TRÀO NGƯỢC DỊCH VỊ                                           HÓC XƯƠNG CÁ N1 ĐÃ LẤY        False                 9               6
14927.14927.0.14946                                 VIÊM MŨI MẠN HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TAI GIỮA TRÊN NỘI SOI               0.0            0.0       0.0                              VIÊM MŨI MẠN HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI GIỮA TRÊN NỘI SOI        False                 3              14
14900.14900.0.14919                               VIÊM MŨI XOANG HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TAI GIỮA TRÊN NỘI SOI               0.0            0.0       0.0                            VIÊM MŨI XOANG HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI GIỮA TRÊN NỘI SOI        False                 3              14
Numeric summary:
       precision_tokens  recall_tokens  token_f1  pred_token_count  gt_token_count
count           20.0000        20.0000   20.0000           20.0000         20.0000
mean             0.0056         0.0038    0.0045            5.4000         11.1000
std              0.0248         0.0172    0.0203            3.0157          4.5642
min              0.0000         0.0000    0.0000            3.0000          1.0000
25%              0.0000         0.0000    0.0000            3.0000          6.7500
50%              0.0000         0.0000    0.0000            3.0000         14.0000
75%              0.0000         0.0000    0.0000            9.0000         14.0000
max              0.1111         0.0769    0.0909            9.0000         14.0000

--- anatomy_error_stratification.csv | shape=(712, 24) ---
Columns: ['case_id', 'prediction', 'ground_truth', 'precision_tokens', 'recall_tokens', 'token_f1', 'pred_norm', 'gt_norm', 'exact_match', 'pred_token_count', 'gt_token_count', 'tai', 'hoc_mui', 'hong_mui', 'hong_thanh_quan', 'hong_mieng', 'ly_do_noi_soi', 'tai__present', 'hoc_mui__present', 'hong_mui__present', 'hong_thanh_quan__present', 'hong_mieng__present', 'ly_do_noi_soi__present', 'gt_region_heuristic']
            case_id                          prediction                                         ground_truth  precision_tokens  recall_tokens  token_f1  ... hoc_mui__present hong_mui__present  hong_thanh_quan__present  hong_mieng__present  ly_do_noi_soi__present gt_region_heuristic
10017.10017.0.10031 VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP      VIÊM MÀNG NHĨ CẤP BÓNG NƯỚC P - NHIỀU RÁY TAI T             0.750       0.545455  0.631579  ...            False             False                     False                False                    True                 Tai
10057.10057.0.10071 VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP       VIÊM ỐNG TAI NGOÀI (T) MẠN / VIÊM MŨI ĐỢT CẤP.             0.750       0.600000  0.666667  ...             True              True                     False                False                    True  Tai + Mũi/xoang/VA
10116.10116.0.10130 VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                    VIÊM ỐNG TAI NGOÀI MÀNG NHĨ P CẤP             0.875       0.875000  0.875000  ...            False             False                     False                False                    True                 Tai
10125.10125.0.10139                        VIÊM MŨI MẠN VIÊM MŨI MẠN VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ 2 BÊN MẠN             1.000       0.250000  0.400000  ...             True              True                     False                False                    True  Tai + Mũi/xoang/VA
Numeric summary:
       precision_tokens  recall_tokens  token_f1  pred_token_count  gt_token_count
count          712.0000       712.0000  712.0000          712.0000        712.0000
mean             0.7170         0.5885    0.6097            4.8722          7.1236
std              0.2756         0.3213    0.2842            2.4390          4.3334
min              0.0000         0.0000    0.0000            2.0000          1.0000
25%              0.6667         0.3333    0.3750            3.0000          3.0000
50%              0.6667         0.5394    0.6667            3.0000          6.0000
75%              1.0000         1.0000    0.8000            8.0000          9.0000
max              1.0000         1.0000    1.0000            9.0000         24.0000

--- tympanic_membrane_cases.csv | shape=(158, 5) ---
Columns: ['case_id', 'prediction', 'ground_truth', 'pred_mentions_tympanum', 'gt_mentions_tympanum']
            case_id                          prediction                                         ground_truth  pred_mentions_tympanum  gt_mentions_tympanum
10017.10017.0.10031 VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP      VIÊM MÀNG NHĨ CẤP BÓNG NƯỚC P - NHIỀU RÁY TAI T                    True                  True
10057.10057.0.10071 VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP       VIÊM ỐNG TAI NGOÀI (T) MẠN / VIÊM MŨI ĐỢT CẤP.                    True                 False
10116.10116.0.10130 VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                    VIÊM ỐNG TAI NGOÀI MÀNG NHĨ P CẤP                    True                  True
10125.10125.0.10139                        VIÊM MŨI MẠN VIÊM MŨI MẠN VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ 2 BÊN MẠN                   False                  True

--- cell10_prediction_audit.csv | shape=(581, 3) ---
Columns: ['case_id', 'prediction', 'ground_truth']
            case_id                          prediction                                         ground_truth
10017.10017.0.10031 VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP      VIÊM MÀNG NHĨ CẤP BÓNG NƯỚC P - NHIỀU RÁY TAI T
10057.10057.0.10071 VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP       VIÊM ỐNG TAI NGOÀI (T) MẠN / VIÊM MŨI ĐỢT CẤP.
10116.10116.0.10130 VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                    VIÊM ỐNG TAI NGOÀI MÀNG NHĨ P CẤP
10125.10125.0.10139                        VIÊM MŨI MẠN VIÊM MŨI MẠN VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ 2 BÊN MẠN

========================================================================================
3. EXISTING TEXT AUDITS — RELEVANT LINES
========================================================================================

--- cell1_schema_ontology_audit.txt ---
L51: Path: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/test_predictions_712.csv
L56: Columns (3): ['case_id', 'prediction', 'ground_truth']

--- cell6_training_source_audit.txt ---
L68: f"{V4_DIR}/checkpoints/epoch_02.pt"
L72: f"{V4_DIR}/checkpoints/epoch_03.pt"
L76: f"{V4_DIR}/checkpoints/best.pt"
L94: #   - checkpoint save
L162: f"{V4_DIR}/checkpoints/epoch_02.pt"
L166: f"{V4_DIR}/checkpoints/epoch_03.pt"
L170: f"{V4_DIR}/checkpoints/best.pt"
L182: "E2 checkpoint": E2_CKPT,
L183: "E3 checkpoint": E3_CKPT,
L184: "Best checkpoint": BEST_CKPT,
L1066: print("\nLOADING CHECKPOINTS")
L1126: "\nCHECKPOINT RESTORE: PASS"
... 499 additional matching lines omitted.

--- cell7_v5_training_flow.txt ---
L37: 161:     "last.pt"
L42: 166:     "best.pt"
L177: 2106:     "best.pt:",
L190: 2119: print("PASS: Checkpoints saved.")

--- cell8_saved_training_history.txt ---
L85: SOURCE   96:     V5_CKPT_DIR / "best.pt"
L143: SOURCE 1168:         save_checkpoint(
L150: SOURCE 1284:         f"best.pt exists  : {BEST_CKPT.exists()}"
L159: SOURCE 1294:         "CHECKPOINT STATUS: PASS"

In [43]:

# ============================================================
# V5 INFERENCE PROVENANCE AUDIT — READ ONLY
# Mục tiêu: truy vết code/checkpoint đã tạo test_predictions_712.csv
# Không training, không load checkpoint, không sửa file dự án
# ============================================================

from google.colab import drive
drive.mount('/content/drive')

import os
import re
import json
from pathlib import Path

ROOT = Path('/content/drive/MyDrive/NoiSoi_Matching')
NB_PATH = Path('/content/drive/MyDrive/Colab Notebooks/25sep.ipynb')
V5 = ROOT / 'baseline_model_v5'
AUDIT = V5 / 'diagnostics' / 'audit_20261015'

print('=' * 100)
print('V5 INFERENCE PROVENANCE AUDIT — READ ONLY')
print('=' * 100)
print('Notebook exists:', NB_PATH.exists())
print('Project exists :', ROOT.exists())
print('V5 directory   :', V5.exists())

# ------------------------------------------------------------
# 1. Read notebook and identify cells related to inference,
#    predictions, checkpoint loading, and CSV writing.
# ------------------------------------------------------------
if not NB_PATH.exists():
    print('\nERROR: Notebook not found:', NB_PATH)
else:
    with open(NB_PATH, 'r', encoding='utf-8') as f:
        nb = json.load(f)

    cells = nb.get('cells', [])
    print(f'\nNotebook cells: {len(cells)}')

    terms = [
        'test_predictions_712.csv',
        'prediction_path',
        'prediction_df',
        'predictions_df',
        'model.generate',
        'exact_generate',
        'generate(',
        'torch.load(',
        'load_state_dict',
        'from_pretrained',
        'best.pt',
        'last.pt',
        'checkpoint',
        'ground_truth',
        'prediction',
        'to_csv(',
        'argmax',
        'AutoModel',
        'T5ForConditionalGeneration',
        'MT5ForConditionalGeneration',
    ]

    hits = []
    for i, cell in enumerate(cells):
        source = ''.join(cell.get('source', []))
        outputs = cell.get('outputs', [])
        output_texts = []

        for out in outputs:
            if 'text' in out:
                value = out['text']
                output_texts.append(
                    ''.join(value) if isinstance(value, list) else str(value)
                )
            data = out.get('data', {})
            if 'text/plain' in data:
                value = data['text/plain']
                output_texts.append(
                    ''.join(value) if isinstance(value, list) else str(value)
                )

        out_text = '\n'.join(output_texts)
        combined = source + '\n' + out_text
        found = [t for t in terms if t.lower() in combined.lower()]

        if found:
            hits.append({
                'cell_index': i,
                'cell_type': cell.get('cell_type'),
                'execution_count': cell.get('execution_count'),
                'terms': found,
                'source': source,
                'output': out_text,
            })

    print(f'Cells with relevant terms: {len(hits)}')

    # First show cells mentioning the exact prediction CSV path/name.
    exact_hits = [
        h for h in hits
        if 'test_predictions_712.csv' in
        (h['source'] + '\n' + h['output']).lower()
    ]

    print('\n' + '=' * 100)
    print('SECTION 1 — EXACT CSV NAME IN NOTEBOOK')
    print('=' * 100)
    print('Exact-name hits:', len(exact_hits))

    if not exact_hits:
        print('No notebook cell source/output explicitly mentions test_predictions_712.csv.')
    else:
        for h in exact_hits:
            print(
                f"\n--- Cell {h['cell_index']} | type={h['cell_type']} "
                f"| execution_count={h['execution_count']} "
                f"| terms={h['terms']} ---"
            )
            print('SOURCE:')
            print(h['source'][:7000] or '[empty source]')
            print('OUTPUT:')
            print(h['output'][:2500] or '[no captured text output]')

    # Then show cells with model loading / generation / CSV writing.
    # Print compact snippets, prioritizing actual source over noisy output.
    print('\n' + '=' * 100)
    print('SECTION 2 — INFERENCE / CHECKPOINT / CSV-WRITING CELLS')
    print('=' * 100)

    priority_terms = [
        'torch.load(', 'load_state_dict', 'from_pretrained',
        'model.generate', 'exact_generate', 'generate(',
        'to_csv(', 'best.pt', 'last.pt'
    ]

    priority_hits = []
    for h in hits:
        src = h['source'].lower()
        if any(t.lower() in src for t in priority_terms):
            priority_hits.append(h)

    print('Relevant source cells:', len(priority_hits))

    for h in priority_hits:
        src = h['source']
        lines = src.splitlines()
        relevant_lines = set()

        for line_no, line in enumerate(lines):
            if any(t.lower() in line.lower() for t in priority_terms):
                for j in range(max(0, line_no - 3), min(len(lines), line_no + 5)):
                    relevant_lines.add(j)

        selected = sorted(relevant_lines)
        print(
            f"\n--- Cell {h['cell_index']} | execution_count={h['execution_count']} "
            f"| matches={h['terms']} | source_lines={len(lines)} ---"
        )

        if not selected:
            print(src[:2500])
        else:
            # Limit output per cell so the notebook audit remains readable.
            selected = selected[:100]
            for j in selected:
                print(f'{j + 1:4d}: {lines[j]}')

        # Show only a short error/result excerpt from captured output.
        if h['output']:
            out = h['output']
            markers = [
                'Traceback', 'Error', 'Exception', 'PASS',
                'FAIL', 'checkpoint', 'prediction', 'saved'
            ]
            out_lines = out.splitlines()
            chosen = [
                (j, line) for j, line in enumerate(out_lines)
                if any(m.lower() in line.lower() for m in markers)
            ][:15]
            if chosen:
                print('OUTPUT EXCERPT:')
                for j, line in chosen:
                    print(f'  OUT {j + 1}: {line[:350]}')

    # --------------------------------------------------------
    # 2. Inspect existing provenance/audit reports.
    # --------------------------------------------------------
    print('\n' + '=' * 100)
    print('SECTION 3 — EXISTING AUDIT REPORTS')
    print('=' * 100)

    report_names = [
        'cell1_schema_ontology_audit.txt',
        'cell6_training_source_audit.txt',
        'cell7_v5_training_flow.txt',
        'cell8_saved_training_history.txt',
        'cell11_prediction_generation_source.txt',
        'cell12_checkpoint_and_prediction_source.txt',
        'cell13_full_notebook_prediction_trace.txt',
    ]

    report_terms = [
        'test_predictions_712.csv',
        'prediction generation',
        'prediction source',
        'inference',
        'torch.load',
        'load_state_dict',
        'best.pt',
        'last.pt',
        'exact_generate',
        'to_csv',
        'missing',
        'error',
        'traceback',
        'execution_count',
        'not found',
    ]

    for name in report_names:
        path = AUDIT / name
        if not path.exists():
            print(f'\n--- MISSING REPORT: {name} ---')
            continue

        try:
            lines = path.read_text(encoding='utf-8', errors='replace').splitlines()
        except Exception as e:
            print(f'\n--- READ ERROR: {name}: {e} ---')
            continue

        matched = []
        for i, line in enumerate(lines):
            if any(term.lower() in line.lower() for term in report_terms):
                matched.append(i)

        # Add nearby lines around matched entries.
        selected = set()
        for i in matched:
            for j in range(max(0, i - 2), min(len(lines), i + 3)):
                selected.add(j)

        print(f'\n--- {name} | lines={len(lines)} | matched_lines={len(matched)} ---')
        if not selected:
            print('[No matching provenance terms found.]')
        else:
            # Avoid huge reports overwhelming the output.
            for j in sorted(selected)[:100]:
                print(f'L{j + 1}: {lines[j][:500]}')

    # --------------------------------------------------------
    # 3. Verify prediction file metadata without changing it.
    # --------------------------------------------------------
    print('\n' + '=' * 100)
    print('SECTION 4 — PREDICTION FILE METADATA')
    print('=' * 100)

    pred_path = V5 / 'test_predictions_712.csv'
    if pred_path.exists():
        stat = pred_path.stat()
        print('Path:', pred_path)
        print('Bytes:', stat.st_size)
        print('Modified time (local runtime):', __import__('datetime').datetime.fromtimestamp(stat.st_mtime))
        print('CSV file hash (SHA256):')
        import hashlib
        sha = hashlib.sha256()
        with open(pred_path, 'rb') as f:
            for chunk in iter(lambda: f.read(1024 * 1024), b''):
                sha.update(chunk)
        print(sha.hexdigest())
    else:
        print('Prediction CSV does not exist:', pred_path)

    # List provenance-like small files near the V5 root.
    print('\nPotential provenance files:')
    for base in [V5, V5 / 'diagnostics', AUDIT, V5 / 'runtime_state']:
        if not base.exists():
            continue
        for p in sorted(base.iterdir()):
            if p.is_file() and any(
                word in p.name.lower()
                for word in ['summary', 'history', 'prediction', 'inference',
                             'source', 'runtime', 'path', 'log', 'audit']
            ):
                try:
                    print(f'{p} | {p.stat().st_size:,} bytes')
                except OSError:
                    print(p)

    print('\n' + '=' * 100)
    print('AUDIT FINISHED — READ ONLY')
    print('No checkpoint loaded; no training; no files written.')
    print('=' * 100)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
====================================================================================================
V5 INFERENCE PROVENANCE AUDIT — READ ONLY
====================================================================================================
Notebook exists: True
Project exists : True
V5 directory   : True

Notebook cells: 162
Cells with relevant terms: 100

====================================================================================================
SECTION 1 — EXACT CSV NAME IN NOTEBOOK
====================================================================================================
Exact-name hits: 0
No notebook cell source/output explicitly mentions test_predictions_712.csv.

====================================================================================================
SECTION 2 — INFERENCE / CHECKPOINT / CSV-WRITING CELLS
====================================================================================================
Relevant source cells: 47

--- Cell 0 | execution_count=None | matches=['best.pt', 'checkpoint', 'T5ForConditionalGeneration', 'MT5ForConditionalGeneration'] | source_lines=74 ---
  70: )
  71:
  72: BEST_CKPT = (
  73:     f"{V4_DIR}/checkpoints/best.pt"
  74: )

--- Cell 1 | execution_count=None | matches=['exact_generate', 'generate(', 'torch.load(', 'load_state_dict', 'from_pretrained', 'best.pt', 'checkpoint', 'prediction', 'argmax', 'T5ForConditionalGeneration', 'MT5ForConditionalGeneration'] | source_lines=1914 ---
  87: )
  88:
  89: BEST_CKPT = (
  90:     f"{V4_DIR}/checkpoints/best.pt"
  91: )
  92:
  93: # ------------------------------------------------
  94: # Path checks
 170:
 171: print("\nLOADING TOKENIZER")
 172:
 173: tokenizer = AutoTokenizer.from_pretrained(
 174:     "google/mt5-small"
 175: )
 176:
 177: print(
 196:
 197: print("\nLOADING IMAGE PROCESSOR")
 198:
 199: image_processor = AutoImageProcessor.from_pretrained(
 200:     "google/vit-base-patch16-224"
 201: )
 202:
 203: print(
 891:
 892:         super().__init__()
 893:
 894:         self.vision = ViTModel.from_pretrained(
 895:             "google/vit-base-patch16-224"
 896:         )
 897:
 898:         self.mt5 = MT5ForConditionalGeneration.from_pretrained(
 899:             "google/mt5-small"
 900:         )
 901:
 902:         self.projector = nn.Linear(
 985:
 986: print("\nLOADING CHECKPOINTS")
 987:
 988: E2 = torch.load(
 989:     E2_CKPT,
 990:     map_location="cpu",
 991:     weights_only=False,
 992: )
 993:
 994: E3 = torch.load(
 995:     E3_CKPT,
 996:     map_location="cpu",
 997:     weights_only=False,
 998: )
1014: # Strict load
1015: # ------------------------------------------------
1016:
1017: load_result = model.load_state_dict(
1018:     E2["model_state"],
1019:     strict=True,
1020: )
1021:
1028:     E2["best_val"]
1029: )
1030:
1031: model.load_state_dict(
1032:     E3["model_state"],
1033:     strict=True,
1034: )
1035:
1099: # 14. SNAPSHOT
1100: # ================================================================
1101:
1102: model.load_state_dict(
1103:     E2["model_state"],
1104:     strict=True,
1105: )
1106:
1413: # ================================================================
1414:
1415: @torch.no_grad()
1416: def exact_generate(
1417:     cond,
1418:     max_new_tokens=20,
1419: ):
1420:
1504:     print(checkpoint_name)
1505:     print("=" * 70)
1506:
1507:     model.load_state_dict(
1508:         checkpoint["model_state"],
1509:         strict=True,
1510:     )
1511:
1530:             zero_struct=False,
1531:         )
1532:
1533:         pred_full = exact_generate(
1534:             full
1535:         )
1536:
1537:         # ------------------------------------------------
1548:         )
1549:
OUTPUT EXCERPT:
  OUT 7:   V4 manifest           : PASS -> /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv
  OUT 8:   Structured targets    : PASS -> /content/drive/MyDrive/NoiSoi_Matching/v3_ontology_v2/v3_structured_targets_v2_2.csv
  OUT 9:   Image manifest        : PASS -> /content/drive/MyDrive/NoiSoi_Matching/final_manifest/final_dataset_manifest.csv
  OUT 10:   V4 config             : PASS -> /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_config.json
  OUT 11:   E2 checkpoint         : PASS -> /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_02.pt
  OUT 12:   E3 checkpoint         : PASS -> /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt
  OUT 13:   Best checkpoint       : PASS -> /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt
  OUT 43:   source_v3_checkpoint: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt
  OUT 47: Ontology dimensions: PASS
  OUT 76: Manifest shapes: PASS
  OUT 117: - MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
  OUT 122: [transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.
  OUT 131: LOADING CHECKPOINTS

--- Cell 2 | execution_count=None | matches=['load_state_dict', 'from_pretrained', 'checkpoint', 'T5ForConditionalGeneration', 'MT5ForConditionalGeneration'] | source_lines=101 ---
  15:     def __init__(self):
  16:         super().__init__()
  17:
  18:         self.vision = ViTModel.from_pretrained(
  19:             "google/vit-base-patch16-224"
  20:         )
  21:
  22:         self.mt5 = MT5ForConditionalGeneration.from_pretrained(
  23:             "google/mt5-small"
  24:         )
  25:
  26:         # IMPORTANT:
  85: # ------------------------------------------------------------
  86: # STRICT LOAD E2
  87: # ------------------------------------------------------------
  88: model.load_state_dict(E2["model_state"], strict=True)
  89:
  90: print("\n✓ E2 STRICT LOAD PASSED")
  91:
  92: # ------------------------------------------------------------
  93: # STRICT LOAD E3
  94: # ------------------------------------------------------------
  95: model.load_state_dict(E3["model_state"], strict=True)
  96:
  97: print("✓ E3 STRICT LOAD PASSED")
  98:
  99: print("\n" + "=" * 70)
OUTPUT EXCERPT:
  OUT 2: REBUILDING V4 WITH CHECKPOINT-EXACT PROJECTOR
  OUT 16: - MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
  OUT 19: [transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.
  OUT 22: Checkpoint projector keys:
  OUT 26: ✓ Checkpoint projector structure confirmed
  OUT 34: ✓ E2 STRICT LOAD PASSED
  OUT 35: ✓ E3 STRICT LOAD PASSED
  OUT 38: V4 CHECKPOINT RESTORE: PASS

--- Cell 5 | execution_count=None | matches=['load_state_dict', 'checkpoint', 'argmax'] | source_lines=445 ---
 277:     print(f"CHECKPOINT: {epoch_name}")
 278:     print("=" * 70)
 279:
 280:     model.load_state_dict(
 281:         ckpt["model_state"],
 282:         strict=True,
 283:     )
 284:
OUTPUT EXCERPT:
  OUT 3: CHECKPOINT: E2
  OUT 35: CHECKPOINT: E3

--- Cell 6 | execution_count=None | matches=['load_state_dict', 'checkpoint', 'argmax'] | source_lines=233 ---
  56:     print(f"LOGIT INTERVENTION — {epoch_name}")
  57:     print("=" * 70)
  58:
  59:     model.load_state_dict(
  60:         ckpt["model_state"],
  61:         strict=True,
  62:     )
  63:

--- Cell 7 | execution_count=None | matches=['load_state_dict', 'checkpoint', 'to_csv(', 'argmax'] | source_lines=368 ---
  37:     f"found {len(val_loader.dataset)}"
  38: )
  39:
  40: model.load_state_dict(E3["model_state"], strict=True)
  41: model.to(device)
  42: model.eval()
  43:
  44: print("=" * 70)
 347:     "e3_val756_first_token_sensitivity_summary.csv",
 348: )
 349:
 350: sensitivity_df.to_csv(
 351:     detail_path,
 352:     index=False,
 353: )
 354:
 355: summary_df.to_csv(
 356:     summary_path,
 357:     index=False,
 358: )
 359:
OUTPUT EXCERPT:
  OUT 6: Checkpoint epoch: 3
  OUT 26: /tmp/ipykernel_1990/3742130145.py:280: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after group
  OUT 126: Checkpoint unchanged.

--- Cell 8 | execution_count=None | matches=['from_pretrained', 'checkpoint', 'T5ForConditionalGeneration', 'MT5ForConditionalGeneration'] | source_lines=605 ---
 252:         super().__init__()
 253:
 254:         # Same backbone
 255:         self.vision = ViTModel.from_pretrained(
 256:             "google/vit-base-patch16-224"
 257:         )
 258:
 259:         self.mt5 = MT5ForConditionalGeneration.from_pretrained(
 260:             "google/mt5-small"
 261:         )
 262:
 263:         # EXACT V4 projector structure
OUTPUT EXCERPT:
  OUT 18: - MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
  OUT 21: [transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.
  OUT 50: V5 ARCHITECTURE AUDIT: PASS
  OUT 53: No checkpoint written.

--- Cell 9 | execution_count=None | matches=['load_state_dict', 'checkpoint'] | source_lines=190 ---
  11: # 1. Load V4 E3 into reference model
  12: # ------------------------------------------------------------
  13:
  14: model.load_state_dict(
  15:     E3["model_state"],
  16:     strict=True,
  17: )
  18:
OUTPUT EXCERPT:
  OUT 12: V5 WARM-START AUDIT: PASS
  OUT 16:     V4 E3 checkpoint
  OUT 28: Checkpoint:

--- Cell 10 | execution_count=None | matches=['load_state_dict', 'checkpoint'] | source_lines=389 ---
  15: # 0. Restore V4 E3 reference + V5 warm-start
  16: # ------------------------------------------------------------
  17:
  18: model.load_state_dict(
  19:     E3["model_state"],
  20:     strict=True,
  21: )
  22: model.eval()

--- Cell 23 | execution_count=None | matches=['torch.load(', 'load_state_dict', 'checkpoint'] | source_lines=400 ---
 185: # 9. Load
 186: # ------------------------------------------------------------
 187:
 188: loaded = torch.load(
 189:     DRYRUN_PATH,
 190:     map_location="cpu",
 191:     weights_only=False,
 192: )
 202:
 203: v5_restore = V5Model()
 204:
 205: v5_restore.load_state_dict(
 206:     loaded["model_state"],
 207:     strict=True,
 208: )
 209:
 243:     eta_min=0,
 244: )
 245:
 246: optimizer_restore.load_state_dict(
 247:     loaded["optimizer_state"]
 248: )
 249:
 250: scheduler_restore.load_state_dict(
 251:     loaded["scheduler_state"]
 252: )
 253:
 254: # ------------------------------------------------------------
OUTPUT EXCERPT:
  OUT 2: V5 CHECKPOINT / RESUME DRY-RUN
  OUT 5: V5 checkpoint dir:
  OUT 6: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints
  OUT 8: V4 checkpoint dir:
  OUT 9: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints
  OUT 11: Checkpoint keys:
  OUT 14: Dry-run checkpoint written: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/_dryrun_checkpoint.pt
  OUT 17: Loaded checkpoint keys:
  OUT 31: - MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
  OUT 34: [transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.
  OUT 50: PASS — V5 CHECKPOINT / RESUME DRY-RUN
  OUT 58: V4 checkpoint isolation: PASS
  OUT 59: Temporary checkpoint: removed

--- Cell 24 | execution_count=None | matches=['best.pt', 'last.pt', 'checkpoint'] | source_lines=332 ---
 259:     for epoch in range(1, EPOCHS + 1)
 260: }
 261:
 262: checkpoint_paths["last"] = os.path.join(CKPT_DIR, "last.pt")
 263: checkpoint_paths["best"] = os.path.join(CKPT_DIR, "best.pt")
 264:
 265: print()
 266: print("Checkpoint directory:")
 267: print(CKPT_DIR)

--- Cell 54 | execution_count=None | matches=['torch.load(', 'checkpoint'] | source_lines=62 ---
  18: print("Size (MB):", round(os.path.getsize(CKPT) / 1024**2, 2))
  19:
  20: # Load to CPU only
  21: ckpt = torch.load(
  22:     CKPT,
  23:     map_location="cpu",
  24:     weights_only=False
  25: )
OUTPUT EXCERPT:
  OUT 1: Checkpoint: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt
  OUT 17: Dataset/image-related checkpoint keys:
  OUT 20: PASS: checkpoint inspected on CPU only.

--- Cell 68 | execution_count=None | matches=['from_pretrained', 'checkpoint'] | source_lines=118 ---
  31:
  32:     from transformers import ViTImageProcessor
  33:
  34:     image_processor = ViTImageProcessor.from_pretrained(
  35:         "google/vit-base-patch16-224-in21k"
  36:     )
  37:
  38:     print("Created image_processor")
  45:
  46:     from transformers import AutoTokenizer
  47:
  48:     tokenizer = AutoTokenizer.from_pretrained(
  49:         "google/mt5-small"
  50:     )
  51:
  52:     print("Created tokenizer")
OUTPUT EXCERPT:
  OUT 40: PASS: image_processor available
  OUT 41: PASS: tokenizer available
  OUT 42: PASS: tokenizer max_length=96 smoke test
  OUT 45: V4 CHECKPOINTS: UNTOUCHED

--- Cell 75 | execution_count=None | matches=['torch.load(', 'load_state_dict', 'best.pt', 'checkpoint'] | source_lines=175 ---
  32: candidates = [
  33:     os.path.join(V4_CKPT_DIR, "epoch_03.pt"),
  34:     os.path.join(V4_CKPT_DIR, "epoch_03.pth"),
  35:     os.path.join(V4_CKPT_DIR, "best.pt"),
  36: ]
  37:
  38: existing = [p for p in candidates if os.path.exists(p)]
  39:
  86: # -------------------------------------------------------------------------
  87: # 4. Load V4 weights into compatible V5 keys
  88: # -------------------------------------------------------------------------
  89: ckpt = torch.load(
  90:     v4_ckpt_path,
  91:     map_location="cpu",
  92: )
  93:
 136: # -------------------------------------------------------------------------
 137: # 5. Load compatible weights
 138: # -------------------------------------------------------------------------
 139: load_result = v5.load_state_dict(
 140:     compatible,
 141:     strict=False,
 142: )
 143:

--- Cell 78 | execution_count=None | matches=['from_pretrained', 'checkpoint', 'T5ForConditionalGeneration', 'MT5ForConditionalGeneration'] | source_lines=245 ---
  43: required_markers = [
  44:     "class SoftStructuredConditioner",
  45:     "class V5Model",
  46:     'self.vision = ViTModel.from_pretrained',
  47:     'self.mt5 = MT5ForConditionalGeneration.from_pretrained',
  48:     "self.projector = Projector",
  49:     "self.conditioner = SoftStructuredConditioner",
  50:     "self.structured_heads",
  51: ]
OUTPUT EXCERPT:
  OUT 13: PASS: Exact V5 architecture markers found

--- Cell 81 | execution_count=None | matches=['from_pretrained', 'checkpoint', 'prediction', 'T5ForConditionalGeneration', 'MT5ForConditionalGeneration'] | source_lines=373 ---
 103:         super().__init__()
 104:
 105:         # Vision encoder
 106:         self.vision = ViTModel.from_pretrained(
 107:             "google/vit-base-patch16-224"
 108:         )
 109:
 110:         # Text decoder
 111:         self.mt5 = MT5ForConditionalGeneration.from_pretrained(
 112:             "google/mt5-small"
 113:         )
 114:
 115:         # Vision -> decoder hidden dimension
OUTPUT EXCERPT:
  OUT 28: - MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
  OUT 33: [transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.
  OUT 42: vision              : PASS
  OUT 43: mt5                 : PASS
  OUT 44: projector           : PASS
  OUT 45: conditioner         : PASS
  OUT 46: concept_head        : PASS
  OUT 47: negative_head       : PASS
  OUT 48: attribute_head      : PASS
  OUT 71: PASS: V5Model instantiated
  OUT 72: PASS: ViT encoder restored
  OUT 73: PASS: mT5 decoder restored
  OUT 74: PASS: Exact Projector restored
  OUT 75: PASS: Structured heads = 48 / 5 / 6
  OUT 76: PASS: SoftStructuredConditioner restored

--- Cell 82 | execution_count=None | matches=['torch.load(', 'load_state_dict', 'checkpoint'] | source_lines=322 ---
 102: # ------------------------------------------------------------------
 103: print("\n[LOAD CHECKPOINT]")
 104:
 105: checkpoint = torch.load(
 106:     checkpoint_path,
 107:     map_location="cpu",
 108:     weights_only=False,
 109: )
 207: # ------------------------------------------------------------------
 208: # 9. Load only compatible weights
 209: # ------------------------------------------------------------------
 210: load_result = v5.load_state_dict(
 211:     compatible,
 212:     strict=False,
 213: )
 214:
OUTPUT EXCERPT:
  OUT 9: [V4 CHECKPOINT DIRECTORY]
  OUT 10: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints
  OUT 13:  - /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt
  OUT 15: Selected checkpoint:
  OUT 16: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt
  OUT 18: [LOAD CHECKPOINT]
  OUT 19: Checkpoint type: dict
  OUT 20: Checkpoint keys:

--- Cell 84 | execution_count=None | matches=['load_state_dict', 'checkpoint'] | source_lines=276 ---
  92: # ------------------------------------------------------------------
  93: print("\n[LOAD V4 -> V5]")
  94:
  95: load_result = v5.load_state_dict(
  96:     fresh_compatible,
  97:     strict=False,
  98: )
  99:
OUTPUT EXCERPT:
  OUT 10: checkpoint_path     : FOUND
  OUT 14: PASS: Compatible set exactly matches audit
  OUT 57: [V4 CHECKPOINT SAFETY]
  OUT 58: Checkpoint exists: PASS
  OUT 59: Path: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt
  OUT 64: PASS: Exactly 394 V4 tensors copied into V5
  OUT 65: PASS: All 394 copied tensors verified exactly
  OUT 66: PASS: Max weight difference = 0.0
  OUT 67: PASS: 9 V5-only structured tensors retained
  OUT 68: PASS: 15 V4-only tensors correctly excluded
  OUT 69: PASS: V4 checkpoint untouched

--- Cell 95 | execution_count=None | matches=['load_state_dict', 'checkpoint'] | source_lines=499 ---
 423:     eta_min=ETA_MIN,
 424: )
 425:
 426: test_optimizer.load_state_dict(
 427:     copy.deepcopy(optimizer_state)
 428: )
 429:
 430: test_scheduler.load_state_dict(
 431:     copy.deepcopy(scheduler_state)
 432: )
 433:
 434: if (
OUTPUT EXCERPT:
  OUT 8: PASS: No previous optimizer_v5/scheduler_v5 reused
  OUT 18: PASS: All 5 parameter groups and learning rates correct
  OUT 26: PASS: Exact optimizer parameter coverage
  OUT 31: PASS: Parameter counts match
  OUT 37: PASS: Scheduler configuration correct
  OUT 45: PASS: Initial learning rates correct
  OUT 50: PASS: Scheduler state serialization/restoration
  OUT 56: Checkpoint: NOT SAVED
  OUT 62: PASS: V5 optimizer created

In [45]:
# ============================================================
# V5 CHECKPOINT ↔ PREDICTION FORENSIC AUDIT — READ ONLY
# Không train, không ghi file, không load toàn bộ checkpoint 4.3GB
# ============================================================

from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import os
import re
import json
import hashlib
import ast
import pandas as pd
from pathlib import Path

ROOT = Path('/content/drive/MyDrive/NoiSoi_Matching')
NB_PATH = Path('/content/drive/MyDrive/Colab Notebooks/25sep.ipynb')
V5 = ROOT / 'baseline_model_v5'
PRED = V5 / 'test_predictions_712.csv'
CKPT_DIR = V5 / 'checkpoints'

print('=' * 88)
print('V5 CHECKPOINT ↔ PREDICTION FORENSIC AUDIT — READ ONLY')
print('=' * 88)

# ------------------------------------------------------------
# 1. Existing artifact metadata; do not load checkpoint weights
# ------------------------------------------------------------
print('\n[1] FILE METADATA')

for p in [
    PRED,
    CKPT_DIR / 'best.pt',
    CKPT_DIR / 'last.pt',
    V5 / 'diagnostics' / 'v5_final_training_summary.json',
]:
    if p.exists():
        s = p.stat()
        print(f'{p.name:38s} exists=True size={s.st_size:,} bytes '
              f'mtime={pd.Timestamp(s.st_mtime, unit="s")}')
    else:
        print(f'{p.name:38s} exists=False')

# ------------------------------------------------------------
# 2. Prediction CSV fingerprint and schema
# ------------------------------------------------------------
print('\n[2] PREDICTION CSV')

if PRED.exists():
    df = pd.read_csv(PRED)
    print('shape:', df.shape)
    print('columns:', df.columns.tolist())
    print('dtypes:', df.dtypes.astype(str).to_dict())
    print('duplicate case_id:', int(df['case_id'].duplicated().sum())
          if 'case_id' in df else 'case_id missing')

    if {'prediction', 'ground_truth'}.issubset(df.columns):
        pred = df['prediction'].fillna('').astype(str).str.strip().str.lower()
        truth = df['ground_truth'].fillna('').astype(str).str.strip().str.lower()
        print('unique predictions:', pred.nunique())
        print('unique ground truths:', truth.nunique())
        print('exact normalized match rate:', round(float((pred == truth).mean()), 4))
        print('\nTop 12 predictions:')
        print(df['prediction'].value_counts(dropna=False).head(12).to_string())
else:
    df = None
    print('PREDICTION CSV NOT FOUND')

if PRED.exists():
    h = hashlib.sha256()
    with open(PRED, 'rb') as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b''):
            h.update(chunk)
    print('SHA256:', h.hexdigest())

# ------------------------------------------------------------
# 3. Training summary JSON; safe small metadata file only
# ------------------------------------------------------------
print('\n[3] V5 TRAINING SUMMARY')

summary_path = V5 / 'diagnostics' / 'v5_final_training_summary.json'
if summary_path.exists():
    try:
        summary = json.loads(summary_path.read_text(encoding='utf-8'))
        print(json.dumps(summary, ensure_ascii=False, indent=2)[:14000])
    except Exception as e:
        print('Could not parse summary:', repr(e))
else:
    print('Summary JSON not found.')

# ------------------------------------------------------------
# 4. Scan small text/code/config files for explicit inference provenance
# ------------------------------------------------------------
print('\n[4] SEARCH PROJECT TEXT/CONFIG FILES')

needles = [
    'test_predictions_712.csv',
    'prediction_path',
    'prediction_csv',
    'pd.DataFrame',
    'model.generate(',
    'generate(**',
    'argmax(',
    'best.pt',
    'last.pt',
    'load_state_dict(',
]

skip_parts = {
    'checkpoints', 'images', 'image', 'dataset', 'datasets',
    '.git', '__pycache__'
}
extensions = {'.py', '.ipynb', '.json', '.txt', '.yaml', '.yml', '.log', '.md'}
hits = 0
max_hits = 100

for base in [V5, ROOT / 'baseline_model_v4', ROOT / 'baseline_model_v3']:
    if not base.exists():
        continue
    for p in base.rglob('*'):
        if not p.is_file() or p.suffix.lower() not in extensions:
            continue
        if any(part in skip_parts for part in p.parts):
            continue
        try:
            if p.stat().st_size > 3_000_000:
                continue
            text = p.read_text(encoding='utf-8', errors='ignore')
        except Exception:
            continue

        lines = text.splitlines()
        matching = [
            (i + 1, line.strip()[:240])
            for i, line in enumerate(lines)
            if any(term.lower() in line.lower() for term in needles)
        ]
        if matching:
            print(f'\nFILE: {p}')
            for line_no, line in matching[:8]:
                print(f'  L{line_no}: {line}')
                hits += 1
                if hits >= max_hits:
                    break
        if hits >= max_hits:
            print('\nHit limit reached.')
            break
    if hits >= max_hits:
        break

print('\nText/config matches printed:', hits)

# ------------------------------------------------------------
# 5. Notebook: focus only on cells that might create predictions
# ------------------------------------------------------------
print('\n[5] NOTEBOOK INFERENCE SOURCE')

if NB_PATH.exists():
    try:
        nb = json.loads(NB_PATH.read_text(encoding='utf-8'))
        cells = nb.get('cells', [])
        print('Notebook cells:', len(cells))

        terms = [
            'test_predictions_712.csv',
            'prediction_path',
            'to_csv(',
            'model.generate(',
            'generate(**',
            'argmax(',
            'torch.load(',
            'load_state_dict(',
            'baseline_model_v5/checkpoints',
        ]

        found = 0
        for i, cell in enumerate(cells):
            source = ''.join(cell.get('source', []))
            matched = [
                (j + 1, line.strip()[:220])
                for j, line in enumerate(source.splitlines())
                if any(term.lower() in line.lower() for term in terms)
            ]
            if not matched:
                continue

            # Only print cells containing prediction-generation or CSV-write clues.
            print(f'\nCELL {i} | execution_count={cell.get("execution_count")}')
            for line_no, line in matched[:12]:
                print(f'  L{line_no}: {line}')
            found += 1
            if found >= 20:
                print('Cell display limit reached.')
                break

        print('\nRelevant source cells printed:', found)
    except Exception as e:
        print('Notebook parse error:', repr(e))
else:
    print('Notebook not found.')

# ------------------------------------------------------------
# 6. Existing diagnostics that might describe prediction collapse
# ------------------------------------------------------------
print('\n[6] EXISTING DIAGNOSTIC SCHEMAS')

for p in [
    V5 / 'diagnostics' / 'prediction_frequency_audit.csv',
    V5 / 'diagnostics' / 'prediction_quality_audit.csv',
    V5 / 'diagnostics' / 'distribution_shift_audit.csv',
]:
    if p.exists():
        try:
            x = pd.read_csv(p, nrows=5)
            print(f'\n{p.name}:')
            print('columns:', x.columns.tolist())
            print(x.to_string(index=False, max_cols=14))
        except Exception as e:
            print(p.name, 'read error:', repr(e))
    else:
        print(p.name, 'not found')

print('\n' + '=' * 88)
print('AUDIT FINISHED — NO TRAINING, NO CHECKPOINT WEIGHT LOAD, NO FILE WRITES')
print('=' * 88)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
========================================================================================
V5 CHECKPOINT ↔ PREDICTION FORENSIC AUDIT — READ ONLY
========================================================================================

[1] FILE METADATA
test_predictions_712.csv               exists=True size=62,941 bytes mtime=2026-09-30 16:34:27
best.pt                                exists=True size=4,640,037,647 bytes mtime=2026-09-29 04:20:44
last.pt                                exists=True size=4,640,037,647 bytes mtime=2026-09-29 04:25:51
v5_final_training_summary.json         exists=True size=649 bytes mtime=2026-09-29 04:23:10

[2] PREDICTION CSV
shape: (712, 3)
columns: ['case_id', 'prediction', 'ground_truth']
dtypes: {'case_id': 'object', 'prediction': 'object', 'ground_truth': 'object'}
duplicate case_id: 0
unique predictions: 16
unique ground truths: 267
exact normalized match rate: 0.184

Top 12 predictions:
prediction
VIÊM MŨI MẠN                                    324
VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP             126
VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.     81
VIÊM MŨI XOANG                                   52
VIÊM MŨI + VA                                    47
VIÊM TAI GIỮA P MẠN                              46
VIÊM TAI GIỮA T CẤP VIÊM MŨI                     10
VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T                   8
VIÊM MŨI XOANG MẠN - POLYP MŨI                    6
VIÊM ỐNG TAI NGOÀI 2 BÊN MẠN                      4
VIÊM ỐNG TAI NGOÀI P CẤP                          2
VIÊM TAI GIỮA T MẠN                               2
SHA256: 244ae2e75060222c4603ca1641482f31304f88e8ad8ccffa638998acca4fe52c

[3] V5 TRAINING SUMMARY
{
  "model": "V5",
  "status": "TRAINING_COMPLETE",
  "num_epochs": 5,
  "global_step": 1920,
  "epoch": 5,
  "next_batch": 0,
  "best_val": 0.424518172663671,
  "train_loss": [
    0.5731708970967303,
    0.5046075203082849,
    0.47171955251829634,
    0.45422747778290645,
    0.44715843725379206
  ],
  "val_loss": [
    0.46700948011622856,
    0.44155955633946825,
    0.42823387978095856,
    0.4258775923539091,
    0.424518172663671
  ],
  "last_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/last.pt",
  "best_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/best.pt"
}

[4] SEARCH PROJECT TEXT/CONFIG FILES

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/v5_final_training_summary.json
  L23: "last_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/last.pt",
  L24: "best_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/best.pt"

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/runtime_state/paths.json
  L4: "v4_best": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell1_schema_ontology_audit.txt
  L51: Path: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/test_predictions_712.csv

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell6_training_source_audit.txt
  L76: f"{V4_DIR}/checkpoints/best.pt"
  L170: f"{V4_DIR}/checkpoints/best.pt"
  L1097: load_result = model.load_state_dict(
  L1111: model.load_state_dict(
  L1182: model.load_state_dict(
  L1539: next_token = torch.argmax(
  L1587: model.load_state_dict(
  L1762: summary = pd.DataFrame(

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell7_v5_training_flow.txt
  L37: 161:     "last.pt"
  L42: 166:     "best.pt"
  L177: 2106:     "best.pt:",

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell8_saved_training_history.txt
  L85: SOURCE   96:     V5_CKPT_DIR / "best.pt"
  L150: SOURCE 1284:         f"best.pt exists  : {BEST_CKPT.exists()}"
  L161: SOURCE 1332:     "best.pt:",
  L172: SOURCE 1343: print("PASS: last.pt maintained.")
  L173: SOURCE 1344: print("PASS: best.pt maintained.")
  L184: SOURCE  107:     V5_CKPT_DIR / "best.pt"
  L260: SOURCE 1404:     "best.pt:",
  L299: SOURCE  166:     "best.pt"

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell11_prediction_generation_source.txt
  L40: 1459:         next_token = torch.argmax(
  L139: 214:         next_token = torch.argmax(
  L167: 128:             full_argmax = int(torch.argmax(full))
  L168: 129:             other_argmax = int(torch.argmax(other))
  L192: 96:     full_top = full.argmax(dim=-1)
  L193: 97:     other_top = other.argmax(dim=-1)

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell12_checkpoint_and_prediction_source.txt
  L4: 73: f"{V4_DIR}/checkpoints/best.pt"
  L13: 90: f"{V4_DIR}/checkpoints/best.pt"
  L17: 1017: load_result = model.load_state_dict(
  L18: 1031: model.load_state_dict(
  L19: 1102: model.load_state_dict(
  L20: 1507: model.load_state_dict(
  L21: 1902: model.load_state_dict(
  L95: 88: model.load_state_dict(E2["model_state"], strict=True)

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell13_full_notebook_prediction_trace.txt
  L4: 73: f"{V4_DIR}/checkpoints/best.pt"
  L8: 90: f"{V4_DIR}/checkpoints/best.pt"
  L15: output line 13: Best checkpoint       : PASS -> /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt
  L16: output line 43: source_v3_checkpoint: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt
  L25: 262: checkpoint_paths["last"] = os.path.join(CKPT_DIR, "last.pt")
  L26: 263: checkpoint_paths["best"] = os.path.join(CKPT_DIR, "best.pt")
  L30: output line 11: checkpoint_best: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt
  L31: output line 14: checkpoint_last: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_config.json
  L23: "source_v3_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt",

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_runtime_state.json
  L6: "checkpoint_best": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",
  L9: "checkpoint_last": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt",

Text/config matches printed: 48

[5] NOTEBOOK INFERENCE SOURCE
Notebook cells: 162

CELL 1 | execution_count=None
  L988: E2 = torch.load(
  L994: E3 = torch.load(
  L1017: load_result = model.load_state_dict(
  L1031: model.load_state_dict(
  L1102: model.load_state_dict(
  L1459: next_token = torch.argmax(
  L1507: model.load_state_dict(
  L1902: model.load_state_dict(

CELL 2 | execution_count=None
  L88: model.load_state_dict(E2["model_state"], strict=True)
  L95: model.load_state_dict(E3["model_state"], strict=True)

CELL 5 | execution_count=None
  L214: next_token = torch.argmax(
  L280: model.load_state_dict(

CELL 6 | execution_count=None
  L59: model.load_state_dict(
  L128: full_argmax = int(torch.argmax(full))
  L129: other_argmax = int(torch.argmax(other))

CELL 7 | execution_count=None
  L40: model.load_state_dict(E3["model_state"], strict=True)
  L96: full_top = full.argmax(dim=-1)
  L97: other_top = other.argmax(dim=-1)
  L350: sensitivity_df.to_csv(
  L355: summary_df.to_csv(

CELL 9 | execution_count=None
  L14: model.load_state_dict(

CELL 10 | execution_count=None
  L18: model.load_state_dict(

CELL 23 | execution_count=None
  L188: loaded = torch.load(
  L205: v5_restore.load_state_dict(
  L246: optimizer_restore.load_state_dict(
  L250: scheduler_restore.load_state_dict(

CELL 54 | execution_count=None
  L21: ckpt = torch.load(

CELL 75 | execution_count=None
  L89: ckpt = torch.load(
  L139: load_result = v5.load_state_dict(

CELL 82 | execution_count=None
  L105: checkpoint = torch.load(
  L210: load_result = v5.load_state_dict(

CELL 84 | execution_count=None
  L95: load_result = v5.load_state_dict(

CELL 95 | execution_count=None
  L426: test_optimizer.load_state_dict(
  L430: test_scheduler.load_state_dict(

CELL 96 | execution_count=None
  L278: checkpoint = torch.load(
  L307: model.load_state_dict(
  L311: optimizer.load_state_dict(
  L315: scheduler.load_state_dict(

CELL 97 | execution_count=None
  L165: checkpoint = torch.load(

CELL 104 | execution_count=None
  L66: v4_ckpt = torch.load(
  L493: v4_ckpt_after = torch.load(

CELL 105 | execution_count=None
  L7: v4_ckpt_after = torch.load(

CELL 106 | execution_count=None
  L217: v4_ckpt = torch.load(
  L433: v4_check_after = torch.load(

CELL 107 | execution_count=None
  L474: optimizer_v5_restored.load_state_dict(
  L486: scheduler_v5_restored.load_state_dict(

CELL 108 | execution_count=None
  L183: loaded = torch.load(
  L231: v5_restored.load_state_dict(
  L322: optimizer_restored.load_state_dict(
  L355: scheduler_restored.load_state_dict(
Cell display limit reached.

Relevant source cells printed: 20

[6] EXISTING DIAGNOSTIC SCHEMAS
prediction_frequency_audit.csv not found
prediction_quality_audit.csv not found
distribution_shift_audit.csv not found

========================================================================================
AUDIT FINISHED — NO TRAINING, NO CHECKPOINT WEIGHT LOAD, NO FILE WRITES
========================================================================================

In [46]:
# ============================================================
# V5 SOURCE TRACE — READ ONLY
# Mục tiêu: tìm luồng inference có thể liên quan đến predictions
# ============================================================

from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import json
from pathlib import Path

NB_PATH = Path('/content/drive/MyDrive/Colab Notebooks/25sep.ipynb')
AUDIT_DIR = Path(
    '/content/drive/MyDrive/NoiSoi_Matching/'
    'baseline_model_v5/diagnostics/audit_20261015'
)

print('=' * 90)
print('V5 SOURCE TRACE — READ ONLY')
print('=' * 90)

if not NB_PATH.exists():
    print('ERROR: Notebook not found:', NB_PATH)
else:
    nb = json.loads(NB_PATH.read_text(encoding='utf-8'))
    cells = nb.get('cells', [])
    print('Notebook cells:', len(cells))

    # Những dấu hiệu có thể giúp nhận diện luồng inference.
    inference_terms = [
        'test_predictions_712.csv',
        'prediction_path',
        'predictions_df',
        'predictions =',
        'model.generate(',
        'model.generate (',
        'generate(',
        'argmax(',
        'decode(',
        'batch_decode(',
        'prediction',
        'ground_truth',
        'to_csv(',
        'to_csv (',
    ]

    checkpoint_terms = [
        'torch.load(',
        'load_state_dict(',
        'best.pt',
        'last.pt',
        'V5_CKPT_DIR',
        'CKPT_DIR',
        'AutoModel',
        'from_pretrained(',
        'class ',
        'def collate_v5',
    ]

    # 1. Tìm mọi cell có dấu hiệu ghi dự đoán hoặc xử lý nhãn.
    print('\n' + '=' * 90)
    print('[1] CELLS WITH PREDICTION / CSV-WRITING CLUES')
    print('=' * 90)

    candidate_cells = []
    for idx, cell in enumerate(cells):
        src = ''.join(cell.get('source', []))
        low = src.lower()
        matched = [t for t in inference_terms if t.lower() in low]

        # Ưu tiên các cell vừa xử lý prediction vừa nạp checkpoint/model.
        if matched:
            candidate_cells.append((idx, cell, matched, src))

    print('Candidate cells:', len(candidate_cells))

    for idx, cell, matched, src in candidate_cells:
        lines = src.splitlines()
        low_lines = [line.lower() for line in lines]

        # Cell có đúng tên file là bằng chứng mạnh nhất.
        exact_name = 'test_predictions_712.csv' in src
        checkpoint_hits = [
            i for i, line in enumerate(low_lines)
            if any(t.lower() in line for t in checkpoint_terms)
        ]
        prediction_hits = [
            i for i, line in enumerate(low_lines)
            if any(t.lower() in line for t in inference_terms)
        ]

        print(
            f'\nCELL {idx} | execution_count={cell.get("execution_count")} '
            f'| exact_csv_name={exact_name}'
        )
        print('Matched terms:', matched)

        # In tất cả dòng khớp chính xác tên file; nếu không có,
        # in các dòng quan trọng về model/checkpoint/prediction.
        if exact_name:
            selected = set()
            for i, line in enumerate(lines):
                if 'test_predictions_712.csv' in line:
                    selected.update(range(max(0, i-8), min(len(lines), i+9)))
        else:
            selected = set()
            important = sorted(set(checkpoint_hits + prediction_hits))
            # Giữ output gọn, tối đa 30 dòng ngữ cảnh mỗi cell.
            for i in important:
                selected.update(range(max(0, i-2), min(len(lines), i+3)))
                if len(selected) >= 30:
                    break

        for i in sorted(selected)[:36]:
            print(f'  L{i+1}: {lines[i][:240]}')

        # Đọc output đã lưu của cell, chỉ in những dòng có liên quan.
        outputs = cell.get('outputs', [])
        output_matches = []
        for out in outputs:
            data = out.get('data', {})
            text_parts = []
            if 'text' in out:
                text_parts.extend(out['text'] if isinstance(out['text'], list)
                                  else [out['text']])
            if 'text/plain' in data:
                text_parts.extend(
                    data['text/plain'] if isinstance(data['text/plain'], list)
                    else [data['text/plain']]
                )
            for part in text_parts:
                for line in str(part).splitlines():
                    if any(k in line.lower() for k in [
                        'prediction', 'checkpoint', 'best.pt', 'last.pt',
                        'test_predictions', 'accuracy', 'exact match',
                        'saved', 'error:', 'exception',
                    ]):
                        output_matches.append(line.strip()[:240])

        if output_matches:
            print('  SAVED OUTPUT CLUES:')
            for line in output_matches[:8]:
                print('   ', line)

    # 2. Đọc báo cáo provenance nếu có.
    print('\n' + '=' * 90)
    print('[2] EXISTING PROVENANCE REPORTS')
    print('=' * 90)

    report_names = [
        'cell11_prediction_generation_source.txt',
        'cell12_checkpoint_and_prediction_source.txt',
        'cell13_full_notebook_prediction_trace.txt',
        'cell6_training_source_audit.txt',
        'cell7_v5_training_flow.txt',
    ]

    terms = [
        'test_predictions_712.csv',
        'prediction_path',
        'to_csv',
        'model.generate',
        'generate(',
        'best.pt',
        'last.pt',
        'load_state_dict',
        'prediction source',
        'inference',
    ]

    for name in report_names:
        p = AUDIT_DIR / name
        print(f'\n--- {name} ---')
        if not p.exists():
            print('Not found at:', p)
            continue

        lines = p.read_text(encoding='utf-8', errors='ignore').split

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
==========================================================================================
V5 SOURCE TRACE — READ ONLY
==========================================================================================
Notebook cells: 162

==========================================================================================
[1] CELLS WITH PREDICTION / CSV-WRITING CLUES
==========================================================================================
Candidate cells: 7

CELL 1 | execution_count=None | exact_csv_name=False
Matched terms: ['generate(', 'argmax(', 'decode(', 'prediction']
  L88:
  L89: BEST_CKPT = (
  L90:     f"{V4_DIR}/checkpoints/best.pt"
  L91: )
  L92:
  L171: print("\nLOADING TOKENIZER")
  L172:
  L173: tokenizer = AutoTokenizer.from_pretrained(
  L174:     "google/mt5-small"
  L175: )
  L197: print("\nLOADING IMAGE PROCESSOR")
  L198:
  L199: image_processor = AutoImageProcessor.from_pretrained(
  L200:     "google/vit-base-patch16-224"
  L201: )
  L495: # ================================================================
  L496:
  L497: class V4ValidationDataset(Dataset):
  L498:
  L499:     def __init__(
  L686: # ================================================================
  L687:
  L688: class StructuredConditioner(nn.Module):
  L689:
  L690:     def __init__(
  L866:
  L867:
  L868: class Projector(nn.Module):
  L869:
  L870:     def __init__(
  SAVED OUTPUT CLUES:
    E2 checkpoint         : PASS -> /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_02.pt
    E3 checkpoint         : PASS -> /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt
    Best checkpoint       : PASS -> /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt
    source_v3_checkpoint: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt
    - MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
    [transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `t
    LOADING CHECKPOINTS

CELL 4 | execution_count=None | exact_csv_name=False
Matched terms: ['decode(']
  L3: # ============================================================
  L4:
  L5: def safe_decode(token_ids):
  L6:     """
  L7:     Decode generated mT5 token IDs while removing
  L14:         token_ids = [token_ids]
  L15:
  L16:     return tokenizer.decode(
  L17:         token_ids,
  L18:         skip_special_tokens=True,
  L25:
  L26: # sanity check
  L27: test_text = safe_decode([tokenizer.eos_token_id])
  L28: print("Test decode:", repr(test_text))
  L29:

CELL 5 | execution_count=None | exact_csv_name=False
Matched terms: ['argmax(', 'decode(']
  L212:         )
  L213:
  L214:         next_token = torch.argmax(
  L215:             out.logits[:, -1, :],
  L216:             dim=-1,
  L230:         )
  L231:
  L232:     return safe_decode(generated)
  L233:
  L234:
  L278:     print("=" * 70)
  L279:
  L280:     model.load_state_dict(
  L281:         ckpt["model_state"],
  L282:         strict=True,
  SAVED OUTPUT CLUES:
    CHECKPOINT: E2
    CHECKPOINT: E3

CELL 6 | execution_count=None | exact_csv_name=False
Matched terms: ['argmax(', 'decode(']
  L35:
  L36:     for p, token_id in zip(vals.tolist(), ids.tolist()):
  L37:         token = tokenizer.decode(
  L38:             [token_id],
  L39:             skip_special_tokens=False,
  L57:     print("=" * 70)
  L58:
  L59:     model.load_state_dict(
  L60:         ckpt["model_state"],
  L61:         strict=True,
  L126:
  L127:             # Does argmax change?
  L128:             full_argmax = int(torch.argmax(full))
  L129:             other_argmax = int(torch.argmax(other))
  L130:
  L131:             argmax_changed = (
  L141:                 "cosine_similarity": cosine,
  L142:                 "argmax_changed": argmax_changed,
  L143:                 "full_top_token": tokenizer.decode(
  L144:                     [full_argmax],
  L145:                     skip_special_tokens=False,
  L146:                 ),
  L147:                 "other_top_token": tokenizer.decode(
  L148:                     [other_argmax],
  L149:                     skip_special_tokens=False,

CELL 7 | execution_count=None | exact_csv_name=False
Matched terms: ['argmax(', 'to_csv(']
  L38: )
  L39:
  L40: model.load_state_dict(E3["model_state"], strict=True)
  L41: model.to(device)
  L42: model.eval()
  L94:     other_probs = torch.softmax(other, dim=-1)
  L95:
  L96:     full_top = full.argmax(dim=-1)
  L97:     other_top = other.argmax(dim=-1)
  L98:
  L99:     # Probability assigned to FULL's preferred token
  L348: )
  L349:
  L350: sensitivity_df.to_csv(
  L351:     detail_path,
  L352:     index=False,
  L353: )
  L354:
  L355: summary_df.to_csv(
  L356:     summary_path,
  L357:     index=False,
  SAVED OUTPUT CLUES:
    Checkpoint epoch: 3
    Checkpoint unchanged.

CELL 16 | execution_count=None | exact_csv_name=False
Matched terms: ['prediction']
  L54:
  L55:     # --------------------------------------------------------
  L56:     # 4. Structured prediction heads
  L57:     # --------------------------------------------------------
  L58:     concept_logits = self.structured_heads["concept"](pooled)

CELL 81 | execution_count=None | exact_csv_name=False
Matched terms: ['prediction']
  L37: #    Source: 25sep.ipynb — original V5 architecture
  L38: # ------------------------------------------------------------------
  L39: class SoftStructuredConditioner(nn.Module):
  L40:     def __init__(
  L41:         self,
  L98: # 3. Restore exact V5Model
  L99: # ------------------------------------------------------------------
  L100: class V5Model(nn.Module):
  L101:
  L102:     def __init__(self):
  L104:
  L105:         # Vision encoder
  L106:         self.vision = ViTModel.from_pretrained(
  L107:             "google/vit-base-patch16-224"
  L108:         )
  L109:
  L110:         # Text decoder
  L111:         self.mt5 = MT5ForConditionalGeneration.from_pretrained(
  L112:             "google/mt5-small"
  L113:         )
  L119:         )
  L120:
  L121:         # Structured prediction heads
  L122:         self.concept_head = nn.Linear(512, 48)
  L123:         self.negative_head = nn.Linear(512, 5)
  L177:
  L178:         # ----------------------------------------------------------
  L179:         # Structured prediction
  L180:         # ----------------------------------------------------------
  L181:         concept_logits = self.concept_head(
  SAVED OUTPUT CLUES:
    - MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
    [transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `t
    V4 checkpoint: UNTOUCHED

==========================================================================================
[2] EXISTING PROVENANCE REPORTS
==========================================================================================

--- cell11_prediction_generation_source.txt ---

--- cell12_checkpoint_and_prediction_source.txt ---

--- cell13_full_notebook_prediction_trace.txt ---

--- cell6_training_source_audit.txt ---

--- cell7_v5_training_flow.txt ---

In [47]:
# ============================================================
# V5 INFERENCE TRACE — DEEP READ-ONLY SCAN
# Không train, không nạp checkpoint, không ghi/chỉnh sửa file
# ============================================================

from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import json
from pathlib import Path

NB_PATH = Path('/content/drive/MyDrive/Colab Notebooks/25sep.ipynb')
PROJECT = Path('/content/drive/MyDrive/NoiSoi_Matching')
V5 = PROJECT / 'baseline_model_v5'

nb = json.loads(NB_PATH.read_text(encoding='utf-8'))
cells = nb.get('cells', [])

print('=' * 90)
print('DEEP V5 INFERENCE TRACE')
print('=' * 90)

# A. Quét toàn bộ cell 70 trở đi, không chỉ dựa vào một từ khóa.
terms = [
    'torch.load', 'load_state_dict', 'model.eval', '.eval()',
    'model.generate', 'generate(', 'greedy_search',
    'argmax(', 'batch_decode', 'tokenizer.decode',
    'safe_decode', 'prediction', 'predictions',
    'ground_truth', 'to_csv', 'test_loader', 'test_dataset',
    'best.pt', 'last.pt', 'checkpoint', 'save_path',
    'prediction_path', 'csv_path', 'DataFrame(',
    'V5Model(', 'from_pretrained'
]

print('\n[A] SOURCE HITS — CELLS 70+')
for idx in range(70, len(cells)):
    cell = cells[idx]
    src = ''.join(cell.get('source', []))
    lines = src.splitlines()

    hits = [
        (i, line) for i, line in enumerate(lines)
        if any(term.lower() in line.lower() for term in terms)
    ]
    if not hits:
        continue

    print(f'\n--- CELL {idx} | execution_count={cell.get("execution_count")} '
          f'| lines={len(lines)} | hits={len(hits)} ---')

    # In các dòng khớp và một ít ngữ cảnh trước/sau.
    selected = set()
    for i, _ in hits:
        selected.update(range(max(0, i - 2), min(len(lines), i + 3)))

    for i in sorted(selected):
        print(f'L{i+1}: {lines[i][:260]}')

# B. Tìm chính xác mọi chuỗi liên quan đến CSV trong toàn bộ notebook.
print('\n' + '=' * 90)
print('[B] EXACT CSV / OUTPUT PATH REFERENCES')
print('=' * 90)

needles = [
    'test_predictions_712.csv',
    'test_predictions',
    'prediction_path',
    'predictions_path',
    'to_csv(',
    'to_csv (',
]
found = 0
for idx, cell in enumerate(cells):
    src = ''.join(cell.get('source', []))
    for i, line in enumerate(src.splitlines()):
        if any(n.lower() in line.lower() for n in needles):
            print(f'CELL {idx}, L{i+1}: {line[:300]}')
            found += 1

print('Total matching source lines:', found)

# C. Liệt kê tên các file nhỏ liên quan đến prediction/inference trong V5.
print('\n' + '=' * 90)
print('[C] V5 FILE INVENTORY — RELEVANT FILENAMES')
print('=' * 90)

if V5.exists():
    for p in sorted(V5.rglob('*')):
        if not p.is_file():
            continue
        rel = str(p.relative_to(V5))
        low = rel.lower()

        if any(k in low for k in [
            'predict', 'infer', 'generation', 'summary',
            'config', 'runtime', 'audit', 'history', 'log'
        ]):
            # Chỉ đọc metadata; bỏ qua nội dung checkpoint và file dữ liệu lớn.
            try:
                stat = p.stat()
                print(f'{rel} | {stat.st_size:,} bytes')
            except OSError:
                pass
else:
    print('V5 directory not found:', V5)

print('\nTRACE COMPLETE — READ ONLY')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
==========================================================================================
DEEP V5 INFERENCE TRACE
==========================================================================================

[A] SOURCE HITS — CELLS 70+

--- CELL 70 | execution_count=None | lines=173 | hits=1 ---
L170: print("BLOCKED: collate_v4 must be restored from persisted V4 code.")
L171: print("V5 TRAINING: NOT STARTED")
L172: print("V4 CHECKPOINTS: UNTOUCHED")
L173: print("=" * 80)

--- CELL 71 | execution_count=None | lines=145 | hits=1 ---
L142:
L143: print("V5 TRAINING: NOT STARTED")
L144: print("V4 CHECKPOINTS: UNTOUCHED")
L145: print("=" * 80)

--- CELL 72 | execution_count=None | lines=145 | hits=1 ---
L142:
L143: print("V5 TRAINING: NOT STARTED")
L144: print("V4 CHECKPOINTS: UNTOUCHED")
L145: print("=" * 80)

--- CELL 73 | execution_count=None | lines=523 | hits=1 ---
L520: print("")
L521: print("V5 TRAINING: NOT STARTED")
L522: print("V4 CHECKPOINTS: UNTOUCHED")
L523: print("=" * 80)

--- CELL 74 | execution_count=None | lines=700 | hits=3 ---
L519: print("\n[V5 FORWARD SMOKE]")
L520:
L521: v5.eval()
L522:
L523: with torch.no_grad():
L696: print("OPTIMIZER: NOT CREATED")
L697: print("SCHEDULER: NOT CREATED")
L698: print("CHECKPOINTS: NOT TOUCHED")
L699: print("V4 CHECKPOINTS: UNTOUCHED")
L700: print("=" * 80)

--- CELL 75 | execution_count=None | lines=175 | hits=16 ---
L26:
L27: # -------------------------------------------------------------------------
L28: # 2. Find V4 checkpoint
L29: # -------------------------------------------------------------------------
L30: V4_CKPT_DIR = "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints"
L31:
L32: candidates = [
L33:     os.path.join(V4_CKPT_DIR, "epoch_03.pt"),
L34:     os.path.join(V4_CKPT_DIR, "epoch_03.pth"),
L35:     os.path.join(V4_CKPT_DIR, "best.pt"),
L36: ]
L37:
L38: existing = [p for p in candidates if os.path.exists(p)]
L39:
L40: print("\n[V4 CHECKPOINT CANDIDATES]")
L41: for p in candidates:
L42:     print(f"{'FOUND' if os.path.exists(p) else 'MISSING'} : {p}")
L44: if not existing:
L45:     raise FileNotFoundError(
L46:         "Could not find a V4 checkpoint for V5 warm-start. "
L47:         "Do NOT train."
L48:     )
L54: )
L55:
L56: print("\n[SELECTED V4 CHECKPOINT]")
L57: print(v4_ckpt_path)
L58:
L72:
L73: try:
L74:     v5 = V5Model().to(device)
L75: except TypeError as e:
L76:     raise RuntimeError(
L77:         "V5Model exists, but its constructor signature does not match "
L78:         "V5Model(). Please inspect the constructor before proceeding. "
L79:         f"Original error: {e}"
L80:     )
L87: # 4. Load V4 weights into compatible V5 keys
L88: # -------------------------------------------------------------------------
L89: ckpt = torch.load(
L90:     v4_ckpt_path,
L91:     map_location="cpu",
L92: )
L93:
L94: print("\n[V4 CHECKPOINT TYPE]")
L95: print(type(ckpt))
L96:
L100:     v4_state = ckpt["state_dict"]
L101: elif isinstance(ckpt, dict):
L102:     # fallback: checkpoint itself may be a state_dict
L103:     v4_state = ckpt
L104: else:
L105:     raise RuntimeError("Unsupported V4 checkpoint format.")
L106:
L107: # -------------------------------------------------------------------------
L129:
L130: print("\n[WARM-START AUDIT]")
L131: print("V4 checkpoint tensors :", len(v4_state))
L132: print("Compatible V4 -> V5   :", len(compatible))
L133: print("Shape mismatches      :", len(shape_mismatch))
L137: # 5. Load compatible weights
L138: # -------------------------------------------------------------------------
L139: load_result = v5.load_state_dict(
L140:     compatible,
L141:     strict=False,
L168: print("\nSTATUS")
L169: print("PASS: V5 model object restored")
L170: print("PASS: V4 checkpoint loaded into compatible V5 keys")
L171: print("PASS: No optimizer created")
L172: print("PASS: No scheduler created")
L173: print("PASS: No training performed")
L174: print("PASS: V4 checkpoint was not modified")
L175: print("\nNEXT: Re-run CELL 25.")

--- CELL 76 | execution_count=None | lines=129 | hits=1 ---
L45: patterns = [
L46:     "class V5Model",
L47:     "V5Model(",
L48:     "SoftStructuredConditioner",
L49:     "structured_heads",

--- CELL 77 | execution_count=None | lines=99 | hits=1 ---
L33:     "SoftStructuredConditioner",
L34:     "class V5",
L35:     "V5Model(",
L36: ]
L37:

--- CELL 78 | execution_count=None | lines=245 | hits=5 ---
L44:     "class SoftStructuredConditioner",
L45:     "class V5Model",
L46:     'self.vision = ViTModel.from_pretrained',
L47:     'self.mt5 = MT5ForConditionalGeneration.from_pretrained',
L48:     "self.projector = Projector",
L49:     "self.conditioner = SoftStructuredConditioner",
L181: print(device)
L182:
L183: v5 = V5Model().to(device)
L184:
L185: # No training.
L186: v5.eval()
L187:
L188: # -------------------------------------------------------------------------
L238: print("PASS: V5 architecture instantiated")
L239: print("PASS: V5 parameter shapes match original audit")
L240: print("PASS: No V4 checkpoint loaded")
L241: print("PASS: No optimizer created")
L242: print("PASS: No scheduler created")

--- CELL 80 | execution_count=None | lines=119 | hits=1 ---
L110: print("")
L111: print("V5 model: NOT instantiated yet")
L112: print("V4 checkpoint: UNTOUCHED")
L113: print("Optimizer: NOT CREATED")
L114: print("Scheduler: NOT CREATED")

--- CELL 81 | execution_count=None | lines=373 | hits=7 ---
L98: # 3. Restore exact V5Model
L99: # ------------------------------------------------------------------
L100: class V5Model(nn.Module):
L101:
L102:     def __init__(self):
L104:
L105:         # Vision encoder
L106:         self.vision = ViTModel.from_pretrained(
L107:             "google/vit-base-patch16-224"
L108:         )
L109:
L110:         # Text decoder
L111:         self.mt5 = MT5ForConditionalGeneration.from_pretrained(
L112:             "google/mt5-small"
L113:         )
L119:         )
L120:
L121:         # Structured prediction heads
L122:         self.concept_head = nn.Linear(512, 48)
L123:         self.negative_head = nn.Linear(512, 5)
L177:
L178:         # ----------------------------------------------------------
L179:         # Structured prediction
L180:         # ----------------------------------------------------------
L181:         concept_logits = self.concept_head(
L245:     )
L246:
L247: v5 = V5Model().to(device)
L248:
L249: print(f"Device: {device}")
L364: print("PASS: V5 architecture audit completed")
L365:
L366: print("\nV4 checkpoint: UNTOUCHED")
L367: print("Optimizer: NOT CREATED")
L368: print("Scheduler: NOT CREATED")

--- CELL 82 | execution_count=None | lines=322 | hits=44 ---
L35:
L36: # ------------------------------------------------------------------
L37: # 2. Locate V4 checkpoint
L38: # ------------------------------------------------------------------
L39: V4_CHECKPOINT_DIR = (
L40:     "/content/drive/MyDrive/NoiSoi_Matching/"
L41:     "baseline_model_v4/checkpoints"
L42: )
L43:
L44: print("\n[V4 CHECKPOINT DIRECTORY]")
L45: print(V4_CHECKPOINT_DIR)
L46:
L47: if not os.path.isdir(V4_CHECKPOINT_DIR):
L48:     raise RuntimeError(
L49:         f"V4 checkpoint directory not found: "
L50:         f"{V4_CHECKPOINT_DIR}"
L51:     )
L52:
L53: # Find Epoch 3 checkpoint candidates
L54: candidates = sorted([
L55:     os.path.join(V4_CHECKPOINT_DIR, f)
L56:     for f in os.listdir(V4_CHECKPOINT_DIR)
L57:     if "epoch_03" in f.lower()
L58:     or "epoch3" in f.lower()
L65: if not candidates:
L66:     raise RuntimeError(
L67:         "Could not find V4 Epoch 3 checkpoint. "
L68:         "Do NOT guess another checkpoint."
L69:     )
L70:
L77: ]
L78:
L79: checkpoint_path = None
L80:
L81: for name in preferred_names:
L82:     p = os.path.join(V4_CHECKPOINT_DIR, name)
L83:     if os.path.isfile(p):
L84:         checkpoint_path = p
L85:         break
L86:
L87: if checkpoint_path is None:
L88:     if len(candidates) == 1:
L89:         checkpoint_path = candidates[0]
L90:     else:
L91:         raise RuntimeError(
L92:             "Multiple V4 Epoch 3 checkpoint candidates found "
L93:             "but no exact filename could be selected safely:\n"
L94:             + "\n".join(candidates)
L95:         )
L96:
L97: print("\nSelected checkpoint:")
L98: print(checkpoint_path)
L99:
L100: # ------------------------------------------------------------------
L101: # 3. Load checkpoint
L102: # ------------------------------------------------------------------
L103: print("\n[LOAD CHECKPOINT]")
L104:
L105: checkpoint = torch.load(
L106:     checkpoint_path,
L107:     map_location="cpu",
L108:     weights_only=False,
L109: )
L110:
L111: print("Checkpoint type:", type(checkpoint).__name__)
L112:
L113: if isinstance(checkpoint, dict):
L114:     print("Checkpoint keys:")
L115:     for k in checkpoint.keys():
L116:         print(" -", k)
L117: else:
L118:     raise RuntimeError(
L119:         "Unexpected V4 checkpoint format: "
L120:         f"{type(checkpoint)}"
L121:     )
L122:
L124: # 4. Extract model state
L125: # ------------------------------------------------------------------
L126: if "model_state" in checkpoint:
L127:     v4_state = checkpoint["model_state"]
L128: elif "state_dict" in checkpoint:
L129:     v4_state = checkpoint["state_dict"]
L130: else:
L131:     raise RuntimeError(
L132:         "V4 checkpoint does not contain "
L133:         "'model_state' or 'state_dict'."
L134:     )
L208: # 9. Load only compatible weights
L209: # ------------------------------------------------------------------
L210: load_result = v5.load_state_dict(
L211:     compatible,
L212:     strict=False,
L283:
L284: # ------------------------------------------------------------------
L285: # 12. Confirm V4 checkpoint was not modified
L286: # ------------------------------------------------------------------
L287: file_size = os.path.getsize(checkpoint_path)
L288:
L289: print("\n[V4 CHECKPOINT SAFETY]")
L290: print("Checkpoint exists:", os.path.isfile(checkpoint_path))
L291: print("Checkpoint size:", file_size, "bytes")
L292:
L293: # ------------------------------------------------------------------
L298: print("=" * 80)
L299:
L300: print("PASS: V4 Epoch 3 checkpoint loaded")
L301: print(
L302:     f"PASS: Compatible V4 -> V5 keys = "
L312: )
L313: print("PASS: V5 warm-start completed")
L314: print("PASS: V4 checkpoint remains untouched")
L315:
L316: print("\nOptimizer: NOT CREATED")

--- CELL 83 | execution_count=None | lines=248 | hits=1 ---
L13: # 1. Runtime checks
L14: # ------------------------------------------------------------------
L15: required = ["v5", "checkpoint_path", "v4_state", "v5_state", "compatible"]
L16:
L17: missing = [

--- CELL 84 | execution_count=None | lines=276 | hits=9 ---
L17:     "v5_state",
L18:     "exact_compatible",
L19:     "checkpoint_path",
L20: ]
L21:
L93: print("\n[LOAD V4 -> V5]")
L94:
L95: load_result = v5.load_state_dict(
L96:     fresh_compatible,
L97:     strict=False,
L242:
L243: # ------------------------------------------------------------------
L244: # 8. Confirm V4 checkpoint itself was not modified
L245: # ------------------------------------------------------------------
L246: print("\n[V4 CHECKPOINT SAFETY]")
L247:
L248: if not os.path.isfile(checkpoint_path):
L249:     raise RuntimeError(
L250:         "V4 checkpoint disappeared unexpectedly."
L251:     )
L252:
L253: print("Checkpoint exists: PASS")
L254: print("Path:", checkpoint_path)
L255:
L256: # ------------------------------------------------------------------
L266: print("PASS: 9 V5-only structured tensors retained")
L267: print("PASS: 15 V4-only tensors correctly excluded")
L268: print("PASS: V4 checkpoint untouched")
L269:
L270: print("\nOptimizer: NOT CREATED")

--- CELL 85 | execution_count=None | lines=687 | hits=3 ---
L455: print("\n[V5 FORWARD]")
L456:
L457: v5.eval()
L458:
L459: with torch.no_grad():
L645:
L646: # Ensure we leave the model in eval mode after audit.
L647: v5.eval()
L648:
L649: print(
L655: print("Optimizer: NOT CREATED")
L656: print("Scheduler: NOT CREATED")
L657: print("Checkpoint: NOT SAVED")
L658: print("Training step: NOT RUN")
L659:

--- CELL 92 | execution_count=None | lines=672 | hits=2 ---
L426: print("\n[V5 FORWARD]")
L427:
L428: v5.eval()
L429:
L430: with torch.no_grad():
L665: print("Backward: NOT RUN")
L666: print("Optimizer step: NOT RUN")
L667: print("Checkpoint: NOT SAVED")
L668: print("V4: UNTOUCHED")
L669:

--- CELL 93 | execution_count=None | lines=233 | hits=2 ---
L93: print("\n[FORWARD]")
L94:
L95: v5.eval()
L96:
L97: with torch.no_grad():
L226: print("PASS: No backward")
L227: print("PASS: No optimizer step")
L228: print("PASS: No checkpoint")
L229: print("PASS: No training")
L230:

--- CELL 94 | execution_count=None | lines=505 | hits=2 ---
L474:
L475: print(
L476:     "Checkpoint: NOT SAVED"
L477: )
L478:
L499:
L500: print("\nV5 TRAINING: NOT STARTED")
L501: print("V4 CHECKPOINTS: UNTOUCHED")
L502:
L503: print("=" * 80)

--- CELL 95 | execution_count=None | lines=499 | hits=4 ---
L424: )
L425:
L426: test_optimizer.load_state_dict(
L427:     copy.deepcopy(optimizer_state)
L428: )
L429:
L430: test_scheduler.load_state_dict(
L431:     copy.deepcopy(scheduler_state)
L432: )
L463:
L464: print(
L465:     "Checkpoint: NOT SAVED"
L466: )
L467:
L493: print("V5 OPTIMIZER STEP: NOT RUN")
L494: print("V5 SCHEDULER STEP: NOT RUN")
L495: print("V4 CHECKPOINTS: UNTOUCHED")
L496:
L497: print("=" * 80)

--- CELL 96 | execution_count=None | lines=805 | hits=69 ---
L1: # ================================================================================
L2: # CELL 27 — V5 CHECKPOINT / RESUME AUDIT
L3: # ================================================================================
L4:
L10:
L11: print("=" * 80)
L12: print("CELL 27 — V5 CHECKPOINT / RESUME AUDIT")
L13: print("=" * 80)
L14:
L42:
L43: # ------------------------------------------------------------------------------
L44: # 1. CHECKPOINT DIRECTORIES
L45: # ------------------------------------------------------------------------------
L46:
L50: )
L51:
L52: V5_CHECKPOINT_DIR = os.path.join(
L53:     V5_ROOT,
L54:     "checkpoints",
L55: )
L56:
L61:
L62: os.makedirs(
L63:     V5_CHECKPOINT_DIR,
L64:     exist_ok=True,
L65: )
L78:
L79: print(
L80:     "Checkpoint dir:",
L81:     V5_CHECKPOINT_DIR
L82: )
L83:
L96: )
L97:
L98: V4_CHECKPOINT_DIR = os.path.join(
L99:     V4_ROOT,
L100:     "checkpoints",
L101: )
L102:
L103: if not os.path.isdir(V4_CHECKPOINT_DIR):
L104:     raise RuntimeError(
L105:         f"V4 checkpoint directory missing: "
L106:         f"{V4_CHECKPOINT_DIR}"
L107:     )
L108:
L109: v4_files_before = sorted(
L110:     os.listdir(V4_CHECKPOINT_DIR)
L111: )
L112:
L114:
L115: print(
L116:     "V4 checkpoint files:",
L117:     len(v4_files_before)
L118: )
L215:
L216: # ------------------------------------------------------------------------------
L217: # 5. CHECKPOINT FUNCTIONS
L218: # ------------------------------------------------------------------------------
L219:
L220: def save_v5_checkpoint(
L221:     path,
L222:     epoch,
L228: ):
L229:
L230:     checkpoint = {
L231:         "epoch": int(epoch),
L232:
L263:
L264:     torch.save(
L265:         checkpoint,
L266:         path,
L267:     )
L268:
L269:
L270: def load_v5_checkpoint(
L271:     path,
L272:     model,
L276: ):
L277:
L278:     checkpoint = torch.load(
L279:         path,
L280:         map_location=map_location,
L295:         key
L296:         for key in required_keys
L297:         if key not in checkpoint
L298:     ]
L299:
L301:
L302:         raise RuntimeError(
L303:             "Checkpoint missing keys: "
L304:             f"{missing_keys}"
L305:         )
L306:
L307:     model.load_state_dict(
L308:         checkpoint["model_state"]
L309:     )
L310:
L311:     optimizer.load_state_dict(
L312:         checkpoint["optimizer_state"]
L313:     )
L314:
L315:     scheduler.load_state_dict(
L316:         checkpoint["scheduler_state"]
L317:     )
L318:
L319:     restore_rng_state(
L320:         checkpoint["rng_state"]
L321:     )
L322:
L323:     return checkpoint
L324:
L325:
L326: print(
L327:     "PASS: Checkpoint save/load functions defined"
L328: )
L329:
L382:
L383: # ------------------------------------------------------------------------------
L384: # 8. TEMP CHECKPOINT
L385: # ------------------------------------------------------------------------------
L386:
L387: temp_checkpoint = os.path.join(
L388:     V5_CHECKPOINT_DIR,
L389:     "_audit_temp_checkpoint.pt",
L390: )
L391:
L392: if os.path.exists(
L393:     temp_checkpoint
L394: ):
L395:
L396:     os.remove(
L397:         temp_checkpoint
L398:     )
L399:
L400: print("\n[TEMP CHECKPOINT]")
L401:
L402: save_v5_checkpoint(
L403:     path=temp_checkpoint,
L404:     epoch=test_epoch,
L405:     model=v5,
L411:
L412: if not os.path.exists(
L413:     temp_checkpoint
L414: ):
L415:
L416:     raise RuntimeError(
L417:         "Temporary checkpoint was not created."
L418:     )
L419:
L420: checkpoint_size_mb = (
L421:     os.path.getsize(
L422:         temp_checkpoint
L423:     )
L424:     / (
L429: print(
L430:     "Created:",
L431:     temp_checkpoint
L432: )
L433:
L434: print(
L435:     "Size:",
L436:     f"{checkpoint_size_mb:.2f} MB"
L437: )
L438:
L439: if checkpoint_size_mb <= 0:
L440:
L441:     raise RuntimeError(
L442:         "Checkpoint file is empty."
L443:     )
L444:
L457:
L458: # Instantiate a fresh copy using exact current architecture.
L459: fresh_v5 = V5Model().to(
L460:     device_v5
L461: )
L512:
L513: # ------------------------------------------------------------------------------
L514: # 10. LOAD CHECKPOINT
L515: # ------------------------------------------------------------------------------
L516:
L517: restored = load_v5_checkpoint(
L518:     path=temp_checkpoint,
L519:     model=fresh_v5,
L520:     optimizer=fresh_optimizer_v5,
L524:
L525: print(
L526:     "Checkpoint epoch:",
L527:     restored["epoch"]
L528: )
L529:
L530: print(
L531:     "Checkpoint best_val:",
L532:     restored["best_val"]
L533: )
L534:
L535: print(
L536:     "Checkpoint history:",
L537:     restored["history"]
L538: )
L712: v4_files_after = sorted(
L713:     os.listdir(
L714:         V4_CHECKPOINT_DIR
L715:     )
L716: )
L733:
L734:     raise RuntimeError(
L735:         "V4 checkpoint directory changed."
L736:     )
L737:
L738: print(
L739:     "PASS: V4 checkpoint directory unchanged"
L740: )
L741:
L742: # ------------------------------------------------------------------------------
L743: # 17. DELETE TEMP CHECKPOINT
L744: # ------------------------------------------------------------------------------
L745:
L746: if os.path.exists(
L747:     temp_checkpoint
L748: ):
L749:
L750:     os.remove(
L751:         temp_checkpoint
L752:     )
L753:
L754: if os.path.exists(
L755:     temp_checkpoint
L756: ):
L757:
L758:     raise RuntimeError(
L759:         "Temporary checkpoint could not be deleted."
L760:     )
L761:
L762: print(
L763:     "\nPASS: Temporary checkpoint deleted"
L764: )
L765:
L784: print("=" * 80)
L785:
L786: print("PASS: V5 checkpoint creation")
L787: print("PASS: Required checkpoint keys")
L788: print("PASS: Model state exact restore")
L789: print("PASS: Optimizer state exact restore")
L794: print("PASS: RNG state structure")
L795: print("PASS: V4 isolation")
L796: print("PASS: Temporary checkpoint cleanup")
L797:
L798: print("\nV5 TRAINING: NOT STARTED")
L799: print("OPTIMIZER STEP: NOT RUN")
L800: print("SCHEDULER STEP: NOT RUN")
L801: print("V4 CHECKPOINTS: UNTOUCHED")
L802:
L803: print("=" * 80)

--- CELL 97 | execution_count=None | lines=541 | hits=18 ---
L70: print("\n[V5 MODEL]")
L71:
L72: v5 = V5Model().to(
L73:     device_v5
L74: )
L139:
L140: # ------------------------------------------------------------------------------
L141: # 5. V4 CHECKPOINT
L142: # ------------------------------------------------------------------------------
L143:

In [48]:
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import json
from pathlib import Path

nb_path = Path('/content/drive/MyDrive/Colab Notebooks/25sep.ipynb')
nb = json.loads(nb_path.read_text(encoding='utf-8'))
cells = nb['cells']

print('=' * 85)
print('V5 TRAINING TARGET / LOSS AUDIT — READ ONLY')
print('=' * 85)

keywords = [
    'labels', 'target_text', 'target_ids', 'decoder_input_ids',
    'label_ids', 'loss', 'cross_entropy', 'criterion',
    'tokenizer(', 'encode(', 'ground_truth', 'ket_luan',
    'concepts_v2_str', 'teacher_forcing', 'logits',
    'val_loss', 'validation', 'attention_mask', 'IGNORE_INDEX',
    'pad_token_id', 'eos_token_id', 'max_length',
]

for idx in [139, 140]:
    if idx >= len(cells):
        continue

    cell = cells[idx]
    lines = ''.join(cell.get('source', [])).splitlines()

    print(f'\n{"=" * 85}')
    print(f'CELL {idx} | {len(lines)} lines')
    print('=' * 85)

    hits = [
        i for i, line in enumerate(lines)
        if any(k.lower() in line.lower() for k in keywords)
    ]

    # Gộp các đoạn gần nhau để tránh in trùng lặp quá nhiều.
    ranges = []
    for i in hits:
        start, end = max(0, i - 3), min(len(lines), i + 5)
        if ranges and start <= ranges[-1][1] + 2:
            ranges[-1] = (ranges[-1][0], max(ranges[-1][1], end))
        else:
            ranges.append((start, end))

    printed = 0
    for start, end in ranges:
        print(f'\n--- Lines {start + 1}-{end} ---')
        for j in range(start, end):
            print(f'{j + 1:4d}: {lines[j][:220]}')
            printed += 1
            if printed >= 220:
                print('... output limit reached for this cell ...')
                break
        if printed >= 220:
            break

print('\nAUDIT COMPLETE — NO TRAINING OR FILE WRITES')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
=====================================================================================
V5 TRAINING TARGET / LOSS AUDIT — READ ONLY
=====================================================================================

=====================================================================================
CELL 139 | 2121 lines
=====================================================================================

--- Lines 392-399 ---
 392:                     str(found)
 393:                 )
 394:
 395:     # V4 validation/test: first 8
 396:     # Training: random selection >8
 397:     case_to_images[
 398:         case_id
 399:     ] = resolved_paths

--- Lines 503-522 ---
 503: # 10. TARGET TEXT
 504: # ============================================================
 505:
 506: assert "ket_luan" in v4_df.columns
 507:
 508: report_map = dict(
 509:     zip(
 510:         v4_df["case_id"].astype(str),
 511:         v4_df["ket_luan"].fillna("").astype(str)
 512:     )
 513: )
 514:
 515: assert len(report_map) == 7606
 516:
 517: print(
 518:     "PASS: Report target = ket_luan."
 519: )
 520:
 521:
 522: # ============================================================

--- Lines 659-666 ---
 659:                 dtype=torch.float32
 660:             ),
 661:
 662:         "structured_loss_mask":
 663:             1.0,
 664:     }
 665:
 666:

--- Lines 687-694 ---
 687:         report_map,
 688:         processor,
 689:         tokenizer,
 690:         max_length=96,
 691:     ):
 692:
 693:         self.case_ids = [
 694:             str(x)

--- Lines 699-706 ---
 699:         self.report_map = report_map
 700:         self.processor = processor
 701:         self.tokenizer = tokenizer
 702:         self.max_length = max_length
 703:
 704:
 705:     def __len__(self):
 706:         return len(

--- Lines 754-782 ---
 754:             )["pixel_values"]
 755:         )
 756:
 757:         labels = (
 758:             self.tokenizer(
 759:                 self.report_map[
 760:                     case_id
 761:                 ],
 762:                 max_length=self.max_length,
 763:                 padding="max_length",
 764:                 truncation=True,
 765:                 return_tensors="pt",
 766:             )["input_ids"]
 767:             .squeeze(0)
 768:         )
 769:
 770:         labels[
 771:             labels
 772:             == self.tokenizer.pad_token_id
 773:         ] = -100
 774:
 775:         return {
 776:             "case_id": case_id,
 777:             "pixel_values": pixel_values,
 778:             "labels": labels,
 779:         }
 780:
 781:
 782: # ============================================================

--- Lines 807-815 ---
 807:         dtype=torch.float32,
 808:     )
 809:
 810:     labels = torch.stack([
 811:         x["labels"]
 812:         for x in batch
 813:     ])
 814:
 815:     case_ids = []

--- Lines 840-847 ---
 840:         "case_id": case_ids,
 841:         "pixel_values": pixels,
 842:         "image_mask": mask,
 843:         "labels": labels,
 844:     }
 845:
 846:
 847: # ============================================================

--- Lines 877-884 ---
 877:
 878:
 879: # ============================================================
 880: # 16. VALIDATION LOADER
 881: # ============================================================
 882:
 883: val_loader_v5 = DataLoader(
 884:     val_dataset_v5,

--- Lines 1002-1012 ---
1002: )
1003:
1004: print(
1005:     "labels:",
1006:     tuple(
1007:         audit_batch[
1008:             "labels"
1009:         ].shape
1010:     )
1011: )
1012:

--- Lines 1026-1033 ---
1026:
1027: assert (
1028:     audit_batch[
1029:         "labels"
1030:     ].shape
1031:     == (4, 96)
1032: )
1033:

--- Lines 1290-1298 ---
1290: # ============================================================
1291:
1292: history = {
1293:     "train_loss": [],
1294:     "val_loss": [],
1295:     "lr": [],
1296: }
1297:
1298: best_val = float("inf")

--- Lines 1451-1514 ---
1451:
1452:
1453: # ============================================================
1454: # 26. LOSS
1455: # ============================================================
1456:
1457: def compute_total_loss(
1458:     outputs,
1459:     concept_targets,
1460:     negative_targets,
1461:     attribute_targets,
1462: ):
1463:
1464:     report_loss = outputs[
1465:         "report_loss"
1466:     ]
1467:
1468:     concept_loss = (
1469:         F.binary_cross_entropy_with_logits(
1470:             outputs[
1471:                 "concept_logits"
1472:             ],
1473:             concept_targets,
1474:         )
1475:     )
1476:
1477:     negative_loss = (
1478:         F.binary_cross_entropy_with_logits(
1479:             outputs[
1480:                 "negative_logits"
1481:             ],
1482:             negative_targets,
1483:         )
1484:     )
1485:
1486:     attribute_loss = (
1487:         F.binary_cross_entropy_with_logits(
1488:             outputs[
1489:                 "attribute_logits"
1490:             ],
1491:             attribute_targets,
1492:         )
1493:     )
1494:
1495:     total = (
1496:         REPORT_W * report_loss
1497:         +
1498:         CONCEPT_W * concept_loss
1499:         +
1500:         NEGATIVE_W * negative_loss
1501:         +
1502:         ATTRIBUTE_W * attribute_loss
1503:     )
1504:
1505:     return (
1506:         total,
1507:         report_loss,
1508:         concept_loss,
1509:         negative_loss,
1510:         attribute_loss,
1511:     )
1512:
1513:
1514: # ============================================================

--- Lines 1560-1567 ---
1560:         else 0
1561:     )
1562:
1563:     running_loss = 0.0
1564:     batch_count = 0
1565:
1566:     optimizer_v5.zero_grad(
1567:         set_to_none=True

--- Lines 1598-1606 ---
1598:             non_blocking=True
1599:         )
1600:
1601:         labels = batch[
1602:             "labels"
1603:         ].to(
1604:             device,
1605:             non_blocking=True
1606:         )

--- Lines 1650-1678 ---
1650:             outputs = v5(
1651:                 pixel_values=pixel_values,
1652:                 image_mask=image_mask,
1653:                 labels=labels,
1654:             )
... output limit reached for this cell ...

=====================================================================================
CELL 140 | 1154 lines
=====================================================================================

--- Lines 158-170 ---
 158: # ============================================================
 159:
 160: history = {
 161:     "train_loss": [],
 162:     "val_loss": [],
 163:     "report_loss": [],
 164:     "concept_loss": [],
 165:     "negative_loss": [],
 166:     "attribute_loss": [],
 167:     "lr": [],
 168: }
 169:
 170: best_val = float("inf")

--- Lines 400-431 ---
 400:
 401:
 402: # ============================================================
 403: # 12. LOSS FUNCTION
 404: # ============================================================
 405:
 406: def compute_structured_losses(
 407:     outputs,
 408:     concept_targets,
 409:     negative_targets,
 410:     attribute_targets,
 411:     structured_masks,
 412: ):
 413:
 414:     concept_loss = F.binary_cross_entropy_with_logits(
 415:         outputs["concept_logits"],
 416:         concept_targets,
 417:         reduction="none",
 418:     ).mean(dim=1)
 419:
 420:     negative_loss = F.binary_cross_entropy_with_logits(
 421:         outputs["negative_logits"],
 422:         negative_targets,
 423:         reduction="none",
 424:     ).mean(dim=1)
 425:
 426:     attribute_loss = F.binary_cross_entropy_with_logits(
 427:         outputs["attribute_logits"],
 428:         attribute_targets,
 429:         reduction="none",
 430:     ).mean(dim=1)
 431:

--- Lines 435-466 ---
 435:         min=1.0
 436:     )
 437:
 438:     concept_loss = (
 439:         concept_loss * mask
 440:     ).sum() / denom
 441:
 442:     negative_loss = (
 443:         negative_loss * mask
 444:     ).sum() / denom
 445:
 446:     attribute_loss = (
 447:         attribute_loss * mask
 448:     ).sum() / denom
 449:
 450:     total_loss = (
 451:         REPORT_W * outputs["report_loss"]
 452:         + CONCEPT_W * concept_loss
 453:         + NEGATIVE_W * negative_loss
 454:         + ATTRIBUTE_W * attribute_loss
 455:     )
 456:
 457:     return (
 458:         total_loss,
 459:         outputs["report_loss"],
 460:         concept_loss,
 461:         negative_loss,
 462:         attribute_loss,
 463:     )
 464:
 465:
 466: # ============================================================

--- Lines 520-528 ---
 520:             non_blocking=True
 521:         )
 522:
 523:         labels = batch[
 524:             "labels"
 525:         ].to(
 526:             device,
 527:             non_blocking=True
 528:         )

--- Lines 559-566 ---
 559:
 560:         structured_masks_gpu = torch.tensor([
 561:             structured_targets_v5[c][
 562:                 "structured_loss_mask"
 563:             ]
 564:             for c in batch_case_ids
 565:         ], dtype=torch.float32).to(
 566:             device,

--- Lines 580-615 ---
 580:             outputs = v5(
 581:                 pixel_values=pixel_values,
 582:                 image_mask=image_mask,
 583:                 labels=labels,
 584:                 concept_targets=concept_targets_gpu,
 585:                 negative_targets=negative_targets_gpu,
 586:                 attribute_targets=attribute_targets_gpu,
 587:             )
 588:
 589:             (
 590:                 total_loss,
 591:                 report_loss,
 592:                 concept_loss,
 593:                 negative_loss,
 594:                 attribute_loss,
 595:             ) = compute_structured_losses(
 596:                 outputs,
 597:                 concept_targets_gpu,
 598:                 negative_targets_gpu,
 599:                 attribute_targets_gpu,
 600:                 structured_masks_gpu,
 601:             )
 602:
 603:             loss_for_backward = (
 604:                 total_loss / GRAD_ACCUM
 605:             )
 606:
 607:         # ----------------------------------------------------
 608:         # Backward
 609:         # ----------------------------------------------------
 610:
 611:         loss_for_backward.backward()
 612:
 613:         # ----------------------------------------------------
 614:         # Optimizer step
 615:         # ----------------------------------------------------

--- Lines 660-689 ---
 660:         # ----------------------------------------------------
 661:
 662:         running_total += float(
 663:             total_loss.detach()
 664:         )
 665:
 666:         running_report += float(
 667:             report_loss.detach()
 668:         )
 669:
 670:         running_concept += float(
 671:             concept_loss.detach()
 672:         )
 673:
 674:         running_negative += float(
 675:             negative_loss.detach()
 676:         )
 677:
 678:         running_attribute += float(
 679:             attribute_loss.detach()
 680:         )
 681:
 682:         train_batches_seen += 1
 683:
 684:         progress.set_postfix(
 685:             loss=f"{running_total/train_batches_seen:.4f}",
 686:             step=global_step,
 687:             lr=f"{optimizer_v5.param_groups[0]['lr']:.2e}",
 688:         )
 689:

--- Lines 694-701 ---
 694:         del outputs
 695:         del pixel_values
 696:         del image_mask
 697:         del labels
 698:
 699:         del concept_targets_gpu
 700:         del negative_targets_gpu
 701:         del attribute_targets_gpu

--- Lines 732-739 ---
 732:
 733:
 734:     # ========================================================
 735:     # VALIDATION
 736:     # ========================================================
 737:
 738:     v5.eval()
 739:

--- Lines 750-757 ---
 750:         for batch in tqdm(
 751:             val_loader_v5,
 752:             total=len(val_loader_v5),
 753:             desc=f"Validation {epoch}/{EPOCHS}",
 754:         ):
 755:
 756:             batch_case_ids = batch["case_id"]
 757:

--- Lines 769-777 ---
 769:                 non_blocking=True
 770:             )
 771:
 772:             labels = batch[
 773:                 "labels"
 774:             ].to(
 775:                 device,
 776:                 non_blocking=True
 777:             )

--- Lines 808-815 ---
 808:
 809:             structured_masks_gpu = torch.tensor([
 810:                 structured_targets_v5[c][
 811:                     "structured_loss_mask"
 812:                 ]
 813:                 for c in batch_case_ids
 814:             ], dtype=torch.float32).to(
 815:                 device,

--- Lines 825-876 ---
 825:                 outputs = v5(
 826:                     pixel_values=pixel_values,
 827:                     image_mask=image_mask,
 828:                     labels=labels,
 829:                     concept_targets=concept_targets_gpu,
 830:                     negative_targets=negative_targets_gpu,
 831:                     attribute_targets=attribute_targets_gpu,
 832:                 )
 833:
 834:                 (
 835:                     total_loss,
 836:                     report_loss,
 837:                     concept_loss,
 838:                     negative_loss,
 839:                     attribute_loss,
 840:                 ) = compute_structured_losses(
 841:                     outputs,
 842:                     concept_targets_gpu,
 843:                     negative_targets_gpu,
... output limit reached for this cell ...

AUDIT COMPLETE — NO TRAINING OR FILE WRITES

In [49]:

from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import json
from pathlib import Path

# ============================================================
# READ-ONLY AUDIT: V5 FORWARD / VALIDATION / CHECKPOINT
# ============================================================
nb_path = Path('/content/drive/MyDrive/Colab Notebooks/25sep.ipynb')
assert nb_path.exists(), f'Không tìm thấy notebook: {nb_path}'

nb = json.loads(nb_path.read_text(encoding='utf-8'))
cells = nb['cells']

print('=' * 100)
print('V5 MODEL / VALIDATION / CHECKPOINT AUDIT — READ ONLY')
print('=' * 100)

# Các vùng code cần trích xuất
targets = {
    81: [
        'class V5Model',
        'def forward',
        'report_loss',
        'labels=',
        'logits',
        'generate(',
    ],
    139: [
        'class V5Model',
        'def forward',
        'report_loss',
        'val_loss',
        'best_val',
        'save',
        'torch.save',
        'load_state_dict',
        'Validation',
        'checkpoint',
    ],
    140: [
        'class V5Model',
        'def forward',
        'report_loss',
        'val_loss',
        'best_val',
        'save_v5_checkpoint',
        'load_v5_checkpoint',
        'torch.save',
        'load_state_dict',
        'Validation',
        'checkpoint',
    ],
}

MAX_LINES_PER_CELL = 280
CONTEXT_BEFORE = 5
CONTEXT_AFTER = 10

for cell_idx, keywords in targets.items():
    if cell_idx >= len(cells):
        print(f'\n[SKIP] Cell {cell_idx} không tồn tại.')
        continue

    cell = cells[cell_idx]
    source = ''.join(cell.get('source', [])).splitlines()

    print('\n' + '=' * 100)
    print(
        f'CELL {cell_idx} | '
        f'type={cell.get("cell_type")} | '
        f'lines={len(source)} | '
        f'execution_count={cell.get("execution_count")}'
    )
    print('=' * 100)

    # Tìm dòng chứa keyword, bỏ qua phân biệt chữ hoa/thường
    hits = [
        i for i, line in enumerate(source)
        if any(key.lower() in line.lower() for key in keywords)
    ]

    # Gom các vùng code gần nhau để hạn chế trùng lặp
    ranges = []
    for i in hits:
        start = max(0, i - CONTEXT_BEFORE)
        end = min(len(source), i + CONTEXT_AFTER + 1)

        if ranges and start <= ranges[-1][1] + 2:
            ranges[-1] = (
                ranges[-1][0],
                max(ranges[-1][1], end)
            )
        else:
            ranges.append((start, end))

    printed = 0
    for start, end in ranges:
        if printed >= MAX_LINES_PER_CELL:
            print('\n... Đã đạt giới hạn output của cell ...')
            break

        print(f'\n--- Source lines {start + 1}-{end} ---')
        for line_idx in range(start, end):
            print(f'{line_idx + 1:5d}: {source[line_idx]}')
            printed += 1
            if printed >= MAX_LINES_PER_CELL:
                print('... Đã đạt giới hạn output của cell ...')
                break

    if not hits:
        print('Không tìm thấy keyword phù hợp trong source cell này.')

    # Chỉ in metadata của output đã lưu, không thực thi lại cell
    outputs = cell.get('outputs', [])
    print('\n--- SAVED EXECUTION OUTPUT METADATA ---')
    print('Số output đã lưu:', len(outputs))
    for out_idx, out in enumerate(outputs):
        data = out.get('data', {})
        text_parts = data.get('text', [])
        if text_parts:
            text_value = ''.join(text_parts)
            print(f'Output {out_idx}:')
            print(text_value[:1200])
        elif out.get('ename'):
            print(
                f'Output {out_idx}: '
                f'{out.get("ename")}: {out.get("evalue", "")}'
            )

print('\n' + '=' * 100)
print('AUDIT COMPLETE — KHÔNG TRAINING / KHÔNG LOAD CHECKPOINT / KHÔNG GHI FILE')
print('=' * 100)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
====================================================================================================
V5 MODEL / VALIDATION / CHECKPOINT AUDIT — READ ONLY
====================================================================================================

====================================================================================================
CELL 81 | type=code | lines=373 | execution_count=None
====================================================================================================

--- Source lines 56-80 ---
   56:
   57:         self.attribute_embeddings = nn.Parameter(
   58:             torch.randn(n_attributes, hidden_dim)
   59:         )
   60:
   61:     def forward(
   62:         self,
   63:         concept_logits,
   64:         negative_logits,
   65:         attribute_logits,
   66:     ):
   67:         # Differentiable soft conditioning
   68:         concept_prob = torch.sigmoid(concept_logits)
   69:         negative_prob = torch.sigmoid(negative_logits)
   70:         attribute_prob = torch.sigmoid(attribute_logits)
   71:
   72:         concept_tokens = torch.matmul(
   73:             concept_prob,
   74:             self.concept_embeddings
   75:         ).unsqueeze(1)
   76:
   77:         negative_tokens = torch.matmul(
   78:             negative_prob,
   79:             self.negative_embeddings
   80:         ).unsqueeze(1)

--- Source lines 95-110 ---
   95:
   96:
   97: # ------------------------------------------------------------------
   98: # 3. Restore exact V5Model
   99: # ------------------------------------------------------------------
  100: class V5Model(nn.Module):
  101:
  102:     def __init__(self):
  103:         super().__init__()
  104:
  105:         # Vision encoder
  106:         self.vision = ViTModel.from_pretrained(
  107:             "google/vit-base-patch16-224"
  108:         )
  109:
  110:         # Text decoder

--- Source lines 129-148 ---
  129:             n_concepts=48,
  130:             n_negative=5,
  131:             n_attributes=6,
  132:         )
  133:
  134:     def forward(
  135:         self,
  136:         pixel_values,
  137:         image_mask,
  138:         labels=None,
  139:         concept_targets=None,
  140:         negative_targets=None,
  141:         attribute_targets=None,
  142:     ):
  143:         B, N, C, H, W = pixel_values.shape
  144:
  145:         # ----------------------------------------------------------
  146:         # Flatten images for ViT
  147:         # ----------------------------------------------------------
  148:         x = pixel_values.view(

--- Source lines 176-209 ---
  176:         visual_hidden = self.projector(pooled)
  177:
  178:         # ----------------------------------------------------------
  179:         # Structured prediction
  180:         # ----------------------------------------------------------
  181:         concept_logits = self.concept_head(
  182:             visual_hidden
  183:         )
  184:
  185:         negative_logits = self.negative_head(
  186:             visual_hidden
  187:         )
  188:
  189:         attribute_logits = self.attribute_head(
  190:             visual_hidden
  191:         )
  192:
  193:         # ----------------------------------------------------------
  194:         # Soft structured conditioning
  195:         # ----------------------------------------------------------
  196:         structured_tokens = self.conditioner(
  197:             concept_logits,
  198:             negative_logits,
  199:             attribute_logits,
  200:         )
  201:
  202:         # ----------------------------------------------------------
  203:         # Visual token
  204:         # ----------------------------------------------------------
  205:         visual_tokens = visual_hidden.unsqueeze(1)
  206:
  207:         # ----------------------------------------------------------
  208:         # Decoder conditioning
  209:         # ----------------------------------------------------------

--- Source lines 218-241 ---
  218:         # ----------------------------------------------------------
  219:         # mT5 decoder
  220:         # ----------------------------------------------------------
  221:         outputs = self.mt5(
  222:             inputs_embeds=inputs_embeds,
  223:             labels=labels,
  224:         )
  225:
  226:         return {
  227:             "report_loss": outputs.loss,
  228:             "concept_logits": concept_logits,
  229:             "negative_logits": negative_logits,
  230:             "attribute_logits": attribute_logits,
  231:             "logits": outputs.logits,
  232:             "inputs_embeds": inputs_embeds,
  233:         }
  234:
  235:
  236: # ================================================================================
  237: # 4. Instantiate V5
  238: # ================================================================================
  239:
  240: print("\n[INSTANTIATE V5]")
  241:

--- SAVED EXECUTION OUTPUT METADATA ---
Số output đã lưu: 14

====================================================================================================
CELL 139 | type=code | lines=2121 | execution_count=15
====================================================================================================

--- Source lines 11-33 ---
   11: #   ↓
   12: #   structured targets
   13: #   ↓
   14: #   optimizer / scheduler
   15: #   ↓
   16: #   checkpoint resume
   17: #   ↓
   18: #   V5 training
   19: #
   20: # CHECKPOINT:
   21: #   every 48 optimizer steps
   22: #   2 rolling checkpoints
   23: #   epoch checkpoints
   24: #   best.pt
   25: #   last.pt
   26: # ============================================================
   27:
   28: import os
   29: import gc
   30: import ast
   31: import json
   32: import math
   33: import random

--- Source lines 93-108 ---
   93:
   94: OPT_STEPS_PER_EPOCH = 384
   95: TOTAL_OPT_STEPS = 1920
   96: WARMUP_STEPS = 96
   97:
   98: CHECKPOINT_EVERY = 48
   99:
  100: BF16 = True
  101:
  102: REPORT_W = 1.0
  103: CONCEPT_W = 0.5
  104: NEGATIVE_W = 0.5
  105: ATTRIBUTE_W = 0.25
  106:
  107: device = torch.device("cuda")
  108:

--- Source lines 146-161 ---
  146:     "baseline_model_v5"
  147: )
  148:
  149: CKPT_DIR = (
  150:     V5_ROOT /
  151:     "checkpoints"
  152: )
  153:
  154: CKPT_DIR.mkdir(
  155:     parents=True,
  156:     exist_ok=True
  157: )
  158:
  159: LAST_CKPT = (
  160:     CKPT_DIR /
  161:     "last.pt"

--- Source lines 390-405 ---
  390:             if found is not None:
  391:                 resolved_paths.append(
  392:                     str(found)
  393:                 )
  394:
  395:     # V4 validation/test: first 8
  396:     # Training: random selection >8
  397:     case_to_images[
  398:         case_id
  399:     ] = resolved_paths
  400:
  401:
  402: # ============================================================
  403: # 8. APPLY V4 SPLIT IMAGE POLICY
  404: # ============================================================
  405:

--- Source lines 875-890 ---
  875:     MAX_TARGET_LENGTH,
  876: )
  877:
  878:
  879: # ============================================================
  880: # 16. VALIDATION LOADER
  881: # ============================================================
  882:
  883: val_loader_v5 = DataLoader(
  884:     val_dataset_v5,
  885:     batch_size=BATCH_SIZE,
  886:     shuffle=False,
  887:     num_workers=2,
  888:     pin_memory=True,
  889:     collate_fn=collate_v5,
  890: )

--- Source lines 1162-1217 ---
 1162:     eta_min=0.0,
 1163: )
 1164:
 1165:
 1166: # ============================================================
 1167: # 22. CHECKPOINT FUNCTIONS
 1168: # ============================================================
 1169:
 1170: EXPECTED_KEYS = {
 1171:     "epoch",
 1172:     "model_state",
 1173:     "optimizer_state",
 1174:     "scheduler_state",
 1175:     "best_val",
 1176:     "rng_state",
 1177:     "cuda_rng_state",
 1178:     "history",
 1179: }
 1180:
 1181:
 1182: def save_ckpt(
 1183:     path,
 1184:     epoch,
 1185:     model,
 1186:     optimizer,
 1187:     scheduler,
 1188:     best_val,
 1189:     history,
 1190: ):
 1191:
 1192:     payload = {
 1193:
 1194:         "epoch":
 1195:             int(epoch),
 1196:
 1197:         "model_state":
 1198:             model.state_dict(),
 1199:
 1200:         "optimizer_state":
 1201:             optimizer.state_dict(),
 1202:
 1203:         "scheduler_state":
 1204:             scheduler.state_dict(),
 1205:
 1206:         "best_val":
 1207:             float(best_val),
 1208:
 1209:         "rng_state":
 1210:             torch.get_rng_state(),
 1211:
 1212:         "cuda_rng_state":
 1213:             torch.cuda.get_rng_state_all(),
 1214:
 1215:         "history":
 1216:             history,
 1217:     }

--- Source lines 1223-1253 ---
 1223:
 1224:     tmp = Path(
 1225:         str(path) + ".tmp"
 1226:     )
 1227:
 1228:     torch.save(
 1229:         payload,
 1230:         tmp
 1231:     )
 1232:
 1233:     os.replace(
 1234:         tmp,
 1235:         path
 1236:     )
 1237:
 1238:
 1239: # ============================================================
 1240: # 23. FIND RESUME CHECKPOINT
 1241: # ============================================================
 1242:
 1243: def checkpoint_step(path):
 1244:
 1245:     try:
 1246:
 1247:         ckpt = torch.load(
 1248:             path,
 1249:             map_location="cpu",
 1250:             weights_only=False,
 1251:         )
 1252:
 1253:         return int(

--- Source lines 1269-1284 ---
 1269:     [LAST_CKPT]
 1270: ):
 1271:
 1272:     if p.exists():
 1273:
 1274:         step = checkpoint_step(
 1275:             p
 1276:         )
 1277:
 1278:         if step >= 0:
 1279:
 1280:             candidates.append(
 1281:                 (
 1282:                     step,
 1283:                     p
 1284:                 )

--- Source lines 1289-1308 ---
 1289: # 24. INITIAL STATE
 1290: # ============================================================
 1291:
 1292: history = {
 1293:     "train_loss": [],
 1294:     "val_loss": [],
 1295:     "lr": [],
 1296: }
 1297:
 1298: best_val = float("inf")
 1299:
 1300: global_step = 0
 1301:
 1302: start_epoch = 1
 1303: start_batch = 0
 1304:
 1305:
 1306: # ============================================================
 1307: # 25. RESUME
 1308: # ============================================================

--- Source lines 1316-1335 ---
 1316:     resume_step, resume_path = (
 1317:         candidates[-1]
 1318:     )
 1319:
 1320:     print("\n" + "=" * 80)
 1321:     print("RESUMING CHECKPOINT")
 1322:     print("=" * 80)
 1323:
 1324:     print(
 1325:         "Checkpoint:",
 1326:         resume_path
 1327:     )
 1328:
 1329:     print(
 1330:         "Step:",
 1331:         resume_step
 1332:     )
 1333:
 1334:     ckpt = torch.load(
 1335:         resume_path,

--- Source lines 1340-1369 ---
 1340:     assert (
 1341:         set(ckpt.keys())
 1342:         == EXPECTED_KEYS
 1343:     )
 1344:
 1345:     v5.load_state_dict(
 1346:         ckpt["model_state"],
 1347:         strict=True,
 1348:     )
 1349:
 1350:     optimizer_v5.load_state_dict(
 1351:         ckpt["optimizer_state"]
 1352:     )
 1353:
 1354:     scheduler_v5.load_state_dict(
 1355:         ckpt["scheduler_state"]
 1356:     )
 1357:
 1358:     best_val = float(
 1359:         ckpt["best_val"]
 1360:     )
 1361:
 1362:     history = ckpt[
 1363:         "history"
 1364:     ]
 1365:
 1366:     global_step = int(
 1367:         scheduler_v5.last_epoch
 1368:     )
 1369:

--- Source lines 1387-1420 ---
 1387:             ]
 1388:         )
 1389:
 1390:     else:
 1391:
 1392:         # Old epoch-level checkpoint
 1393:         if (
 1394:             global_step
 1395:             % OPT_STEPS_PER_EPOCH
 1396:             == 0
 1397:         ):
 1398:
 1399:             start_epoch = (
 1400:                 global_step
 1401:                 // OPT_STEPS_PER_EPOCH
 1402:                 + 1
 1403:             )
 1404:
 1405:             start_batch = 0
 1406:
... Đã đạt giới hạn output của cell ...

... Đã đạt giới hạn output của cell ...

--- SAVED EXECUTION OUTPUT METADATA ---
Số output đã lưu: 2
Output 1: AssertionError: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv

====================================================================================================
CELL 140 | type=code | lines=1154 | execution_count=16
====================================================================================================

--- Source lines 1-29 ---
    1: # ============================================================
    2: # V5 — CELL 9K
    3: # REAL TRAINING — CHECKPOINT / RESUME SAFE
    4: # ============================================================
    5:
    6: import os
    7: import math
    8: import random
    9: import time
   10: from pathlib import Path
   11:
   12: import numpy as np
   13: import torch
   14: import torch.nn.functional as F
   15: from tqdm.auto import tqdm
   16:
   17:
   18: print("=" * 80)
   19: print("V5 REAL TRAINING — CHECKPOINT / RESUME SAFE")
   20: print("=" * 80)
   21:
   22:
   23: # ============================================================
   24: # 1. CONFIG
   25: # ============================================================
   26:
   27: SEED = 42
   28:
   29: EPOCHS = 5

--- Source lines 39-54 ---
   39:
   40: V5_ROOT = Path(
   41:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5"
   42: )
   43:
   44: V5_CKPT_DIR = V5_ROOT / "checkpoints"
   45:
   46: V5_CKPT_DIR.mkdir(
   47:     parents=True,
   48:     exist_ok=True
   49: )
   50:
   51: LAST_CKPT = V5_CKPT_DIR / "last.pt"
   52: BEST_CKPT = V5_CKPT_DIR / "best.pt"
   53:
   54:

--- Source lines 157-324 ---
  157: # 7. HISTORY / RESUME STATE
  158: # ============================================================
  159:
  160: history = {
  161:     "train_loss": [],
  162:     "val_loss": [],
  163:     "report_loss": [],
  164:     "concept_loss": [],
  165:     "negative_loss": [],
  166:     "attribute_loss": [],
  167:     "lr": [],
  168: }
  169:
  170: best_val = float("inf")
  171: start_epoch = 1
  172: global_step = 0
  173:
  174:
  175: # ============================================================
  176: # 8. CHECKPOINT SAVE FUNCTION
  177: # ============================================================
  178:
  179: def save_v5_checkpoint(
  180:     path,
  181:     epoch,
  182:     model,
  183:     optimizer,
  184:     scheduler,
  185:     best_val,
  186:     history,
  187: ):
  188:
  189:     checkpoint = {
  190:         "epoch": int(epoch),
  191:
  192:         "model_state": model.state_dict(),
  193:
  194:         "optimizer_state": optimizer.state_dict(),
  195:
  196:         "scheduler_state": scheduler.state_dict(),
  197:
  198:         "best_val": float(best_val),
  199:
  200:         "rng_state": torch.get_rng_state(),
  201:
  202:         "cuda_rng_state": (
  203:             torch.cuda.get_rng_state_all()
  204:             if torch.cuda.is_available()
  205:             else None
  206:         ),
  207:
  208:         "history": history,
  209:     }
  210:
  211:     expected_keys = {
  212:         "epoch",
  213:         "model_state",
  214:         "optimizer_state",
  215:         "scheduler_state",
  216:         "best_val",
  217:         "rng_state",
  218:         "cuda_rng_state",
  219:         "history",
  220:     }
  221:
  222:     assert set(checkpoint.keys()) == expected_keys
  223:
  224:     tmp_path = Path(
  225:         str(path) + ".tmp"
  226:     )
  227:
  228:     # Atomic-ish replacement:
  229:     # write completely first, then replace target.
  230:     torch.save(
  231:         checkpoint,
  232:         tmp_path
  233:     )
  234:
  235:     os.replace(
  236:         tmp_path,
  237:         path
  238:     )
  239:
  240:     assert path.exists()
  241:
  242:     return path
  243:
  244:
  245: # ============================================================
  246: # 9. CHECKPOINT LOAD FUNCTION
  247: # ============================================================
  248:
  249: def load_v5_checkpoint(
  250:     path,
  251:     model,
  252:     optimizer,
  253:     scheduler,
  254: ):
  255:
  256:     print("\n[RESUME]")
  257:     print("Loading:", path)
  258:
  259:     checkpoint = torch.load(
  260:         path,
  261:         map_location="cpu",
  262:         weights_only=False,
  263:     )
  264:
  265:     expected_keys = {
  266:         "epoch",
  267:         "model_state",
  268:         "optimizer_state",
  269:         "scheduler_state",
  270:         "best_val",
  271:         "rng_state",
  272:         "cuda_rng_state",
  273:         "history",
  274:     }
  275:
  276:     assert set(checkpoint.keys()) == expected_keys
  277:
  278:     model.load_state_dict(
  279:         checkpoint["model_state"],
  280:         strict=True,
  281:     )
  282:
  283:     optimizer.load_state_dict(
  284:         checkpoint["optimizer_state"]
  285:     )
  286:
  287:     scheduler.load_state_dict(
  288:         checkpoint["scheduler_state"]
  289:     )
  290:
  291:     torch.set_rng_state(
  292:         checkpoint["rng_state"]
  293:     )
  294:
  295:     if (
  296:         torch.cuda.is_available()
  297:         and checkpoint["cuda_rng_state"] is not None
  298:     ):
  299:         torch.cuda.set_rng_state_all(
  300:             checkpoint["cuda_rng_state"]
  301:         )
  302:
  303:     restored_history = checkpoint["history"]
  304:
  305:     restored_best = float(
  306:         checkpoint["best_val"]
  307:     )
  308:
  309:     restored_epoch = int(
  310:         checkpoint["epoch"]
  311:     )
  312:
  313:     print(
  314:         "Checkpoint epoch:",
  315:         restored_epoch
  316:     )
  317:
  318:     print(
  319:         "Best val:",
  320:         restored_best
  321:     )
  322:
  323:     print(
  324:         "Scheduler last_epoch:",

--- Source lines 338-355 ---
  338:
  339: if LAST_CKPT.exists():
  340:
  341:     (
  342:         restored_epoch,
  343:         best_val,
  344:         history
  345:     ) = load_v5_checkpoint(
  346:         LAST_CKPT,
  347:         v5,
  348:         optimizer_v5,
  349:         scheduler_v5,
  350:     )
  351:
  352:     start_epoch = restored_epoch + 1
  353:
  354:     # Scheduler step count corresponds to optimizer steps.
  355:     global_step = (

--- Source lines 446-469 ---
  446:     attribute_loss = (
  447:         attribute_loss * mask
  448:     ).sum() / denom
  449:
  450:     total_loss = (
  451:         REPORT_W * outputs["report_loss"]
  452:         + CONCEPT_W * concept_loss
  453:         + NEGATIVE_W * negative_loss
  454:         + ATTRIBUTE_W * attribute_loss
  455:     )
  456:
  457:     return (
  458:         total_loss,
  459:         outputs["report_loss"],
  460:         concept_loss,
  461:         negative_loss,
  462:         attribute_loss,
  463:     )
  464:
  465:
  466: # ============================================================
  467: # 13. TRAINING
  468: # ============================================================
  469:

--- Source lines 586-601 ---
  586:                 attribute_targets=attribute_targets_gpu,
  587:             )
  588:
  589:             (
  590:                 total_loss,
  591:                 report_loss,
  592:                 concept_loss,
  593:                 negative_loss,
  594:                 attribute_loss,
  595:             ) = compute_structured_losses(
  596:                 outputs,
  597:                 concept_targets_gpu,

In [50]:

from google.colab import drive
drive.mount('/content/drive', force_remount=False)

import json
from pathlib import Path
import pandas as pd

# ============================================================
# V5 EXISTING ARTIFACT AUDIT — READ ONLY
# ============================================================
ROOT = Path('/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5')
AUDIT = ROOT / 'diagnostics' / 'audit_20261015'
CKPT = ROOT / 'checkpoints'

print('=' * 90)
print('V5 ARTIFACT / PREDICTION COLLAPSE AUDIT — READ ONLY')
print('=' * 90)

# 1. Check file existence, size and modification time.
print('\n[1] FILE INVENTORY')
paths = [
    ROOT / 'test_predictions_712.csv',
    ROOT / 'diagnostics' / 'v5_final_training_summary.json',
    ROOT / 'prediction_frequency_audit.csv',
    ROOT / 'prediction_quality_audit.csv',
    ROOT / 'distribution_shift_audit.csv',
    ROOT / 'text_overlap_audit.csv',
    ROOT / 'anatomy_error_stratification.csv',
    AUDIT / 'prediction_frequency_audit.csv',
    AUDIT / 'prediction_quality_audit.csv',
    AUDIT / 'distribution_shift_audit.csv',
    AUDIT / 'text_overlap_audit.csv',
    AUDIT / 'anatomy_error_stratification.csv',
    CKPT / 'best.pt',
    CKPT / 'last.pt',
]
for p in paths:
    if p.exists():
        st = p.stat()
        print(f'FOUND | {p.name} | {st.st_size:,} bytes | mtime={pd.Timestamp(st.st_mtime, unit="s")}')
    else:
        print(f'NOT FOUND | {p}')

# 2. Read training summary JSON only.
print('\n[2] TRAINING SUMMARY JSON')
summary_path = ROOT / 'diagnostics' / 'v5_final_training_summary.json'
if summary_path.exists():
    try:
        summary = json.loads(summary_path.read_text(encoding='utf-8'))
        print(json.dumps(summary, ensure_ascii=False, indent=2, default=str)[:18000])
    except Exception as e:
        print('Không đọc được JSON:', repr(e))
else:
    print('Không tìm thấy training summary JSON.')

# 3. Inspect existing CSV diagnostics; print schema and compact summaries.
print('\n[3] EXISTING DIAGNOSTIC CSV FILES')
csv_names = [
    'prediction_frequency_audit.csv',
    'prediction_quality_audit.csv',
    'distribution_shift_audit.csv',
    'text_overlap_audit.csv',
    'anatomy_error_stratification.csv',
    'low_overlap_image_metadata.csv',
    'tympanic_membrane_cases.csv',
]
for name in csv_names:
    candidates = [ROOT / name, AUDIT / name]
    p = next((x for x in candidates if x.exists()), None)
    if p is None:
        print(f'\n--- {name}: NOT FOUND ---')
        continue

    print(f'\n--- {name} | {p} ---')
    try:
        df = pd.read_csv(p, low_memory=False)
        print('Shape:', df.shape)
        print('Columns:', list(df.columns))
        print(df.head(8).to_string(index=False, max_colwidth=100))
        if len(df) > 8:
            print(f'... còn {len(df) - 8} dòng')
    except Exception as e:
        print('Lỗi đọc CSV:', repr(e))

# 4. Independently summarize prediction CSV, without changing it.
print('\n[4] TEST PREDICTION DISTRIBUTION')
pred_path = ROOT / 'test_predictions_712.csv'
if pred_path.exists():
    df = pd.read_csv(pred_path, low_memory=False)
    print('Shape:', df.shape)
    print('Columns:', list(df.columns))

    required = {'case_id', 'prediction', 'ground_truth'}
    if required.issubset(df.columns):
        print('Rows:', len(df))
        print('Unique case_id:', df['case_id'].nunique(dropna=False))
        print('Duplicate case_id rows:', int(df['case_id'].duplicated().sum()))
        print('Missing predictions:', int(df['prediction'].isna().sum()))
        print('Missing ground truth:', int(df['ground_truth'].isna().sum()))

        pred = df['prediction'].fillna('').astype(str).str.strip()
        truth = df['ground_truth'].fillna('').astype(str).str.strip()

        print('Unique prediction strings:', pred.nunique())
        print('Unique ground-truth strings:', truth.nunique())
        print('Exact string match rate:', round(float((pred == truth).mean()), 4))
        print('\nTop 20 predictions:')
        print(pred.value_counts().head(20).to_string())
        print('\nTop 20 ground-truth labels:')
        print(truth.value_counts().head(20).to_string())

        print('\nPrediction frequency quantiles:')
        print(pred.value_counts().describe(percentiles=[.5, .9, .95, .99]).to_string())
    else:
        print('CSV thiếu cột bắt buộc:', sorted(required - set(df.columns)))
else:
    print('Không tìm thấy test_predictions_712.csv.')

# 5. Compare prediction case IDs against the V4 test split, if available.
print('\n[5] TEST SPLIT ID CONSISTENCY')
manifest = Path('/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv')
if manifest.exists() and pred_path.exists():
    try:
        m = pd.read_csv(manifest, usecols=['case_id', 'split'])
        p = pd.read_csv(pred_path, usecols=['case_id'])

        expected = set(
            m.loc[m['split'].astype(str).str.lower().eq('test'), 'case_id']
            .astype(str).str.strip()
        )
        actual = set(p['case_id'].astype(str).str.strip())

        print('Manifest test IDs:', len(expected))
        print('Prediction unique IDs:', len(actual))
        print('Intersection:', len(expected & actual))
        print('Missing prediction IDs:', len(expected - actual))
        print('Unexpected prediction IDs:', len(actual - expected))
        if expected - actual:
            print('Sample missing IDs:', list(sorted(expected - actual))[:10])
        if actual - expected:
            print('Sample unexpected IDs:', list(sorted(actual - expected))[:10])
    except Exception as e:
        print('Lỗi đối chiếu ID:', repr(e))
else:
    print('Không đủ file để đối chiếu manifest và prediction CSV.')

print('\n' + '=' * 90)
print('AUDIT COMPLETE — KHÔNG LOAD CHECKPOINT / KHÔNG TRAINING / KHÔNG GHI FILE')
print('=' * 90)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
==========================================================================================
V5 ARTIFACT / PREDICTION COLLAPSE AUDIT — READ ONLY
==========================================================================================

[1] FILE INVENTORY
FOUND | test_predictions_712.csv | 62,941 bytes | mtime=2026-09-30 16:34:27
FOUND | v5_final_training_summary.json | 649 bytes | mtime=2026-09-29 04:23:10
FOUND | prediction_frequency_audit.csv | 710 bytes | mtime=2026-10-14 12:14:15
FOUND | prediction_quality_audit.csv | 79,960 bytes | mtime=2026-10-14 12:19:52
FOUND | distribution_shift_audit.csv | 1,669 bytes | mtime=2026-10-14 12:26:22
FOUND | text_overlap_audit.csv | 140,287 bytes | mtime=2026-10-14 12:28:11
FOUND | anatomy_error_stratification.csv | 331,383 bytes | mtime=2026-10-14 12:34:59
NOT FOUND | /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/prediction_frequency_audit.csv
NOT FOUND | /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/prediction_quality_audit.csv
NOT FOUND | /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/distribution_shift_audit.csv
NOT FOUND | /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/text_overlap_audit.csv
NOT FOUND | /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/anatomy_error_stratification.csv
FOUND | best.pt | 4,640,037,647 bytes | mtime=2026-09-29 04:20:44
FOUND | last.pt | 4,640,037,647 bytes | mtime=2026-09-29 04:25:51

[2] TRAINING SUMMARY JSON
{
  "model": "V5",
  "status": "TRAINING_COMPLETE",
  "num_epochs": 5,
  "global_step": 1920,
  "epoch": 5,
  "next_batch": 0,
  "best_val": 0.424518172663671,
  "train_loss": [
    0.5731708970967303,
    0.5046075203082849,
    0.47171955251829634,
    0.45422747778290645,
    0.44715843725379206
  ],
  "val_loss": [
    0.46700948011622856,
    0.44155955633946825,
    0.42823387978095856,
    0.4258775923539091,
    0.424518172663671
  ],
  "last_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/last.pt",
  "best_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/best.pt"
}

[3] EXISTING DIAGNOSTIC CSV FILES

--- prediction_frequency_audit.csv | /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/prediction_frequency_audit.csv ---
Shape: (16, 4)
Columns: ['prediction', 'case_count', 'ground_truth_unique', 'percent_of_test']
                                  prediction  case_count  ground_truth_unique  percent_of_test
                                VIÊM MŨI MẠN         324                  100            45.51
         VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP         126                   83            17.70
VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.          81                   28            11.38
                              VIÊM MŨI XOANG          52                   34             7.30
                               VIÊM MŨI + VA          47                   19             6.60
                         VIÊM TAI GIỮA P MẠN          46                   29             6.46
                VIÊM TAI GIỮA T CẤP VIÊM MŨI          10                    9             1.40
             VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T           8                    8             1.12
... còn 8 dòng

--- prediction_quality_audit.csv | /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/prediction_quality_audit.csv ---
Shape: (712, 6)
Columns: ['case_id', 'prediction', 'ground_truth', 'exact_match', 'token_f1', 'prediction_is_subset']
            case_id                                   prediction                                                                ground_truth  exact_match  token_f1  prediction_is_subset
10017.10017.0.10031          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                             VIÊM MÀNG NHĨ CẤP BÓNG NƯỚC P - NHIỀU RÁY TAI T        False  0.631579                 False
10057.10057.0.10071          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                              VIÊM ỐNG TAI NGOÀI (T) MẠN / VIÊM MŨI ĐỢT CẤP.        False  0.666667                 False
10116.10116.0.10130          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                                           VIÊM ỐNG TAI NGOÀI MÀNG NHĨ P CẤP        False  0.875000                 False
10125.10125.0.10139                                 VIÊM MŨI MẠN                        VIÊM MŨI MẠN VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ 2 BÊN MẠN        False  0.400000                  True
10126.10126.0.10140 VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.                                                              VIÊM A-MI-ĐAN.        False  0.153846                 False
10142.10142.0.10156                                 VIÊM MŨI MẠN                                                                VIÊM MŨI MẠN         True  1.000000                  True
10153.10153.0.10167                               VIÊM MŨI XOANG HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI GIỮA TRÊN NỘI SOI / VIÊM MŨI        False  0.210526                 False
10156.10156.0.10170          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                                                    VIÊM ỐNG TAI NGOÀI P CẤP        False  0.714286                 False
... còn 704 dòng

--- distribution_shift_audit.csv | /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/distribution_shift_audit.csv ---
Shape: (16, 10)
Columns: ['normalized_label', 'prediction', 'predicted_cases', 'test_GT_exact_label_cases', 'train_exact_label_cases', 'predicted_pct', 'test_GT_pct', 'train_pct', 'prediction_vs_GT_count_ratio', 'seen_exactly_in_train']
                         normalized_label                                   prediction  predicted_cases  test_GT_exact_label_cases  train_exact_label_cases  predicted_pct  test_GT_pct  train_pct  prediction_vs_GT_count_ratio  seen_exactly_in_train
                             VIÊM MŨI MẠN                                 VIÊM MŨI MẠN              324                         83                      618          45.51        11.66      10.07                          3.90                   True
        VIÊM ỐNG TAI NGOÀI MÀNG NHĨ T CẤP          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP              126                          6                       90          17.70         0.84       1.47                         21.00                   True
VIÊM HỌNG MẠN THEO DÕI TRÀO NGƯỢC DỊCH VỊ VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.               81                         51                      270          11.38         7.16       4.40                          1.59                   True
                           VIÊM MŨI XOANG                               VIÊM MŨI XOANG               52                         36                      302           7.30         5.06       4.92                          1.44                   True
                              VIÊM MŨI VA                                VIÊM MŨI + VA               47                         14                      201           6.60         1.97       3.27                          3.36                   True
                      VIÊM TAI GIỮA P MẠN                          VIÊM TAI GIỮA P MẠN               46                          5                       62           6.46         0.70       1.01                          9.20                   True
             VIÊM TAI GIỮA T CẤP VIÊM MŨI                 VIÊM TAI GIỮA T CẤP VIÊM MŨI               10                          3                       12           1.40         0.42       0.20                          3.33                   True
            VIÊM ỐNG TAI NGOÀI MÀNG NHĨ T              VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T                8                          4                       63           1.12         0.56       1.03                          2.00                   True
... còn 8 dòng

--- text_overlap_audit.csv | /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/text_overlap_audit.csv ---
Shape: (712, 11)
Columns: ['case_id', 'prediction', 'ground_truth', 'precision_tokens', 'recall_tokens', 'token_f1', 'pred_norm', 'gt_norm', 'exact_match', 'pred_token_count', 'gt_token_count']
            case_id                                   prediction                                                                ground_truth  precision_tokens  recall_tokens  token_f1                                 pred_norm                                                                   gt_norm  exact_match  pred_token_count  gt_token_count
10017.10017.0.10031          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                             VIÊM MÀNG NHĨ CẤP BÓNG NƯỚC P - NHIỀU RÁY TAI T          0.750000       0.545455  0.631579         VIÊM ỐNG TAI NGOÀI MÀNG NHĨ T CẤP                             VIÊM MÀNG NHĨ CẤP BÓNG NƯỚC P NHIỀU RÁY TAI T        False                 8              11
10057.10057.0.10071          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                              VIÊM ỐNG TAI NGOÀI (T) MẠN / VIÊM MŨI ĐỢT CẤP.          0.750000       0.600000  0.666667         VIÊM ỐNG TAI NGOÀI MÀNG NHĨ T CẤP                                 VIÊM ỐNG TAI NGOÀI T MẠN VIÊM MŨI ĐỢT CẤP        False                 8              10
10116.10116.0.10130          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                                           VIÊM ỐNG TAI NGOÀI MÀNG NHĨ P CẤP          0.875000       0.875000  0.875000         VIÊM ỐNG TAI NGOÀI MÀNG NHĨ T CẤP                                         VIÊM ỐNG TAI NGOÀI MÀNG NHĨ P CẤP        False                 8               8
10125.10125.0.10139                                 VIÊM MŨI MẠN                        VIÊM MŨI MẠN VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ 2 BÊN MẠN          1.000000       0.250000  0.400000                              VIÊM MŨI MẠN                        VIÊM MŨI MẠN VIÊM ỐNG TAI NGOÀI MÀNG NHĨ 2 BÊN MẠN        False                 3              12
10126.10126.0.10140 VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.                                                              VIÊM A-MI-ĐAN.          0.111111       0.250000  0.153846 VIÊM HỌNG MẠN THEO DÕI TRÀO NGƯỢC DỊCH VỊ                                                             VIÊM A MI ĐAN        False                 9               4
10142.10142.0.10156                                 VIÊM MŨI MẠN                                                                VIÊM MŨI MẠN          1.000000       1.000000  1.000000                              VIÊM MŨI MẠN                                                              VIÊM MŨI MẠN         True                 3               3
10153.10153.0.10167                               VIÊM MŨI XOANG HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI GIỮA TRÊN NỘI SOI / VIÊM MŨI          0.666667       0.125000  0.210526                            VIÊM MŨI XOANG HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI GIỮA TRÊN NỘI SOI VIÊM MŨI        False                 3              16
10156.10156.0.10170          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                                                    VIÊM ỐNG TAI NGOÀI P CẤP          0.625000       0.833333  0.714286         VIÊM ỐNG TAI NGOÀI MÀNG NHĨ T CẤP                                                  VIÊM ỐNG TAI NGOÀI P CẤP        False                 8               6
... còn 704 dòng

--- anatomy_error_stratification.csv | /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/anatomy_error_stratification.csv ---
Shape: (712, 24)
Columns: ['case_id', 'prediction', 'ground_truth', 'precision_tokens', 'recall_tokens', 'token_f1', 'pred_norm', 'gt_norm', 'exact_match', 'pred_token_count', 'gt_token_count', 'tai', 'hoc_mui', 'hong_mui', 'hong_thanh_quan', 'hong_mieng', 'ly_do_noi_soi', 'tai__present', 'hoc_mui__present', 'hong_mui__present', 'hong_thanh_quan__present', 'hong_mieng__present', 'ly_do_noi_soi__present', 'gt_region_heuristic']
            case_id                                   prediction                                                                ground_truth  precision_tokens  recall_tokens  token_f1                                 pred_norm                                                                   gt_norm  exact_match  pred_token_count  gt_token_count                                                                                                  tai                                                                                              hoc_mui                      hong_mui hong_thanh_quan                                 hong_mieng ly_do_noi_soi  tai__present  hoc_mui__present  hong_mui__present  hong_thanh_quan__present  hong_mieng__present  ly_do_noi_soi__present    gt_region_heuristic
10017.10017.0.10031          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                             VIÊM MÀNG NHĨ CẤP BÓNG NƯỚC P - NHIỀU RÁY TAI T          0.750000       0.545455  0.631579         VIÊM ỐNG TAI NGOÀI MÀNG NHĨ T CẤP                             VIÊM MÀNG NHĨ CẤP BÓNG NƯỚC P NHIỀU RÁY TAI T        False                 8              11                                             P: màng nhĩ đỏ, có bóng nước. T: ống tai ngoài đọng ráy.                                                                                                  NaN                           NaN             NaN                                        NaN     đau tai P          True             False              False                     False                False                    True                    Tai
10057.10057.0.10071          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                              VIÊM ỐNG TAI NGOÀI (T) MẠN / VIÊM MŨI ĐỢT CẤP.          0.750000       0.600000  0.666667         VIÊM ỐNG TAI NGOÀI MÀNG NHĨ T CẤP                                 VIÊM ỐNG TAI NGOÀI T MẠN VIÊM MŨI ĐỢT CẤP        False                 8              10 P: ống tai ngoài đọng ít vảy vàng, màng nhĩ bóng sáng. T: da ống tai ngoài khô, ống tai ngoài + m... Cuốn mũi: hồng, gồ ghề nhẹ. Vách ngăn T có mào => điểm tiếp xúc cuốn mũi dưới. Khe mũi: thoáng, s... lỗ vòi nhĩ 2 bên thoáng sạch.             NaN                                        NaN       ù tai T          True              True               True                     False                False                    True     Tai + Mũi/xoang/VA
10116.10116.0.10130          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                                           VIÊM ỐNG TAI NGOÀI MÀNG NHĨ P CẤP          0.875000       0.875000  0.875000         VIÊM ỐNG TAI NGOÀI MÀNG NHĨ T CẤP                                         VIÊM ỐNG TAI NGOÀI MÀNG NHĨ P CẤP        False                 8               8                             P: ống tai ngoài đỏ, màng nhĩ đọng tinh thể trắng T: màng nhĩ bóng sáng.                                                                                                  NaN                           NaN             NaN                                        NaN     đau tai P          True             False              False                     False                False                    True                    Tai
10125.10125.0.10139                                 VIÊM MŨI MẠN                        VIÊM MŨI MẠN VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ 2 BÊN MẠN          1.000000       0.250000  0.400000                              VIÊM MŨI MẠN                        VIÊM MŨI MẠN VIÊM ỐNG TAI NGOÀI MÀNG NHĨ 2 BÊN MẠN        False                 3              12                                                     P+T: da ống tai ngoài khô, màng nhĩ đọng ít ráy.                              Cuốn mũi: nhợt, gồ ghề. Khe mũi: thoáng, sạch Sàn mũi: đọng nhầy trắng.               đọng nhầy trắng             NaN                                        NaN            ho          True              True               True                     False                False                    True     Tai + Mũi/xoang/VA
10126.10126.0.10140 VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.                                                              VIÊM A-MI-ĐAN.          0.111111       0.250000  0.153846 VIÊM HỌNG MẠN THEO DÕI TRÀO NGƯỢC DỊCH VỊ                                                             VIÊM A MI ĐAN        False                 9               4                                                                                                  NaN                                                                                                  NaN                           NaN             NaN Hai a-mi-đan: độ III, đỏ, đọng nhầy trắng.      ĐAU HỌNG         False             False              False                     False                 True                    True Họng/thanh quản/dị vật
10142.10142.0.10156                                 VIÊM MŨI MẠN                                                                VIÊM MŨI MẠN          1.000000       1.000000  1.000000                              VIÊM MŨI MẠN                                                              VIÊM MŨI MẠN         True                 3               3                                                        P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.                              Cuốn mũi: hồng, gồ ghề. Khe mũi: thoáng, sạch Sàn mũi: đọng nhầy trắng.               đọng nhầy trắng             NaN                                        NaN            ho          True              True               True                     False                False                    True           Mũi/xoang/VA
10153.10153.0.10167                               VIÊM MŨI XOANG HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI GIỮA TRÊN NỘI SOI / VIÊM MŨI          0.666667       0.125000  0.210526                            VIÊM MŨI XOANG HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI GIỮA TRÊN NỘI SOI VIÊM MŨI        False                 3              16                                       P+T: ống tai ngoài + màng nhĩ đọng ít ráy, màng nhĩ bóng sáng.                               Cuốn mũi: hồng, láng Khe mũi: thoáng, sạch. Sàn mũi P: đọng nhầy trắng                           NaN             NaN                                        NaN     Đau tai P          True              True              False                     False                False                    True     Tai + Mũi/xoang/VA
10156.10156.0.10170          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                                                    VIÊM ỐNG TAI NGOÀI P CẤP          0.625000       0.833333  0.714286         VIÊM ỐNG TAI NGOÀI MÀNG NHĨ T CẤP                                                  VIÊM ỐNG TAI NGOÀI P CẤP        False                 8               6             P: ống tai ngoài nề, đỏ, màng nhĩ dày. T: ống tai ngoài thoáng sạch, màng nhĩ bóng sáng.                                    Cuốn mũi: hồng, láng. Khe mũi: thoáng, sạch Sàn mũi: thoáng sạch. lỗ vòi nhĩ 2 bên thoáng sạch.             NaN                                        NaN     đau tai P          True              True               True                     False                False                    True                    Tai
... còn 704 dòng

--- low_overlap_image_metadata.csv | /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/low_overlap_image_metadata.csv ---
Shape: (20, 11)
Columns: ['case_id', 'prediction', 'ground_truth', 'precision_tokens', 'recall_tokens', 'token_f1', 'pred_norm', 'gt_norm', 'exact_match', 'pred_token_count', 'gt_token_count']
            case_id                                   prediction                                                      ground_truth  precision_tokens  recall_tokens  token_f1                                 pred_norm                                                          gt_norm  exact_match  pred_token_count  gt_token_count

In [1]:

from google.colab import drive
drive.mount('/content/drive', force_remount=False)

from pathlib import Path
import pandas as pd
import numpy as np

ROOT = Path('/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5')

PRED_PATH = ROOT / 'test_predictions_712.csv'
QUALITY_PATH = ROOT / 'prediction_quality_audit.csv'
ANATOMY_PATH = ROOT / 'anatomy_error_stratification.csv'
SHIFT_PATH = ROOT / 'distribution_shift_audit.csv'

print('=' * 90)
print('V5 ERROR STRATIFICATION — READ ONLY')
print('=' * 90)

for p in [PRED_PATH, QUALITY_PATH, ANATOMY_PATH, SHIFT_PATH]:
    assert p.exists(), f'Thiếu file cần đọc: {p}'

pred = pd.read_csv(PRED_PATH, low_memory=False)
quality = pd.read_csv(QUALITY_PATH, low_memory=False)
anatomy = pd.read_csv(ANATOMY_PATH, low_memory=False)
shift = pd.read_csv(SHIFT_PATH, low_memory=False)

# Merge bằng case_id để tránh phụ thuộc thứ tự dòng.
df = pred.merge(
    quality[['case_id', 'token_f1', 'exact_match']],
    on='case_id',
    how='left',
    validate='one_to_one'
)

region_cols = [
    'tai', 'hoc_mui', 'hong_mui',
    'hong_thanh_quan', 'hong_mieng', 'ly_do_noi_soi'
]
available_regions = [c for c in region_cols if c in anatomy.columns]

anatomy_cols = [
    'case_id', 'gt_region_heuristic',
    'tai__present', 'hoc_mui__present',
    'hong_mui__present', 'hong_thanh_quan__present',
    'hong_mieng__present', 'ly_do_noi_soi__present'
]
anatomy_cols = [c for c in anatomy_cols if c in anatomy.columns]

df = df.merge(
    anatomy[anatomy_cols],
    on='case_id',
    how='left',
    validate='one_to_one'
)

print('\n[1] OVERALL METRICS')
print('Cases:', len(df))
print('Exact match:', round(df['exact_match'].fillna(False).astype(bool).mean(), 4))
print('Mean token F1:', round(df['token_f1'].mean(), 4))
print('Median token F1:', round(df['token_f1'].median(), 4))
print('Cases token F1 = 0:', int((df['token_f1'] == 0).sum()))
print('Cases token F1 < 0.25:', int((df['token_f1'] < 0.25).sum()))

print('\n[2] PERFORMANCE BY GROUND-TRUTH ANATOMICAL REGION')
if 'gt_region_heuristic' in df.columns:
    region_summary = (
        df.groupby('gt_region_heuristic', dropna=False)
        .agg(
            cases=('case_id', 'count'),
            exact_match_rate=('exact_match', lambda x: x.fillna(False).astype(bool).mean()),
            mean_token_f1=('token_f1', 'mean'),
            zero_f1_cases=('token_f1', lambda x: int((x == 0).sum()))
        )
        .sort_values('cases', ascending=False)
    )
    print(region_summary.round(3).to_string())
else:
    print('Không có cột gt_region_heuristic.')

print('\n[3] MOST COMMON PREDICTIONS AND THEIR ERROR PROFILE')
pred_summary = (
    df.groupby('prediction', dropna=False)
    .agg(
        cases=('case_id', 'count'),
        exact_match_rate=('exact_match', lambda x: x.fillna(False).astype(bool).mean()),
        mean_token_f1=('token_f1', 'mean'),
        distinct_ground_truth=('ground_truth', 'nunique')
    )
    .sort_values('cases', ascending=False)
)
print(pred_summary.head(16).round(3).to_string())

print('\n[4] TOP GROUND-TRUTH LABELS AND MOST COMMON PREDICTION')
top_truth = df['ground_truth'].value_counts().head(15).index
for gt in top_truth:
    sub = df[df['ground_truth'] == gt]
    common_pred = sub['prediction'].value_counts().head(3).to_dict()
    print(
        f'\nGT ({len(sub)} cases): {gt}\n'
        f'  Top predictions: {common_pred}\n'
        f'  Exact match: {sub["exact_match"].fillna(False).astype(bool).mean():.3f}'
        f' | Mean token F1: {sub["token_f1"].mean():.3f}'
    )

print('\n[5] PREDICTION FREQUENCY VS TRAIN/TEST LABEL COUNTS')
show_cols = [
    'prediction', 'predicted_cases', 'test_GT_exact_label_cases',
    'train_exact_label_cases', 'prediction_vs_GT_count_ratio',
    'seen_exactly_in_train'
]
show_cols = [c for c in show_cols if c in shift.columns]
print(
    shift.sort_values('predicted_cases', ascending=False)[show_cols]
    .head(16).to_string(index=False)
)

print('\n[6] DOES PREDICTION VARY WITH ANATOMICAL EVIDENCE?')
for col in available_regions:
    values = df[col].fillna('').astype(str).str.strip()
    valid = values.ne('') & values.str.lower().ne('nan')
    if valid.sum() == 0:
        continue
    sub = df.loc[valid].copy()
    sub['_region_text'] = values[valid]
    print(
        f'{col}: {len(sub)} cases with text; '
        f'{sub["_region_text"].nunique()} unique region descriptions; '
        f'{sub["prediction"].nunique()} unique predictions'
    )
    print('  Frequent predictions:', sub['prediction'].value_counts().head(3).to_dict())

print('\n' + '=' * 90)
print('COMPLETE — CHỈ ĐỌC CSV CÓ SẴN, KHÔNG LOAD MODEL / KHÔNG GHI FILE')
print('=' * 90)

Mounted at /content/drive
==========================================================================================
V5 ERROR STRATIFICATION — READ ONLY
==========================================================================================

[1] OVERALL METRICS
Cases: 712
Exact match: 0.1896
Mean token F1: 0.6097
Median token F1: 0.6667
Cases token F1 = 0: 19
Cases token F1 < 0.25: 82

[2] PERFORMANCE BY GROUND-TRUTH ANATOMICAL REGION
                                             cases  exact_match_rate  mean_token_f1  zero_f1_cases
gt_region_heuristic
Mũi/xoang/VA                                   345             0.229          0.701              1
Tai + Mũi/xoang/VA                             152             0.000          0.410              0
Tai                                            110             0.045          0.506             11
Họng/thanh quản/dị vật                          79             0.646          0.805              7
Mũi/xoang/VA + Họng/thanh quản/dị vật           14             0.000          0.500              0
Khác/chưa rõ                                    10             0.000          0.274              0
Tai + Họng/thanh quản/dị vật                     1             0.000          0.636              0
Tai + Mũi/xoang/VA + Họng/thanh quản/dị vật      1             0.000          0.308              0

[3] MOST COMMON PREDICTIONS AND THEIR ERROR PROFILE
                                              cases  exact_match_rate  mean_token_f1  distinct_ground_truth
prediction
VIÊM MŨI MẠN                                    324             0.207          0.623                    109
VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP             126             0.016          0.509                     90
VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.     81             0.630          0.789                     28
VIÊM MŨI XOANG                                   52             0.077          0.528                     35
VIÊM MŨI + VA                                    47             0.170          0.735                     21
VIÊM TAI GIỮA P MẠN                              46             0.065          0.512                     29
VIÊM TAI GIỮA T CẤP VIÊM MŨI                     10             0.000          0.579                      9
VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T                   8             0.000          0.586                      8
VIÊM MŨI XOANG MẠN - POLYP MŨI                    6             0.000          0.529                      6
VIÊM ỐNG TAI NGOÀI 2 BÊN MẠN                      4             0.000          0.441                      4
VIÊM ỐNG TAI NGOÀI P CẤP                          2             0.000          0.399                      2
VIÊM TAI GIỮA T MẠN                               2             0.000          0.374                      2
VIÊM TAI GIỮA 2 BÊN VIÊM MŨI                      1             0.000          0.400                      1
VIÊM MŨI XOANG + VA                               1             0.000          0.462                      1
VIÊM MŨI                                          1             0.000          0.250                      1
VIÊM TAI GIỮA T CẤP VIÊM MŨI XOANG                1             0.000          0.706                      1

[4] TOP GROUND-TRUTH LABELS AND MOST COMMON PREDICTION

GT (79 cases): VIÊM MŨI MẠN
  Top predictions: {'VIÊM MŨI MẠN': 63, 'VIÊM TAI GIỮA P MẠN': 6, 'VIÊM MŨI XOANG': 4}
  Exact match: 0.797 | Mean token F1: 0.908

GT (66 cases): VIÊM MŨI
  Top predictions: {'VIÊM MŨI MẠN': 48, 'VIÊM MŨI XOANG': 7, 'VIÊM MŨI + VA': 5}
  Exact match: 0.000 | Mean token F1: 0.753

GT (51 cases): VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.
  Top predictions: {'VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.': 51}
  Exact match: 1.000 | Mean token F1: 1.000

GT (35 cases): VIÊM MŨI XOANG
  Top predictions: {'VIÊM MŨI MẠN': 24, 'VIÊM MŨI XOANG': 4, 'VIÊM MŨI + VA': 4}
  Exact match: 0.114 | Mean token F1: 0.665

GT (18 cases): VIÊM MŨI ĐỢT CẤP
  Top predictions: {'VIÊM MŨI MẠN': 16, 'VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP': 1, 'VIÊM MŨI + VA': 1}
  Exact match: 0.000 | Mean token F1: 0.558

GT (14 cases): VIÊM MŨI + VA
  Top predictions: {'VIÊM MŨI + VA': 8, 'VIÊM MŨI MẠN': 3, 'VIÊM MŨI XOANG': 2}
  Exact match: 0.571 | Mean token F1: 0.838

GT (12 cases): HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TAI GIỮA TRÊN NỘI SOI
  Top predictions: {'VIÊM MŨI MẠN': 7, 'VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP': 4, 'VIÊM MŨI XOANG': 1}
  Exact match: 0.000 | Mean token F1: 0.061

GT (10 cases): VIÊM TAI GIỮA T MẠN
  Top predictions: {'VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP': 5, 'VIÊM TAI GIỮA P MẠN': 5}
  Exact match: 0.000 | Mean token F1: 0.631

GT (10 cases): HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI GIỮA TRÊN NỘI SOI
  Top predictions: {'VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP': 4, 'VIÊM MŨI MẠN': 3, 'VIÊM TAI GIỮA T CẤP VIÊM MŨI': 2}
  Exact match: 0.000 | Mean token F1: 0.132

GT (9 cases): VIÊM MŨI XOANG MẠN - POLYP MŨI
  Top predictions: {'VIÊM MŨI MẠN': 8, 'VIÊM MŨI XOANG': 1}
  Exact match: 0.000 | Mean token F1: 0.667

GT (9 cases): VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ P CẤP
  Top predictions: {'VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP': 9}
  Exact match: 0.000 | Mean token F1: 0.875

GT (9 cases): VIÊM TAI GIỮA T MẠN VIÊM MŨI XOANG MẠN / ĐÃ PTNS MŨI XOANG
  Top predictions: {'VIÊM TAI GIỮA P MẠN': 4, 'VIÊM MŨI MẠN': 3, 'VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP': 2}
  Exact match: 0.000 | Mean token F1: 0.386

GT (9 cases): VIÊM MŨI MẠN + VA
  Top predictions: {'VIÊM MŨI MẠN': 4, 'VIÊM MŨI + VA': 4, 'VIÊM MŨI XOANG': 1}
  Exact match: 0.000 | Mean token F1: 0.825

GT (7 cases): VIÊM MŨI XOANG MẠN (ĐÃ PT)
  Top predictions: {'VIÊM MŨI MẠN': 7}
  Exact match: 0.000 | Mean token F1: 0.667

GT (7 cases): VIÊM MŨI XOANG + VIÊM VA
  Top predictions: {'VIÊM MŨI + VA': 6, 'VIÊM MŨI MẠN': 1}
  Exact match: 0.000 | Mean token F1: 0.714

[5] PREDICTION FREQUENCY VS TRAIN/TEST LABEL COUNTS
                                  prediction  predicted_cases  test_GT_exact_label_cases  train_exact_label_cases  prediction_vs_GT_count_ratio  seen_exactly_in_train
                                VIÊM MŨI MẠN              324                         83                      618                          3.90                   True
         VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP              126                          6                       90                         21.00                   True
VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.               81                         51                      270                          1.59                   True
                              VIÊM MŨI XOANG               52                         36                      302                          1.44                   True
                               VIÊM MŨI + VA               47                         14                      201                          3.36                   True
                         VIÊM TAI GIỮA P MẠN               46                          5                       62                          9.20                   True
                VIÊM TAI GIỮA T CẤP VIÊM MŨI               10                          3                       12                          3.33                   True
             VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T                8                          4                       63                          2.00                   True
              VIÊM MŨI XOANG MẠN - POLYP MŨI                6                          9                      120                          0.67                   True
                VIÊM ỐNG TAI NGOÀI 2 BÊN MẠN                4                          1                       24                          4.00                   True
                    VIÊM ỐNG TAI NGOÀI P CẤP                2                          2                       22                          1.00                   True
                         VIÊM TAI GIỮA T MẠN                2                         10                       41                          0.20                   True
                VIÊM TAI GIỮA 2 BÊN VIÊM MŨI                1                          1                        5                          1.00                   True
                         VIÊM MŨI XOANG + VA                1                          3                       55                          0.33                   True
                                    VIÊM MŨI                1                         67                      670                          0.01                   True
          VIÊM TAI GIỮA T CẤP VIÊM MŨI XOANG                1                          2                       13                          0.50                   True

[6] DOES PREDICTION VARY WITH ANATOMICAL EVIDENCE?

KeyError: 'tai'

In [2]:
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

from pathlib import Path
import pandas as pd
import numpy as np

ROOT = Path('/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5')
PRED = ROOT / 'test_predictions_712.csv'
QUALITY = ROOT / 'prediction_quality_audit.csv'
ANATOMY = ROOT / 'anatomy_error_stratification.csv'
SHIFT = ROOT / 'distribution_shift_audit.csv'

for p in [PRED, QUALITY, ANATOMY, SHIFT]:
    assert p.exists(), f'Thiếu file: {p}'

pred = pd.read_csv(PRED, low_memory=False)
quality = pd.read_csv(QUALITY, low_memory=False)
anatomy = pd.read_csv(ANATOMY, low_memory=False)
shift = pd.read_csv(SHIFT, low_memory=False)

# Chỉ lấy các cột cần thiết; tránh merge trùng tên cột.
qcols = [c for c in ['case_id', 'token_f1', 'exact_match'] if c in quality.columns]
acols = [
    c for c in [
        'case_id', 'gt_region_heuristic',
        'tai', 'hoc_mui', 'hong_mui',
        'hong_thanh_quan', 'hong_mieng', 'ly_do_noi_soi',
        'tai__present', 'hoc_mui__present', 'hong_mui__present',
        'hong_thanh_quan__present', 'hong_mieng__present',
        'ly_do_noi_soi__present'
    ] if c in anatomy.columns
]

df = pred.merge(
    quality[qcols], on='case_id', how='left', validate='one_to_one'
).merge(
    anatomy[acols], on='case_id', how='left', validate='one_to_one'
)

print('=' * 85)
print('CELL 1 — FIXED ERROR STRATIFICATION')
print('=' * 85)
print('Rows:', len(df), '| Unique case IDs:', df['case_id'].nunique())
print('Columns successfully joined:', acols)
print('Exact match rate:', round(df['exact_match'].fillna(False).astype(bool).mean(), 4))
print('Mean token F1:', round(df['token_f1'].mean(), 4))
print('Zero token-F1 cases:', int((df['token_f1'] == 0).sum()))

if 'gt_region_heuristic' in df.columns:
    print('\n[Performance by ground-truth region]')
    print(
        df.groupby('gt_region_heuristic', dropna=False)
        .agg(
            cases=('case_id', 'size'),
            exact_match_rate=('exact_match',
                              lambda s: s.fillna(False).astype(bool).mean()),
            mean_token_f1=('token_f1', 'mean'),
            zero_f1=('token_f1', lambda s: int((s == 0).sum())),
            unique_predictions=('prediction', 'nunique')
        )
        .sort_values('cases', ascending=False)
        .round(3).to_string()
    )

print('\n[Prediction counts and performance]')
print(
    df.groupby('prediction', dropna=False)
    .agg(
        cases=('case_id', 'size'),
        exact_match_rate=('exact_match',
                          lambda s: s.fillna(False).astype(bool).mean()),
        mean_token_f1=('token_f1', 'mean'),
        unique_ground_truth=('ground_truth', 'nunique')
    )
    .sort_values('cases', ascending=False)
    .head(16).round(3).to_string()
)

print('\n[Anatomical text coverage and prediction diversity]')
for col in ['tai', 'hoc_mui', 'hong_mui',
            'hong_thanh_quan', 'hong_mieng', 'ly_do_noi_soi']:
    if col not in df.columns:
        print(f'{col}: column absent')
        continue
    s = df[col].fillna('').astype(str).str.strip()
    valid = s.ne('') & s.str.lower().ne('nan')
    sub = df.loc[valid]
    print(
        f'{col}: text_cases={int(valid.sum())}, '
        f'unique_texts={s[valid].nunique()}, '
        f'unique_predictions={sub["prediction"].nunique()}'
    )
    if len(sub):
        print('  Top predictions:', sub['prediction'].value_counts().head(4).to_dict())

print('\nREAD ONLY — no model loaded; no files written.')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
=====================================================================================
CELL 1 — FIXED ERROR STRATIFICATION
=====================================================================================
Rows: 712 | Unique case IDs: 712
Columns successfully joined: ['case_id', 'gt_region_heuristic', 'tai', 'hoc_mui', 'hong_mui', 'hong_thanh_quan', 'hong_mieng', 'ly_do_noi_soi', 'tai__present', 'hoc_mui__present', 'hong_mui__present', 'hong_thanh_quan__present', 'hong_mieng__present', 'ly_do_noi_soi__present']
Exact match rate: 0.1896
Mean token F1: 0.6097
Zero token-F1 cases: 19

[Performance by ground-truth region]
                                             cases  exact_match_rate  mean_token_f1  zero_f1  unique_predictions
gt_region_heuristic
Mũi/xoang/VA                                   345             0.229          0.701        1                  10
Tai + Mũi/xoang/VA                             152             0.000          0.410        0                  13
Tai                                            110             0.045          0.506       11                  10
Họng/thanh quản/dị vật                          79             0.646          0.805        7                   1
Mũi/xoang/VA + Họng/thanh quản/dị vật           14             0.000          0.500        0                   2
Khác/chưa rõ                                    10             0.000          0.274        0                   2
Tai + Họng/thanh quản/dị vật                     1             0.000          0.636        0                   1
Tai + Mũi/xoang/VA + Họng/thanh quản/dị vật      1             0.000          0.308        0                   1

[Prediction counts and performance]
                                              cases  exact_match_rate  mean_token_f1  unique_ground_truth
prediction
VIÊM MŨI MẠN                                    324             0.207          0.623                  109
VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP             126             0.016          0.509                   90
VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.     81             0.630          0.789                   28
VIÊM MŨI XOANG                                   52             0.077          0.528                   35
VIÊM MŨI + VA                                    47             0.170          0.735                   21
VIÊM TAI GIỮA P MẠN                              46             0.065          0.512                   29
VIÊM TAI GIỮA T CẤP VIÊM MŨI                     10             0.000          0.579                    9
VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T                   8             0.000          0.586                    8
VIÊM MŨI XOANG MẠN - POLYP MŨI                    6             0.000          0.529                    6
VIÊM ỐNG TAI NGOÀI 2 BÊN MẠN                      4             0.000          0.441                    4
VIÊM ỐNG TAI NGOÀI P CẤP                          2             0.000          0.399                    2
VIÊM TAI GIỮA T MẠN                               2             0.000          0.374                    2
VIÊM TAI GIỮA 2 BÊN VIÊM MŨI                      1             0.000          0.400                    1
VIÊM MŨI XOANG + VA                               1             0.000          0.462                    1
VIÊM MŨI                                          1             0.000          0.250                    1
VIÊM TAI GIỮA T CẤP VIÊM MŨI XOANG                1             0.000          0.706                    1

[Anatomical text coverage and prediction diversity]
tai: text_cases=468, unique_texts=214, unique_predictions=16
  Top predictions: {'VIÊM MŨI MẠN': 193, 'VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP': 125, 'VIÊM MŨI XOANG': 52, 'VIÊM TAI GIỮA P MẠN': 46}
hoc_mui: text_cases=569, unique_texts=298, unique_predictions=15
  Top predictions: {'VIÊM MŨI MẠN': 322, 'VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP': 78, 'VIÊM MŨI XOANG': 52, 'VIÊM MŨI + VA': 47}
hong_mui: text_cases=524, unique_texts=54, unique_predictions=15
  Top predictions: {'VIÊM MŨI MẠN': 315, 'VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP': 57, 'VIÊM MŨI + VA': 45, 'VIÊM MŨI XOANG': 43}
hong_thanh_quan: text_cases=77, unique_texts=19, unique_predictions=1
  Top predictions: {'VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.': 77}
hong_mieng: text_cases=93, unique_texts=18, unique_predictions=4
  Top predictions: {'VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.': 80, 'VIÊM MŨI + VA': 6, 'VIÊM MŨI MẠN': 6, 'VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP': 1}
ly_do_noi_soi: text_cases=707, unique_texts=210, unique_predictions=16
  Top predictions: {'VIÊM MŨI MẠN': 322, 'VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP': 126, 'VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.': 80, 'VIÊM MŨI XOANG': 51}

READ ONLY — no model loaded; no files written.

In [3]:
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

from pathlib import Path
import pandas as pd

ROOT = Path('/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5')
PRED = ROOT / 'test_predictions_712.csv'
QUALITY = ROOT / 'prediction_quality_audit.csv'
ANATOMY = ROOT / 'anatomy_error_stratification.csv'

for p in [PRED, QUALITY, ANATOMY]:
    assert p.exists(), f'Thiếu file: {p}'

pred = pd.read_csv(PRED, low_memory=False)
quality = pd.read_csv(QUALITY, low_memory=False)
anatomy = pd.read_csv(ANATOMY, low_memory=False)

keep_q = [c for c in ['case_id', 'token_f1', 'exact_match'] if c in quality.columns]
keep_a = [
    c for c in [
        'case_id', 'gt_region_heuristic',
        'tai', 'hoc_mui', 'hong_mui',
        'hong_thanh_quan', 'hong_mieng', 'ly_do_noi_soi'
    ] if c in anatomy.columns
]

df = pred.merge(
    quality[keep_q], on='case_id', how='left', validate='one_to_one'
).merge(
    anatomy[keep_a], on='case_id', how='left', validate='one_to_one'
)

region_cols = [
    c for c in [
        'tai', 'hoc_mui', 'hong_mui',
        'hong_thanh_quan', 'hong_mieng', 'ly_do_noi_soi'
    ] if c in df.columns
]

print('=' * 85)
print('CELL 2 — LOW-OVERLAP CASE REVIEW')
print('=' * 85)

# Ưu tiên ca token F1 thấp nhất; dùng case_id để có thể truy lại dữ liệu.
df['token_f1'] = pd.to_numeric(df['token_f1'], errors='coerce')
low = df.sort_values(['token_f1', 'case_id'], ascending=[True, True]).head(30)

print('\n[30 ca có token F1 thấp nhất]')
show = ['case_id', 'token_f1', 'prediction', 'ground_truth', 'gt_region_heuristic']
show += region_cols
show = [c for c in show if c in low.columns]
print(low[show].to_string(index=False, max_colwidth=100))

print('\n[Nhóm dự đoán thường gặp trong các ca token F1 < 0.25]')
bad = df[df['token_f1'] < 0.25].copy()
print('Số ca:', len(bad))
if len(bad):
    print(
        bad.groupby('prediction')
        .agg(
            cases=('case_id', 'size'),
            mean_token_f1=('token_f1', 'mean'),
            unique_ground_truth=('ground_truth', 'nunique')
        )
        .sort_values('cases', ascending=False)
        .head(12).round(3).to_string()
    )

    print('\n[Phân bố vùng giải phẫu ở nhóm F1 thấp]')
    if 'gt_region_heuristic' in bad.columns:
        print(bad['gt_region_heuristic'].fillna('(missing)').value_counts().to_string())

print('\n[Đối chiếu mô tả giải phẫu với dự đoán]')
for col in region_cols:
    s = bad[col].fillna('').astype(str).str.strip()
    valid = s.ne('') & s.str.lower().ne('nan')
    subset = bad.loc[valid]
    print(f'\n{col}: {len(subset)} ca F1 thấp có mô tả')
    if len(subset):
        print('Dự đoán phổ biến:', subset['prediction'].value_counts().head(5).to_dict())
        print('Ví dụ mô tả:')
        for value in subset[col].dropna().astype(str).head(3):
            print(' -', value[:250])

print('\nREAD ONLY — no model loaded; no files written.')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
=====================================================================================
CELL 2 — LOW-OVERLAP CASE REVIEW
=====================================================================================

[30 ca có token F1 thấp nhất]
            case_id  token_f1                                   prediction                                                                 ground_truth    gt_region_heuristic                                                                                                 tai                                                                                              hoc_mui                      hong_mui                                                                                      hong_thanh_quan                                                                            hong_mieng        ly_do_noi_soi
10783.10783.0.10798  0.000000 VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.                 HIỆN KHÔNG THẤY ĐIỂM CHẢY MÁU TRÊN NỘI SOI A-MI-ĐAN QUÁ PHÁT Họng/thanh quản/dị vật                                                                                                 NaN                                                                                                  NaN                           NaN                                                                                                  NaN                                                  Hai a-mi-đan: độ III, bề mặt gồ ghề.             KHẠC MÁU
10854.10854.0.10869  0.000000 VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.               A-MI-ĐAN QUÁ PHÁT HIỆN KHÔNG THẤY ĐIỂM CHẢY MÁU TRÊN NỘI SOI . Họng/thanh quản/dị vật                                                                                                 NaN                                                                                                  NaN                           NaN                                                                                                  NaN Hai a-mi-đan: to độ III, bên P có điểm sung huyết. Thành sau họng: có ít hạt rải rác.                 NGÁY
11630.11630.0.11647  0.000000 VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.                                                             LIỆT DÂY THANH P Họng/thanh quản/dị vật                                                                                                 NaN                                                                                                  NaN                           NaN Thanh thiệt: hồng, láng. Dây thanh: trơn, láng, P di động yếu. Sụn phễu: hồng, láng. Vùng gian ph...                                    Hai a-mi-đan: không to. Thành sau họng: trơn láng.           NUỐT VƯỚNG
12668.12668.0.12686  0.000000                                 VIÊM MŨI MẠN             HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI GIỮA TRÊN NỘI SOI                    Tai                                                       P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.                              Cuốn mũi: hồng, gồ ghề. Các khe mũi: thoáng, sạch Sàn mũi: thoáng sạch.  lỗ vòi nhĩ 2 bên thoáng sạch                                                                                                  NaN                                                                                   NaN              ù tai p
12808.12808.0.12826  0.000000                                 VIÊM MŨI MẠN             HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI GIỮA TRÊN NỘI SOI                    Tai                                                       P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.                                Cuốn mũi: hồng, láng. Các khe mũi: thoáng, sạch Sàn mũi: thoáng sạch.  lỗ vòi nhĩ 2 bên thoáng sạch                                                                                                  NaN                                                                                   NaN            đau tai T
12907.12907.0.12925  0.000000                                 VIÊM MŨI MẠN             HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI GIỮA TRÊN NỘI SOI                    Tai                         P: màng nhĩ bóng sáng. T: màng nhĩ đọng ít ráy, sau hút màng nhĩ bóng sáng.                         Cuốn mũi: hồng, láng. Các khe mũi: thoáng, sạch Sàn mũi: đọng ít nhầy trắng.  lỗ vòi nhĩ 2 bên thoáng sạch                                                                                                  NaN                                                                                   NaN            đau tai T
14009.14009.0.14028  0.000000                                 VIÊM MŨI MẠN                                                                           VA           Mũi/xoang/VA                                                       P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.                                Cuốn mũi: hồng, láng. Các khe mũi: thoáng, sạch Sàn mũi: thoáng sạch.                      VA độ II                                                                                                  NaN                                                                                   NaN          Kiểm tra VA
14900.14900.0.14919  0.000000                               VIÊM MŨI XOANG            HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TAI GIỮA TRÊN NỘI SOI                    Tai                                                       P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.                                    Cuốn mũi: hồng, láng. Khe mũi: thoáng, sạch Sàn mũi: thoáng sạch.  lỗ vòi nhĩ 2 bên thoáng sạch                                                                                                  NaN                                                                                   NaN            ĐAU TAI P
14927.14927.0.14946  0.000000                                 VIÊM MŨI MẠN            HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TAI GIỮA TRÊN NỘI SOI                    Tai                                                                                                 NaN                                  Cuốn mũi: hông, gồ ghề. Khe mũi: thoáng, sạch Sàn mũi: thoáng sạch.                   thoáng sạch                                                                                                  NaN                                                                                   NaN           nặng hàm T
15036.15036.0.15055  0.000000                                 VIÊM MŨI MẠN            HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TAI GIỮA TRÊN NỘI SOI                    Tai                                                                                                 NaN                                  Cuốn mũi: hông, gồ ghề. Khe mũi: thoáng, sạch Sàn mũi: thoáng sạch.                   thoáng sạch                                                                                                  NaN                                                                                   NaN            ĐAU HÀM T
15066.15066.0.15085  0.000000                                 VIÊM MŨI MẠN            HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TAI GIỮA TRÊN NỘI SOI                    Tai P: ống tai ngoài đọng ít ráy, màng nhĩ bóng sáng. T: ống tai ngoài đọng ít ráy, màng nhĩ bóng sáng.                                Cuốn mũi: hồng, láng. Các khe mũi: thoáng, sạch Sàn mũi: thoáng sạch.                   thoáng sạch                                                                                                  NaN                                                                                   NaN            Đau tai P
15264.15264.0.15284  0.000000                                 VIÊM MŨI MẠN            HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TAI GIỮA TRÊN NỘI SOI                    Tai             P: ống tai ngoài thoáng sạch, màng nhĩ dày. T: ống tai ngoài thoáng sạch, màng nhĩ dày.                                Cuốn mũi: hồng, láng. Các khe mũi: thoáng, sạch Sàn mũi: thoáng sạch.                   thoáng sạch                                                                                                  NaN                                                                                   NaN          Ù TAI 2 BÊN
15284.15284.0.15304  0.000000 VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.                                                 HÓC XƯƠNG CÁ NGÀY 1 (ĐÃ LẤY) Họng/thanh quản/dị vật                                                                                                 NaN                                                                                                  NaN                           NaN                                                                             Thanh thiệt: hồng, láng.                                                  A-mi-đan: bên T có xương cá (đã lấy)    NUỐT VƯỚNG SAU ĂN
15356.15356.0.15376  0.000000 VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.                                                       HÓC XƯƠNG CÁ (ĐÃ LẤY). Họng/thanh quản/dị vật                                                                                                 NaN                                                                                                  NaN                           NaN Đáy lưỡi: có xương cá. Thanh thiệt: hồng, láng. Dây thanh: trơn, láng, di động tốt. Sụn phễu: hồn...                               Hai a-mi-đan: không to. Thành sau họng: có hạt rải rác. NUỐT VƯỚNG SAU ĂN CÁ
16027.16027.0.16048  0.000000                                 VIÊM MŨI MẠN            HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TAI GIỮA TRÊN NỘI SOI                    Tai P: ống tai ngoài thoáng sạch, màng nhĩ bóng sáng. T: ống tai ngoài thoáng sạch, màng nhĩ bóng sáng.                                Cuốn mũi: hồng, láng. Các khe mũi: thoáng, sạch Sàn mũi: thoáng sạch.  lỗ vòi nhĩ 2 bên thoáng sạch                                                                                                  NaN                                                                                   NaN          Ù tai 2 bên
16051.16051.0.16072  0.000000                                 VIÊM MŨI MẠN            HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TAI GIỮA TRÊN NỘI SOI                    Tai                                                       P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.                            Cuốn mũi: hồng, trơn láng Khe mũi: thoáng, sạch Sàn mũi: đọng nhầy trắng.               đọng nhầy trắng                                                                                                  NaN                                                                                   NaN            CHÓNG MẶT
16806.16806.0.16828  0.000000                                 VIÊM MŨI MẠN            HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TAI GIỮA TRÊN NỘI SOI                    Tai P: ống tai ngoài thoáng sạch, màng nhĩ bóng sáng. T: ống tai ngoài thoáng sạch, màng nhĩ bóng sáng.                                                                                                  NaN                           NaN                                                                                                  NaN                                                                                   NaN       NGỨA TAI 2 BÊN
17557.17557.0.17582  0.000000 VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.                                                               HÓC DỊ VẬT N1. Họng/thanh quản/dị vật                                                                                                 NaN                                                                                                  NaN                           NaN Thanh thiệt: hồng, láng. Dây thanh: trơn, láng, di động tốt. Sụn phễu: hồng, láng. Vùng gian phễu...                        Hai a-mi-đan: bên P có dị vật. Thành sau họng: có hạt rải rác. Nuốt vướng sau ăn N1
17686.17686.0.17711  0.000000 VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.                                                    HÓC XƯƠNG CÁ N1 (ĐÃ LẤY). Họng/thanh quản/dị vật                                                                                                 NaN                                                                                                  NaN                           NaN Thanh thiệt: hồng, láng. Vùng đáy lưỡi: có xương cá Dây thanh: trơn, láng, di động tốt. Sụn phễu:...                               Hai a-mi-đan: không to. Thành sau họng: có hạt rải rác. Nuốt vướng sau ăn N1
17546.17546.0.17571  0.090909 VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.              HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ HỌNG - THANH QUẢN TRÊN NỘI SOI Họng/thanh quản/dị vật                                                                                                 NaN                                                                                                  NaN                           NaN Thanh thiệt: hồng, láng. Dây thanh: trơn, láng, di động tốt. Sụn phễu: hồng, láng. Vùng gian phễu...                               Hai a-mi-đan: không to. Thành sau họng: có hạt rải rác.                  NaN
12070.12070.0.12088  0.105263                                 VIÊM MŨI MẠN  HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ MŨI XOANG, TAI NGOÀI TAI GIỮA TRÊN NỘI SOI     Tai + Mũi/xoang/VA                                                       P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.                                   Cuốn mũi: hồng, láng. Khe mũi: thoáng, sạch. Sàn mũi: thoáng sạch. lỗ vòi nhĩ 2 bên thoáng sạch.                                                                                                  NaN                                                                                   NaN     Đau trán + mắt T
13486.13486.0.13505  0.105263                                 VIÊM MŨI MẠN  HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI GIỮA, MŨI XOANG TRÊN NỘI SOI     Tai + Mũi/xoang/VA                                                       P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.                                Cuốn mũi: hồng, láng. Các khe mũi: thoáng, sạch. Sàn mũi: thoáng sạch  lỗ vòi nhĩ 2 bên thoáng sạch                                                                                                  NaN                                                                                   NaN            đau tai T
14156.14156.0.14175  0.105263          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                         VIÊM MŨI- HIỆN KHÔNG THẤY ĐIỂM CHẢY MÁU TRÊN NỘI SOI           Mũi/xoang/VA                                          T+P: ống tai ngoài nhiều ráy, sau lấy, màng nhĩ bóng sáng. Vách ngăn: sung huyết điểm mạch 2 bên Cuốn mũi: nhợt, gồ ghề, có điểm tiếp xúc Khe mũi: thoáng, s...                           NaN                                                                                                  NaN                                                                                   NaN                   Ho
14901.14901.0.14920  0.105263                                 VIÊM MŨI MẠN HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ MŨI XOANG, TAI NGOÀI, TAI GIỮA TRÊN NỘI SOI     Tai + Mũi/xoang/VA                                                       P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.                                Cuốn mũi: hồng, láng. Các khe mũi: thoáng, sạch Sàn mũi: thoáng sạch.                   thoáng sạch                                                                                                  NaN                                                                                   NaN         ĐAU ĐẦU 2 TD
14950.14950.0.14969  0.105263                                 VIÊM MŨI MẠN HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ MŨI XOANG, TAI NGOÀI, TAI GIỮA TRÊN NỘI SOI     Tai + Mũi/xoang/VA P: ống tai ngoài thoáng sạch, màng nhĩ bóng sáng. T: ống tai ngoài thoáng sạch, màng nhĩ bóng sáng.                                Cuốn mũi: hồng, láng. Các khe mũi: thoáng, sạch. Sàn mũi: thoáng sạch                   thoáng sạch                                                                                                  NaN                                                                                   NaN                   ho
15065.15065.0.15084  0.105263                                 VIÊM MŨI MẠN HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ MŨI XOANG, TAI NGOÀI, TAI GIỮA TRÊN NỘI SOI     Tai + Mũi/xoang/VA                                                       P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.                                                           Cuốn mũi: hồng, láng. Sàn mũi: thoáng sạch                           NaN                                                                                                  NaN                                                                                   NaN                   HO
16182.16182.0.16203  0.105263                                 VIÊM MŨI MẠN HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ MŨI XOANG, TAI NGOÀI, TAI GIỮA TRÊN NỘI SOI     Tai + Mũi/xoang/VA P: ống tai ngoài thoáng sạch, màng nhĩ bóng sáng. T: ống tai ngoài thoáng sạch, màng nhĩ bóng sáng.                Cuốn mũi: hồng, xuất tiết nhầy trắng. Các khe mũi: thoáng, sạch Sàn mũi: thoáng sạch.  lỗ vòi nhĩ 2 bên thoáng sạch                                                                                                  NaN                                                                                   NaN            ĐAU ĐẦU P
12042.12042.0.12060  0.133333                               VIÊM MŨI XOANG                       HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ MŨI, TAI TRÊN NỘI SOI     Tai + Mũi/xoang/VA                                                       P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.                                 Cuốn mũi: hồng, láng. Các khe mũi: thoáng, sạch Sàn mũi: thoáng sạch                   thoáng sạch                                                                                                  NaN                                                                                   NaN             Nhức đầu
17368.17368.0.17391  0.133333                                 VIÊM MŨI MẠN                      HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ MŨI XOANG TRÊN NỘI SOI           Mũi/xoang/VA                                                                                                 NaN                                 Cuốn mũi: hồng, láng Các khe mũi: thoáng, sạch Sàn mũi: thoáng sạch.                   thoáng sạch                                                                                                  NaN                                                                                   NaN                   HO
14485.14485.0.14504  0.142857 VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.                                                           VIÊM MŨI XOANG T>P           Mũi/xoang/VA                                                       P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.                       Cuốn mũi: nhợt, gồ ghề. Khe mũi đọng nhầy trắng T>P. Sàn mũi: đọng nhầy trắng.               đọng nhầy trắng                                                                                                  NaN                                                                                   NaN                   Ho

[Nhóm dự đoán thường gặp trong các ca token F1 < 0.25]
Số ca: 82
                                              cases  mean_token_f1  unique_ground_truth
prediction
VIÊM MŨI MẠN                                     39          0.128                   24
VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP              22          0.183                   13
VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.     11          0.050                   11
VIÊM MŨI XOANG                                    4          0.131                    4

In [4]:
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

from pathlib import Path
import json

PROJECT = Path('/content/drive/MyDrive/NoiSoi_Matching')
ROOT = PROJECT / 'baseline_model_v5'
NB_PATH = Path('/content/drive/MyDrive/Colab Notebooks/25sep.ipynb')
SUMMARY = ROOT / 'diagnostics/v5_final_training_summary.json'
PRED = ROOT / 'test_predictions_712.csv'

print('=' * 85)
print('CELL 3 — NOTEBOOK / ARTIFACT PROVENANCE AUDIT')
print('=' * 85)

# 1. Metadata only: no checkpoint deserialization.
for p in [PRED, SUMMARY, ROOT / 'checkpoints/best.pt', ROOT / 'checkpoints/last.pt']:
    if p.exists():
        st = p.stat()
        print(f'\nFILE: {p}')
        print(f'  size_bytes={st.st_size}')
        print(f'  modified={__import__("datetime").datetime.fromtimestamp(st.st_mtime).isoformat()}')
    else:
        print(f'\nMISSING: {p}')

if SUMMARY.exists():
    try:
        meta = json.loads(SUMMARY.read_text(encoding='utf-8'))
        print('\n[Training summary JSON]')
        for key in [
            'model', 'status', 'num_epochs', 'global_step', 'epoch',
            'best_val', 'last_checkpoint', 'best_checkpoint'
        ]:
            if key in meta:
                print(f'{key}: {meta[key]}')
        print('train_loss:', meta.get('train_loss'))
        print('val_loss:', meta.get('val_loss'))
    except Exception as e:
        print('Could not parse summary:', repr(e))

# 2. Search saved notebook source AND saved cell outputs.
if not NB_PATH.exists():
    print('\nNOTEBOOK NOT FOUND:', NB_PATH)
else:
    nb = json.loads(NB_PATH.read_text(encoding='utf-8'))
    cells = nb.get('cells', [])
    terms = [
        'test_predictions_712.csv',
        'test_predictions',
        'prediction_path',
        'model.generate',
        'exact_generate',
        'generate(',
        'best.pt',
        'last.pt',
        'torch.save',
        'to_csv(',
        'load_state_dict',
        'TRAINING_COMPLETE'
    ]

    print(f'\nNotebook cells: {len(cells)}')
    matches = []
    for i, cell in enumerate(cells):
        source = ''.join(cell.get('source', []))
        output_texts = []
        for out in cell.get('outputs', []):
            if 'text' in out:
                output_texts.append(''.join(out['text']))
            data = out.get('data', {})
            if 'text/plain' in data:
                value = data['text/plain']
                output_texts.append(''.join(value) if isinstance(value, list) else str(value))
            if 'ename' in out:
                output_texts.append(f"{out.get('ename')}: {out.get('evalue', '')}")

        output = '\n'.join(output_texts)
        found_source = [t for t in terms if t.lower() in source.lower()]
        found_output = [t for t in terms if t.lower() in output.lower()]

        if found_source or found_output:
            matches.append((i, cell.get('execution_count'), found_source, found_output, source, output))

    for i, execution_count, src_terms, out_terms, source, output in matches:
        print(f'\n--- CELL INDEX {i} | execution_count={execution_count} ---')
        print('Source matches:', src_terms)
        print('Output matches:', out_terms)

        if src_terms:
            lines = source.splitlines()
            shown = 0
            for j, line in enumerate(lines):
                if any(t.lower() in line.lower() for t in src_terms):
                    lo, hi = max(0, j-2), min(len(lines), j+3)
                    print(f'  Lines {lo+1}-{hi}:')
                    for k in range(lo, hi):
                        print(f'    {k+1}: {lines[k][:240]}')
                    shown += 1
                    if shown >= 5:
                        print('  ... source excerpts truncated')
                        break

        if output:
            relevant = [
                line for line in output.splitlines()
                if any(t.lower() in line.lower() for t in terms)
                or 'Error' in line or 'Traceback' in line
            ]
            if relevant:
                print('Relevant saved output:')
                for line in relevant[:15]:
                    print(' ', line[:240])

    exact_source_hits = [
        i for i, cell in enumerate(cells)
        if 'test_predictions_712.csv' in ''.join(cell.get('source', []))
    ]
    print('\n[Direct source reference to prediction CSV]')
    print('Cell indices:', exact_source_hits if exact_source_hits else 'NONE FOUND')

print('\nREAD ONLY — checkpoint weights were NOT loaded; no files written.')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
=====================================================================================
CELL 3 — NOTEBOOK / ARTIFACT PROVENANCE AUDIT
=====================================================================================

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/test_predictions_712.csv
  size_bytes=62941
  modified=2026-09-30T16:34:27

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/v5_final_training_summary.json
  size_bytes=649
  modified=2026-09-29T04:23:10

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/best.pt
  size_bytes=4640037647
  modified=2026-09-29T04:20:44

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/last.pt
  size_bytes=4640037647
  modified=2026-09-29T04:25:51

[Training summary JSON]
model: V5
status: TRAINING_COMPLETE
num_epochs: 5
global_step: 1920
epoch: 5
best_val: 0.424518172663671
last_checkpoint: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/last.pt
best_checkpoint: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/best.pt
train_loss: [0.5731708970967303, 0.5046075203082849, 0.47171955251829634, 0.45422747778290645, 0.44715843725379206]
val_loss: [0.46700948011622856, 0.44155955633946825, 0.42823387978095856, 0.4258775923539091, 0.424518172663671]

Notebook cells: 162

--- CELL INDEX 0 | execution_count=None ---
Source matches: ['best.pt']
Output matches: []
  Lines 71-74:
    71:
    72: BEST_CKPT = (
    73:     f"{V4_DIR}/checkpoints/best.pt"
    74: )

--- CELL INDEX 1 | execution_count=None ---
Source matches: ['exact_generate', 'generate(', 'best.pt', 'load_state_dict']
Output matches: ['best.pt']
  Lines 88-92:
    88:
    89: BEST_CKPT = (
    90:     f"{V4_DIR}/checkpoints/best.pt"
    91: )
    92:
  Lines 1015-1019:
    1015: # ------------------------------------------------
    1016:
    1017: load_result = model.load_state_dict(
    1018:     E2["model_state"],
    1019:     strict=True,
  Lines 1029-1033:
    1029: )
    1030:
    1031: model.load_state_dict(
    1032:     E3["model_state"],
    1033:     strict=True,
  Lines 1100-1104:
    1100: # ================================================================
    1101:
    1102: model.load_state_dict(
    1103:     E2["model_state"],
    1104:     strict=True,
  Lines 1414-1418:
    1414:
    1415: @torch.no_grad()
    1416: def exact_generate(
    1417:     cond,
    1418:     max_new_tokens=20,
  ... source excerpts truncated
Relevant saved output:
    Best checkpoint       : PASS -> /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt
    source_v3_checkpoint: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt
  RuntimeError: Error(s) in loading state_dict for V4Model:

--- CELL INDEX 2 | execution_count=None ---
Source matches: ['load_state_dict']
Output matches: []
  Lines 86-90:
    86: # STRICT LOAD E2
    87: # ------------------------------------------------------------
    88: model.load_state_dict(E2["model_state"], strict=True)
    89:
    90: print("\n✓ E2 STRICT LOAD PASSED")
  Lines 93-97:
    93: # STRICT LOAD E3
    94: # ------------------------------------------------------------
    95: model.load_state_dict(E3["model_state"], strict=True)
    96:
    97: print("✓ E3 STRICT LOAD PASSED")

--- CELL INDEX 5 | execution_count=None ---
Source matches: ['load_state_dict']
Output matches: []
  Lines 278-282:
    278:     print("=" * 70)
    279:
    280:     model.load_state_dict(
    281:         ckpt["model_state"],
    282:         strict=True,

--- CELL INDEX 6 | execution_count=None ---
Source matches: ['load_state_dict']
Output matches: []
  Lines 57-61:
    57:     print("=" * 70)
    58:
    59:     model.load_state_dict(
    60:         ckpt["model_state"],
    61:         strict=True,

--- CELL INDEX 7 | execution_count=None ---
Source matches: ['to_csv(', 'load_state_dict']
Output matches: []
  Lines 38-42:
    38: )
    39:
    40: model.load_state_dict(E3["model_state"], strict=True)
    41: model.to(device)
    42: model.eval()
  Lines 348-352:
    348: )
    349:
    350: sensitivity_df.to_csv(
    351:     detail_path,
    352:     index=False,
  Lines 353-357:
    353: )
    354:
    355: summary_df.to_csv(
    356:     summary_path,
    357:     index=False,

--- CELL INDEX 9 | execution_count=None ---
Source matches: ['load_state_dict']
Output matches: []
  Lines 12-16:
    12: # ------------------------------------------------------------
    13:
    14: model.load_state_dict(
    15:     E3["model_state"],
    16:     strict=True,

--- CELL INDEX 10 | execution_count=None ---
Source matches: ['load_state_dict']
Output matches: []
  Lines 16-20:
    16: # ------------------------------------------------------------
    17:
    18: model.load_state_dict(
    19:     E3["model_state"],
    20:     strict=True,
Relevant saved output:
  KeyError: 'concept_targets'

--- CELL INDEX 23 | execution_count=None ---
Source matches: ['torch.save', 'load_state_dict']
Output matches: []
  Lines 165-169:
    165: # ------------------------------------------------------------
    166:
    167: torch.save(
    168:     checkpoint,
    169:     DRYRUN_PATH
  Lines 203-207:
    203: v5_restore = V5Model()
    204:
    205: v5_restore.load_state_dict(
    206:     loaded["model_state"],
    207:     strict=True,
  Lines 244-248:
    244: )
    245:
    246: optimizer_restore.load_state_dict(
    247:     loaded["optimizer_state"]
    248: )
  Lines 248-252:
    248: )
    249:
    250: scheduler_restore.load_state_dict(
    251:     loaded["scheduler_state"]
    252: )

--- CELL INDEX 24 | execution_count=None ---
Source matches: ['best.pt', 'last.pt']
Output matches: []
  Lines 260-264:
    260: }
    261:
    262: checkpoint_paths["last"] = os.path.join(CKPT_DIR, "last.pt")
    263: checkpoint_paths["best"] = os.path.join(CKPT_DIR, "best.pt")
    264:
  Lines 261-265:
    261:
    262: checkpoint_paths["last"] = os.path.join(CKPT_DIR, "last.pt")
    263: checkpoint_paths["best"] = os.path.join(CKPT_DIR, "best.pt")
    264:
    265: print()
Relevant saved output:
  AssertionError: FAIL: missing object `train_loader`

--- CELL INDEX 44 | execution_count=None ---
Source matches: []
Output matches: ['best.pt', 'last.pt']
Relevant saved output:
    checkpoint_best: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt
    checkpoint_last: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt
    source_v3_checkpoint: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt

--- CELL INDEX 52 | execution_count=None ---
Source matches: []
Output matches: ['best.pt', 'last.pt']
Relevant saved output:
      best.pt
      last.pt

--- CELL INDEX 53 | execution_count=None ---
Source matches: []
Output matches: ['generate(']
Relevant saved output:
    then generate(encoder_outputs=...)

--- CELL INDEX 71 | execution_count=None ---
Source matches: []
Output matches: ['best.pt']
Relevant saved output:
      f"{V4_DIR}/checkpoints/best.pt"
      raise KeyError(
      raise RuntimeError(
      raise RuntimeError(
      raise RuntimeError(
      raise RuntimeError(

--- CELL INDEX 72 | execution_count=None ---
Source matches: []
Output matches: ['best.pt']
Relevant saved output:
      f"{V4_DIR}/checkpoints/best.pt"
      raise KeyError(
      raise RuntimeError(
      raise RuntimeError(
      raise RuntimeError(
      raise RuntimeError(

--- CELL INDEX 75 | execution_count=None ---
Source matches: ['best.pt', 'load_state_dict']
Output matches: []
  Lines 33-37:
    33:     os.path.join(V4_CKPT_DIR, "epoch_03.pt"),
    34:     os.path.join(V4_CKPT_DIR, "epoch_03.pth"),
    35:     os.path.join(V4_CKPT_DIR, "best.pt"),
    36: ]
    37:
  Lines 137-141:
    137: # 5. Load compatible weights
    138: # -------------------------------------------------------------------------
    139: load_result = v5.load_state_dict(
    140:     compatible,
    141:     strict=False,
Relevant saved output:
  RuntimeError: Missing required V5 architecture object(s): ['V5Model']. Do NOT train yet. We need to restore the V5 class definition first.

--- CELL INDEX 77 | execution_count=None ---
Source matches: []
Output matches: ['best.pt', 'torch.save', 'load_state_dict']
Relevant saved output:
  torch.save(
  v5_restore.load_state_dict(
  optimizer_restore.load_state_dict(
  scheduler_restore.load_state_dict(
      raise RuntimeError(
      os.path.join(V4_CKPT_DIR, "best.pt"),
      raise FileNotFoundError(
  except TypeError as e:
      raise RuntimeError(
      raise RuntimeError("Unsupported V4 checkpoint format.")
  load_result = v5.load_state_dict(
      raise RuntimeError(

--- CELL INDEX 79 | execution_count=None ---
Source matches: []
Output matches: ['exact_generate', 'generate(', 'best.pt', 'load_state_dict']
Relevant saved output:
      f"{V4_DIR}/checkpoints/best.pt"
      f"{V4_DIR}/checkpoints/best.pt"
      raise KeyError(
  load_result = model.load_state_dict(
  model.load_state_dict(
  model.load_state_dict(
  def exact_generate(
      model.load_state_dict(
          pred_full = exact_generate(
              exact_generate(
              exact_generate(
              exact_generate(
  model.load_state_dict(
  model.load_state_dict(E2["model_state"], strict=True)
  model.load_state_dict(E3["model_state"], strict=True)

--- CELL INDEX 82 | execution_count=None ---
Source matches: ['load_state_dict']
Output matches: []
  Lines 208-212:
    208: # 9. Load only compatible weights
    209: # ------------------------------------------------------------------
    210: load_result = v5.load_state_dict(
    211:     compatible,
    212:     strict=False,
Relevant saved output:
  RuntimeError: Unexpectedly low compatible-key count: 394. Expected approximately 409 based on the audited V4/V5 architecture.

--- CELL INDEX 84 | execution_count=None ---
Source matches: ['load_state_dict']
Output matches: []
  Lines 93-97:
    93: print("\n[LOAD V4 -> V5]")
    94:
    95: load_result = v5.load_state_dict(
    96:     fresh_compatible,
    97:     strict=False,

--- CELL INDEX 95 | execution_count=None ---
Source matches: ['load_state_dict']
Output matches: []
  Lines 424-428:
    424: )
    425:
    426: test_optimizer.load_state_dict(
    427:     copy.deepcopy(optimizer_state)
    428: )
  Lines 428-432:
    428: )
    429:
    430: test_scheduler.load_state_dict(
    431:     copy.deepcopy(scheduler_state)
    432: )

--- CELL INDEX 96 | execution_count=None ---
Source matches: ['torch.save', 'load_state_dict']
Output matches: []
  Lines 262-266:
    262:     }
    263:
    264:     torch.save(
    265:         checkpoint,
    266:         path,
  Lines 305-309:
    305:         )
    306:
    307:     model.load_state_dict(
    308:         checkpoint["model_state"]
    309:     )
  Lines 309-313:
    309:     )
    310:
    311:     optimizer.load_state_dict(
    312:         checkpoint["optimizer_state"]
    313:     )
  Lines 313-317:
    313:     )
    314:
    315:     scheduler.load_state_dict(
    316:         checkpoint["scheduler_state"]
    317:     )
Relevant saved output:
  RuntimeError: Missing runtime objects: ['v5', 'optimizer_v5', 'scheduler_v5']

--- CELL INDEX 107 | execution_count=None ---
Source matches: ['load_state_dict']
Output matches: []
  Lines 472-476:
    472: )
    473:
    474: optimizer_v5_restored.load_state_dict(
    475:     optimizer_state_test
    476: )
  Lines 484-488:
    484: )
    485:
    486: scheduler_v5_restored.load_state_dict(
    487:     scheduler_state_test
    488: )

--- CELL INDEX 108 | execution_count=None ---
Source matches: ['torch.save', 'load_state_dict']
Output matches: []
  Lines 149-153:
    149: print("\n[SAVE]")
    150:
    151: torch.save(
    152:     checkpoint,
    153:     TEST_CHECKPOINT,
  Lines 229-233:
    229: )
    230:
    231: v5_restored.load_state_dict(
    232:     loaded["model_state"]
    233: )
  Lines 320-324:
    320: )
    321:
    322: optimizer_restored.load_state_dict(
    323:     loaded["optimizer_state"]
    324: )
  Lines 353-357:
    353: )
    354:
    355: scheduler_restored.load_state_dict(
    356:     loaded["scheduler_state"]
    357: )

--- CELL INDEX 126 | execution_count=1 ---
Source matches: ['best.pt', 'last.pt', 'torch.save', 'load_state_dict']
Output matches: []
  Lines 6-10:
    6: #   - every 48 optimizer steps
    7: #   - rolling checkpoint: resume_0.pt / resume_1.pt
    8: #   - last.pt
    9: #   - epoch_XX.pt
    10: #   - best.pt
  Lines 8-12:
    8: #   - last.pt
    9: #   - epoch_XX.pt
    10: #   - best.pt
    11: #
    12: # IMPORTANT:
  Lines 90-94:
    90:
    91: LAST_CKPT = (
    92:     V5_CKPT_DIR / "last.pt"
    93: )
    94:
  Lines 94-98:
    94:
    95: BEST_CKPT = (
    96:     V5_CKPT_DIR / "best.pt"
    97: )
    98:
  Lines 292-296:
    292:
    293:     # Write first
    294:     torch.save(
    295:         checkpoint,
    296:         tmp
  ... source excerpts truncated
Relevant saved output:
  NameError: name 'train_loader_v5' is not defined

--- CELL INDEX 127 | execution_count=3 ---
Source matches: ['best.pt', 'last.pt', 'torch.save', 'load_state_dict']
Output matches: []
  Lines 101-105:
    101:
    102: LAST_CKPT = (
    103:     V5_CKPT_DIR / "last.pt"
    104: )
    105:
  Lines 105-109:
    105:
    106: BEST_CKPT = (
    107:     V5_CKPT_DIR / "best.pt"
    108: )
    109:
  Lines 425-429:
    425:     )
    426:
    427:     torch.save(
    428:         checkpoint,
    429:         tmp_path
  Lines 560-564:
    560:     # --------------------------------------------------------
    561:
    562:     v5.load_state_dict(
    563:         checkpoint["model_state"],
    564:         strict=True,
  Lines 569-573:
    569:     # --------------------------------------------------------
    570:
    571:     optimizer_v5.load_state_dict(
    572:         checkpoint["optimizer_state"]
    573:     )
  ... source excerpts truncated
Relevant saved output:
  ValueError: Mountpoint must not already contain files

--- CELL INDEX 139 | execution_count=15 ---
Source matches: ['best.pt', 'last.pt', 'torch.save', 'load_state_dict']
Output matches: []
  Lines 22-26:
    22: #   2 rolling checkpoints
    23: #   epoch checkpoints
    24: #   best.pt
    25: #   last.pt
    26: # ============================================================
  Lines 23-27:
    23: #   epoch checkpoints
    24: #   best.pt
    25: #   last.pt
    26: # ============================================================
    27:
  Lines 159-163:
    159: LAST_CKPT = (
    160:     CKPT_DIR /
    161:     "last.pt"
    162: )
    163:
  Lines 164-168:
    164: BEST_CKPT = (
    165:     CKPT_DIR /
    166:     "best.pt"
    167: )
    168:
  Lines 1226-1230:
    1226:     )
    1227:
    1228:     torch.save(
    1229:         payload,
    1230:         tmp
  ... source excerpts truncated
Relevant saved output:
  AssertionError: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv

--- CELL INDEX 140 | execution_count=16 ---
Source matches: ['best.pt', 'last.pt', 'torch.save', 'load_state_dict']
Output matches: []
  Lines 49-53:
    49: )
    50:
    51: LAST_CKPT = V5_CKPT_DIR / "last.pt"
    52: BEST_CKPT = V5_CKPT_DIR / "best.pt"
    53:
  Lines 50-54:
    50:
    51: LAST_CKPT = V5_CKPT_DIR / "last.pt"
    52: BEST_CKPT = V5_CKPT_DIR / "best.pt"
    53:
    54:
  Lines 228-232:
    228:     # Atomic-ish replacement:
    229:     # write completely first, then replace target.
    230:     torch.save(
    231:         checkpoint,
    232:         tmp_path
  Lines 276-280:
    276:     assert set(checkpoint.keys()) == expected_keys
    277:
    278:     model.load_state_dict(
    279:         checkpoint["model_state"],
    280:         strict=True,
  Lines 281-285:
    281:     )
    282:
    283:     optimizer.load_state_dict(
    284:         checkpoint["optimizer_state"]
    285:     )
  ... source excerpts truncated
Relevant saved output:
  NameError: name 'train_loader_v5' is not defined

--- CELL INDEX 146 | execution_count=26 ---
Source matches: ['best.pt']
Output matches: []
  Lines 16-20:
    16:     "epoch_03.pt",
    17:     "epoch_02.pt",
    18:     "best.pt",
    19: }
    20:

--- CELL INDEX 147 | execution_count=29 ---
Source matches: ['best.pt', 'last.pt']
Output matches: []
  Lines 67-71:
    67:
    68:     # checkpoints
    69:     "best.pt",
    70:     "last.pt",
    71:     "epoch_01.pt",
  Lines 68-72:
    68:     # checkpoints
    69:     "best.pt",
    70:     "last.pt",
    71:     "epoch_01.pt",
    72:     "epoch_02.pt",

--- CELL INDEX 149 | execution_count=31 ---
Source matches: ['best.pt', 'last.pt']
Output matches: ['best.pt', 'last.pt']
  Lines 20-24:
    20:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv",
    21:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_config.json",
    22:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",
    23:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt",
    24:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_01.pt",
  Lines 21-25:
    21:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_config.json",
    22:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",
    23:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt",
    24:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_01.pt",
    25:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_02.pt",
  Lines 31-35:
    31:     # V3
    32:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3",
    33:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt",
    34:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/last.pt",
    35:
  Lines 32-36:
    32:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3",
    33:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt",
    34:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/last.pt",
    35:
    36:     # Structured
  Lines 75-79:
    75:     "epoch_02.pt",
    76:     "epoch_03.pt",
    77:     "best.pt",
    78:     "last.pt",
    79:     "v3_structured_targets_v2_2.csv",
  ... source excerpts truncated
Relevant saved output:
  MISSING /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt
  MISSING /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt
  MISSING /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt
  MISSING /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/last.pt

--- CELL INDEX 153 | execution_count=35 ---
Source matches: ['best.pt', 'last.pt']
Output matches: ['best.pt', 'last.pt']
  Lines 18-22:
    18:     "NoiSoi_Matching/baseline_model_v4/v4_config.json",
    19:     "NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt",
    20:     "NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",
    21:     "NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt",
    22:
  Lines 19-23:
    19:     "NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt",
    20:     "NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",
    21:     "NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt",
    22:
    23:     # Structured targets
Relevant saved output:
  FOUND       4425.07 MB    NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt
  FOUND       4425.07 MB    NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt


In [6]:
# CELL 2 — Review low-overlap cases (read-only)
from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import numpy as np

ROOT = '/content/drive/MyDrive/NoiSoi_Matching'
AUDIT = os.path.join(ROOT, 'baseline_model_v5', 'diagnostics', 'audit_20261015')

candidates = [
    os.path.join(AUDIT, 'low_overlap_image_metadata.csv'),
    os.path.join(AUDIT, 'text_overlap_audit.csv'),
    os.path.join(AUDIT, 'anatomy_error_stratification.csv'),
]

for path in candidates:
    print(f'{os.path.basename(path)}: {"FOUND" if os.path.exists(path) else "NOT FOUND"}')

low_path = candidates[0]
overlap_path = candidates[1]
anatomy_path = candidates[2]

if os.path.exists(overlap_path):
    df = pd.read_csv(overlap_path)
elif os.path.exists(anatomy_path):
    df = pd.read_csv(anatomy_path)
elif os.path.exists(low_path):
    df = pd.read_csv(low_path)
else:
    raise FileNotFoundError('Không tìm thấy các file audit đã dự kiến.')

print('\nShape:', df.shape)
print('Columns:', df.columns.tolist())

# Sort the weakest-overlap cases first, when the score exists.
score_col = next(
    (c for c in ['token_f1', 'f1', 'token_F1'] if c in df.columns),
    None
)
if score_col:
    df[score_col] = pd.to_numeric(df[score_col], errors='coerce')
    df = df.sort_values(score_col, ascending=True, na_position='last')

# Show only useful clinical/text fields; keep available anatomy fields.
preferred = [
    'case_id', 'prediction', 'ground_truth',
    'precision_tokens', 'recall_tokens', 'token_f1', 'exact_match',
    'gt_region_heuristic',
    'tai', 'hoc_mui', 'hong_mui',
    'hong_thanh_quan', 'hong_mieng', 'ly_do_noi_soi'
]
show_cols = [c for c in preferred if c in df.columns]

print('\n=== Lowest-overlap cases (up to 25) ===')
if show_cols:
    display(df[show_cols].head(25).fillna(''))
else:
    display(df.head(25).fillna(''))

print('\n=== Summary ===')
if score_col:
    print(df[score_col].describe().to_string())
if 'exact_match' in df.columns:
    print('\nExact-match distribution:')
    print(df['exact_match'].value_counts(dropna=False).to_string())

print('\nRead-only audit completed; no model training or checkpoint loading.')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
low_overlap_image_metadata.csv: NOT FOUND
text_overlap_audit.csv: NOT FOUND
anatomy_error_stratification.csv: NOT FOUND

FileNotFoundError: Không tìm thấy các file audit đã dự kiến.

In [7]:

# CELL 2A — Locate audit artifacts (read-only; no training)
from google.colab import drive
drive.mount('/content/drive')

import os

MYDRIVE = '/content/drive/MyDrive'
PROJECT = os.path.join(MYDRIVE, 'NoiSoi_Matching')

target_names = {
    'low_overlap_image_metadata.csv',
    'text_overlap_audit.csv',
    'anatomy_error_stratification.csv',
    'prediction_quality_audit.csv',
    'test_predictions_712.csv',
    'v5_final_training_summary.json',
}
skip_dirs = {
    '.ipynb_checkpoints', '__pycache__', '.Trash',
    'node_modules'
}

print('MyDrive exists:', os.path.isdir(MYDRIVE))
print('Project path exists:', os.path.isdir(PROJECT))

if os.path.isdir(PROJECT):
    search_roots = [PROJECT]
else:
    search_roots = [MYDRIVE]
    print('WARNING: Project folder not found at expected path; searching MyDrive.')

found = []
audit_dirs = []

for search_root in search_roots:
    for current, dirs, files in os.walk(search_root):
        dirs[:] = [d for d in dirs if d not in skip_dirs]

        if os.path.basename(current).startswith('audit_'):
            audit_dirs.append(current)

        for filename in files:
            if filename in target_names:
                path = os.path.join(current, filename)
                found.append(path)
                try:
                    stat = os.stat(path)
                    print(
                        f'FOUND: {path}\n'
                        f'  Size: {stat.st_size:,} bytes | '
                        f'Modified: {stat.st_mtime}'
                    )
                except OSError:
                    print('FOUND but metadata unavailable:', path)

print('\n=== Audit directories ===')
for path in sorted(set(audit_dirs)):
    print(path)

print('\n=== Result ===')
if found:
    print(f'Found {len(found)} target file(s).')
else:
    print('No target files found under the searched root.')
    print('No files were created, modified, or deleted.')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
MyDrive exists: True
Project path exists: True
FOUND: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/test_predictions_712.csv
  Size: 62,941 bytes | Modified: 1790786067.0
FOUND: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/prediction_quality_audit.csv
  Size: 79,960 bytes | Modified: 1791980392.0
FOUND: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/text_overlap_audit.csv
  Size: 140,287 bytes | Modified: 1791980891.0
FOUND: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/low_overlap_image_metadata.csv
  Size: 4,948 bytes | Modified: 1791980991.0
FOUND: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/anatomy_error_stratification.csv
  Size: 331,383 bytes | Modified: 1791981299.0
FOUND: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/v5_final_training_summary.json
  Size: 649 bytes | Modified: 1790655790.0

=== Audit directories ===
/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015

=== Result ===
Found 6 target file(s).

In [9]:

# CELL 2C — Fixed low-overlap review (read-only)
from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import numpy as np

ROOT = '/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5'

overlap_path = os.path.join(ROOT, 'text_overlap_audit.csv')
anatomy_path = os.path.join(ROOT, 'anatomy_error_stratification.csv')
low_path = os.path.join(ROOT, 'low_overlap_image_metadata.csv')

# Reload source files from disk; do not depend on partially modified variables.
df = pd.read_csv(overlap_path)
print('Overlap:', df.shape, '| columns:', df.columns.tolist())

if os.path.isfile(anatomy_path):
    anatomy = pd.read_csv(anatomy_path)
    print('\nAnatomy:', anatomy.shape, '| columns:', anatomy.columns.tolist())

    # Only join if both tables have the key.
    if 'case_id' in df.columns and 'case_id' in anatomy.columns:
        extra_cols = [
            c for c in [
                'gt_region_heuristic', 'tai', 'hoc_mui', 'hong_mui',
                'hong_thanh_quan', 'hong_mieng', 'ly_do_noi_soi'
            ]
            if c in anatomy.columns and c not in df.columns
        ]

        if extra_cols:
            anatomy_subset = anatomy[['case_id'] + extra_cols].copy()
            anatomy_subset = anatomy_subset.drop_duplicates(subset=['case_id'])
            df = df.merge(
                anatomy_subset,
                on='case_id',
                how='left',
                validate='one_to_one'
            )
            print('\nJoined anatomy fields:', extra_cols)
        else:
            print('\nNo additional anatomy columns available to join.')
    else:
        print('\nWARNING: case_id is missing from one table; skipped join.')

if 'token_f1' in df.columns:
    df['token_f1'] = pd.to_numeric(df['token_f1'], errors='coerce')
    df = df.sort_values('token_f1', ascending=True, na_position='last')

cols = [
    'case_id', 'prediction', 'ground_truth',
    'precision_tokens', 'recall_tokens', 'token_f1', 'exact_match',
    'gt_region_heuristic', 'tai', 'hoc_mui', 'hong_mui',
    'hong_thanh_quan', 'hong_mieng', 'ly_do_noi_soi'
]
cols = [c for c in cols if c in df.columns]

print('\n=== 25 LOWEST-OVERLAP CASES ===')
display(df[cols].head(25).fillna(''))

print('\n=== SUMMARY ===')
if 'token_f1' in df.columns:
    print(df['token_f1'].describe().to_string())
    print('Zero-F1 cases:', int(df['token_f1'].eq(0).sum()))

if 'exact_match' in df.columns:
    print('\nExact-match distribution:')
    print(df['exact_match'].value_counts(dropna=False).to_string())

if os.path.isfile(low_path):
    low = pd.read_csv(low_path)
    print('\n=== LOW-OVERLAP METADATA ===')
    print('Shape:', low.shape)
    print('Columns:', low.columns.tolist())
    display(low.head(10).fillna(''))

print('\nRead-only audit completed; no checkpoint loaded or files changed.')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Overlap: (712, 11) | columns: ['case_id', 'prediction', 'ground_truth', 'precision_tokens', 'recall_tokens', 'token_f1', 'pred_norm', 'gt_norm', 'exact_match', 'pred_token_count', 'gt_token_count']

Anatomy: (712, 24) | columns: ['case_id', 'prediction', 'ground_truth', 'precision_tokens', 'recall_tokens', 'token_f1', 'pred_norm', 'gt_norm', 'exact_match', 'pred_token_count', 'gt_token_count', 'tai', 'hoc_mui', 'hong_mui', 'hong_thanh_quan', 'hong_mieng', 'ly_do_noi_soi', 'tai__present', 'hoc_mui__present', 'hong_mui__present', 'hong_thanh_quan__present', 'hong_mieng__present', 'ly_do_noi_soi__present', 'gt_region_heuristic']

Joined anatomy fields: ['gt_region_heuristic', 'tai', 'hoc_mui', 'hong_mui', 'hong_thanh_quan', 'hong_mieng', 'ly_do_noi_soi']

=== 25 LOWEST-OVERLAP CASES ===

,case_id,prediction,ground_truth,precision_tokens,recall_tokens,token_f1,exact_match,gt_region_heuristic,tai,hoc_mui,hong_mui,hong_thanh_quan,hong_mieng,ly_do_noi_soi
665,17557.17557.0.17582,VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.,HÓC DỊ VẬT N1.,0.000000,0.000000,0.000000,False,Họng/thanh quản/dị vật,,,,"Thanh thiệt: hồng, láng. Dây thanh: trơn, láng...",Hai a-mi-đan: bên P có dị vật. Thành sau họng:...,Nuốt vướng sau ăn N1
672,17686.17686.0.17711,VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.,HÓC XƯƠNG CÁ N1 (ĐÃ LẤY).,0.000000,0.000000,0.000000,False,Họng/thanh quản/dị vật,,,,"Thanh thiệt: hồng, láng. Vùng đáy lưỡi: có xươ...",Hai a-mi-đan: không to. Thành sau họng: có hạt...,Nuốt vướng sau ăn N1
412,14927.14927.0.14946,VIÊM MŨI MẠN,"HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TA...",0.000000,0.000000,0.000000,False,Tai,,"Cuốn mũi: hông, gồ ghề. Khe mũi: thoáng, sạch ...",thoáng sạch,,,nặng hàm T
408,14900.14900.0.14919,VIÊM MŨI XOANG,"HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TA...",0.000000,0.000000,0.000000,False,Tai,P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.,"Cuốn mũi: hồng, láng. Khe mũi: thoáng, sạch Sà...",lỗ vòi nhĩ 2 bên thoáng sạch,,,ĐAU TAI P
112,11630.11630.0.11647,VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.,LIỆT DÂY THANH P,0.000000,0.000000,0.000000,False,Họng/thanh quản/dị vật,,,,"Thanh thiệt: hồng, láng. Dây thanh: trơn, láng...",Hai a-mi-đan: không to. Thành sau họng: trơn l...,NUỐT VƯỚNG
426,15036.15036.0.15055,VIÊM MŨI MẠN,"HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TA...",0.000000,0.000000,0.000000,False,Tai,,"Cuốn mũi: hông, gồ ghề. Khe mũi: thoáng, sạch ...",thoáng sạch,,,ĐAU HÀM T
461,15356.15356.0.15376,VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.,HÓC XƯƠNG CÁ (ĐÃ LẤY).,0.000000,0.000000,0.000000,False,Họng/thanh quản/dị vật,,,,"Đáy lưỡi: có xương cá. Thanh thiệt: hồng, láng...",Hai a-mi-đan: không to. Thành sau họng: có hạt...,NUỐT VƯỚNG SAU ĂN CÁ
337,14009.14009.0.14028,VIÊM MŨI MẠN,VA,0.000000,0.000000,0.000000,False,Mũi/xoang/VA,P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.,"Cuốn mũi: hồng, láng. Các khe mũi: thoáng, sạc...",VA độ II,,,Kiểm tra VA
506,16027.16027.0.16048,VIÊM MŨI MẠN,"HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TA...",0.000000,0.000000,0.000000,False,Tai,"P: ống tai ngoài thoáng sạch, màng nhĩ bóng sá...","Cuốn mũi: hồng, láng. Các khe mũi: thoáng, sạc...",lỗ vòi nhĩ 2 bên thoáng sạch,,,Ù tai 2 bên
586,16806.16806.0.16828,VIÊM MŨI MẠN,"HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TA...",0.000000,0.000000,0.000000,False,Tai,"P: ống tai ngoài thoáng sạch, màng nhĩ bóng sá...",,,,,NGỨA TAI 2 BÊN
510,16051.16051.0.16072,VIÊM MŨI MẠN,"HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TA...",0.000000,0.000000,0.000000,False,Tai,P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.,"Cuốn mũi: hồng, trơn láng Khe mũi: thoáng, sạc...",đọng nhầy trắng,,,CHÓNG MẶT
59,10854.10854.0.10869,VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.,A-MI-ĐAN QUÁ PHÁT HIỆN KHÔNG THẤY ĐIỂM CHẢY MÁ...,0.000000,0.000000,0.000000,False,Họng/thanh quản/dị vật,,,,,"Hai a-mi-đan: to độ III, bên P có điểm sung hu...",NGÁY
55,10783.10783.0.10798,VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.,HIỆN KHÔNG THẤY ĐIỂM CHẢY MÁU TRÊN NỘI SOI A-M...,0.000000,0.000000,0.000000,False,Họng/thanh quản/dị vật,,,,,"Hai a-mi-đan: độ III, bề mặt gồ ghề.",KHẠC MÁU
213,12668.12668.0.12686,VIÊM MŨI MẠN,HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI...,0.000000,0.000000,0.000000,False,Tai,P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.,"Cuốn mũi: hồng, gồ ghề. Các khe mũi: thoáng, s...",lỗ vòi nhĩ 2 bên thoáng sạch,,,ù tai p
232,12907.12907.0.12925,VIÊM MŨI MẠN,HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI...,0.000000,0.000000,0.000000,False,Tai,P: màng nhĩ bóng sáng. T: màng nhĩ đọng ít ráy...,"Cuốn mũi: hồng, láng. Các khe mũi: thoáng, sạc...",lỗ vòi nhĩ 2 bên thoáng sạch,,,đau tai T
226,12808.12808.0.12826,VIÊM MŨI MẠN,HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI...,0.000000,0.000000,0.000000,False,Tai,P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.,"Cuốn mũi: hồng, láng. Các khe mũi: thoáng, sạc...",lỗ vòi nhĩ 2 bên thoáng sạch,,,đau tai T
449,15264.15264.0.15284,VIÊM MŨI MẠN,"HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TA...",0.000000,0.000000,0.000000,False,Tai,"P: ống tai ngoài thoáng sạch, màng nhĩ dày. T:...","Cuốn mũi: hồng, láng. Các khe mũi: thoáng, sạc...",thoáng sạch,,,Ù TAI 2 BÊN
450,15284.15284.0.15304,VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.,HÓC XƯƠNG CÁ NGÀY 1 (ĐÃ LẤY),0.000000,0.000000,0.000000,False,Họng/thanh quản/dị vật,,,,"Thanh thiệt: hồng, láng.",A-mi-đan: bên T có xương cá (đã lấy),NUỐT VƯỚNG SAU ĂN
434,15066.15066.0.15085,VIÊM MŨI MẠN,"HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TA...",0.000000,0.000000,0.000000,False,Tai,"P: ống tai ngoài đọng ít ráy, màng nhĩ bóng sá...","Cuốn mũi: hồng, láng. Các khe mũi: thoáng, sạc...",thoáng sạch,,,Đau tai P
663,17546.17546.0.17571,VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.,HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ HỌNG - THANH ...,0.111111,0.076923,0.090909,False,Họng/thanh quản/dị vật,,,,"Thanh thiệt: hồng, láng. Dây thanh: trơn, láng...",Hai a-mi-đan: không to. Thành sau họng: có hạt...,
416,14950.14950.0.14969,VIÊM MŨI MẠN,"HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ MŨI XOANG, TA...",0.333333,0.062500,0.105263,False,Tai + Mũi/xoang/VA,"P: ống tai ngoài thoáng sạch, màng nhĩ bóng sá...","Cuốn mũi: hồng, láng. Các khe mũi: thoáng, sạc...",thoáng sạch,,,ho
154,12070.12070.0.12088,VIÊM MŨI MẠN,"HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ MŨI XOANG, TA...",0.333333,0.062500,0.105263,False,Tai + Mũi/xoang/VA,P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.,"Cuốn mũi: hồng, láng. Khe mũi: thoáng, sạch. S...",lỗ vòi nhĩ 2 bên thoáng sạch.,,,Đau trán + mắt T
525,16182.16182.0.16203,VIÊM MŨI MẠN,"HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ MŨI XOANG, TA...",0.333333,0.062500,0.105263,False,Tai + Mũi/xoang/VA,"P: ống tai ngoài thoáng sạch, màng nhĩ bóng sá...","Cuốn mũi: hồng, xuất tiết nhầy trắng. Các khe ...",lỗ vòi nhĩ 2 bên thoáng sạch,,,ĐAU ĐẦU P
433,15065.15065.0.15084,VIÊM MŨI MẠN,"HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ MŨI XOANG, TA...",0.333333,0.062500,0.105263,False,Tai + Mũi/xoang/VA,P: màng nhĩ bóng sáng. T: màng nhĩ bóng sáng.,"Cuốn mũi: hồng, láng. Sàn mũi: thoáng sạch",,,,HO
350,14156.14156.0.14175,VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP,VIÊM MŨI- HIỆN KHÔNG THẤY ĐIỂM CHẢY MÁU TRÊN N...,0.125000,0.090909,0.105263,False,Mũi/xoang/VA,"T+P: ống tai ngoài nhiều ráy, sau lấy, màng nh...",Vách ngăn: sung huyết điểm mạch 2 bên Cuốn mũi...,,,,Ho

=== SUMMARY ===
count    712.000000
mean       0.609702
std        0.284208
min        0.000000
25%        0.375000
50%        0.666667
75%        0.800000
max        1.000000
Zero-F1 cases: 19

Exact-match distribution:
exact_match
False    577
True     135

=== LOW-OVERLAP METADATA ===
Shape: (20, 11)
Columns: ['case_id', 'prediction', 'ground_truth', 'precision_tokens', 'recall_tokens', 'token_f1', 'pred_norm', 'gt_norm', 'exact_match', 'pred_token_count', 'gt_token_count']

,case_id,prediction,ground_truth,precision_tokens,recall_tokens,token_f1,pred_norm,gt_norm,exact_match,pred_token_count,gt_token_count
0,17557.17557.0.17582,VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.,HÓC DỊ VẬT N1.,0.0,0.0,0.0,VIÊM HỌNG MẠN THEO DÕI TRÀO NGƯỢC DỊCH VỊ,HÓC DỊ VẬT N1,False,9,4
1,17686.17686.0.17711,VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.,HÓC XƯƠNG CÁ N1 (ĐÃ LẤY).,0.0,0.0,0.0,VIÊM HỌNG MẠN THEO DÕI TRÀO NGƯỢC DỊCH VỊ,HÓC XƯƠNG CÁ N1 ĐÃ LẤY,False,9,6
2,14927.14927.0.14946,VIÊM MŨI MẠN,"HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TA...",0.0,0.0,0.0,VIÊM MŨI MẠN,HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI...,False,3,14
3,14900.14900.0.14919,VIÊM MŨI XOANG,"HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TA...",0.0,0.0,0.0,VIÊM MŨI XOANG,HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI...,False,3,14
4,11630.11630.0.11647,VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.,LIỆT DÂY THANH P,0.0,0.0,0.0,VIÊM HỌNG MẠN THEO DÕI TRÀO NGƯỢC DỊCH VỊ,LIỆT DÂY THANH P,False,9,4
5,15036.15036.0.15055,VIÊM MŨI MẠN,"HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TA...",0.0,0.0,0.0,VIÊM MŨI MẠN,HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI...,False,3,14
6,15356.15356.0.15376,VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.,HÓC XƯƠNG CÁ (ĐÃ LẤY).,0.0,0.0,0.0,VIÊM HỌNG MẠN THEO DÕI TRÀO NGƯỢC DỊCH VỊ,HÓC XƯƠNG CÁ ĐÃ LẤY,False,9,5
7,14009.14009.0.14028,VIÊM MŨI MẠN,VA,0.0,0.0,0.0,VIÊM MŨI MẠN,VA,False,3,1
8,16027.16027.0.16048,VIÊM MŨI MẠN,"HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TA...",0.0,0.0,0.0,VIÊM MŨI MẠN,HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI...,False,3,14
9,16806.16806.0.16828,VIÊM MŨI MẠN,"HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI, TA...",0.0,0.0,0.0,VIÊM MŨI MẠN,HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI...,False,3,14

Read-only audit completed; no checkpoint loaded or files changed.

In [10]:

# CELL 3A — Trace inference source and prediction export (read-only)
from google.colab import drive
drive.mount('/content/drive')

import os
import json
import re

ROOT = '/content/drive/MyDrive/NoiSoi_Matching'
NB_PATH = '/content/drive/MyDrive/Colab Notebooks/25sep.ipynb'

patterns = [
    'test_predictions_712.csv',
    'test_predictions',
    'prediction_path',
    'model.generate',
    'generate(',
    'best.pt',
    'last.pt',
    'torch.load',
    'load_state_dict',
    'save_pretrained',
    'prediction.to_csv',
    'predictions.to_csv',
]

def scan_text(label, text, max_hits=8):
    hits = []
    lines = text.splitlines()
    for i, line in enumerate(lines, start=1):
        if any(p.lower() in line.lower() for p in patterns):
            hits.append((i, line.strip()[:240]))
    if hits:
        print(f'\n--- {label}: {len(hits)} matching lines ---')
        for line_no, line in hits[:max_hits]:
            print(f'{line_no}: {line}')
        if len(hits) > max_hits:
            print(f'... {len(hits) - max_hits} additional matches omitted')
    return len(hits)

print('=== 1. Notebook source ===')
if os.path.isfile(NB_PATH):
    with open(NB_PATH, 'r', encoding='utf-8') as f:
        nb = json.load(f)

    total_hits = 0
    for idx, cell in enumerate(nb.get('cells', [])):
        source = cell.get('source', [])
        if isinstance(source, list):
            source = ''.join(source)
        if source:
            total_hits += scan_text(
                f'Cell {idx} (execution_count={cell.get("execution_count")})',
                source,
                max_hits=5
            )
    print('\nTotal matching source lines across notebook cells:', total_hits)
else:
    print('Notebook not found at expected path:', NB_PATH)

print('\n=== 2. Project Python scripts ===')
script_count = 0
script_hits = 0

for current, dirs, files in os.walk(ROOT):
    dirs[:] = [
        d for d in dirs
        if d not in {'.ipynb_checkpoints', '__pycache__', '.git'}
    ]
    for filename in files:
        if filename.endswith('.py'):
            script_count += 1
            path = os.path.join(current, filename)
            try:
                with open(path, 'r', encoding='utf-8', errors='replace') as f:
                    text = f.read()
                hits = scan_text(path, text, max_hits=8)
                script_hits += hits
            except OSError as e:
                print('Could not read:', path, str(e))

print('\nPython scripts scanned:', script_count)
print('Matching source lines in scripts:', script_hits)

print('\n=== 3. Training summary metadata ===')
summary_path = os.path.join(
    ROOT, 'baseline_model_v5', 'diagnostics', 'v5_final_training_summary.json'
)
if os.path.isfile(summary_path):
    with open(summary_path, 'r', encoding='utf-8') as f:
        summary = json.load(f)
    print(json.dumps(summary, ensure_ascii=False, indent=2))
else:
    print('Training summary not found.')

print('\nRead-only trace finished; no checkpoint loaded and no files modified.')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
=== 1. Notebook source ===

--- Cell 0 (execution_count=None): 1 matching lines ---
73: f"{V4_DIR}/checkpoints/best.pt"

--- Cell 1 (execution_count=None): 13 matching lines ---
90: f"{V4_DIR}/checkpoints/best.pt"
988: E2 = torch.load(
994: E3 = torch.load(
1017: load_result = model.load_state_dict(
1031: model.load_state_dict(
... 8 additional matches omitted

--- Cell 2 (execution_count=None): 2 matching lines ---
88: model.load_state_dict(E2["model_state"], strict=True)
95: model.load_state_dict(E3["model_state"], strict=True)

--- Cell 5 (execution_count=None): 1 matching lines ---
280: model.load_state_dict(

--- Cell 6 (execution_count=None): 1 matching lines ---
59: model.load_state_dict(

--- Cell 7 (execution_count=None): 1 matching lines ---
40: model.load_state_dict(E3["model_state"], strict=True)

--- Cell 9 (execution_count=None): 1 matching lines ---
14: model.load_state_dict(

--- Cell 10 (execution_count=None): 1 matching lines ---
18: model.load_state_dict(

--- Cell 23 (execution_count=None): 4 matching lines ---
188: loaded = torch.load(
205: v5_restore.load_state_dict(
246: optimizer_restore.load_state_dict(
250: scheduler_restore.load_state_dict(

--- Cell 24 (execution_count=None): 2 matching lines ---
262: checkpoint_paths["last"] = os.path.join(CKPT_DIR, "last.pt")
263: checkpoint_paths["best"] = os.path.join(CKPT_DIR, "best.pt")

--- Cell 54 (execution_count=None): 1 matching lines ---
21: ckpt = torch.load(

--- Cell 75 (execution_count=None): 3 matching lines ---
35: os.path.join(V4_CKPT_DIR, "best.pt"),
89: ckpt = torch.load(
139: load_result = v5.load_state_dict(

--- Cell 82 (execution_count=None): 2 matching lines ---
105: checkpoint = torch.load(
210: load_result = v5.load_state_dict(

--- Cell 84 (execution_count=None): 1 matching lines ---
95: load_result = v5.load_state_dict(

--- Cell 95 (execution_count=None): 2 matching lines ---
426: test_optimizer.load_state_dict(
430: test_scheduler.load_state_dict(

--- Cell 96 (execution_count=None): 4 matching lines ---
278: checkpoint = torch.load(
307: model.load_state_dict(
311: optimizer.load_state_dict(
315: scheduler.load_state_dict(

--- Cell 97 (execution_count=None): 1 matching lines ---
165: checkpoint = torch.load(

--- Cell 104 (execution_count=None): 2 matching lines ---
66: v4_ckpt = torch.load(
493: v4_ckpt_after = torch.load(

--- Cell 105 (execution_count=None): 1 matching lines ---
7: v4_ckpt_after = torch.load(

--- Cell 106 (execution_count=None): 2 matching lines ---
217: v4_ckpt = torch.load(
433: v4_check_after = torch.load(

--- Cell 107 (execution_count=None): 2 matching lines ---
474: optimizer_v5_restored.load_state_dict(
486: scheduler_v5_restored.load_state_dict(

--- Cell 108 (execution_count=None): 4 matching lines ---
183: loaded = torch.load(
231: v5_restored.load_state_dict(
322: optimizer_restored.load_state_dict(
355: scheduler_restored.load_state_dict(

--- Cell 116 (execution_count=8): 1 matching lines ---
49: v4_ckpt = torch.load(

--- Cell 126 (execution_count=1): 16 matching lines ---
8: #   - last.pt
10: #   - best.pt
92: V5_CKPT_DIR / "last.pt"
96: V5_CKPT_DIR / "best.pt"
316: ckpt = torch.load(
... 11 additional matches omitted

--- Cell 127 (execution_count=3): 9 matching lines ---
103: V5_CKPT_DIR / "last.pt"
107: V5_CKPT_DIR / "best.pt"
448: ckpt = torch.load(
547: checkpoint = torch.load(
562: v5.load_state_dict(
... 4 additional matches omitted

--- Cell 132 (execution_count=8): 1 matching lines ---
56: v4_ckpt = torch.load(

--- Cell 138 (execution_count=14): 1 matching lines ---
476: v4_ckpt = torch.load(

--- Cell 139 (execution_count=15): 11 matching lines ---
24: #   best.pt
25: #   last.pt
161: "last.pt"
166: "best.pt"
1247: ckpt = torch.load(
... 6 additional matches omitted

--- Cell 140 (execution_count=16): 14 matching lines ---
51: LAST_CKPT = V5_CKPT_DIR / "last.pt"
52: BEST_CKPT = V5_CKPT_DIR / "best.pt"
259: checkpoint = torch.load(
278: model.load_state_dict(
283: optimizer.load_state_dict(
... 9 additional matches omitted

--- Cell 146 (execution_count=26): 1 matching lines ---
18: "best.pt",

--- Cell 147 (execution_count=29): 2 matching lines ---
69: "best.pt",
70: "last.pt",

--- Cell 149 (execution_count=31): 6 matching lines ---
22: "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",
23: "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt",
33: "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt",
34: "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/last.pt",
77: "best.pt",
... 1 additional matches omitted

--- Cell 153 (execution_count=35): 2 matching lines ---
20: "NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",
21: "NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt",

--- Cell 155 (execution_count=37): 2 matching lines ---
22: f"{ROOT}/baseline_model_v4/checkpoints/best.pt",
25: f"{ROOT}/baseline_model_v4/checkpoints/last.pt",

--- Cell 161 (execution_count=43): 1 matching lines ---
62: f"{ROOT}/baseline_model_v4/checkpoints/best.pt",

Total matching source lines across notebook cells: 119

=== 2. Project Python scripts ===

Python scripts scanned: 0
Matching source lines in scripts: 0

=== 3. Training summary metadata ===
{
  "model": "V5",
  "status": "TRAINING_COMPLETE",
  "num_epochs": 5,
  "global_step": 1920,
  "epoch": 5,
  "next_batch": 0,
  "best_val": 0.424518172663671,
  "train_loss": [
    0.5731708970967303,
    0.5046075203082849,
    0.47171955251829634,
    0.45422747778290645,
    0.44715843725379206
  ],
  "val_loss": [
    0.46700948011622856,
    0.44155955633946825,
    0.42823387978095856,
    0.4258775923539091,
    0.424518172663671
  ],
  "last_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/last.pt",
  "best_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/best.pt"
}

Read-only trace finished; no checkpoint loaded and no files modified.

In [11]:

# CELL 3B — Inspect likely inference/export code (read-only)
from google.colab import drive
drive.mount('/content/drive')

import json
import os

NB_PATH = '/content/drive/MyDrive/Colab Notebooks/25sep.ipynb'

if not os.path.isfile(NB_PATH):
    raise FileNotFoundError(f'Notebook not found: {NB_PATH}')

with open(NB_PATH, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Terms that can identify inference, decoding, evaluation, and CSV export.
terms = [
    'test_predictions', 'to_csv', 'test_loader', 'val_loader',
    'model.generate', 'batch_decode', 'tokenizer.decode',
    'model.eval()', 'torch.no_grad', 'prediction',
    'ground_truth', 'argmax', 'generate(', 'decode(',
    'test_predictions_712'
]

# Prioritize cells that appear relevant from the earlier scan,
# while also searching every cell for prediction/export terms.
priority_cells = {
    0, 1, 2, 23, 24, 54, 75, 82, 84,
    126, 127, 139, 140
}

def get_source(cell):
    source = cell.get('source', [])
    return ''.join(source) if isinstance(source, list) else str(source)

def matching_lines(source):
    lines = source.splitlines()
    return [
        i for i, line in enumerate(lines)
        if any(term.lower() in line.lower() for term in terms)
    ]

shown = set()
print('Notebook cells:', len(nb.get('cells', [])))

# First: show concise context around relevant lines in priority cells.
print('\n=== PRIORITY CELLS ===')
for idx in sorted(priority_cells):
    cells = nb.get('cells', [])
    if idx >= len(cells):
        continue

    cell = cells[idx]
    source = get_source(cell)
    hits = matching_lines(source)
    if not hits:
        continue

    print(
        f'\n--- CELL {idx} | type={cell.get("cell_type")} | '
        f'execution_count={cell.get("execution_count")} | '
        f'{len(source.splitlines())} source lines ---'
    )

    printed = set()
    for hit in hits[:12]:
        start = max(0, hit - 3)
        end = min(len(source.splitlines()), hit + 4)
        lines = source.splitlines()
        for line_idx in range(start, end):
            if line_idx not in printed:
                print(f'{line_idx + 1}: {lines[line_idx][:220]}')
                printed.add(line_idx)
        print('...')
    shown.add(idx)

# Second: report other cells with relevant inference/export code.
print('\n=== OTHER CELLS WITH INFERENCE/EXPORT TERMS ===')
for idx, cell in enumerate(nb.get('cells', [])):
    if idx in shown:
        continue
    source = get_source(cell)
    hits = matching_lines(source)
    if hits:
        print(
            f'Cell {idx} | type={cell.get("cell_type")} | '
            f'execution_count={cell.get("execution_count")} | '
            f'lines={len(source.splitlines())} | '
            f'hits={len(hits)}'
        )
        for hit in hits[:5]:
            print(f'  {hit + 1}: {source.splitlines()[hit].strip()[:200]}')

# Finally: inspect saved outputs only for clues about prediction/export.
print('\n=== SAVED OUTPUT CLUES ===')
output_terms = [
    'test_predictions_712.csv', 'to_csv', 'prediction saved',
    'predictions saved', 'test exact match', 'generating predictions',
    'inference complete'
]
output_count = 0

for idx, cell in enumerate(nb.get('cells', [])):
    for output in cell.get('outputs', []):
        text_parts = []
        if 'text' in output:
            value = output['text']
            text_parts.append(''.join(value) if isinstance(value, list) else str(value))
        data = output.get('data', {})
        if 'text/plain' in data:
            value = data['text/plain']
            text_parts.append(''.join(value) if isinstance(value, list) else str(value))

        output_text = '\n'.join(text_parts)
        matching = [
            line for line in output_text.splitlines()
            if any(term.lower() in line.lower() for term in output_terms)
        ]
        if matching:
            output_count += len(matching)
            print(f'\nCell {idx} saved output:')
            for line in matching[:5]:
                print(' ', line[:240])

print('\nSaved-output clue lines:', output_count)
print('\nInspection complete. No notebook cells executed and no files modified.')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Notebook cells: 162

=== PRIORITY CELLS ===

--- CELL 1 | type=code | execution_count=None | 1914 source lines ---
656:     max_target_length=96,
657: )
658:
659: val_loader = DataLoader(
660:     val_dataset,
661:     batch_size=4,
662:     shuffle=False,
...
673: )
674:
675: print(
676:     "val_loader batches:",
677:     len(val_loader)
678: )
679:
...
680: assert len(val_dataset) == 756
...
681: assert len(val_loader) == 189
682:
683:
684: # ================================================================
...
937:
938: model = V4Model().to(device)
939:
940: model.eval()
941:
942: print(
943:     "Model device:",
...
1053:
1054: print("\nDATASET SANITY CHECK")
1055:
1056: batch0 = next(iter(val_loader))
1057:
1058: print(
1059:     "pixel_values:",
...
1104:     strict=True,
1105: )
1106:
1107: model.eval()
1108:
1109: model_snapshot = {
1110:     k: v.detach().cpu().clone()
...
1116: # SAFE DECODE
1117: # ================================================================
1118:
1119: def safe_decode(ids):
1120:
1121:     if torch.is_tensor(ids):
1122:         ids = ids.detach().cpu().tolist()
...
1128:         for x in ids
1129:     ]
1130:
1131:     return tokenizer.decode(
1132:         ids,
1133:         skip_special_tokens=True,
1134:     ).strip()
...
1138: # EXACT V4 CONDITIONING
1139: # ================================================================
1140:
1141: @torch.no_grad()
1142: def exact_v4_conditioning(
1143:     pixel_values,
1144:     image_mask,
...
1278:     )
1279:
1280:     # ------------------------------------------------
1281:     # HARD PREDICTIONS
1282:     # EXACT
1283:     # ------------------------------------------------
1284:
...
1412: # EXACT GENERATION
1413: # ================================================================
1414:
1415: @torch.no_grad()
1416: def exact_generate(
1417:     cond,
1418:     max_new_tokens=20,
...

--- CELL 24 | type=code | execution_count=None | 332 source lines ---
90: required_objects = [
91:     "v5",
92:     "train_loader",
93:     "val_loader",
94: ]
95:
96: for name in required_objects:
...
108:     f"expected {TRAIN_BATCHES}"
109: )
110:
111: assert len(val_loader) > 0, "FAIL: val_loader is empty"
112:
113: print(f"PASS: train batches = {len(train_loader)}")
114: print(f"PASS: val batches   = {len(val_loader)}")
...
115:
116:
117: # ------------------------------------------------------------
...

--- CELL 126 | type=code | execution_count=1 | 1348 source lines ---
13: # Run after runtime reconnect AND after restoring:
14: #   v5
15: #   train_loader_v5
16: #   val_loader_v5
17: #   structured_targets_v5
18: #   optimizer/scheduler dependencies
19: # ============================================================
...
111: assert V5_ROOT.name == "baseline_model_v5"
112:
113: assert len(train_loader_v5) == 1535
114: assert len(val_loader_v5) == 189
115:
116: assert EPOCHS == 5
117: assert GRAD_ACCUM == 4
...
971:
972:     val_count = 0
973:
974:     with torch.no_grad():
975:
976:         for batch in tqdm(
977:             val_loader_v5,
...
978:             total=len(val_loader_v5),
979:             desc=f"Val {epoch}/{EPOCHS}",
980:         ):
...
981:
...

--- CELL 127 | type=code | execution_count=3 | 1426 source lines ---
179: required_objects = [
180:     "v5",
181:     "train_loader_v5",
182:     "val_loader_v5",
183:     "structured_targets_v5",
184: ]
185:
...
221: ) == 1535
222:
223: assert len(
224:     val_loader_v5
225: ) == 189
226:
227: assert (
...
1100:     val_sum = 0.0
1101:     val_count = 0
1102:
1103:     with torch.no_grad():
1104:
1105:         for batch in tqdm(
1106:             val_loader_v5,
...
1107:             total=len(val_loader_v5),
1108:             desc=f"Val {epoch}/{EPOCHS}",
1109:         ):
...
1110:
...

--- CELL 139 | type=code | execution_count=15 | 2121 source lines ---
880: # 16. VALIDATION LOADER
881: # ============================================================
882:
883: val_loader_v5 = DataLoader(
884:     val_dataset_v5,
885:     batch_size=BATCH_SIZE,
886:     shuffle=False,
...
889:     collate_fn=collate_v5,
890: )
891:
892: test_loader_v5 = DataLoader(
893:     test_dataset_v5,
894:     batch_size=BATCH_SIZE,
895:     shuffle=False,
...
1821:     val_sum = 0.0
1822:     val_count = 0
1823:
1824:     with torch.no_grad():
1825:
1826:         for batch in tqdm(
1827:             val_loader_v5,
...
1828:             total=len(val_loader_v5),
1829:             desc=f"Val {epoch}/{EPOCHS}",
1830:         ):
...
1831:
...

--- CELL 140 | type=code | execution_count=16 | 1154 source lines ---
60: assert device.type == "cuda"
61:
62: assert len(train_loader_v5) == 1535
63: assert len(val_loader_v5) == 189
64:
65: assert EPOCHS == 5
66: assert GRAD_ACCUM == 4
...
745:
746:     val_batches_seen = 0
747:
748:     with torch.no_grad():
749:
750:         for batch in tqdm(
751:             val_loader_v5,
...
752:             total=len(val_loader_v5),
753:             desc=f"Validation {epoch}/{EPOCHS}",
754:         ):
...
755:
...

=== OTHER CELLS WITH INFERENCE/EXPORT TERMS ===
Cell 3 | type=code | execution_count=None | lines=68 | hits=1
  13: model.eval()
Cell 4 | type=code | execution_count=None | lines=32 | hits=3
  5: def safe_decode(token_ids):
  16: return tokenizer.decode(
  27: test_text = safe_decode([tokenizer.eos_token_id])
Cell 5 | type=code | execution_count=None | lines=445 | hits=7
  12: model.eval()
  19: @torch.no_grad()
  165: @torch.no_grad()
  187: @torch.no_grad()
  214: next_token = torch.argmax(
Cell 6 | type=code | execution_count=None | lines=233 | hits=15
  5: @torch.no_grad()
  37: token = tokenizer.decode(
  64: model.eval()
  127: # Does argmax change?
  128: full_argmax = int(torch.argmax(full))
Cell 7 | type=code | execution_count=None | lines=368 | hits=16
  22: "val_loader",
  35: assert len(val_loader.dataset) == 756, (
  37: f"found {len(val_loader.dataset)}"
  42: model.eval()
  47: print("Validation cases:", len(val_loader.dataset))
Cell 9 | type=code | execution_count=None | lines=190 | hits=2
  19: model.eval()
  66: with torch.no_grad():
Cell 10 | type=code | execution_count=None | lines=389 | hits=2
  22: model.eval()
  29: batch = next(iter(val_loader))
Cell 11 | type=code | execution_count=None | lines=47 | hits=1
  6: batch = next(iter(val_loader))
Cell 12 | type=code | execution_count=None | lines=224 | hits=1
  178: model.eval()
Cell 14 | type=code | execution_count=None | lines=259 | hits=1
  15: batch = next(iter(val_loader))
Cell 16 | type=code | execution_count=None | lines=203 | hits=1
  56: # 4. Structured prediction heads
Cell 17 | type=code | execution_count=None | lines=84 | hits=1
  8: with torch.no_grad():
Cell 25 | type=code | execution_count=None | lines=52 | hits=2
  10: "val_loader",
  11: "test_loader",
Cell 26 | type=code | execution_count=None | lines=73 | hits=3
  57: print("val_loader class  :", type(val_loader))
  58: print("val_loader len    :", len(val_loader))
  62: batch = next(iter(val_loader))
Cell 27 | type=code | execution_count=None | lines=79 | hits=3
  55: print("val_loader class  :", type(val_loader))
  56: print("val_loader len    :", len(val_loader))
  61: batch = next(iter(val_loader))
Cell 65 | type=code | execution_count=None | lines=223 | hits=1
  16: "val_loader",
Cell 69 | type=code | execution_count=None | lines=448 | hits=4
  378: val_loader_v5 = DataLoader(
  389: print("Val batches  :", len(val_loader_v5))
  392: assert len(val_loader_v5) == 189
  440: print("PASS: Val loader    =", len(val_loader_v5), "batches")
Cell 73 | type=code | execution_count=None | lines=523 | hits=4
  450: val_loader_v5 = DataLoader(
  460: assert len(val_loader_v5) == 189
  464: print("Val batches  :", len(val_loader_v5))
  516: print("PASS: Val loader    =", len(val_loader_v5))
Cell 74 | type=code | execution_count=None | lines=700 | hits=2
  51: "val_loader_v5",
  523: with torch.no_grad():
Cell 81 | type=code | execution_count=None | lines=373 | hits=2
  121: # Structured prediction heads
  179: # Structured prediction
Cell 85 | type=code | execution_count=None | lines=687 | hits=2
  24: "val_loader_v5",
  459: with torch.no_grad():
Cell 92 | type=code | execution_count=None | lines=672 | hits=2
  22: "val_loader_v5",
  430: with torch.no_grad():
Cell 93 | type=code | execution_count=None | lines=233 | hits=1
  97: with torch.no_grad():
Cell 97 | type=code | execution_count=None | lines=541 | hits=1
  228: with torch.no_grad():
Cell 104 | type=code | execution_count=None | lines=602 | hits=1
  355: with torch.no_grad():
Cell 106 | type=code | execution_count=None | lines=479 | hits=1
  347: with torch.no_grad():
Cell 116 | type=code | execution_count=8 | lines=257 | hits=2
  157: with torch.no_grad():
  175: with torch.no_grad():
Cell 118 | type=code | execution_count=10 | lines=208 | hits=2
  73: with torch.no_grad():
  99: with torch.no_grad():
Cell 123 | type=code | execution_count=15 | lines=398 | hits=6
  231: val_loader_v5 = DataLoader(
  241: test_loader_v5 = DataLoader(
  265: len(val_loader_v5)
  270: len(test_loader_v5)
  274: assert len(val_loader_v5) == 189
Cell 124 | type=code | execution_count=16 | lines=315 | hits=1
  86: with torch.no_grad():
Cell 130 | type=code | execution_count=6 | lines=191 | hits=3
  37: "val_loader_v5",
  102: len(val_loader_v5)
  106: assert len(val_loader_v5) == 189
Cell 132 | type=code | execution_count=8 | lines=363 | hits=1
  237: with torch.no_grad():
Cell 138 | type=code | execution_count=14 | lines=1021 | hits=1
  847: with torch.no_grad():
Cell 144 | type=code | execution_count=24 | lines=319 | hits=3
  299: val_loader_v5 = DataLoader(
  312: print("Val batches  :", len(val_loader_v5))
  317: assert len(val_loader_v5) == 189

=== SAVED OUTPUT CLUES ===

Saved-output clue lines: 0

Inspection complete. No notebook cells executed and no files modified.

In [12]:

from google.colab import drive
drive.mount('/content/drive')

import json, re
from pathlib import Path

NB_PATH = Path('/content/drive/MyDrive/Colab Notebooks/25sep.ipynb')
assert NB_PATH.exists(), f"Không tìm thấy notebook: {NB_PATH}"

with NB_PATH.open('r', encoding='utf-8') as f:
    nb = json.load(f)

cells = nb.get('cells', [])

# Từ khóa phân biệt nạp model, inference và xuất file
patterns = {
    "checkpoint_load": re.compile(
        r'torch\.load|load_state_dict|from_pretrained|'
        r'best\.pt|last\.pt|checkpoint|ckpt_path|resume_from',
        re.I
    ),
    "inference": re.compile(
        r'\.generate\(|model\.eval\(|generate\(|'
        r'test_loader|test_dataset|argmax|beam_search|'
        r'greedy|safe_decode|tokenizer\.decode|'
        r'prediction\s*=|predictions\.append',
        re.I
    ),
    "export": re.compile(
        r'test_predictions_712|to_csv|to_json|'
        r'write_csv|prediction_path|output_path|'
        r'csv_path|DataFrame\(',
        re.I
    )
}

priority = [116, 118, 123, 124, 130, 138, 144]
print(f"Notebook: {NB_PATH}")
print(f"Tổng số cells: {len(cells)}")
print("\n" + "=" * 90)
print("PHẦN A — CÁC CELL CẦN KIỂM TRA")
print("=" * 90)

for idx in priority:
    if idx >= len(cells):
        continue

    cell = cells[idx]
    source = ''.join(cell.get('source', []))
    lines = source.splitlines()
    print(f"\n--- CELL {idx} | type={cell.get('cell_type')} "
          f"| execution_count={cell.get('execution_count')} "
          f"| source_lines={len(lines)} ---")

    # In các dòng liên quan và ngữ cảnh xung quanh
    hits = set()
    for line_no, line in enumerate(lines):
        if any(p.search(line) for p in patterns.values()):
            for j in range(max(0, line_no - 2),
                           min(len(lines), line_no + 3)):
                hits.add(j)

    if hits:
        prev = -2
        for j in sorted(hits):
            if j > prev + 1:
                print("   ...")
            print(f"{j+1:4}: {lines[j]}")
            prev = j
    else:
        print("(Không thấy từ khóa liên quan trong source.)")

    # Output đã lưu của cell — không thực thi lại
    outputs = cell.get('outputs', [])
    print(f"\n[SAVED OUTPUTS: {len(outputs)}]")
    for oi, out in enumerate(outputs):
        typ = out.get('output_type', '')
        text_parts = []
        if 'text' in out:
            text_parts.append(''.join(out['text']))
        data = out.get('data', {})
        for mime in ('text/plain', 'text/markdown'):
            if mime in data:
                value = data[mime]
                text_parts.append(''.join(value) if isinstance(value, list)
                                  else str(value))
        if out.get('ename'):
            text_parts.append(
                f"ERROR: {out.get('ename')}: {out.get('evalue', '')}"
            )
        saved_text = '\n'.join(text_parts).strip()
        if saved_text:
            print(f"[output {oi} | {typ}]")
            print(saved_text[:1800])
            if len(saved_text) > 1800:
                print("... [đã rút gọn]")
        elif typ == 'execute_result':
            print(f"[output {oi} | {typ}] (không có text hiển thị)")

print("\n" + "=" * 90)
print("PHẦN B — CÁC CELL KHÁC CÓ DẤU HIỆU NẠP CHECKPOINT + INFERENCE/EXPORT")
print("=" * 90)

for idx, cell in enumerate(cells):
    if idx in priority or cell.get('cell_type') != 'code':
        continue

    source = ''.join(cell.get('source', []))
    has_load = bool(patterns["checkpoint_load"].search(source))
    has_infer = bool(patterns["inference"].search(source))
    has_export = bool(patterns["export"].search(source))

    # Ưu tiên cell có ít nhất hai nhóm tín hiệu
    if sum([has_load, has_infer, has_export]) >= 2:
        lines = source.splitlines()
        print(f"\n--- CELL {idx} | execution_count={cell.get('execution_count')} "
              f"| lines={len(lines)} | load={has_load} "
              f"| inference={has_infer} | export={has_export} ---")
        count = 0
        for line_no, line in enumerate(lines):
            if any(p.search(line) for p in patterns.values()):
                print(f"{line_no+1:4}: {line[:240]}")
                count += 1
                if count >= 18:
                    print("... [giới hạn 18 dòng khớp]")
                    break

        # Chỉ lấy output lỗi hoặc output nhắc đến dự đoán/checkpoint
        for oi, out in enumerate(cell.get('outputs', [])):
            parts = []
            if 'text' in out:
                parts.append(''.join(out['text']))
            data = out.get('data', {})
            if 'text/plain' in data:
                v = data['text/plain']
                parts.append(''.join(v) if isinstance(v, list) else str(v))
            if out.get('ename'):
                parts.append(
                    f"ERROR: {out.get('ename')}: {out.get('evalue', '')}"
                )
            s = '\n'.join(parts).strip()
            if s and (
                out.get('ename') or
                re.search(r'predict|checkpoint|\.pt|saved|export|test_predictions',
                          s, re.I)
            ):
                print(f"[saved output {oi}] {s[:900]}")

print("\nHoàn tất: chỉ đọc notebook và outputs đã lưu; không chạy cell notebook.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Notebook: /content/drive/MyDrive/Colab Notebooks/25sep.ipynb
Tổng số cells: 162

==========================================================================================
PHẦN A — CÁC CELL CẦN KIỂM TRA
==========================================================================================

--- CELL 116 | type=code | execution_count=8 | source_lines=257 ---
   ...
   4: #
   5: # IMPORTANT:
   6: # - V4 checkpoint loaded on CPU
   7: # - NO deepcopy of V5
   8: # - NO optimizer
   ...
  17: V4_CKPT = (
  18:     "/content/drive/MyDrive/NoiSoi_Matching/"
  19:     "baseline_model_v4/checkpoints/epoch_03.pt"
  20: )
  21:
   ...
  25:
  26: assert os.path.isfile(V4_CKPT), \
  27:     "FAIL: V4 Epoch 3 checkpoint not found."
  28:
  29: # ------------------------------------------------------------
   ...
  41:
  42: # ------------------------------------------------------------
  43: # Load V4 checkpoint on CPU
  44: # ------------------------------------------------------------
  45: print("\n[LOADING]")
  46: print("Loading V4 Epoch 3 checkpoint on CPU...")
  47: print("This avoids placing the 4.4 GB checkpoint on GPU.")
  48:
  49: v4_ckpt = torch.load(
  50:     V4_CKPT,
  51:     map_location="cpu",
   ...
  54:
  55: assert isinstance(v4_ckpt, dict), \
  56:     "FAIL: V4 checkpoint is not a dictionary."
  57:
  58: assert "model_state" in v4_ckpt, \
  59:     "FAIL: model_state missing from V4 checkpoint."
  60:
  61: v4_state = v4_ckpt["model_state"]
  62:
  63: print("PASS: V4 checkpoint loaded on CPU.")
  64: print("V4 checkpoint keys:", list(v4_ckpt.keys()))
  65: print("V4 state tensors:", len(v4_state))
  66:
   ...
 215: # ------------------------------------------------------------
 216: print("\n[V4 SAFETY]")
 217: print("V4 checkpoint path:", V4_CKPT)
 218: print("V4 checkpoint still exists:", os.path.isfile(V4_CKPT))
 219:
 220: assert os.path.isfile(V4_CKPT)
 221:
 222: # ------------------------------------------------------------
 223: # Release CPU checkpoint immediately
 224: # ------------------------------------------------------------
 225: del v4_state
   ...
 247: print("PASS: 15 V4-only tensors identified.")
 248: print("PASS: 9 V5-only tensors preserved.")
 249: print("PASS: V4 checkpoint remains untouched.")
 250: print("PASS: No optimizer created.")
 251: print("PASS: No scheduler created.")

[SAVED OUTPUTS: 2]
[output 0 | stream]
======================================================================
V5 RESTORE — V4 EPOCH 3 WARM-START
======================================================================

[BEFORE V4 LOAD]
GPU allocated: 1.44 GB

[LOADING]
Loading V4 Epoch 3 checkpoint on CPU...
This avoids placing the 4.4 GB checkpoint on GPU.
PASS: V4 checkpoint loaded on CPU.
V4 checkpoint keys: ['epoch', 'model_state', 'optimizer_state', 'scheduler_state', 'best_val', 'rng_state', 'cuda_rng_state', 'history']
V4 state tensors: 409

[STATE DICT COMPARISON]
V4 tensors: 409
V5 tensors: 403

[COMPATIBILITY]
Compatible      : 392
Shape mismatch  : 0
V4-only         : 17
V5-only         : 11
[output 1 | error]
ERROR: AssertionError: FAIL: expected 394 compatible tensors, got 392

--- CELL 118 | type=code | execution_count=10 | source_lines=208 ---
   ...
 151: V4_CKPT = (
 152:     "/content/drive/MyDrive/NoiSoi_Matching/"
 153:     "baseline_model_v4/checkpoints/epoch_03.pt"
 154: )
 155:
   ...
 157:
 158: print("\n[V4 SAFETY]")
 159: print("V4 checkpoint exists:", True)
 160: print("V4 checkpoint was only READ:", True)
 161:
 162: # ------------------------------------------------------------
 163: # Release V4 checkpoint from RAM
 164: # ------------------------------------------------------------
 165: del v4_state
   ...
 198: print("PASS: 11 V5-only tensors retained.")
 199: print("PASS: max copy diff = 0.")
 200: print("PASS: V4 checkpoint untouched.")
 201: print("PASS: No optimizer.")
 202: print("PASS: No scheduler.")

[SAVED OUTPUTS: 1]
[output 0 | stream]
======================================================================
V5 RESTORE — OFFICIAL WARM-START
======================================================================

[PRE-COPY AUDIT]
Compatible     : 392
V4-only        : 17
V5-only        : 11
Shape mismatch : 0

[SHARED MODULES]
vision    : 200
mt5       : 192

[COPY]
Copying 392 compatible tensors...
Copied: 392

[VERIFICATION]
Maximum absolute difference: 0.0

[V5-ONLY — RETAINED]
  attribute_head.bias
  attribute_head.weight
  concept_head.bias
  concept_head.weight
  conditioner.attribute_embeddings
  conditioner.concept_embeddings
  conditioner.negative_embeddings
  negative_head.bias
  negative_head.weight
  projector.bias
  projector.weight

PASS: all 11 V5-specific tensors retained.

[V4 SAFETY]
V4 checkpoint exists: True
V4 checkpoint was only READ: True

[MEMORY AFTER CLEANUP]
GPU allocated: 1.44 GB
GPU reserved : 1.48 GB

[SAFETY]
PASS: 392 V4-compatible tensors copied.
PASS: 0 shape mismatches.
PASS: 17 V4-only tensors ignored.
PASS: 11 V5-only tensors retained.
PASS: max copy diff = 0.
PASS: V4 checkpoint untouched.
PASS: No optimizer.
PASS: No scheduler.
PASS: No backward.
PASS: No training.

======================================================================
CELL 8 PASS — send me this output.
======================================================================

--- CELL 123 | type=code | execution_count=15 | source_lines=398 ---
   ...
 239: )
 240:
 241: test_loader_v5 = DataLoader(
 242:     test_dataset_v5,
 243:     batch_size=4,
 244:     shuffle=False,
   ...
 268: print(
 269:     "Test batches:",
 270:     len(test_loader_v5)
 271: )
 272:
 273: assert len(train_loader_v5) == 1535
 274: assert len(val_loader_v5) == 189
 275: assert len(test_loader_v5) == 178
 276:
 277:

[SAVED OUTPUTS: 1]
[output 0 | stream]
======================================================================
V5 RESTORE — DATALOADER + STRUCTURED TARGET AUDIT
======================================================================

[VOCABULARY]
Negative: ['no_abnormal_ent', 'no_abnormal_external_middle_ear', 'no_abnormal_nose_sinus', 'no_bleeding', 'no_foreign_body']
Attribute: ['acute', 'bilateral', 'chronic', 'left', 'post_surgery', 'right']

[STRUCTURED TARGETS]
Cases: 7606
10000.10000.0.10014 concept= (48,) negative= (5,) attribute= (6,) mask= 1.0
10001.10001.0.10015 concept= (48,) negative= (5,) attribute= (6,) mask= 1.0
10002.10002.0.10016 concept= (48,) negative= (5,) attribute= (6,) mask= 1.0

[COUNT CONSISTENCY]
PASS: concept vectors match num_concepts_v2.
PASS: negative vectors match num_negative_findings.
PASS: attribute vectors match num_attributes_v2.

[LOADERS]
Train batches: 1535
Val batches: 189
Test batches: 178

[REAL BATCH AUDIT]
case_id: ['13931.13931.0.13950', '15080.15080.0.15099', '14286.14286.0.14305', '15667.15667.0.15688']
pixel_values: (4, 8, 3, 224, 224) torch.float32
image_mask: (4, 8) torch.float32
labels: (4, 96) torch.int64

[STRUCTURED BATCH LOOKUP]
concept_targets: (4, 48)
negative_targets: (4, 5)
attribute_targets: (4, 6)
structured_masks: (4,)

[SAFETY]
PASS: Exact V4 structured vectors used.
PASS: 48 concept targets.
PASS: 5 negative targets.
PASS: 6 attribute targets.
PASS: Vector/count consistency verified.
PASS: Train loader = 1535 batches.
PASS: Val loader = 189 batches.
PASS: Test loader = 178 batches.
PASS: Real batch schema valid.
PASS: No optimizer.
PASS: No backward.
PASS: No training.

======================================================================
CELL 9H PASS — send me this output.
======================================================================

--- CELL 124 | type=code | execution_count=16 | source_lines=315 ---
(Không thấy từ khóa liên quan trong source.)

[SAVED OUTPUTS: 1]
[output 0 | stream]
======================================================================
V5 RESTORE — REAL FORWARD + LOSS AUDIT
======================================================================

[DEVICE]
Device: cuda

[MODEL]
V5 parameters: 387020219

[FORWARD]
Forward completed.

[OUTPUT KEYS]
['report_loss', 'concept_logits', 'negative_logits', 'attribute_logits', 'logits', 'inputs_embeds']

[OUTPUT SHAPES]
report_loss: torch.Size([])
concept_logits: (4, 48)
negative_logits: (4, 5)
attribute_logits: (4, 6)
logits: (4, 96, 250112)
inputs_embeds: (4, 4, 512)

[LOSSES]
Report loss: 0.6206221580505371
Concept loss: 0.7240947484970093
Negative loss: 0.6943707466125488
Attribute loss: 0.7342574596405029
Total loss: 1.5134193897247314

[SAFETY]
PASS: Real V5 forward completed.
PASS: Output schema matches Cell 81 architecture.
PASS: Concept logits = (4,48).
PASS: Negative logits = (4,5).
PASS: Attribute logits = (4,6).
PASS: Decoder logits = (4,96,V).
PASS: inputs_embeds = (4,4,512).
PASS: All losses finite.
PASS: Structured loss weights = 0.5 / 0.5 / 0.25.
PASS: No gradients.
PASS: No optimizer step.
PASS: No training.

GPU MEMORY:
allocated = 1.83 GB
reserved  = 2.53 GB

======================================================================
CELL 9I COMPLETE — send me the full output.
======================================================================

--- CELL 130 | type=code | execution_count=6 | source_lines=191 ---
   ...
 116:
 117: # ------------------------------------------------------------
 118: # 5. CHECKPOINT DIRECTORY
 119: # ------------------------------------------------------------
 120:
 121: print("\n[5] Checkpoint directory")
 122:
 123: from pathlib import Path
   ...
 125: V5_CKPT_DIR = Path(
 126:     "/content/drive/MyDrive/NoiSoi_Matching/"
 127:     "baseline_model_v5/checkpoints"
 128: )
 129:
   ...
 145:
 146: assert len(existing_ckpts) == 0, (
 147:     "Unexpected checkpoint found. "
 148:     "Stop before training."
 149: )
 150:
 151: print(
 152:     "PASS: Clean V5 checkpoint directory."
 153: )
 154:

[SAVED OUTPUTS: 2]
[output 0 | stream]
================================================================================
V5 RUNTIME PRE-TRAINING AUDIT
================================================================================

[1] CUDA
CUDA available: True
GPU: NVIDIA A100-SXM4-80GB

[2] Required runtime objects
MISSING: ['v5', 'train_loader_v5', 'val_loader_v5', 'structured_targets_v5']
[output 1 | error]
ERROR: RuntimeError: FAIL: Missing runtime objects. Restore V5/data cells first.

--- CELL 138 | type=code | execution_count=14 | source_lines=1021 ---
   ...
   1: # ============================================================
   2: # V5 — ONE-CELL V4 CHECKPOINT DISCOVERY + WARM START
   3: #
   4: # This cell:
   5: #   1. Verifies Drive
   6: #   2. Searches all reasonable locations
   7: #   3. Finds V4 checkpoint automatically
   8: #   4. Validates checkpoint
   9: #   5. Performs exact 392-tensor warm-start
  10: #   6. Verifies max_diff == 0
   ...
  12: # IMPORTANT:
  13: #   - Does NOT train
  14: #   - Does NOT modify V4 checkpoint
  15: #   - Does NOT overwrite existing V5 checkpoints
  16: # ============================================================
  17:
   ...
  28:
  29: print("=" * 80)
  30: print("V5 — AUTOMATIC V4 CHECKPOINT DISCOVERY + WARM START")
  31: print("=" * 80)
  32:
   ...
 102: V4_CKPT_DIR = (
 103:     V4_ROOT
 104:     / "checkpoints"
 105: )
 106:
   ...
 112: V5_CKPT_DIR = (
 113:     V5_ROOT
 114:     / "checkpoints"
 115: )
 116:
   ...
 135:
 136: print("\n" + "=" * 80)
 137: print("[2] SEARCHING FOR V4 CHECKPOINT")
 138: print("=" * 80)
 139:
   ...
 192:
 193: # ============================================================
 194: # 4. CHECKPOINT NAME PATTERNS
 195: # ============================================================
 196:
   ...
 207:     "V4_epoch_3.pt",
 208:
 209:     # Generic checkpoint variants
 210:     "*epoch_03*.pt",
 211:     "*epoch_3*.pt",
 212:
 213:     # Any checkpoint
 214:     "*.pt",
 215: ]
   ...
 265:
 266:             # ------------------------------------------------
 267:             # Ignore V5 checkpoints
 268:             # ------------------------------------------------
 269:
   ...
 309:
 310: print("\n" + "=" * 80)
 311: print("DISCOVERED CHECKPOINT CANDIDATES")
 312: print("=" * 80)
 313:
   ...
 340: # ============================================================
 341:
 342: def checkpoint_score(item):
 343:
 344:     path = str(
   ...
 382:     # Size heuristic
 383:     #
 384:     # V4 checkpoint is expected to be several GB.
 385:     # Do not require exact size because serialization
 386:     # can vary.
   ...
 394: ranked_candidates = sorted(
 395:     candidates,
 396:     key=checkpoint_score,
 397:     reverse=True,
 398: )
   ...
 404:
 405: print("\n" + "=" * 80)
 406: print("CHECKPOINT SELECTION")
 407: print("=" * 80)
 408:
   ...
 411:
 412:     print(
 413:         "NO V4 CHECKPOINT FOUND."
 414:     )
 415:
   ...
 419:
 420:     print(
 421:         "\nNo V4 checkpoint will be fabricated "
 422:         "or substituted."
 423:     )
   ...
 429:
 430:     raise SystemExit(
 431:         "STOP: V4 checkpoint unavailable."
 432:     )
 433:
   ...
 441:
 442: print(
 443:     "Selected checkpoint:"
 444: )
 445:
   ...
 450: print(
 451:     "Score:",
 452:     checkpoint_score(
 453:         selected
 454:     )
   ...
 461:
 462: # ============================================================
 463: # 9. CHECK IF IT IS REALLY A V4 CHECKPOINT
 464: # ============================================================
 465:
 466: print("\n" + "=" * 80)
 467: print("[3] VALIDATING CHECKPOINT")
 468: print("=" * 80)
 469:
   ...
 474: )
 475:
 476: v4_ckpt = torch.load(
 477:     V4_CKPT,
 478:     map_location="cpu",
   ...
 482:
 483: print(
 484:     "Checkpoint keys:"
 485: )
 486:
   ...
 781:
 782:     print(
 783:         "\nWARNING: Checkpoint is loadable "
 784:         "but does NOT match the expected "
 785:         "V4 Epoch-3 forensic signature."
   ...
 831:
 832:     raise RuntimeError(
 833:         "STOP: Checkpoint does not match "
 834:         "the known V4 Epoch-3 forensic state."
 835:     )
   ...
 951:
 952: print(
 953:     "V4 checkpoint still exists:",
 954:     V4_CKPT
 955: )
 956:
 957: print(
 958:     "PASS: V4 checkpoint untouched."
 959: )
 960:

[SAVED OUTPUTS: 3]
[output 0 | stream]
================================================================================
V5 — AUTOMATIC V4 CHECKPOINT DISCOVERY + WARM START
================================================================================

================================================================================
[1] GOOGLE DRIVE
================================================================================
PASS: MyDrive accessible.

Project root:
/content/drive/MyDrive/NoiSoi_Matching
V4 root exists: False
V5 root exists: True

================================================================================
[2] SEARCHING FOR V4 CHECKPOINT
================================================================================

Searching: /content/drive/MyDrive/NoiSoi_Matching

Searching: /content/drive/MyDrive

Searching: /content

================================================================================
DISCOVERED CHECKPOINT CANDIDATES
================================================================================
Total: 0

================================================================================
CHECKPOINT SELECTION
================================================================================
NO V4 CHECKPOINT FOUND.

WARM START STATUS: NOT AVAILABLE

No V4 checkpoint will be fabricated or substituted.
V5 training MUST NOT start with warm-start assumptions.
[output 1 | error]
ERROR: SystemExit: STOP: V4 checkpoint unavailable.
[output 2 | stream]
/usr/local/lib/python3.13/dist-packages/IPython/core/interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

--- CELL 144 | type=code | execution_count=24 | source_lines=319 ---
(Không thấy từ khóa liên quan trong source.)

[SAVED OUTPUTS: 1]
[output 0 | error]
ERROR: AssertionError: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv

==========================================================================================
PHẦN B — CÁC CELL KHÁC CÓ DẤU HIỆU NẠP CHECKPOINT + INFERENCE/EXPORT
==========================================================================================

--- CELL 1 | execution_count=None | lines=1914 | load=True | inference=True | export=True ---
  14: #   - checkpoint save
  82:     f"{V4_DIR}/checkpoints/epoch_02.pt"
  86:     f"{V4_DIR}/checkpoints/epoch_03.pt"
  90:     f"{V4_DIR}/checkpoints/best.pt"
 102:     "E2 checkpoint": E2_CKPT,
 103:     "E3 checkpoint": E3_CKPT,
 104:     "Best checkpoint": BEST_CKPT,
 173: tokenizer = AutoTokenizer.from_pretrained(
 199: image_processor = AutoImageProcessor.from_pretrained(
 894:         self.vision = ViTModel.from_pretrained(
 898:         self.mt5 = MT5ForConditionalGeneration.from_pretrained(
 940: model.eval()
 986: print("\nLOADING CHECKPOINTS")
 988: E2 = torch.load(
 994: E3 = torch.load(
1017: load_result = model.load_state_dict(
1031: model.load_state_dict(
1046:     "\nCHECKPOINT RESTORE: PASS"
... [giới hạn 18 dòng khớp]
[saved output 0] ======================================================================
V4 NEW-NOTEBOOK BOOTSTRAP
======================================================================
Google Drive: already mounted

PATH CHECK
  V4 manifest           : PASS -> /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv
  Structured targets    : PASS -> /content/drive/MyDrive/NoiSoi_Matching/v3_ontology_v2/v3_structured_targets_v2_2.csv
  Image manifest        : PASS -> /content/drive/MyDrive/NoiSoi_Matching/final_manifest/final_dataset_manifest.csv
  V4 config             : PASS -> /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_config.json
  E2 checkpoint         : PASS -> /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_02.pt
  E3 checkpoint         : PASS -> /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt
  Be
[saved output 13] [transformers] ViTModel LOAD REPORT from: google/vit-base-patch16-224
Key                 | Status     |
--------------------+------------+-
classifier.bias     | UNEXPECTED |
classifier.weight   | UNEXPECTED |
pooler.dense.weight | MISSING    |
pooler.dense.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
[saved output 17] [transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.
[saved output 19] Model device: cuda:0
Projector: (512, 768)
Concept head: (48, 512)
Negative head: (5, 512)
Attribute head: (6, 512)

LOADING CHECKPOINTS
[saved output 23] ERROR: RuntimeError: Error(s) in loading state_dict for V4Model:
	Missing key(s) in state_dict: "projector.weight", "projector.bias".
	Unexpected key(s) in state_dict: "projector.proj.weight", "projector.proj.bias".

--- CELL 3 | execution_count=None | lines=68 | load=True | inference=True | export=False ---
  13: model.eval()
  33: # 3. Verify checkpoint-loaded parameters are finite

--- CELL 5 | execution_count=None | lines=445 | load=True | inference=True | export=True ---
  12: model.eval()
  42:     # EXACT checkpoint projector
 214:         next_token = torch.argmax(
 232:     return safe_decode(generated)
 268: # 5. RUN ONE CHECKPOINT
 271: def run_ablation_for_checkpoint(

In [3]:

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
from datetime import datetime
import os, re, json

ROOT = Path('/content/drive/MyDrive/NoiSoi_Matching')
V5 = ROOT / 'baseline_model_v5'
TARGET = 'test_predictions_712.csv'

print('=' * 80)
print('A. FILE METADATA — PREDICTIONS, CHECKPOINTS, SUMMARY')
print('=' * 80)

paths = [
    V5 / TARGET,
    V5 / 'checkpoints' / 'best.pt',
    V5 / 'checkpoints' / 'last.pt',
    V5 / 'diagnostics' / 'v5_final_training_summary.json',
    V5 / 'runtime_state' / 'environment.json',
    V5 / 'runtime_state' / 'gpu_state.json',
    V5 / 'runtime_state' / 'paths.json',
    V5 / 'runtime_state' / 'runtime_info.json',
]

for p in paths:
    print(f'\n{p}')
    if not p.exists():
        print('  STATUS: NOT FOUND')
        continue
    st = p.stat()
    print('  size_bytes:', st.st_size)
    print('  modified:', datetime.fromtimestamp(st.st_mtime).isoformat(
        sep=' ', timespec='seconds'))
    print('  created/changed metadata time:', datetime.fromtimestamp(
        st.st_ctime).isoformat(sep=' ', timespec='seconds'))

    if p.suffix.lower() == '.json' and st.st_size < 2_000_000:
        try:
            obj = json.loads(p.read_text(encoding='utf-8'))
            print('  JSON content:')
            print(json.dumps(obj, ensure_ascii=False, indent=2)[:5000])
        except Exception as e:
            print('  JSON read error:', repr(e))

print('\n' + '=' * 80)
print('B. SEARCH SMALL TEXT FILES FOR EXACT CSV NAME / EXPORT REFERENCES')
print('=' * 80)

# Search source, logs, configs and notebooks only.
# Skip large binaries, images, datasets, and checkpoint files.
extensions = {
    '.py', '.ipynb', '.json', '.jsonl', '.txt', '.log',
    '.md', '.yaml', '.yml', '.sh'
}
terms = [
    TARGET,
    'test_predictions',
    'to_csv(',
    'best.pt',
    'last.pt',
    'load_state_dict',
    'model.generate(',
    'tokenizer.decode(',
]

max_file_bytes = 20_000_000
max_hits_per_file = 12
files_scanned = 0
matches_found = 0

for dirpath, dirnames, filenames in os.walk(ROOT):
    # Avoid irrelevant bulky directories
    dirnames[:] = [
        d for d in dirnames
        if d not in {
            '.git', '__pycache__', 'node_modules',
            'images', 'image_cache', 'raw_images'
        }
    ]

    for filename in filenames:
        p = Path(dirpath) / filename
        if p.suffix.lower() not in extensions:
            continue
        try:
            if p.stat().st_size > max_file_bytes:
                continue
            content = p.read_text(encoding='utf-8', errors='ignore')
            files_scanned += 1
        except Exception:
            continue

        lines = content.splitlines()
        hits = []
        for i, line in enumerate(lines):
            if any(term.lower() in line.lower() for term in terms):
                hits.append((i + 1, line.strip()[:240]))

        if hits:
            matches_found += 1
            print(f'\n--- {p} | {len(hits)} matching lines ---')
            for line_no, line in hits[:max_hits_per_file]:
                print(f'{line_no:5}: {line}')
            if len(hits) > max_hits_per_file:
                print('  ... additional matches omitted')

print('\n' + '=' * 80)
print('C. CSV STRUCTURE AND ORDER CHECK — READ ONLY')
print('=' * 80)

csv_path = V5 / TARGET
manifest_path = ROOT / 'baseline_model_v4' / 'v4_training_manifest.csv'

if csv_path.exists():
    import pandas as pd
    pred = pd.read_csv(csv_path)
    print('CSV shape:', pred.shape)
    print('CSV columns:', pred.columns.tolist())
    print('Unique case IDs:', pred['case_id'].nunique()
          if 'case_id' in pred.columns else 'case_id column absent')
    print('First 8 rows:')
    print(pred.head(8).to_string(index=False))

    if manifest_path.exists():
        manifest = pd.read_csv(manifest_path, usecols=['case_id', 'split'])
        expected = manifest.loc[manifest['split'].eq('test'), 'case_id'].astype(str)
        actual = pred['case_id'].astype(str) if 'case_id' in pred.columns else pd.Series([], dtype=str)

        print('\nTest manifest rows:', len(expected))
        print('Prediction rows:', len(actual))
        print('Same ID set:', set(expected) == set(actual))
        print('Same ID order:', list(expected) == list(actual))
        print('First 10 manifest test IDs:', expected.head(10).tolist())
        print('First 10 prediction IDs:', actual.head(10).tolist())
    else:
        print('V4 manifest missing; skipped order comparison.')
else:
    print('Prediction CSV not found:', csv_path)

print('\nFiles scanned:', files_scanned)
print('Files with matching references:', matches_found)
print('READ-ONLY CHECK COMPLETE — no files modified; no model loaded.')

Mounted at /content/drive
================================================================================
A. FILE METADATA — PREDICTIONS, CHECKPOINTS, SUMMARY
================================================================================

/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/test_predictions_712.csv
  size_bytes: 62941
  modified: 2026-09-30 16:34:27
  created/changed metadata time: 2026-09-30 16:34:27

/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/best.pt
  size_bytes: 4640037647
  modified: 2026-09-29 04:20:44
  created/changed metadata time: 2026-09-29 04:20:44

/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/last.pt
  size_bytes: 4640037647
  modified: 2026-09-29 04:25:51
  created/changed metadata time: 2026-09-29 04:25:51

/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/v5_final_training_summary.json
  size_bytes: 649
  modified: 2026-09-29 04:23:10
  created/changed metadata time: 2026-09-29 04:23:10
  JSON content:
{
  "model": "V5",
  "status": "TRAINING_COMPLETE",
  "num_epochs": 5,
  "global_step": 1920,
  "epoch": 5,
  "next_batch": 0,
  "best_val": 0.424518172663671,
  "train_loss": [
    0.5731708970967303,
    0.5046075203082849,
    0.47171955251829634,
    0.45422747778290645,
    0.44715843725379206
  ],
  "val_loss": [
    0.46700948011622856,
    0.44155955633946825,
    0.42823387978095856,
    0.4258775923539091,
    0.424518172663671
  ],
  "last_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/last.pt",
  "best_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/best.pt"
}

/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/runtime_state/environment.json
  size_bytes: 182
  modified: 2026-09-28 08:24:55
  created/changed metadata time: 2026-09-28 08:24:55
  JSON content:
{
  "torch_version": "2.11.0+cu128",
  "transformers_version": "5.16.1",
  "cuda_available": true,
  "cuda_version": "12.8",
  "gpu_name": "NVIDIA A100-SXM4-80GB",
  "gpu_count": 1
}

/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/runtime_state/gpu_state.json
  size_bytes: 101
  modified: 2026-09-28 08:24:55
  created/changed metadata time: 2026-09-28 08:24:55
  JSON content:
{
  "allocated_gb": 1.4432291984558105,
  "reserved_gb": 1.482421875,
  "total_gb": 79.250732421875
}

/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/runtime_state/paths.json
  size_bytes: 719
  modified: 2026-09-28 08:24:55
  created/changed metadata time: 2026-09-28 08:24:55
  JSON content:
{
  "v4_manifest": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv",
  "v4_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt",
  "v4_best": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",
  "structured_targets": "/content/drive/MyDrive/NoiSoi_Matching/v3_ontology_v2/v3_structured_targets_v2_2.csv",
  "ontology_mapping": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/diagnostics/frozen_concept_ontology_mapping.csv",
  "final_manifest": "/content/drive/MyDrive/NoiSoi_Matching/final_manifest/final_dataset_manifest.csv",
  "v5_root": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5"
}

/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/runtime_state/runtime_info.json
  size_bytes: 310
  modified: 2026-09-28 08:24:55
  created/changed metadata time: 2026-09-28 08:24:55
  JSON content:
{
  "has_image_processor": true,
  "has_tokenizer": true,
  "has_v4_df": true,
  "has_image_df": true,
  "has_structured_df": true,
  "has_case_to_images": true,
  "has_train_cases": true,
  "has_val_cases": true,
  "has_test_cases": true,
  "has_v5": true,
  "has_optimizer": false,
  "has_scheduler": false
}

================================================================================
B. SEARCH SMALL TEXT FILES FOR EXACT CSV NAME / EXPORT REFERENCES
================================================================================

--- /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_config.json | 1 matching lines ---
   23: "source_v3_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt",

--- /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_runtime_state.json | 3 matching lines ---
    6: "checkpoint_best": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",
    9: "checkpoint_last": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt",
   10: "status": "Generation audit pending after fixing tokenizer.decode(-100)",

--- /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/v5_final_training_summary.json | 2 matching lines ---
   23: "last_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/last.pt",
   24: "best_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/best.pt"

--- /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell1_schema_ontology_audit.txt | 1 matching lines ---
   51: Path: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/test_predictions_712.csv

--- /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell6_training_source_audit.txt | 96 matching lines ---
   76: f"{V4_DIR}/checkpoints/best.pt"
  170: f"{V4_DIR}/checkpoints/best.pt"
 1097: load_result = model.load_state_dict(
 1111: model.load_state_dict(
 1182: model.load_state_dict(
 1211: return tokenizer.decode(
 1587: model.load_state_dict(
 1982: model.load_state_dict(
 2085: model.load_state_dict(E2["model_state"], strict=True)
 2092: model.load_state_dict(E3["model_state"], strict=True)
 2381: model.load_state_dict(
 2586: token = tokenizer.decode(
  ... additional matches omitted

--- /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell7_v5_training_flow.txt | 3 matching lines ---
   37: 161:     "last.pt"
   42: 166:     "best.pt"
  177: 2106:     "best.pt:",

--- /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell8_saved_training_history.txt | 14 matching lines ---
   85: SOURCE   96:     V5_CKPT_DIR / "best.pt"
  150: SOURCE 1284:         f"best.pt exists  : {BEST_CKPT.exists()}"
  161: SOURCE 1332:     "best.pt:",
  172: SOURCE 1343: print("PASS: last.pt maintained.")
  173: SOURCE 1344: print("PASS: best.pt maintained.")
  184: SOURCE  107:     V5_CKPT_DIR / "best.pt"
  260: SOURCE 1404:     "best.pt:",
  299: SOURCE  166:     "best.pt"
  457: SOURCE 2106:     "best.pt:",
  478: SOURCE   51: LAST_CKPT = V5_CKPT_DIR / "last.pt"
  479: SOURCE   52: BEST_CKPT = V5_CKPT_DIR / "best.pt"
  484: SOURCE  390:         "best.pt exists:",
  ... additional matches omitted

--- /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell11_prediction_generation_source.txt | 5 matching lines ---
   16: 1131:     return tokenizer.decode(
  119: 16:     return tokenizer.decode(
  159: 37:         token = tokenizer.decode(
  176: 143:                 "full_top_token": tokenizer.decode(
  180: 147:                 "other_top_token": tokenizer.decode(

--- /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell12_checkpoint_and_prediction_source.txt | 92 matching lines ---
    4: 73: f"{V4_DIR}/checkpoints/best.pt"
   13: 90: f"{V4_DIR}/checkpoints/best.pt"
   17: 1017: load_result = model.load_state_dict(
   18: 1031: model.load_state_dict(
   19: 1102: model.load_state_dict(
   20: 1507: model.load_state_dict(
   21: 1902: model.load_state_dict(
   95: 88: model.load_state_dict(E2["model_state"], strict=True)
   96: 95: model.load_state_dict(E3["model_state"], strict=True)
  138: 280: model.load_state_dict(
  159: 59: model.load_state_dict(
  202: 40: model.load_state_dict(E3["model_state"], strict=True)
  ... additional matches omitted

--- /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell13_full_notebook_prediction_trace.txt | 72 matching lines ---
    4: 73: f"{V4_DIR}/checkpoints/best.pt"
    8: 90: f"{V4_DIR}/checkpoints/best.pt"
   15: output line 13: Best checkpoint       : PASS -> /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt
   16: output line 43: source_v3_checkpoint: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt
   20: 350: sensitivity_df.to_csv(
   21: 355: summary_df.to_csv(
   25: 262: checkpoint_paths["last"] = os.path.join(CKPT_DIR, "last.pt")
   26: 263: checkpoint_paths["best"] = os.path.join(CKPT_DIR, "best.pt")
   30: output line 11: checkpoint_best: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt
   31: output line 14: checkpoint_last: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt
   32: output line 45: source_v3_checkpoint: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt
   36: output line 10: best.pt
  ... additional matches omitted

--- /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/runtime_state/paths.json | 1 matching lines ---
    4: "v4_best": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",

================================================================================
C. CSV STRUCTURE AND ORDER CHECK — READ ONLY
================================================================================
CSV shape: (712, 3)
CSV columns: ['case_id', 'prediction', 'ground_truth']
Unique case IDs: 712
First 8 rows:
            case_id                                   prediction                                                                ground_truth
10017.10017.0.10031          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                             VIÊM MÀNG NHĨ CẤP BÓNG NƯỚC P - NHIỀU RÁY TAI T
10057.10057.0.10071          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                              VIÊM ỐNG TAI NGOÀI (T) MẠN / VIÊM MŨI ĐỢT CẤP.
10116.10116.0.10130          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                                           VIÊM ỐNG TAI NGOÀI MÀNG NHĨ P CẤP
10125.10125.0.10139                                 VIÊM MŨI MẠN                        VIÊM MŨI MẠN VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ 2 BÊN MẠN
10126.10126.0.10140 VIÊM HỌNG MẠN - THEO DÕI TRÀO NGƯỢC DỊCH VỊ.                                                              VIÊM A-MI-ĐAN.
10142.10142.0.10156                                 VIÊM MŨI MẠN                                                                VIÊM MŨI MẠN
10153.10153.0.10167                               VIÊM MŨI XOANG HIỆN KHÔNG THẤY HÌNH ẢNH BỆNH LÝ TAI NGOÀI TAI GIỮA TRÊN NỘI SOI / VIÊM MŨI
10156.10156.0.10170          VIÊM ỐNG TAI NGOÀI + MÀNG NHĨ T CẤP                                                    VIÊM ỐNG TAI NGOÀI P CẤP

Test manifest rows: 712
Prediction rows: 712
Same ID set: True
Same ID order: True
First 10 manifest test IDs: ['10017.10017.0.10031', '10057.10057.0.10071', '10116.10116.0.10130', '10125.10125.0.10139', '10126.10126.0.10140', '10142.10142.0.10156', '10153.10153.0.10167', '10156.10156.0.10170', '10175.10175.0.10189', '10213.10213.0.10227']
First 10 prediction IDs: ['10017.10017.0.10031', '10057.10057.0.10071', '10116.10116.0.10130', '10125.10125.0.10139', '10126.10126.0.10140', '10142.10142.0.10156', '10153.10153.0.10167', '10156.10156.0.10170', '10175.10175.0.10189', '10213.10213.0.10227']

Files scanned: 135
Files with matching references: 11
READ-ONLY CHECK COMPLETE — no files modified; no model loaded.

In [4]:
from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import json
from pathlib import Path

NOTEBOOK_PATH = Path(
    "/content/drive/MyDrive/Colab Notebooks/25sep.ipynb"
)

assert NOTEBOOK_PATH.exists(), f"Notebook not found: {NOTEBOOK_PATH}"

with NOTEBOOK_PATH.open("r", encoding="utf-8") as f:
    nb = json.load(f)

cells = nb.get("cells", [])
print("Notebook:", NOTEBOOK_PATH)
print("Total cells:", len(cells))

# Print the current source cell 139 exactly as stored.
TARGET_INDEX = 139
if TARGET_INDEX < len(cells):
    cell = cells[TARGET_INDEX]
    source = "".join(cell.get("source", []))
    print("\n" + "=" * 90)
    print(f"CELL {TARGET_INDEX} | type={cell.get('cell_type')}")
    print("=" * 90)
    print(source)
else:
    print(f"Cell {TARGET_INDEX} does not exist.")

# Search all cell source and saved output for inference/provenance clues.
terms = [
    "test_predictions_712.csv",
    "test_predictions",
    "generate(",
    "generate_one",
    "generate_batch",
    "model.generate",
    "mt5.generate",
    "tokenizer.decode",
    "batch_decode",
    "max_new_tokens",
    "num_beams",
    "do_sample",
    "best.pt",
    "last.pt",
    "load_state_dict",
    "to_csv(",
]

print("\n" + "=" * 90)
print("MATCHING NOTEBOOK CELLS")
print("=" * 90)

for i, cell in enumerate(cells):
    source = "".join(cell.get("source", []))
    outputs = cell.get("outputs", [])
    output_text = []
    for out in outputs:
        output_text.extend(out.get("text", []))
        for data in out.get("data", {}).values():
            if isinstance(data, list):
                output_text.extend(data)
    searchable = source + "\n" + "".join(output_text)

    hits = [term for term in terms if term.lower() in searchable.lower()]
    if hits:
        print(f"\n--- CELL {i} | hits: {hits} ---")
        # Print source only here; output may be large.
        print(source[:12000])
        if len(source) > 12000:
            print("[SOURCE TRUNCATED]")

Streaming output truncated to the last 5000 lines.
)

original_rng_state = capture_rng_state()

print(
    "Model tensors:",
    len(original_model_state)
)

print(
    "Optimizer state entries:",
    len(
        original_optimizer_state["state"]
    )
)

print(
    "PASS: Original V5 state captured"
)

# ------------------------------------------------------------------------------
# 8. TEMP CHECKPOINT
# ------------------------------------------------------------------------------

temp_checkpoint = os.path.join(
    V5_CHECKPOINT_DIR,
    "_audit_temp_checkpoint.pt",
)

if os.path.exists(
    temp_checkpoint
):

    os.remove(
        temp_checkpoint
    )

print("\n[TEMP CHECKPOINT]")

save_v5_checkpoint(
    path=temp_checkpoint,
    epoch=test_epoch,
    model=v5,
    optimizer=optimizer_v5,
    scheduler=scheduler_v5,
    best_val=test_best_val,
    history=test_history,
)

if not os.path.exists(
    temp_checkpoint
):

    raise RuntimeError(
        "Temporary checkpoint was not created."
    )

checkpoint_size_mb = (
    os.path.getsize(
        temp_checkpoint
    )
    / (
        1024 ** 2
    )
)

print(
    "Created:",
    temp_checkpoint
)

print(
    "Size:",
    f"{checkpoint_size_mb:.2f} MB"
)

if checkpoint_size_mb <= 0:

    raise RuntimeError(
        "Checkpoint file is empty."
    )

# ------------------------------------------------------------------------------
# 9. FRESH MODEL / OPTIMIZER / SCHEDULER FOR RESTORE TEST
# ------------------------------------------------------------------------------

print(
    "\n[RESTORE TEST]"
)

# Save current V5 object references.
original_v5 = v5
original_optimizer_v5 = optimizer_v5
original_scheduler_v5 = scheduler_v5

# Instantiate a fresh copy using exact current architecture.
fresh_v5 = V5Model().to(
    device_v5
)

# Exact optimizer structure.
fresh_optimizer_v5 = torch.optim.AdamW(
    [
        {
            "name": "vision",
            "params": fresh_v5.vision.parameters(),
            "lr": 1e-5,
        },
        {
            "name": "projector",
            "params": fresh_v5.projector.parameters(),
            "lr": 1e-4,
        },
        {
            "name": "conditioner",
            "params": fresh_v5.conditioner.parameters(),
            "lr": 1e-4,
        },
        {
            "name": "structured_heads",
            "params": (
                list(
                    fresh_v5.concept_head.parameters()
                )
                + list(
                    fresh_v5.negative_head.parameters()
                )
                + list(
                    fresh_v5.attribute_head.parameters()
                )
            ),
            "lr": 1e-4,
        },
        {
            "name": "mT5",
            "params": fresh_v5.mt5.parameters(),
            "lr": 5e-5,
        },
    ],
    weight_decay=0.01,
)

fresh_scheduler_v5 = (
    torch.optim.lr_scheduler.CosineAnnealingLR(
        fresh_optimizer_v5,
        T_max=TOTAL_STEPS,
        eta_min=0.0,
    )
)

# ------------------------------------------------------------------------------
# 10. LOAD CHECKPOINT
# ------------------------------------------------------------------------------

restored = load_v5_checkpoint(
    path=temp_checkpoint,
    model=fresh_v5,
    optimizer=fresh_optimizer_v5,
    scheduler=fresh_scheduler_v5,
    map_location=device_v5,
)

print(
    "Checkpoint epoch:",
    restored["epoch"]
)

print(
    "Checkpoint best_val:",
    restored["best_val"]
)

print(
    "Checkpoint history:",
    restored["history"]
)

# ------------------------------------------------------------------------------
# 11. EXACT MODEL STATE COMPARISON
# ------------------------------------------------------------------------------

print(
    "\n[MODEL STATE COMPARISON]"
)

restored_model_state = {
    key: value.detach().cpu()
    for key, value
    in fresh_v5.state_dict().items()
}

if (
    original_model_state.keys()
    != restored_model_state.keys()
):

    raise RuntimeError(
        "Model state keys changed after restore."
    )

model_max_diff = 0.0

for key in original_model_state:

    diff = torch.max(
        torch.abs(
            original_model_state[key]
            - restored_model_state[key]
        )
    ).item()

    model_max_diff = max(
        model_max_diff,
        float(diff),
    )

print(
    "Model max absolute diff:",
    model_max_diff
)

if model_max_diff != 0.0:

    raise RuntimeError(
        "Restored model state differs from original."
    )

print(
    "PASS: Model state restored exactly"
)

# ------------------------------------------------------------------------------
# 12. OPTIMIZER STATE COMPARISON
# ------------------------------------------------------------------------------

print(
    "\n[OPTIMIZER STATE]"
)

restored_optimizer_state = (
    fresh_optimizer_v5.state_dict()
)

if (
    restored_optimizer_state
    != original_optimizer_state
):

    raise RuntimeError(
        "Optimizer state differs after restore."
    )

print(
    "PASS: Optimizer state restored exactly"
)

# ------------------------------------------------------------------------------
# 13. SCHEDULER STATE COMPARISON
# ------------------------------------------------------------------------------

print(
    "\n[SCHEDULER STATE]"
)

restored_scheduler_state = (
    fresh_scheduler_v5.state_dict()
)

if (
    restored_scheduler_state
    != original_scheduler_state
):

    raise RuntimeError(
        "Sch
[SOURCE TRUNCATED]

--- CELL 107 | hits: ['load_state_dict'] ---
# ================================================================================
# CELL 29 — V5 OPTIMIZER + SCHEDULER AUDIT
# ================================================================================

import torch

print("=" * 80)
print("CELL 29 — V5 OPTIMIZER + SCHEDULER AUDIT")
print("=" * 80)

# ------------------------------------------------------------------------------
# 1. VERIFY V5
# ------------------------------------------------------------------------------

if "v5" not in globals():
    raise RuntimeError("V5 model missing.")

expected_params = 387_020_219

actual_params = sum(
    p.numel()
    for p in v5.parameters()
    if p.requires_grad
)

print("\n[V5]")
print("Trainable parameters:", f"{actual_params:,}")

if actual_params != expected_params:
    raise RuntimeError(
        f"Unexpected V5 parameter count: {actual_params:,}"
    )

print("PASS: Correct V5 model")

# ------------------------------------------------------------------------------
# 2. VERIFY WARM-START STATE
# ------------------------------------------------------------------------------

v5_state = v5.state_dict()

if len(v5_state) != 403:
    raise RuntimeError(
        f"Expected 403 V5 state tensors, got {len(v5_state)}"
    )

print(
    "PASS: V5 state tensors = 403"
)

# ------------------------------------------------------------------------------
# 3. CREATE EXACT 5 OPTIMIZER GROUPS
# ------------------------------------------------------------------------------

optimizer_v5 = torch.optim.AdamW(
    [
        {
            "params": list(
                v5.vision.parameters()
            ),
            "lr": 1e-5,
            "weight_decay": 0.01,
            "name": "vision",
        },
        {
            "params": list(
                v5.projector.parameters()
            ),
            "lr": 1e-4,
            "weight_decay": 0.01,
            "name": "projector",
        },
        {
            "params": list(
                v5.conditioner.parameters()
            ),
            "lr": 1e-4,
            "weight_decay": 0.01,
            "name": "conditioner",
        },
        {
            "params": (
                list(v5.concept_head.parameters())
                + list(v5.negative_head.parameters())
                + list(v5.attribute_head.parameters())
            ),
            "lr": 1e-4,
            "weight_decay": 0.01,
            "name": "structured_heads",
        },
        {
            "params": list(
                v5.mt5.parameters()
            ),
            "lr": 5e-5,
            "weight_decay": 0.01,
            "name": "mT5",
        },
    ]
)

print(
    "\n[OPTIMIZER]"
)

print(
    "Type:",
    type(optimizer_v5).__name__
)

print(
    "Parameter groups:",
    len(optimizer_v5.param_groups)
)

# ------------------------------------------------------------------------------
# 4. GROUP AUDIT
# ------------------------------------------------------------------------------

expected_groups = {
    "vision": {
        "lr": 1e-5,
        "params": 200,
    },
    "projector": {
        "lr": 1e-4,
        "params": 2,
    },
    "conditioner": {
        "lr": 1e-4,
        "params": 3,
    },
    "structured_heads": {
        "lr": 1e-4,
        "params": 6,
    },
    "mT5": {
        "lr": 5e-5,
        "params": 190,
    },
}

for i, group in enumerate(
    optimizer_v5.param_groups
):

    name = group["name"]

    tensor_count = len(
        group["params"]
    )

    lr = group["lr"]

    weight_decay = group[
        "weight_decay"
    ]

    print(
        f"{i}: "
        f"{name:20s} "
        f"tensors={tensor_count:3d} "
        f"lr={lr:.1e} "
        f"weight_decay={weight_decay}"
    )

    if name not in expected_groups:
        raise RuntimeError(
            f"Unexpected optimizer group: {name}"
        )

    expected = expected_groups[name]

    if tensor_count != expected["params"]:
        raise RuntimeError(
            f"{name}: expected "
            f"{expected['params']} tensors, "
            f"got {tensor_count}"
        )

    if lr != expected["lr"]:
        raise RuntimeError(
            f"{name}: expected lr "
            f"{expected['lr']}, got {lr}"
        )

    if weight_decay != 0.01:
        raise RuntimeError(
            f"{name}: unexpected weight_decay"
        )

print(
    "PASS: All 5 optimizer groups exact"
)

# ------------------------------------------------------------------------------
# 5. PARAMETER COVERAGE
# ------------------------------------------------------------------------------

all_optimizer_params = []

for group in optimizer_v5.param_groups:

    all_optimizer_params.extend(
        group["params"]
    )

trainable_tensor_list = [
    p
    for p in v5.parameters()
    if p.requires_grad
]

optimizer_ids = [
    id(p)
    for p in all_optimizer_params
]

model_ids = [
    id(p)
    for p in trainable_tensor_list
]

duplicates = (
    len(optimizer_ids)
    - len(set(optimizer_ids))
)

missing = set(model_ids) - set(
    optimizer_ids
)

unexpected = set(
    optimizer_ids
) - set(model_ids)

print(
    "\n[PARAMETER COVERAGE]"
)

print(
    "Model trainable tensors:",
    len(model_ids)
)

print(
    "Optimizer tensors:",
    len(optimizer_ids)
)

print(
    "Duplicates:",
    duplicates
)

print(
    "Missing:",
    len(missing)
)

print(
    "Unexpected:",
    len(unexpected)
)

if duplicates != 0:
    raise RuntimeError(
        "Duplicate optimizer parameters."
    )

if missing:
    raise RuntimeError(
        "Trainable model parameters missing "
        "from optimizer."
    )

if unexpected:
    raise RuntimeError(
        "Optimizer contains unexpected parameters."
    )

if len(optimizer_ids) != 401:
    raise RuntimeError(
        f"Expected 401 optimizer tensors, "
        f"got {len(optimizer_ids)}"
    )

print(
    "PASS: All 401 trainable tensors covered exactly once"
)

# ------------------------------------------------------------------------------
# 6. TOTAL PARAMETER COUNT BY GROUP
# ------------------------------------------------------------------------------

print(
    "\n[PARAMETER COUNTS]"
)

group_parameter_counts = {}

for group in optimizer_v5.param_groups:

    name = group["name"]

    count = sum(
        p.numel()
        for p in group["params"]
    )

    group_parameter_counts[name] = count

    print(
        f"{name:20s}: {count:,}"
    )

total_group_params = sum(
    group_parameter_counts.values()
)

print(
    "TOTAL:",
    f"{total_group_params:,}"
)

if total_group_params != expected_params:
    raise RuntimeError(
        "Optimizer parameter count does not "
        "match V5 trainable parameter count."
    )

print(
    "PASS: Parameter totals exact"
)

# ------------------------------------------------------------------------------
# 7. CREATE EXACT SCHEDULER
# ------------------------------------------------------------------------------

TOTAL_STEPS = 1920

scheduler_v5 = torch.optim.lr_scheduler.CosineAnnealingLR(
    optimizer_v5,
    T_max=TOTAL_STEPS,
    eta_min=0.0,
)

print(
    "\n[SCHEDULER]"
)

print(
    "Type:",
    type(scheduler_v5).__name__
)

print(
    "T_max:",
    scheduler_v5.T_max
)

print(
    "eta_min:",
    scheduler_v5.eta_min
)

if scheduler_v5.T_max != 1920:
    raise RuntimeError(
        f"Unexpected T_max: {scheduler_v5.T_max}"
    )

if scheduler_v5.eta_min != 0.0:
    raise RuntimeError(
        f"Unexpected eta_min: {scheduler_v5.eta_min}"
    )

print(
    "PASS: CosineAnnealingLR configured exactly"
)

# ------------------------------------------------------------------------------
# 8. INITIAL LR AUDIT
# ------------------------------------------------------------------------------

print(
    "\n[INITIAL LEARNING RATES]"
)

for group in optimizer_v5.param_groups:

    print(
        f"{group['name']:20s}: "
        f"{group['lr']:.8f}"
    )

expected_lrs = {
    "vision": 1e-5,
    "projector": 1e-4,
    "conditioner": 1e-4,
    "structured_heads": 1e-4,
    "mT5": 5e-5,
}

for group in optimizer_v5.param_groups:

    if group["lr"] != expected_lrs[
        group["name"]
    ]:

        raise RuntimeError(
            f"Initial LR mismatch: "
            f"{group['name']}"
        )

print(
    "PASS: Initial LRs exact"
)

# ------------------------------------------------------------------------------
# 9. SERIALIZATION / RESTORATION AUDIT
# ------------------------------------------------------------------------------

print(
    "\n[SERIALIZATION AUDIT]"
)

optimizer_state_test = (
    optimizer_v5.state_dict()
)

scheduler_state_test = (
    scheduler_v5.state_dict()
)

optimizer_v5_restored = torch.optim.AdamW(
    [
        {
            "params": list(v5.vision.parameters()),
            "lr": 1e-5,
            "weight_decay": 0.01,
            "name": "vision",
        },
        {
            "params": list(v5.projector.parameters()),
            "lr": 1e-4,
            "weight_decay": 0.01,
            "name": "projector",
        },
        {
            "params": list(v5.conditioner.parameters()),
            "lr": 1e-4,
            "weight_decay": 0.01,
            "name": "conditioner",
        },
        {
            "params": (
                list(v5.concept_head.parameters())
                + list(v5.negative_head.parameters())
                + list(v5.attribute_head.parameters())
            ),
            "lr": 1e-4,
            "weight_decay": 0.01,
            "name": "structured_heads",
        },
        {
            "params": list(v5.mt5.parameters()),
            "lr": 5e-5,
            "weight_decay": 0.01,
            "name": "mT5",
        },
    ]
)

optimizer_v5_restored.load_state_dict(
    optimizer_state_test
)

scheduler_v5_restored = (
    torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer_v5_restored,
        T_max=TOTAL_STEPS,
        eta_min=0.0,
    )
)

scheduler_v5_restored.load_state_dict(
    scheduler_state_test
)

if (
    optimizer_v5_restored.state_dict()
    != optimizer_state_test
):
    raise RuntimeError(
        "Optimizer serialization mismatch."
    )

if (
    scheduler_v5_restored.state_dict()
    != scheduler_state_test
):
    raise RuntimeError(
        "Scheduler serialization mismatch."
    )

print(
    "PASS: Optimizer serialization/restoration"
)

print(
    "PASS: Scheduler serialization/restoration"
)

# ------------------------------------------------------------------------------
# 10. SAFETY
# ------------------------------------------------------------------------------

print(
    "\n[SAFETY]"
)

print(
    "Optimizer step: NOT RUN"
)

print(
    "Scheduler step: NOT RUN"
)

print(
    "Backward: NOT RUN"
)

print(
    "Training: NOT STARTED"
)

print(
    "V4 checkpoint: UNTOUCHED"
)

# ------------------------------------------------------------------------------
# FINAL
# ------------------------------------------------------------------------------

print(
    "\n" + "=" * 80
)

print(
    "STATUS"
)

print(
    "=" * 80
)

print(
    "PASS: 5 optimizer groups"
)

print(
    "PASS: 401 optimizer tensors"
)

print(
    "PASS: 0 duplicate parameters"
)

print(
    "PASS: 0 missing parameters"
)

print(
    "PASS: 0 unexpected parameters"
)

print(
    "PASS: 387,020,219 optimizer parameters"
)

print(
    "PASS: Initial LRs exact"
)

print(
    "PASS: CosineAnnealingLR T_max = 1920"
)

print(
    "PASS: eta_min = 0"
)

print(
    "PASS: Serialization/restoration"
)

print(
    "\nNO OPTIMIZER STEP"
)

print(
    "NO SCHEDULER STEP"
)

print(
    "NO TRAINING"
)

print(
    "\nNEXT: SEND FULL OUTPUT"
)

print(
    "=" * 80
)

--- CELL 108 | hits: ['load_state_dict'] ---
# ================================================================================
# CELL 30 — V5 CHECKPOINT / RESUME AUDIT
# ================================================================================

import os
import copy
import random
import numpy as np
import torch

print("=" * 80)
print("CELL 30 — V5 CHECKPOINT / RESUME AUDIT")
print("=" * 80)

# ------------------------------------------------------------------------------
# 1. PATHS
# ------------------------------------------------------------------------------

V5_ROOT = (
    "/content/drive/MyDrive/"
    "NoiSoi_Matching/baseline_model_v5"
)

V5_CHECKPOINT_DIR = os.path.join(
    V5_ROOT,
    "checkpoints",
)

os.makedirs(
    V5_CHECKPOINT_DIR,
    exist_ok=True,
)

TEST_CHECKPOINT = os.path.join(
    V5_CHECKPOINT_DIR,
    "_resume_audit_tmp.pt",
)

print("\n[PATH]")
print(
    "V5 root:",
    V5_ROOT
)

print(
    "Checkpoint dir:",
    V5_CHECKPOINT_DIR
)

print(
    "Temporary checkpoint:",
    TEST_CHECKPOINT
)

# ------------------------------------------------------------------------------
# 2. VERIFY REQUIRED RUNTIME OBJECTS
# ------------------------------------------------------------------------------

required_objects = [
    "v5",
    "optimizer_v5",
    "scheduler_v5",
]

print("\n[RUNTIME OBJECTS]")

for name in required_objects:

    found = name in globals()

    print(
        f"{name:20s}: "
        f"{'FOUND' if found else 'MISSING'}"
    )

    if not found:
        raise RuntimeError(
            f"Required object missing: {name}"
        )

print(
    "PASS: V5 / optimizer / scheduler present"
)

# ------------------------------------------------------------------------------
# 3. CREATE AUDIT HISTORY
# ------------------------------------------------------------------------------

history_v5 = {
    "train_loss": [2.75],
    "val_loss": [2.80],
}

best_val_v5 = 2.80
start_epoch_v5 = 1

# ------------------------------------------------------------------------------
# 4. CAPTURE RNG STATES
# ------------------------------------------------------------------------------

rng_state_before = {
    "python": random.getstate(),
    "numpy": np.random.get_state(),
    "torch": torch.get_rng_state(),
}

if torch.cuda.is_available():

    cuda_rng_state_before = (
        torch.cuda.get_rng_state_all()
    )

else:

    cuda_rng_state_before = None

# ------------------------------------------------------------------------------
# 5. SNAPSHOT MODEL
# ------------------------------------------------------------------------------

model_state_before = {
    key: value.detach().cpu().clone()
    for key, value in v5.state_dict().items()
}

optimizer_state_before = copy.deepcopy(
    optimizer_v5.state_dict()
)

scheduler_state_before = copy.deepcopy(

In [5]:

from google.colab import drive
drive.mount("/content/drive", force_remount=False)

import json
from pathlib import Path

NOTEBOOK_PATH = Path(
    "/content/drive/MyDrive/Colab Notebooks/25sep.ipynb"
)

assert NOTEBOOK_PATH.exists(), f"Notebook not found: {NOTEBOOK_PATH}"

with NOTEBOOK_PATH.open("r", encoding="utf-8") as f:
    nb = json.load(f)

terms = [
    "test_predictions_712.csv",
    "test_predictions",
    "prediction_path",
    "to_csv(",
    "model.generate",
    "mt5.generate",
    "generate_one",
    "generate_batch",
    "max_new_tokens",
    "max_length",
    "num_beams",
    "do_sample",
    "early_stopping",
    "load_state_dict",
    "torch.load(",
    "best.pt",
    "last.pt",
]

print("Notebook cells:", len(nb.get("cells", [])))
print("Searching source only; no model/checkpoint will be loaded.")

for i, cell in enumerate(nb.get("cells", [])):
    source = "".join(cell.get("source", []))
    lines = source.splitlines()

    hits = [
        j for j, line in enumerate(lines)
        if any(term.lower() in line.lower() for term in terms)
    ]

    if not hits:
        continue

    # Merge nearby line ranges to avoid dumping entire training cells.
    ranges = []
    for j in hits:
        start, end = max(0, j - 4), min(len(lines), j + 6)
        if ranges and start <= ranges[-1][1]:
            ranges[-1] = (ranges[-1][0], max(ranges[-1][1], end))
        else:
            ranges.append((start, end))

    print(f"\n{'=' * 30} CELL {i} {'=' * 30}")
    for start, end in ranges:
        print(f"\n--- source lines {start + 1}-{end} ---")
        for k in range(start, end):
            print(f"{k + 1:4}: {lines[k]}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Notebook cells: 162
Searching source only; no model/checkpoint will be loaded.

============================== CELL 0 ==============================

--- source lines 69-74 ---
  69:     f"{V4_DIR}/checkpoints/epoch_03.pt"
  70: )
  71:
  72: BEST_CKPT = (
  73:     f"{V4_DIR}/checkpoints/best.pt"
  74: )

============================== CELL 1 ==============================

--- source lines 86-95 ---
  86:     f"{V4_DIR}/checkpoints/epoch_03.pt"
  87: )
  88:
  89: BEST_CKPT = (
  90:     f"{V4_DIR}/checkpoints/best.pt"
  91: )
  92:
  93: # ------------------------------------------------
  94: # Path checks
  95: # ------------------------------------------------

--- source lines 564-575 ---
 564:         )
 565:
 566:         labels = self.tokenizer(
 567:             report,
 568:             padding="max_length",
 569:             truncation=True,
 570:             max_length=self.max_target_length,
 571:             return_tensors="pt",
 572:         )["input_ids"][0]
 573:
 574:         labels = labels.clone()
 575:

--- source lines 984-999 ---
 984: # ================================================================
 985:
 986: print("\nLOADING CHECKPOINTS")
 987:
 988: E2 = torch.load(
 989:     E2_CKPT,
 990:     map_location="cpu",
 991:     weights_only=False,
 992: )
 993:
 994: E3 = torch.load(
 995:     E3_CKPT,
 996:     map_location="cpu",
 997:     weights_only=False,
 998: )
 999:

--- source lines 1013-1022 ---
1013: # ------------------------------------------------
1014: # Strict load
1015: # ------------------------------------------------
1016:
1017: load_result = model.load_state_dict(
1018:     E2["model_state"],
1019:     strict=True,
1020: )
1021:
1022: print(

--- source lines 1027-1036 ---
1027:     "E2 best_val:",
1028:     E2["best_val"]
1029: )
1030:
1031: model.load_state_dict(
1032:     E3["model_state"],
1033:     strict=True,
1034: )
1035:
1036: print(

--- source lines 1098-1107 ---
1098: # ================================================================
1099: # 14. SNAPSHOT
1100: # ================================================================
1101:
1102: model.load_state_dict(
1103:     E2["model_state"],
1104:     strict=True,
1105: )
1106:
1107: model.eval()

--- source lines 1414-1423 ---
1414:
1415: @torch.no_grad()
1416: def exact_generate(
1417:     cond,
1418:     max_new_tokens=20,
1419: ):
1420:
1421:     encoder_outputs = (
1422:         model.mt5.encoder(
1423:             inputs_embeds=

--- source lines 1439-1448 ---
1439:
1440:     generated = []
1441:
1442:     for _ in range(
1443:         max_new_tokens
1444:     ):
1445:
1446:         out = model.mt5(
1447:             encoder_outputs=
1448:                 encoder_outputs,

--- source lines 1503-1512 ---
1503:     print("=" * 70)
1504:     print(checkpoint_name)
1505:     print("=" * 70)
1506:
1507:     model.load_state_dict(
1508:         checkpoint["model_state"],
1509:         strict=True,
1510:     )
1511:
1512:     model.eval()

--- source lines 1898-1907 ---
1898: # ================================================================
1899: # RESTORE MODEL TO ORIGINAL E2 STATE
1900: # ================================================================
1901:
1902: model.load_state_dict(
1903:     model_snapshot,
1904:     strict=True,
1905: )
1906:
1907: print(

============================== CELL 2 ==============================

--- source lines 84-100 ---
  84:
  85: # ------------------------------------------------------------
  86: # STRICT LOAD E2
  87: # ------------------------------------------------------------
  88: model.load_state_dict(E2["model_state"], strict=True)
  89:
  90: print("\n✓ E2 STRICT LOAD PASSED")
  91:
  92: # ------------------------------------------------------------
  93: # STRICT LOAD E3
  94: # ------------------------------------------------------------
  95: model.load_state_dict(E3["model_state"], strict=True)
  96:
  97: print("✓ E3 STRICT LOAD PASSED")
  98:
  99: print("\n" + "=" * 70)
 100: print("V4 CHECKPOINT RESTORE: PASS")

============================== CELL 5 ==============================

--- source lines 184-193 ---
 184: # 3. AUTOREGRESSIVE GENERATION
 185: # ============================================================
 186:
 187: @torch.no_grad()
 188: def generate_one(cond, max_new_tokens=20):
 189:
 190:     encoder_outputs = model.mt5.encoder(
 191:         inputs_embeds=cond["inputs_embeds"],
 192:         attention_mask=cond["attention_mask"],
 193:         return_dict=True,

--- source lines 201-210 ---
 201:     )
 202:
 203:     generated = []
 204:
 205:     for _ in range(max_new_tokens):
 206:
 207:         out = model.mt5(
 208:             encoder_outputs=encoder_outputs,
 209:             attention_mask=cond["attention_mask"],
 210:             decoder_input_ids=decoder_ids,

--- source lines 276-285 ---
 276:     print("\n" + "=" * 70)
 277:     print(f"CHECKPOINT: {epoch_name}")
 278:     print("=" * 70)
 279:
 280:     model.load_state_dict(
 281:         ckpt["model_state"],
 282:         strict=True,
 283:     )
 284:
 285:     model.eval()

--- source lines 330-339 ---
 330:                 cond,
 331:                 batch["labels"].to(device),
 332:             )
 333:
 334:             text = generate_one(cond)
 335:
 336:             losses.append(loss)
 337:             outputs.append(text)
 338:
 339:             concept_counts.append(

============================== CELL 6 ==============================

--- source lines 55-64 ---
  55:     print("\n" + "=" * 70)
  56:     print(f"LOGIT INTERVENTION — {epoch_name}")
  57:     print("=" * 70)
  58:
  59:     model.load_state_dict(
  60:         ckpt["model_state"],
  61:         strict=True,
  62:     )
  63:
  64:     model.eval()

============================== CELL 7 ==============================

--- source lines 36-45 ---
  36:     f"Expected 756 validation cases, "
  37:     f"found {len(val_loader.dataset)}"
  38: )
  39:
  40: model.load_state_dict(E3["model_state"], strict=True)
  41: model.to(device)
  42: model.eval()
  43:
  44: print("=" * 70)
  45: print("V4 E3 — VALIDATION SENSITIVITY")

--- source lines 346-360 ---
 346:     diagnostics_dir,
 347:     "e3_val756_first_token_sensitivity_summary.csv",
 348: )
 349:
 350: sensitivity_df.to_csv(
 351:     detail_path,
 352:     index=False,
 353: )
 354:
 355: summary_df.to_csv(
 356:     summary_path,
 357:     index=False,
 358: )
 359:
 360: assert os.path.isfile(detail_path)

============================== CELL 9 ==============================

--- source lines 10-19 ---
  10: # ------------------------------------------------------------
  11: # 1. Load V4 E3 into reference model
  12: # ------------------------------------------------------------
  13:
  14: model.load_state_dict(
  15:     E3["model_state"],
  16:     strict=True,
  17: )
  18:
  19: model.eval()

============================== CELL 10 ==============================

--- source lines 14-23 ---
  14: # ------------------------------------------------------------
  15: # 0. Restore V4 E3 reference + V5 warm-start
  16: # ------------------------------------------------------------
  17:
  18: model.load_state_dict(
  19:     E3["model_state"],
  20:     strict=True,
  21: )
  22: model.eval()
  23: v5.eval()

============================== CELL 23 ==============================

--- source lines 184-193 ---
 184: # ------------------------------------------------------------
 185: # 9. Load
 186: # ------------------------------------------------------------
 187:
 188: loaded = torch.load(
 189:     DRYRUN_PATH,
 190:     map_location="cpu",
 191:     weights_only=False,
 192: )
 193:

--- source lines 201-210 ---
 201: # ------------------------------------------------------------
 202:
 203: v5_restore = V5Model()
 204:
 205: v5_restore.load_state_dict(
 206:     loaded["model_state"],
 207:     strict=True,
 208: )
 209:
 210: optimizer_restore = torch.optim.AdamW(

--- source lines 242-255 ---
 242:     T_max=1920,
 243:     eta_min=0,
 244: )
 245:
 246: optimizer_restore.load_state_dict(
 247:     loaded["optimizer_state"]
 248: )
 249:
 250: scheduler_restore.load_state_dict(
 251:     loaded["scheduler_state"]
 252: )
 253:
 254: # ------------------------------------------------------------
 255: # 11. Strict weight equality

============================== CELL 24 ==============================

--- source lines 258-268 ---
 258:     )
 259:     for epoch in range(1, EPOCHS + 1)
 260: }
 261:
 262: checkpoint_paths["last"] = os.path.join(CKPT_DIR, "last.pt")
 263: checkpoint_paths["best"] = os.path.join(CKPT_DIR, "best.pt")
 264:
 265: print()
 266: print("Checkpoint directory:")
 267: print(CKPT_DIR)
 268:

============================== CELL 54 ==============================

--- source lines 17-26 ---
  17: print("Checkpoint:", CKPT)
  18: print("Size (MB):", round(os.path.getsize(CKPT) / 1024**2, 2))
  19:
  20: # Load to CPU only
  21: ckpt = torch.load(
  22:     CKPT,
  23:     map_location="cpu",
  24:     weights_only=False
  25: )
  26:

============================== CELL 68 ==============================

--- source lines 88-98 ---
  88: test_text = "test"
  89:
  90: encoded = tokenizer(
  91:     test_text,
  92:     max_length=96,
  93:     padding="max_length",
  94:     truncation=True,
  95:     return_tensors="pt",
  96: )
  97:
  98: print("\n[TOKENIZER SMOKE TEST]")

--- source lines 110-118 ---
 110: print("=" * 80)
 111:
 112: print("PASS: image_processor available")
 113: print("PASS: tokenizer available")
 114: print("PASS: tokenizer max_length=96 smoke test")
 115: print("")
 116: print("V5 TRAINING: NOT STARTED")
 117: print("V4 CHECKPOINTS: UNTOUCHED")
 118: print("=" * 80)

============================== CELL 73 ==============================

--- source lines 260-271 ---
 260:         # Report labels
 261:         # -------------------------------------------------------------
 262:         labels = self.tokenizer(
 263:             report,
 264:             padding="max_length",
 265:             truncation=True,
 266:             max_length=self.max_target_length,
 267:             return_tensors="pt",
 268:         )["input_ids"][0]
 269:
 270:         labels = labels.clone()
 271:

============================== CELL 75 ==============================

--- source lines 31-40 ---
  31:
  32: candidates = [
  33:     os.path.join(V4_CKPT_DIR, "epoch_03.pt"),
  34:     os.path.join(V4_CKPT_DIR, "epoch_03.pth"),
  35:     os.path.join(V4_CKPT_DIR, "best.pt"),
  36: ]
  37:
  38: existing = [p for p in candidates if os.path.exists(p)]
  39:
  40: print("\n[V4 CHECKPOINT CANDIDATES]")

--- source lines 85-94 ---
  85:
  86: # -------------------------------------------------------------------------
  87: # 4. Load V4 weights into compatible V5 keys
  88: # -------------------------------------------------------------------------
  89: ckpt = torch.load(
  90:     v4_ckpt_path,
  91:     map_location="cpu",
  92: )
  93:
  94: print("\n[V4 CHECKPOINT TYPE]")

--- source lines 135-144 ---
 135:
 136: # -------------------------------------------------------------------------
 137: # 5. Load compatible weights
 138: # -------------------------------------------------------------------------
 139: load_result = v5.load_state_dict(
 140:     compatible,
 141:     strict=False,
 142: )
 143:
 144: print("\n[LOAD RESULT]")

============================== CELL 82 ==============================

--- source lines 101-110 ---
 101: # 3. Load checkpoint
 102: # ------------------------------------------------------------------
 103: print("\n[LOAD CHECKPOINT]")
 104:
 105: checkpoint = torch.load(
 106:     checkpoint_path,
 107:     map_location="cpu",
 108:     weights_only=False,
 109: )
 110:

--- source lines 206-215 ---
 206:
 207: # ------------------------------------------------------------------
 208: # 9. Load only compatible weights
 209: # ------------------------------------------------------------------
 210: load_result = v5.load_state_dict(
 211:     compatible,
 212:     strict=False,
 213: )
 214:
 215: print("\n[LOAD RESULT]")

============================== CELL 84 ==============================

--- source lines 91-100 ---
  91: # 4. Load ONLY compatible V4 weights
  92: # ------------------------------------------------------------------
  93: print("\n[LOAD V4 -> V5]")
  94:
  95: load_result = v5.load_state_dict(
  96:     fresh_compatible,
  97:     strict=False,
  98: )
  99:
 100: print(

============================== CELL 95 ==============================

--- source lines 422-435 ---
 422:     T_max=TOTAL_STEPS,
 423:     eta_min=ETA_MIN,
 424: )
 425:
 426: test_optimizer.load_state_dict(
 427:     copy.deepcopy(optimizer_state)
 428: )
 429:
 430: test_scheduler.load_state_dict(
 431:     copy.deepcopy(scheduler_state)
 432: )
 433:
 434: if (
 435:     test_scheduler.state_dict()

============================== CELL 96 ==============================

--- source lines 274-283 ---
 274:     scheduler,
 275:     map_location=None,
 276: ):
 277:
 278:     checkpoint = torch.load(
 279:         path,
 280:         map_location=map_location,
 281:     )
 282:
 283:     required_keys = [

--- source lines 303-320 ---
 303:             "Checkpoint missing keys: "
 304:             f"{missing_keys}"
 305:         )
 306:
 307:     model.load_state_dict(
 308:         checkpoint["model_state"]
 309:     )
 310:
 311:     optimizer.load_state_dict(
 312:         checkpoint["optimizer_state"]
 313:     )
 314:
 315:     scheduler.load_state_dict(
 316:         checkpoint["scheduler_state"]
 317:     )
 318:
 319:     restore_rng_state(
 320:         checkpoint["rng_state"]

============================== CELL 97 ==============================

--- source lines 161-170 ---
 161:     raise FileNotFoundError(
 162:         "V4 Epoch 3 checkpoint not found."
 163:     )
 164:
 165: checkpoint = torch.load(
 166:     V4_CHECKPOINT_PATH,
 167:     map_location="cpu",
 168: )
 169:
 170: print(

============================== CELL 104 ==============================

--- source lines 62-71 ---
  62: # ------------------------------------------------------------------------------
  63:
  64: print("\n[LOAD V4 CHECKPOINT]")
  65:
  66: v4_ckpt = torch.load(
  67:     V4_EPOCH3,
  68:     map_location="cpu",
  69: )
  70:
  71: print(

--- source lines 489-498 ---
 489:
 490: # Re-read checkpoint from disk and compare its tensors
 491: # against the original loaded checkpoint.
 492:
 493: v4_ckpt_after = torch.load(
 494:     V4_EPOCH3,
 495:     map_location="cpu",
 496: )
 497:
 498: v4_state_after = v4_ckpt_after[

============================== CELL 105 ==============================

--- source lines 3-12 ---
   3: # ================================================================================
   4:
   5: print("\n[V4 CHECKPOINT SAFETY]")
   6:
   7: v4_ckpt_after = torch.load(
   8:     V4_EPOCH3,
   9:     map_location="cpu",
  10: )
  11:
  12: v4_state_after = v4_ckpt_after["model_state"]

============================== CELL 106 ==============================

--- source lines 213-222 ---
 213:     raise FileNotFoundError(
 214:         V4_EPOCH3
 215:     )
 216:
 217: v4_ckpt = torch.load(
 218:     V4_EPOCH3,
 219:     map_location="cpu",
 220: )
 221:
 222: v4_state = v4_ckpt["model_state"]

--- source lines 429-438 ---
 429: # ================================================================================
 430: # 13. V4 CHECKPOINT IMMUTABILITY
 431: # ================================================================================
 432:
 433: v4_check_after = torch.load(
 434:     V4_EPOCH3,
 435:     map_location="cpu",
 436: )
 437:
 438: v4_after = v4_check_after[

============================== CELL 107 ==============================

--- source lines 470-479 ---
 470:         },
 471:     ]
 472: )
 473:
 474: optimizer_v5_restored.load_state_dict(
 475:     optimizer_state_test
 476: )
 477:
 478: scheduler_v5_restored = (
 479:     torch.optim.lr_scheduler.CosineAnnealingLR(

--- source lines 482-491 ---
 482:         eta_min=0.0,
 483:     )
 484: )
 485:
 486: scheduler_v5_restored.load_state_dict(
 487:     scheduler_state_test
 488: )
 489:
 490: if (
 491:     optimizer_v5_restored.state_dict()

============================== CELL 108 ==============================

--- source lines 179-188 ---
 179: # ------------------------------------------------------------------------------
 180:
 181: print("\n[LOAD]")
 182:
 183: loaded = torch.load(
 184:     TEST_CHECKPOINT,
 185:     map_location="cpu",
 186: )
 187:
 188: required_keys = [

--- source lines 227-236 ---
 227: v5_restored = copy.deepcopy(
 228:     v5
 229: )
 230:
 231: v5_restored.load_state_dict(
 232:     loaded["model_state"]
 233: )
 234:
 235: v5_restored.eval()
 236:

--- source lines 318-327 ---
 318:         },
 319:     ]
 320: )
 321:
 322: optimizer_restored.load_state_dict(
 323:     loaded["optimizer_state"]
 324: )
 325:
 326: if (
 327:     optimizer_restored.state_dict()

--- source lines 351-360 ---
 351:         eta_min=0.0,
 352:     )
 353: )
 354:
 355: scheduler_restored.load_state_dict(
 356:     loaded["scheduler_state"]
 357: )
 358:
 359: if (
 360:     scheduler_restored.state_dict()

============================== CELL 116 ==============================

--- source lines 45-54 ---
  45: print("\n[LOADING]")
  46: print("Loading V4 Epoch 3 checkpoint on CPU...")
  47: print("This avoids placing the 4.4 GB checkpoint on GPU.")
  48:
  49: v4_ckpt = torch.load(
  50:     V4_CKPT,
  51:     map_location="cpu",
  52:     weights_only=False
  53: )
  54:

============================== CELL 119 ==============================

--- source lines 367-377 ---
 367:         )
 368:
 369:         labels = self.tokenizer(
 370:             report,
 371:             max_length=self.max_target_length,
 372:             padding="max_length",
 373:             truncation=True,
 374:             return_tensors="pt"
 375:         )["input_ids"].squeeze(0)
 376:
 377:         labels[labels == self.tokenizer.pad_token_id] = -100

============================== CELL 120 ==============================

--- source lines 368-378 ---
 368:         )
 369:
 370:         labels = self.tokenizer(
 371:             report,
 372:             max_length=self.max_target_length,
 373:             padding="max_length",
 374:             truncation=True,
 375:             return_tensors="pt"
 376:         )["input_ids"].squeeze(0)
 377:
 378:         labels[

============================== CELL 122 ==============================

--- source lines 94-104 ---
  94:         )
  95:
  96:         labels = self.tokenizer(
  97:             report,
  98:             max_length=self.max_target_length,
  99:             padding="max_length",
 100:             truncation=True,
 101:             return_tensors="pt"
 102:         )["input_ids"].squeeze(0)
 103:
 104:         labels[

============================== CELL 126 ==============================

--- source lines 4-15 ---
   4: #
   5: # Checkpoint:
   6: #   - every 48 optimizer steps
   7: #   - rolling checkpoint: resume_0.pt / resume_1.pt
   8: #   - last.pt
   9: #   - epoch_XX.pt
  10: #   - best.pt
  11: #
  12: # IMPORTANT:
  13: # Run after runtime reconnect AND after restoring:
  14: #   v5
  15: #   train_loader_v5

--- source lines 88-101 ---
  88:     exist_ok=True
  89: )
  90:
  91: LAST_CKPT = (
  92:     V5_CKPT_DIR / "last.pt"
  93: )
  94:
  95: BEST_CKPT = (
  96:     V5_CKPT_DIR / "best.pt"
  97: )
  98:
  99: RESUME_FILES = [
 100:     V5_CKPT_DIR / "resume_0.pt",
 101:     V5_CKPT_DIR / "resume_1.pt",

--- source lines 312-321 ---
 312: def checkpoint_step(path):
 313:
 314:     try:
 315:
 316:         ckpt = torch.load(

In [6]:

from google.colab import drive
drive.mount("/content/drive")

import os
import re
import json
from pathlib import Path

ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
NB = Path("/content/drive/MyDrive/Colab Notebooks/25sep.ipynb")
TARGET = "test_predictions_712.csv"

print("=" * 80)
print("1. CSV METADATA — NO CONTENT MODIFICATION")
print("=" * 80)

csv_path = ROOT / "baseline_model_v5" / TARGET
if csv_path.exists():
    st = csv_path.stat()
    print("Path:", csv_path)
    print("Size:", st.st_size, "bytes")
    print("Modified:", __import__("datetime").datetime.fromtimestamp(
        st.st_mtime).isoformat())
    with open(csv_path, "r", encoding="utf-8-sig") as f:
        print("Header:", f.readline().strip())
else:
    print("CSV not found at expected path:", csv_path)

# Search for source that creates predictions, invokes generation,
# loads a model for inference, or writes the target CSV.
patterns = re.compile(
    r"test_predictions_712|test_predictions|prediction_path|"
    r"predictions.*to_csv|to_csv.*predictions|"
    r"generate_one|generate_batch|model\.generate|mt5\.generate|"
    r"tokenizer\.decode|safe_decode|num_beams|max_new_tokens|"
    r"do_sample|early_stopping|v5\.load_state_dict|"
    r"BEST_CKPT|LAST_CKPT|best\.pt|last\.pt",
    re.IGNORECASE
)

print("\n" + "=" * 80)
print("2. NOTEBOOK SOURCE MATCHES")
print("=" * 80)

if NB.exists():
    with open(NB, "r", encoding="utf-8") as f:
        notebook = json.load(f)

    hits = 0
    for i, cell in enumerate(notebook.get("cells", [])):
        if cell.get("cell_type") != "code":
            continue
        src = "".join(cell.get("source", []))
        lines = src.splitlines()
        matches = [
            j for j, line in enumerate(lines)
            if patterns.search(line)
        ]
        if not matches:
            continue

        # Merge nearby matching lines into compact context ranges.
        ranges = []
        for j in matches:
            a, b = max(0, j - 3), min(len(lines), j + 4)
            if ranges and a <= ranges[-1][1]:
                ranges[-1] = (ranges[-1][0], max(ranges[-1][1], b))
            else:
                ranges.append((a, b))

        print(f"\n--- CELL {i} | {len(matches)} matching lines ---")
        for a, b in ranges[:12]:
            for j in range(a, b):
                print(f"{j+1:4}: {lines[j][:300]}")
            print("...")
        hits += len(matches)

    print("\nTotal matching source lines:", hits)
else:
    print("Notebook not found:", NB)

print("\n" + "=" * 80)
print("3. PROJECT SOURCE FILES")
print("=" * 80)

source_exts = {".py", ".ipynb", ".sh", ".json", ".yaml", ".yml", ".md", ".txt"}
file_count = 0
match_count = 0
max_files = 5000

for dirpath, dirnames, filenames in os.walk(ROOT):
    # Skip large/non-source directories.
    dirnames[:] = [
        d for d in dirnames
        if d not in {".git", "__pycache__", "node_modules"}
    ]

    for name in filenames:
        p = Path(dirpath) / name
        if p.suffix.lower() not in source_exts:
            continue
        file_count += 1
        if file_count > max_files:
            print("Stopped at file limit:", max_files)
            break

        try:
            if p.stat().st_size > 5 * 1024 * 1024:
                continue
            if p.suffix.lower() == ".ipynb":
                with open(p, "r", encoding="utf-8") as f:
                    obj = json.load(f)
                chunks = [
                    "".join(c.get("source", []))
                    for c in obj.get("cells", [])
                    if c.get("cell_type") == "code"
                ]
                text = "\n".join(chunks)
            else:
                text = p.read_text(encoding="utf-8", errors="ignore")

            lines = text.splitlines()
            found = [
                j for j, line in enumerate(lines)
                if patterns.search(line)
            ]
            if found:
                match_count += len(found)
                print(f"\nFILE: {p}")
                for j in found[:12]:
                    a, b = max(0, j-2), min(len(lines), j+3)
                    print(f"  line {j+1}:")
                    for k in range(a, b):
                        print(f"    {k+1}: {lines[k][:250]}")
                if len(found) > 12:
                    print(f"  ... {len(found)-12} additional matching lines")
        except Exception as e:
            print("Skipped unreadable file:", p, "|", type(e).__name__)

    if file_count > max_files:
        break

print("\nSource files scanned:", min(file_count, max_files))
print("Matching lines in project sources:", match_count)
print("\nREAD-ONLY AUDIT COMPLETE — no checkpoint loaded; no files written.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
================================================================================
1. CSV METADATA — NO CONTENT MODIFICATION
================================================================================
Path: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/test_predictions_712.csv
Size: 62941 bytes
Modified: 2026-09-30T16:34:27
Header: case_id,prediction,ground_truth

================================================================================
2. NOTEBOOK SOURCE MATCHES
================================================================================

--- CELL 0 | 2 matching lines ---
  69:     f"{V4_DIR}/checkpoints/epoch_03.pt"
  70: )
  71:
  72: BEST_CKPT = (
  73:     f"{V4_DIR}/checkpoints/best.pt"
  74: )
...

--- CELL 1 | 9 matching lines ---
  86:     f"{V4_DIR}/checkpoints/epoch_03.pt"
  87: )
  88:
  89: BEST_CKPT = (
  90:     f"{V4_DIR}/checkpoints/best.pt"
  91: )
  92:
  93: # ------------------------------------------------
...
 101:     "V4 config": CONFIG_PATH,
 102:     "E2 checkpoint": E2_CKPT,
 103:     "E3 checkpoint": E3_CKPT,
 104:     "Best checkpoint": BEST_CKPT,
 105: }
 106:
 107: print("\nPATH CHECK")
...
1116: # SAFE DECODE
1117: # ================================================================
1118:
1119: def safe_decode(ids):
1120:
1121:     if torch.is_tensor(ids):
1122:         ids = ids.detach().cpu().tolist()
...
1128:         for x in ids
1129:     ]
1130:
1131:     return tokenizer.decode(
1132:         ids,
1133:         skip_special_tokens=True,
1134:     ).strip()
...
1415: @torch.no_grad()
1416: def exact_generate(
1417:     cond,
1418:     max_new_tokens=20,
1419: ):
1420:
1421:     encoder_outputs = (
...
1440:     generated = []
1441:
1442:     for _ in range(
1443:         max_new_tokens
1444:     ):
1445:
1446:         out = model.mt5(
...
1484:             dim=1,
1485:         )
1486:
1487:     return safe_decode(
1488:         generated
1489:     )
1490:
...
1597:                 case["case_id"],
1598:
1599:             "ref":
1600:                 safe_decode(
1601:                     case["labels"]
1602:                 ),
1603:
...

--- CELL 4 | 4 matching lines ---
   2: # RESTORE SAFE DECODE HELPER
   3: # ============================================================
   4:
   5: def safe_decode(token_ids):
   6:     """
   7:     Decode generated mT5 token IDs while removing
   8:     special / sentinel artifacts.
...
  13:     if isinstance(token_ids, int):
  14:         token_ids = [token_ids]
  15:
  16:     return tokenizer.decode(
  17:         token_ids,
  18:         skip_special_tokens=True,
  19:         clean_up_tokenization_spaces=True,
...
  24: print("=" * 70)
  25:
  26: # sanity check
  27: test_text = safe_decode([tokenizer.eos_token_id])
  28: print("Test decode:", repr(test_text))
  29:
  30: assert isinstance(test_text, str)
  31:
  32: print("✓ safe_decode available")
...

--- CELL 5 | 4 matching lines ---
 185: # ============================================================
 186:
 187: @torch.no_grad()
 188: def generate_one(cond, max_new_tokens=20):
 189:
 190:     encoder_outputs = model.mt5.encoder(
 191:         inputs_embeds=cond["inputs_embeds"],
...
 202:
 203:     generated = []
 204:
 205:     for _ in range(max_new_tokens):
 206:
 207:         out = model.mt5(
 208:             encoder_outputs=encoder_outputs,
...
 229:             dim=1,
 230:         )
 231:
 232:     return safe_decode(generated)
 233:
 234:
 235: # ============================================================
...
 331:                 batch["labels"].to(device),
 332:             )
 333:
 334:             text = generate_one(cond)
 335:
 336:             losses.append(loss)
 337:             outputs.append(text)
...

--- CELL 6 | 3 matching lines ---
  34:     result = []
  35:
  36:     for p, token_id in zip(vals.tolist(), ids.tolist()):
  37:         token = tokenizer.decode(
  38:             [token_id],
  39:             skip_special_tokens=False,
  40:         )
...
 140:                 "max_abs_logit_diff": max_abs_diff,
 141:                 "cosine_similarity": cosine,
 142:                 "argmax_changed": argmax_changed,
 143:                 "full_top_token": tokenizer.decode(
 144:                     [full_argmax],
 145:                     skip_special_tokens=False,
 146:                 ),
 147:                 "other_top_token": tokenizer.decode(
 148:                     [other_argmax],
 149:                     skip_special_tokens=False,
 150:                 ),
...

--- CELL 24 | 2 matching lines ---
 259:     for epoch in range(1, EPOCHS + 1)
 260: }
 261:
 262: checkpoint_paths["last"] = os.path.join(CKPT_DIR, "last.pt")
 263: checkpoint_paths["best"] = os.path.join(CKPT_DIR, "best.pt")
 264:
 265: print()
 266: print("Checkpoint directory:")
...

--- CELL 75 | 2 matching lines ---
  32: candidates = [
  33:     os.path.join(V4_CKPT_DIR, "epoch_03.pt"),
  34:     os.path.join(V4_CKPT_DIR, "epoch_03.pth"),
  35:     os.path.join(V4_CKPT_DIR, "best.pt"),
  36: ]
  37:
  38: existing = [p for p in candidates if os.path.exists(p)]
...
 136: # -------------------------------------------------------------------------
 137: # 5. Load compatible weights
 138: # -------------------------------------------------------------------------
 139: load_result = v5.load_state_dict(
 140:     compatible,
 141:     strict=False,
 142: )
...

--- CELL 82 | 1 matching lines ---
 207: # ------------------------------------------------------------------
 208: # 9. Load only compatible weights
 209: # ------------------------------------------------------------------
 210: load_result = v5.load_state_dict(
 211:     compatible,
 212:     strict=False,
 213: )
...

--- CELL 84 | 1 matching lines ---
  92: # ------------------------------------------------------------------
  93: print("\n[LOAD V4 -> V5]")
  94:
  95: load_result = v5.load_state_dict(
  96:     fresh_compatible,
  97:     strict=False,
  98: )
...

--- CELL 126 | 28 matching lines ---
   5: # Checkpoint:
   6: #   - every 48 optimizer steps
   7: #   - rolling checkpoint: resume_0.pt / resume_1.pt
   8: #   - last.pt
   9: #   - epoch_XX.pt
  10: #   - best.pt
  11: #
  12: # IMPORTANT:
  13: # Run after runtime reconnect AND after restoring:
...
  88:     exist_ok=True
  89: )
  90:
  91: LAST_CKPT = (
  92:     V5_CKPT_DIR / "last.pt"
  93: )
  94:
  95: BEST_CKPT = (
  96:     V5_CKPT_DIR / "best.pt"
  97: )
  98:
  99: RESUME_FILES = [
...
 349:             )
 350:
 351:
 352: if LAST_CKPT.exists():
 353:
 354:     step = checkpoint_step(
 355:         LAST_CKPT
 356:     )
 357:
 358:     if step >= 0:
 359:
 360:         candidate_paths.append(
 361:             (step, LAST_CKPT)
 362:         )
 363:
 364:
...
 423:     # Model
 424:     # --------------------------------------------------------
 425:
 426:     v5.load_state_dict(
 427:         checkpoint["model_state"],
 428:         strict=True,
 429:     )
...
 432:     # Optimizer
 433:     # --------------------------------------------------------
 434:
 435:     optimizer_v5.load_state_dict(
 436:         checkpoint["optimizer_state"]
 437:     )
 438:
...
 440:     # Scheduler
 441:     # --------------------------------------------------------
 442:
 443:     scheduler_v5.load_state_dict(
 444:         checkpoint["scheduler_state"]
 445:     )
 446:
...
 877:                     history,
 878:                 )
 879:
 880:                 # Also update last.pt
 881:                 save_checkpoint(
 882:                     LAST_CKPT,
 883:                     epoch,
 884:                     v5,
 885:                     optimizer_v5,
...
1166:         best_val = val_loss
1167:
1168:         save_checkpoint(
1169:             BEST_CKPT,
1170:             epoch,
1171:             v5,
1172:             optimizer_v5,
...
1207:     # ========================================================
1208:
1209:     save_checkpoint(
1210:         LAST_CKPT,
1211:         epoch,
1212:         v5,
1213:         optimizer_v5,
...
1277:     )
1278:
1279:     print(
1280:         f"last.pt exists  : {LAST_CKPT.exists()}"
1281:     )
1282:
1283:     print(
1284:         f"best.pt exists  : {BEST_CKPT.exists()}"
1285:     )
1286:
1287:     assert epoch_path.exists()
1288:     assert LAST_CKPT.exists()
1289:
1290:     if improved:
1291:         assert BEST_CKPT.exists()
1292:
1293:     print(
1294:         "CHECKPOINT STATUS: PASS"
...
1324: )
1325:
1326: print(
1327:     "last.pt:",
1328:     LAST_CKPT.exists()
1329: )
1330:
1331: print(
1332:     "best.pt:",
1333:     BEST_CKPT.exists()
1334: )
1335:
1336: assert global_step == TOTAL_OPTIMIZER_STEPS
1337: assert scheduler_v5.last_epoch == TOTAL_OPTIMIZER_STEPS
1338: assert LAST_CKPT.exists()
1339: assert BEST_CKPT.exists()
1340:
1341: print("\nPASS: V5 training completed.")
1342: print("PASS: Frequent resume checkpoints enabled.")
1343: print("PASS: last.pt maintained.")
1344: print("PASS: best.pt maintained.")
1345: print("PASS: Epoch checkpoints maintained.")
1346: print("PASS: V4 remains untouched.")
1347:
...

--- CELL 127 | 20 matching lines ---
  99:     exist_ok=True
 100: )
 101:
 102: LAST_CKPT = (
 103:     V5_CKPT_DIR / "last.pt"
 104: )
 105:
 106: BEST_CKPT = (
 107:     V5_CKPT_DIR / "best.pt"
 108: )
 109:
 110: RESUME_FILES = [
...
 495:             )
 496:
 497:
 498: if LAST_CKPT.exists():
 499:
 500:     step = get_checkpoint_step(
 501:         LAST_CKPT
 502:     )
 503:
 504:     if step >= 0:
 505:
 506:         candidates.append(
 507:             (step, LAST_CKPT)
 508:         )
 509:
 510:
...
 559:     # Model
 560:     # --------------------------------------------------------
 561:
 562:     v5.load_state_dict(
 563:         checkpoint["model_state"],
 564:         strict=True,
 565:     )
...
 568:     # Optimizer
 569:     # --------------------------------------------------------
 570:
 571:     optimizer_v5.load_state_dict(
 572:         checkpoint["optimizer_state"]
 573:     )
 574:
...
 576:     # Scheduler
 577:     # --------------------------------------------------------
 578:
 579:     scheduler_v5.load_state_dict(
 580:         checkpoint["scheduler_state"]
 581:     )
 582:
...
1048:                 )
1049:
1050:                 save_checkpoint(
1051:                     LAST_CKPT,
1052:                     epoch,
1053:                     v5,
1054:                     optimizer_v5,
...
1257:         best_val = val_loss
1258:
1259:         save_checkpoint(
1260:             BEST_CKPT,
1261:             epoch,
1262:             v5,
1263:             optimizer_v5,
...
1302:     # ========================================================
1303:
1304:     save_checkpoint(
1305:         LAST_CKPT,
1306:         epoch,
1307:         v5,
1308:         optimizer_v5,
...
1360:     )
1361:
1362:     assert epoch_path.exists()
1363:     assert LAST_CKPT.exists()
1364:
1365:     print(
1366:         "CHECKPOINT: PASS"
...
1396: )
1397:
1398: print(
1399:     "last.pt:",
1400:     LAST_CKPT.exists()
1401: )
1402:
1403: print(
1404:     "best.pt:",
1405:     BEST_CKPT.exists()
1406: )
1407:
1408: assert (
...
1415:     == TOTAL_OPTIMIZER_STEPS
1416: )
1417:
1418: assert LAST_CKPT.exists()
1419: assert BEST_CKPT.exists()
1420:
1421: print("\nPASS: V5 training complete.")
1422: print("PASS: Frequent checkpointing.")
...

--- CELL 139 | 18 matching lines ---
  21: #   every 48 optimizer steps
  22: #   2 rolling checkpoints
  23: #   epoch checkpoints
  24: #   best.pt
  25: #   last.pt
  26: # ============================================================
  27:
  28: import os
...
 156:     exist_ok=True
 157: )
 158:
 159: LAST_CKPT = (
 160:     CKPT_DIR /
 161:     "last.pt"
 162: )
 163:
 164: BEST_CKPT = (
 165:     CKPT_DIR /
 166:     "best.pt"
 167: )
 168:
 169: ROLLING = [
...
1266:
1267: for p in (
1268:     ROLLING +
1269:     [LAST_CKPT]
1270: ):
1271:
1272:     if p.exists():
...
1342:         == EXPECTED_KEYS
1343:     )
1344:
1345:     v5.load_state_dict(
1346:         ckpt["model_state"],
1347:         strict=True,
1348:     )
1349:
1350:     optimizer_v5.load_state_dict(
1351:         ckpt["optimizer_state"]
1352:     )
1353:
1354:     scheduler_v5.load_state_dict(
1355:         ckpt["scheduler_state"]
1356:     )
1357:
...
1988:         best_val = val_loss
1989:
1990:         save_ckpt(
1991:             BEST_CKPT,
1992:             epoch,
1993:             v5,
1994:             optimizer_v5,
...
2024:     )
2025:
2026:     save_ckpt(
2027:         LAST_CKPT,
2028:         epoch,
2029:         v5,
2030:         optimizer_v5,
...
2098: )
2099:
2100: print(
2101:     "last.pt:",
2102:     LAST_CKPT.exists()
2103: )
2104:
2105: print(
2106:     "best.pt:",
2107:     BEST_CKPT.exists()
2108: )
2109:
2110: assert (
...
2112:     == TOTAL_OPT_STEPS
2113: )
2114:
2115: assert LAST_CKPT.exists()
2116: assert BEST_CKPT.exists()
2117:
2118: print("\nPASS: V5 TRAINING COMPLETE.")
2119: print("PASS: Checkpoints saved.")
...

--- CELL 140 | 22 matching lines ---
  48:     exist_ok=True
  49: )
  50:
  51: LAST_CKPT = V5_CKPT_DIR / "last.pt"
  52: BEST_CKPT = V5_CKPT_DIR / "best.pt"
  53:
  54:
  55: # ============================================================
...
 333:
 334:
 335: # ============================================================
 336: # 10. RESUME IF last.pt EXISTS
 337: # ============================================================
 338:
 339: if LAST_CKPT.exists():
 340:
 341:     (
 342:         restored_epoch,
 343:         best_val,
 344:         history
 345:     ) = load_v5_checkpoint(
 346:         LAST_CKPT,
 347:         v5,
 348:         optimizer_v5,
 349:         scheduler_v5,
...
 364: else:
 365:
 366:     print("\n[RESUME]")
 367:     print("No last.pt found.")
 368:     print("Starting from epoch 1.")
 369:
 370:     start_epoch = 1
...
 382:     print("=" * 80)
 383:
 384:     print(
 385:         "last.pt:",
 386:         LAST_CKPT
 387:     )
 388:
 389:     print(
 390:         "best.pt exists:",
 391:         BEST_CKPT.exists()
 392:     )
 393:
 394:     print(
...
 945:         best_val = val_total
 946:
 947:         save_v5_checkpoint(
 948:             BEST_CKPT,
 949:             epoch,
 950:             v5,
 951:             optimizer_v5,
...
 986:     # ========================================================
 987:
 988:     save_v5_checkpoint(
 989:         LAST_CKPT,
 990:         epoch,
 991:         v5,
 992:         optimizer_v5,
...
1074:     # --------------------------------------------------------
1075:
1076:     assert epoch_ckpt.exists()
1077:     assert LAST_CKPT.exists()
1078:
1079:     if improved:
1080:         assert BEST_CKPT.exists()
1081:
1082:     print("\nCHECKPOINT STATUS: PASS")
1083:
...
1121: )
1122:
1123: print(
1124:     "last.pt exists:",
1125:     LAST_CKPT.exists()
1126: )
1127:
1128: print(
1129:     "best.pt exists:",
1130:     BEST_CKPT.exists()
1131: )
1132:
1133: print(
...
1137:
1138: assert global_step == 1920
1139: assert scheduler_v5.last_epoch == 1920
1140: assert LAST_CKPT.exists()
1141: assert BEST_CKPT.exists()
1142:
1143: print("\n[FINAL SAFETY]")
1144: print("PASS: 1920 optimizer steps completed.")
1145: print("PASS: Scheduler reached step 1920.")
1146: print("PASS: last.pt exists.")
1147: print("PASS: best.pt exists.")
1148: print("PASS: Epoch checkpoints written.")
1149: print("PASS: V4 checkpoint directory untouched.")
1150:
...

--- CELL 146 | 1 matching lines ---
  15:     "v4_config.json",
  16:     "epoch_03.pt",
  17:     "epoch_02.pt",
  18:     "best.pt",
  19: }
  20:
  21: print("=" * 80)
...

--- CELL 147 | 2 matching lines ---
  66:     "final_dataset_manifest.csv",
  67:
  68:     # checkpoints
  69:     "best.pt",
  70:     "last.pt",
  71:     "epoch_01.pt",
  72:     "epoch_02.pt",
  73:     "epoch_03.pt",
...

--- CELL 149 | 6 matching lines ---
  19:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4",
  20:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv",
  21:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_config.json",
  22:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",
  23:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt",
  24:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_01.pt",
  25:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_02.pt",
  26:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt",
...
  30:
  31:     # V3
  32:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3",
  33:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt",
  34:     "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/last.pt",
  35:
  36:     # Structured
  37:     "/content/drive/MyDrive/NoiSoi_Matching/v3_ontology_v2/v3_structured_targets_v2_2.csv",
...
  74:     "epoch_01.pt",
  75:     "epoch_02.pt",
  76:     "epoch_03.pt",
  77:     "best.pt",
  78:     "last.pt",
  79:     "v3_structured_targets_v2_2.csv",
  80:     "frozen_concept_ontology_mapping.csv",
  81:     "final_dataset_manifest.csv",
...

--- CELL 153 | 2 matching lines ---
  17:     "NoiSoi_Matching/baseline_model_v4/v4_training_manifest.csv",
  18:     "NoiSoi_Matching/baseline_model_v4/v4_config.json",
  19:     "NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt",
  20:     "NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",
  21:     "NoiSoi_Matching/baseline_model_v4/checkpoints/last.pt",
  22:
  23:     # Structured targets
  24:     "NoiSoi_Matching/v3_ontology_v2/v3_structured_targets_v2_2.csv",
...

--- CELL 155 | 2 matching lines ---
  19:         f"{ROOT}/baseline_model_v4/checkpoints/epoch_03.pt",
  20:
  21:     "V4 best":
  22:         f"{ROOT}/baseline_model_v4/checkpoints/best.pt",
  23:
  24:     "V4 last":
  25:         f"{ROOT}/baseline_model_v4/checkpoints/last.pt",
  26:
  27:     "Structured targets":
  28:         f"{ROOT}/v3_ontology_v2/v3_structured_targets_v2_2.csv",
...

--- CELL 161 | 1 matching lines ---
  59:         f"{ROOT}/baseline_model_v4/checkpoints/epoch_03.pt",
  60:
  61:     "v4_best":
  62:         f"{ROOT}/baseline_model_v4/checkpoints/best.pt",
  63:
  64:     "structured_targets":
  65:         f"{ROOT}/v3_ontology_v2/v3_structured_targets_v2_2.csv",
...

Total matching source lines: 130

================================================================================
3. PROJECT SOURCE FILES
================================================================================

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_config.json
  line 23:
    21:   "bf16": true,
    22:   "seed": 42,
    23:   "source_v3_checkpoint": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v3/checkpoints/best.pt",
    24:   "split": "fixed patient-level split",
    25:   "structured_conditioning": "direct_mT5_encoder_prefix"

FILE: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_runtime_state.json
  line 6:
    4:   "best_epoch": 2,
    5:   "best_val": 0.6521643281140656,
    6:   "checkpoint_best": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/best.pt",
    7:   "checkpoint_epoch2": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_02.pt",
    8:   "checkpoint_epoch3": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt",
  line 9:
    7:   "checkpoint_epoch2": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_02.pt",
    8:   "checkpoint_epoch3": "/content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt",

In [7]:

# ============================================================
# ENT PROJECT — WIDE READ-ONLY PROVENANCE SEARCH
# Không load checkpoint; không train; không tạo/sửa/xóa file.
# ============================================================

from google.colab import drive
drive.mount("/content/drive")

import os, re, json, glob, sqlite3, hashlib
from pathlib import Path
from datetime import datetime

ROOT = Path("/content/drive/MyDrive/NoiSoi_Matching")
NB_DIR = Path("/content/drive/MyDrive/Colab Notebooks")
TARGET = "test_predictions_712.csv"
MAX_TEXT_BYTES = 8 * 1024 * 1024
MAX_CONTEXT_PER_FILE = 16
MAX_LINE_LEN = 260

# Nhóm từ khóa rộng, bao gồm trường hợp tên file không xuất hiện trực tiếp.
PATTERNS = {
    "TARGET / PREDICTION": re.compile(
        r"test_predictions_712|test_predictions|predictions?_712|"
        r"prediction|preds?\b|ground_truth|case_id.*prediction|"
        r"prediction.*case_id|inference|infer\b|evaluation|eval_results",
        re.I
    ),
    "GENERATION / DECODING": re.compile(
        r"\.generate\s*\(|generate_one|generate_batch|generate_text|"
        r"max_new_tokens|max_length|num_beams|do_sample|"
        r"early_stopping|greedy|argmax|tokenizer\.decode|"
        r"batch_decode|safe_decode|decoder_input_ids",
        re.I
    ),
    "FILE WRITING / EXPORT": re.compile(
        r"\.to_csv\s*\(|csv\.writer|DictWriter|"
        r"open\s*\(.*[\"']w|write_text|writelines|"
        r"json\.dump|torch\.save|pickle\.dump|"
        r"shutil\.(copy|move)|os\.rename|Path\(.*\)\.rename|"
        r"cp\s+|mv\s+",
        re.I
    ),
    "CHECKPOINT / MODEL LOADING": re.compile(
        r"best\.pt|last\.pt|checkpoint|state_dict|"
        r"torch\.load|load_from_checkpoint|from_pretrained|"
        r"glob\s*\(|os\.listdir|safetensors|"
        r"strict\s*=\s*False|load_state_dict",
        re.I
    ),
    "V5 MODEL / DATA PIPELINE": re.compile(
        r"baseline_model_v5|test_loader|v5_test|"
        r"pixel_values|image_mask|concept_targets|"
        r"MAX_IMAGES|MAX_TARGET_LENGTH|mt5|vit_model|"
        r"visual_projector|structured_conditioner",
        re.I
    ),
}

SOURCE_EXTS = {
    ".py", ".ipynb", ".sh", ".md", ".txt", ".json",
    ".yaml", ".yml", ".log", ".out", ".err"
}
SKIP_DIRS = {
    ".git", "__pycache__", "node_modules", ".cache",
    "site-packages", "dist-packages"
}

def stamp(ts):
    try:
        return datetime.fromtimestamp(ts).isoformat(sep=" ", timespec="seconds")
    except Exception:
        return "unknown"

def short(s, limit=MAX_LINE_LEN):
    s = str(s).replace("\t", "    ")
    return s if len(s) <= limit else s[:limit] + " ...[truncated]"

def safe_read_text(path):
    try:
        if path.stat().st_size > MAX_TEXT_BYTES:
            return None
        return path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return None

def inspect_notebook(path):
    """Search notebook code AND saved cell outputs."""
    try:
        obj = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return []

    found = []
    for idx, cell in enumerate(obj.get("cells", [])):
        source = "".join(cell.get("source", []))
        exec_count = cell.get("execution_count", None)

        # Code source
        for line_no, line in enumerate(source.splitlines(), 1):
            cats = [k for k, p in PATTERNS.items() if p.search(line)]
            if cats:
                found.append({
                    "cell": idx, "where": "SOURCE",
                    "line": line_no, "cats": cats,
                    "text": short(line), "exec": exec_count
                })

        # Saved outputs may reveal a path or generation parameters
        outputs = cell.get("outputs", [])
        for oi, out in enumerate(outputs):
            chunks = []
            data = out.get("data", {})
            for key in ("text/plain", "text/html", "application/json"):
                value = data.get(key)
                if value is not None:
                    chunks.append(
                        "\n".join(value) if isinstance(value, list)
                        else str(value)
                    )
            if out.get("text"):
                value = out["text"]
                chunks.append(
                    "\n".join(value) if isinstance(value, list)
                    else str(value)
                )
            if out.get("ename"):
                chunks.append(
                    f"EXCEPTION {out.get('ename')}: {out.get('evalue')}"
                )

            output_text = "\n".join(chunks)
            for line_no, line in enumerate(output_text.splitlines(), 1):
                cats = [k for k, p in PATTERNS.items() if p.search(line)]
                if cats:
                    found.append({
                        "cell": idx, "where": f"OUTPUT[{oi}]",
                        "line": line_no, "cats": cats,
                        "text": short(line), "exec": exec_count
                    })

    return found

print("\n" + "=" * 90)
print("A. ENVIRONMENT / EXPECTED ARTIFACT")
print("=" * 90)

csv_path = ROOT / "baseline_model_v5" / TARGET
if csv_path.exists():
    st = csv_path.stat()
    print("CSV:", csv_path)
    print("Bytes:", st.st_size, "| Modified:", stamp(st.st_mtime))
    with open(csv_path, "rb") as f:
        head = f.read(4096)
    print("SHA256(first 4KB):", hashlib.sha256(head).hexdigest())
    print("Header:", head.splitlines()[0][:500].decode("utf-8", "replace")
          if head else "(empty)")
else:
    print("Expected CSV not present at:", csv_path)

print("\n" + "=" * 90)
print("B. NOTEBOOKS — SEARCH SOURCE + SAVED OUTPUTS")
print("=" * 90)

notebooks = []
for base in (NB_DIR, ROOT):
    if base.exists():
        for p in base.rglob("*.ipynb"):
            if not any(part in SKIP_DIRS for part in p.parts):
                notebooks.append(p)

# De-duplicate paths
notebooks = sorted(set(notebooks))
print("Notebook files found:", len(notebooks))

notebook_hits = []
for p in notebooks:
    hits = inspect_notebook(p)
    if hits:
        notebook_hits.append((p, hits))

for p, hits in notebook_hits:
    print(f"\nNOTEBOOK: {p}")
    print("Modified:", stamp(p.stat().st_mtime), "| matching lines:", len(hits))

    # Highest-priority matches first: literal target, file writing, generation.
    def priority(h):
        s = h["text"].lower()
        if TARGET.lower() in s: return 0
        if "to_csv" in s or "csv.writer" in s or "open(" in s: return 1
        if "generate" in s or "decode" in s: return 2
        if "best.pt" in s or "last.pt" in s or "torch.load" in s: return 3
        return 4

    chosen = sorted(hits, key=priority)[:MAX_CONTEXT_PER_FILE]
    for h in chosen:
        print(
            f"  cell={h['cell']} exec={h['exec']} "
            f"{h['where']}:{h['line']} [{','.join(h['cats'])}]"
        )
        print("   ", h["text"])
    if len(hits) > len(chosen):
        print(f"  ... {len(hits)-len(chosen)} more matching lines omitted")

print("\n" + "=" * 90)
print("C. PROJECT SOURCE / LOG FILES")
print("=" * 90)

file_hits = []
scanned = 0
MAX_FILES = 12000

for base in (ROOT, NB_DIR):
    if not base.exists():
        continue
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for name in filenames:
            p = Path(dirpath) / name
            if p.suffix.lower() not in SOURCE_EXTS:
                continue
            if p.suffix.lower() == ".ipynb":
                continue  # already inspected with cell/output context
            scanned += 1
            if scanned > MAX_FILES:
                break
            content = safe_read_text(p)
            if content is None:
                continue

            matches = []
            for ln, line in enumerate(content.splitlines(), 1):
                cats = [k for k, pat in PATTERNS.items() if pat.search(line)]
                if cats:
                    matches.append((ln, cats, short(line)))

            if matches:
                file_hits.append((p, matches))
        if scanned > MAX_FILES:
            break
    if scanned > MAX_FILES:
        break

print("Text/source files scanned:", min(scanned, MAX_FILES))
for p, matches in sorted(file_hits, key=lambda x: (
    0 if TARGET.lower() in str(x[0]).lower() else 1,
    -len(x[1])
))[:100]:
    print(f"\nFILE: {p} | modified={stamp(p.stat().st_mtime)} | hits={len(matches)}")
    for ln, cats, line in matches[:10]:
        print(f"  L{ln} [{','.join(cats)}] {line}")
    if len(matches) > 10:
        print(f"  ... {len(matches)-10} additional matches")

print("\n" + "=" * 90)
print("D. CANDIDATE ARTIFACTS — CSV / PREDICTION / LOG / CHECKPOINT METADATA")
print("=" * 90)

candidate_pattern = re.compile(
    r"(predict|preds?|infer|test|submission|result|output|checkpoint|"
    r"best|last|v5|audit|log|history)",
    re.I
)
candidate_files = []

for base in (ROOT, NB_DIR):
    if not base.exists():
        continue
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for name in filenames:
            p = Path(dirpath) / name
            if candidate_pattern.search(name):
                try:
                    st = p.stat()
                    candidate_files.append((
                        p, st.st_size, st.st_mtime, p.suffix.lower()
                    ))
                except Exception:
                    pass

# Show likely predictions first; then newest files.
candidate_files.sort(key=lambda x: (
    0 if re.search(r"predict|preds?|inference|submission", x[0].name, re.I) else 1,
    -x[2]
))
print("Candidate files:", len(candidate_files))
for p, size, mtime, ext in candidate_files[:180]:
    print(f"{stamp(mtime)} | {size:>12} bytes | {p}")

if len(candidate_files) > 180:
    print("... remaining candidates omitted")

print("\n" + "=" * 90)
print("E. IPYTHON HISTORY — IF THIS RUNTIME HAS PERSISTED IT")
print("=" * 90)

history_candidates = [
    Path.home() / ".ipython/profile_default/history.sqlite",
    Path("/root/.ipython/profile_default/history.sqlite"),
]
history_found = False

for hp in history_candidates:
    if not hp.exists():
        continue
    history_found = True
    print("\nHistory DB:", hp, "| modified:", stamp(hp.stat().st_mtime))
    try:
        # SQLite read-only URI: do not alter the database.
        con = sqlite3.connect("file:" + str(hp) + "?mode=ro", uri=True)
        tables = [
            row[0] for row in con.execute(
                "SELECT name FROM sqlite_master WHERE type='table'"
            )
        ]
        print("Tables:", tables)
        if "history" in tables:
            rows = con.execute(
                "SELECT session, line, source FROM history "
                "ORDER BY session DESC, line DESC LIMIT 20000"
            ).fetchall()
            selected = []
            hist_pat = re.compile(
                r"test_predictions|to_csv|generate|decode|"
                r"best\.pt|last\.pt|torch\.load|load_state_dict|"
                r"prediction|inference|baseline_model_v5",
                re.I
            )
            for session, line_no, source in rows:
                if hist_pat.search(source or ""):
                    selected.append((session, line_no, source))
            print("Relevant history commands:", len(selected))
            for session, line_no, source in selected[:100]:
                print(f"\n  session={session} line={line_no}")
                print(" ", short(source, 500))
            if len(selected) > 100:
                print(" ... remaining history matches omitted")
        con.close()
    except Exception as e:
        print("History unreadable:", type(e).__name__, str(e)[:200])

if not history_found:
    print("No persisted IPython history DB found in standard paths.")
    print("This is normal if the runtime was reset or history was not persisted.")

print("\n" + "=" * 90)
print("F. CURRENT RUNTIME — RECENT RELEVANT FILES")
print("=" * 90)

runtime_roots = [Path("/content"), Path("/tmp")]
runtime_candidates = []
for base in runtime_roots:
    if not base.exists():
        continue
    try:
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = [
                d for d in dirnames
                if d not in {"node_modules", "__pycache__", ".git"}
            ]
            for name in filenames:
                p = Path(dirpath) / name
                if not candidate_pattern.search(name):
                    continue
                try:
                    st = p.stat()
                    # Avoid listing huge unrelated model/data files.
                    runtime_candidates.append((p, st.st_size, st.st_mtime))
                except Exception:
                    pass
    except Exception:
        pass

runtime_candidates.sort(key=lambda x: -x[2])
print("Runtime candidates:", len(runtime_candidates))
for p, size, mtime in runtime_candidates[:100]:
    print(f"{stamp(mtime)} | {size:>12} bytes | {p}")

print("\n" + "=" * 90)
print("SEARCH COMPLETE")
print("Read-only: no checkpoint loaded, no training, no predictions generated,")
print("and no existing project artifacts modified.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

==========================================================================================
A. ENVIRONMENT / EXPECTED ARTIFACT
==========================================================================================
CSV: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/test_predictions_712.csv
Bytes: 62941 | Modified: 2026-09-30 16:34:27
SHA256(first 4KB): b3ffae61834f82a3b25250a9f864b65b33540c767354a16017dc67618521511b
Header: ﻿case_id,prediction,ground_truth

==========================================================================================
B. NOTEBOOKS — SEARCH SOURCE + SAVED OUTPUTS
==========================================================================================
Notebook files found: 61

NOTEBOOK: /content/drive/MyDrive/Colab Notebooks/KMeans.ipynb
Modified: 2025-01-29 16:36:05 | matching lines: 6
  cell=10 exec=13 SOURCE:1 [TARGET / PREDICTION]
    y_pred=k_mean_model.predict(X)
  cell=10 exec=13 SOURCE:4 [TARGET / PREDICTION]
    plt.scatter(X[:, 0], X[:, 1], c=y_pred)
  cell=14 exec=15 SOURCE:1 [TARGET / PREDICTION]
    y_pred=k_mean_model.predict(X)
  cell=14 exec=15 SOURCE:4 [TARGET / PREDICTION]
    plt.scatter(X[:, 0], X[:, 1], c=y_pred)
  cell=18 exec=17 SOURCE:1 [TARGET / PREDICTION]
    y_pred=k_mean_model.predict(X)
  cell=18 exec=17 SOURCE:4 [TARGET / PREDICTION]
    plt.scatter(X[:, 0], X[:, 1], c=y_pred)

NOTEBOOK: /content/drive/MyDrive/Colab Notebooks/08sep.ipynb
Modified: 2026-09-09 13:48:47 | matching lines: 1238
  cell=6 exec=2 SOURCE:1 [FILE WRITING / EXPORT]
    images_df.to_csv(
  cell=16 exec=13 SOURCE:1 [FILE WRITING / EXPORT]
    pdf_df.to_csv(
  cell=49 exec=48 SOURCE:30 [FILE WRITING / EXPORT]
    case_candidates.to_csv(
  cell=53 exec=52 SOURCE:92 [FILE WRITING / EXPORT]
            results_df.to_csv(
  cell=53 exec=52 SOURCE:102 [FILE WRITING / EXPORT]
        with open(PROGRESS_FILE, "w") as f:
  cell=67 exec=6 SOURCE:103 [FILE WRITING / EXPORT]
    pdf_df.to_csv(
  cell=67 exec=6 SOURCE:257 [FILE WRITING / EXPORT]
    case_candidates_prod.to_csv(
  cell=68 exec=7 SOURCE:196 [FILE WRITING / EXPORT]
            phash_df.to_csv(
  cell=73 exec=9 SOURCE:42 [FILE WRITING / EXPORT]
    phash_df.to_csv(
  cell=74 exec=12 SOURCE:426 [FILE WRITING / EXPORT]
            pdf_phash_df.to_csv(
  cell=77 exec=6 SOURCE:16 [FILE WRITING / EXPORT]
        df.to_csv(
  cell=78 exec=8 SOURCE:223 [FILE WRITING / EXPORT]
    best.to_csv(
  cell=79 exec=9 SOURCE:362 [FILE WRITING / EXPORT]
    audit.to_csv(
  cell=80 exec=10 SOURCE:294 [FILE WRITING / EXPORT]
    audit.to_csv(
  cell=81 exec=11 SOURCE:314 [FILE WRITING / EXPORT]
    df.to_csv(
  cell=82 exec=12 SOURCE:126 [FILE WRITING / EXPORT]
    out.to_csv(
  ... 1222 more matching lines omitted

NOTEBOOK: /content/drive/MyDrive/Colab Notebooks/10sep.ipynb
Modified: 2026-09-19 13:15:38 | matching lines: 358
  cell=3 exec=None SOURCE:174 [FILE WRITING / EXPORT]
    variant_df.to_csv(
  cell=4 exec=None SOURCE:381 [FILE WRITING / EXPORT]
    cases[audit_columns].to_csv(
  cell=5 exec=None SOURCE:313 [FILE WRITING / EXPORT]
            combined.to_csv(
  cell=5 exec=None SOURCE:350 [FILE WRITING / EXPORT]
    audit.to_csv(
  cell=5 exec=None SOURCE:355 [FILE WRITING / EXPORT]
    audit.to_csv(
  cell=6 exec=None SOURCE:396 [FILE WRITING / EXPORT,CHECKPOINT / MODEL LOADING]
            checkpoint_df.to_csv(
  cell=6 exec=None SOURCE:435 [FILE WRITING / EXPORT]
    final_df.to_csv(
  cell=7 exec=None SOURCE:230 [FILE WRITING / EXPORT]
        loss_df.to_csv(
  cell=7 exec=None SOURCE:293 [FILE WRITING / EXPORT]
        gain_df.to_csv(
  cell=8 exec=None SOURCE:223 [FILE WRITING / EXPORT]
    dataset_cases.to_csv(
  cell=8 exec=None SOURCE:229 [FILE WRITING / EXPORT]
    dataset_images.to_csv(
  cell=10 exec=None SOURCE:267 [FILE WRITING / EXPORT]
    dataset_cases.to_csv(
  cell=10 exec=None SOURCE:273 [FILE WRITING / EXPORT]
    dataset_images.to_csv(
  cell=11 exec=None SOURCE:441 [FILE WRITING / EXPORT]
    audit.to_csv(
  cell=12 exec=None SOURCE:118 [FILE WRITING / EXPORT]
    exact_df.to_csv(EXACT_OUT, index=False)
  cell=12 exec=None SOURCE:236 [FILE WRITING / EXPORT]
    near_df.to_csv(NEAR_OUT, index=False)
  ... 342 more matching lines omitted

NOTEBOOK: /content/drive/MyDrive/Colab Notebooks/14oct.ipynb
Modified: 2026-10-15 11:46:09 | matching lines: 5543
  cell=21 exec=24 SOURCE:15 [TARGET / PREDICTION,V5 MODEL / DATA PIPELINE]
    PRED_PATH = ROOT / "baseline_model_v5/test_predictions_712.csv"
  cell=21 exec=24 OUTPUT[0]:103 [TARGET / PREDICTION,V5 MODEL / DATA PIPELINE]
    Path: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/test_predictions_712.csv
  cell=23 exec=26 SOURCE:12 [TARGET / PREDICTION,V5 MODEL / DATA PIPELINE]
    PRED_PATH = ROOT / "baseline_model_v5/test_predictions_712.csv"
  cell=31 exec=34 SOURCE:11 [TARGET / PREDICTION,V5 MODEL / DATA PIPELINE]
    PRED_CSV = ROOT / "baseline_model_v5/test_predictions_712.csv"
  cell=32 exec=35 SOURCE:12 [TARGET / PREDICTION,V5 MODEL / DATA PIPELINE]
    PRED_PATH = ROOT / "baseline_model_v5/test_predictions_712.csv"
  cell=33 exec=36 SOURCE:17 [TARGET / PREDICTION]
        "test_predictions_712.csv",
  cell=34 exec=37 SOURCE:10 [TARGET / PREDICTION,V5 MODEL / DATA PIPELINE]
    PRED_PATH = ROOT / "baseline_model_v5/test_predictions_712.csv"
  cell=34 exec=37 SOURCE:18 [TARGET / PREDICTION]
        "test_predictions_712.csv",
  cell=34 exec=37 SOURCE:40 [TARGET / PREDICTION]
                "test_predictions_712.csv", "to_csv(", "write_csv(",
  cell=34 exec=37 OUTPUT[0]:1229 [TARGET / PREDICTION,V5 MODEL / DATA PIPELINE]
    Path: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/test_predictions_712.csv
  cell=35 exec=38 SOURCE:19 [TARGET / PREDICTION]
        "test_predictions_712.csv",
  cell=37 exec=40 SOURCE:12 [TARGET / PREDICTION]
        "test_predictions_712.csv",
  cell=37 exec=40 OUTPUT[0]:239 [TARGET / PREDICTION,V5 MODEL / DATA PIPELINE]
      L51: Path: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/test_predictions_712.csv
  cell=38 exec=41 OUTPUT[0]:107 [TARGET / PREDICTION]
      FILE test_predictions_712.csv | 62,941 bytes | modified=2026-09-30T16:34:27
  cell=39 exec=42 SOURCE:30 [TARGET / PREDICTION]
    pred_path = V5 / "test_predictions_712.csv"
  cell=39 exec=42 SOURCE:123 [TARGET / PREDICTION]
        "test_predictions_712.csv", "to_csv(", "to_csv ",
  ... 5527 more matching lines omitted

NOTEBOOK: /content/drive/MyDrive/Colab Notebooks/19sep.ipynb
Modified: 2026-09-25 09:07:59 | matching lines: 3824
  cell=1 exec=3 SOURCE:212 [FILE WRITING / EXPORT]
    cases_model.to_csv(
  cell=2 exec=4 SOURCE:133 [FILE WRITING / EXPORT]
    tokenizer_stats.to_csv(
  cell=9 exec=17 SOURCE:108 [FILE WRITING / EXPORT]
    with open(CONFIG_FILE, "w") as f:
  cell=9 exec=17 SOURCE:611 [FILE WRITING / EXPORT]
        ).to_csv(
  cell=10 exec=19 SOURCE:265 [FILE WRITING / EXPORT]
    test_results_df.to_csv(
  cell=11 exec=21 SOURCE:506 [FILE WRITING / EXPORT]
    metrics_df.to_csv(
  cell=11 exec=21 SOURCE:526 [TARGET / PREDICTION,FILE WRITING / EXPORT]
    prediction_counts.to_csv(
  cell=11 exec=21 SOURCE:532 [TARGET / PREDICTION,FILE WRITING / EXPORT]
    ground_truth_counts.to_csv(
  cell=11 exec=21 SOURCE:548 [FILE WRITING / EXPORT]
    df.to_csv(
  cell=13 exec=23 SOURCE:47 [FILE WRITING / EXPORT]
    with open(V2_CONFIG_FILE, "w") as f:
  cell=15 exec=25 SOURCE:780 [FILE WRITING / EXPORT]
        ).to_csv(
  cell=16 exec=5 SOURCE:339 [TARGET / PREDICTION,FILE WRITING / EXPORT]
    predictions_df.to_csv(
  cell=17 exec=6 SOURCE:285 [TARGET / PREDICTION,FILE WRITING / EXPORT]
    predictions_fp32_df.to_csv(
  cell=21 exec=13 SOURCE:877 [FILE WRITING / EXPORT]
    results.to_csv(
  cell=23 exec=16 SOURCE:977 [FILE WRITING / EXPORT]
    results.to_csv(
  cell=24 exec=17 SOURCE:1115 [FILE WRITING / EXPORT]
    pred_df.to_csv(
  ... 3808 more matching lines omitted

NOTEBOOK: /content/drive/MyDrive/Colab Notebooks/25sep.ipynb
Modified: 2026-09-28 10:33:04 | matching lines: 2707
  cell=7 exec=None SOURCE:350 [FILE WRITING / EXPORT]
    sensitivity_df.to_csv(
  cell=7 exec=None SOURCE:355 [FILE WRITING / EXPORT]
    summary_df.to_csv(
  cell=1 exec=None SOURCE:1119 [GENERATION / DECODING]
    def safe_decode(ids):
  cell=1 exec=None SOURCE:1131 [GENERATION / DECODING]
        return tokenizer.decode(
  cell=1 exec=None SOURCE:1453 [GENERATION / DECODING]
                decoder_input_ids=
  cell=1 exec=None SOURCE:1487 [GENERATION / DECODING]
        return safe_decode(
  cell=1 exec=None SOURCE:1600 [GENERATION / DECODING]
                    safe_decode(
  cell=4 exec=None SOURCE:5 [GENERATION / DECODING]
    def safe_decode(token_ids):
  cell=4 exec=None SOURCE:7 [V5 MODEL / DATA PIPELINE]
        Decode generated mT5 token IDs while removing
  cell=4 exec=None SOURCE:16 [GENERATION / DECODING]
        return tokenizer.decode(
  cell=4 exec=None SOURCE:27 [GENERATION / DECODING]
    test_text = safe_decode([tokenizer.eos_token_id])
  cell=4 exec=None SOURCE:32 [GENERATION / DECODING]
    print("✓ safe_decode available")
  cell=4 exec=None OUTPUT[0]:9 [GENERATION / DECODING]
    ✓ safe_decode available
  cell=5 exec=None SOURCE:188 [GENERATION / DECODING]
    def generate_one(cond, max_new_tokens=20):
  cell=5 exec=None SOURCE:210 [GENERATION / DECODING]
                decoder_input_ids=decoder_ids,
  cell=5 exec=None SOURCE:232 [GENERATION / DECODING]
        return safe_decode(generated)
  ... 2691 more matching lines omitted

NOTEBOOK: /content/drive/MyDrive/Colab Notebooks/28sep.ipynb
Modified: 2026-10-14 15:30:03 | matching lines: 1216
  cell=38 exec=None SOURCE:205 [TARGET / PREDICTION,V5 MODEL / DATA PIPELINE]
        "baseline_model_v5/test_predictions_712.csv"
  cell=38 exec=None OUTPUT[2]:19 [TARGET / PREDICTION,V5 MODEL / DATA PIPELINE]
    /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/test_predictions_712.csv
  cell=39 exec=2 SOURCE:23 [TARGET / PREDICTION,V5 MODEL / DATA PIPELINE]
        "baseline_model_v5/test_predictions_712.csv"
  cell=39 exec=2 OUTPUT[0]:17 [TARGET / PREDICTION,V5 MODEL / DATA PIPELINE]
    Path   : /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/test_predictions_712.csv
  cell=40 exec=3 SOURCE:17 [TARGET / PREDICTION,V5 MODEL / DATA PIPELINE]
        "baseline_model_v5/test_predictions_712.csv"
  cell=41 exec=4 SOURCE:24 [TARGET / PREDICTION,V5 MODEL / DATA PIPELINE]
    pred_path = root / "baseline_model_v5" / "test_predictions_712.csv"
  cell=43 exec=6 SOURCE:24 [TARGET / PREDICTION,V5 MODEL / DATA PIPELINE]
    pred_path = root / "baseline_model_v5" / "test_predictions_712.csv"
  cell=44 exec=7 SOURCE:16 [TARGET / PREDICTION,V5 MODEL / DATA PIPELINE]
        "baseline_model_v5/test_predictions_712.csv"
  cell=45 exec=9 SOURCE:13 [TARGET / PREDICTION,V5 MODEL / DATA PIPELINE]
    pred_path = base / "baseline_model_v5" / "test_predictions_712.csv"
  cell=46 exec=10 SOURCE:14 [TARGET / PREDICTION,V5 MODEL / DATA PIPELINE]
    pred_path = base / "baseline_model_v5" / "test_predictions_712.csv"
  cell=47 exec=11 SOURCE:15 [TARGET / PREDICTION]
        "test_predictions_712.csv"
  cell=38 exec=None SOURCE:208 [FILE WRITING / EXPORT]
    results_df.to_csv(
  cell=40 exec=3 SOURCE:94 [FILE WRITING / EXPORT]
    tympanic_df.to_csv(
  cell=41 exec=4 SOURCE:157 [FILE WRITING / EXPORT]
    tympanic_df.to_csv(
  cell=44 exec=7 SOURCE:73 [FILE WRITING / EXPORT]
    freq.to_csv(out_path, index=False, encoding="utf-8-sig")
  cell=46 exec=10 SOURCE:99 [FILE WRITING / EXPORT]
    audit.to_csv(out, index=False)
  ... 1200 more matching lines omitted

NOTEBOOK: /content/drive/MyDrive/Colab Notebooks/Another copy of Pytorch Training.ipynb
Modified: 2025-09-20 06:53:54 | matching lines: 45
  cell=21 exec=533 SOURCE:112 [FILE WRITING / EXPORT]
        with open(out_path, "w") as f:
  cell=14 exec=527 SOURCE:5 [CHECKPOINT / MODEL LOADING]
                   ckpt_path="lstm_best.pt"):
  cell=15 exec=528 SOURCE:11 [CHECKPOINT / MODEL LOADING]
    ckpt_path = 'rnn_best.pt'
  cell=16 exec=529 OUTPUT[1]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=529 OUTPUT[3]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=529 OUTPUT[5]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=529 OUTPUT[7]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=529 OUTPUT[9]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=529 OUTPUT[11]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=529 OUTPUT[13]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=529 OUTPUT[15]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=529 OUTPUT[17]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=529 OUTPUT[21]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=529 OUTPUT[23]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=529 OUTPUT[27]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=529 OUTPUT[29]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  ... 29 more matching lines omitted

NOTEBOOK: /content/drive/MyDrive/Colab Notebooks/B2.ipynb
Modified: 2025-01-24 16:24:16 | matching lines: 1
  cell=10 exec=39 SOURCE:1 [GENERATION / DECODING]
    oldest_index=np.argmax(ndarray[:, 1])

NOTEBOOK: /content/drive/MyDrive/Colab Notebooks/Bài 1.ipynb
Modified: 2025-01-31 20:40:00 | matching lines: 4
  cell=1 exec=65 SOURCE:24 [TARGET / PREDICTION]
    y_pred = model.predict(x)
  cell=1 exec=65 SOURCE:33 [TARGET / PREDICTION]
    ax.plot(x, y_pred, color="red")
  cell=7 exec=71 SOURCE:3 [TARGET / PREDICTION]
        y_pred = model(x_tensor).cpu().numpy()
  cell=8 exec=72 SOURCE:5 [TARGET / PREDICTION]
    ax.plot(x, y_pred, color="red")

NOTEBOOK: /content/drive/MyDrive/Colab Notebooks/Bài 2.ipynb
Modified: 2025-02-01 15:54:53 | matching lines: 4
  cell=9 exec=11 SOURCE:2 [TARGET / PREDICTION]
    y_pred = model.predict(x)
  cell=10 exec=12 SOURCE:3 [TARGET / PREDICTION]
    ax.plot(x, y_pred, color="red")
  cell=22 exec=23 SOURCE:3 [TARGET / PREDICTION]
        y_pred = model(x_tensor).cpu().numpy()
  cell=22 exec=23 SOURCE:9 [TARGET / PREDICTION]
    ax.plot(x, y_pred, color="red")

NOTEBOOK: /content/drive/MyDrive/Colab Notebooks/Bài 3.ipynb
Modified: 2025-02-01 16:51:44 | matching lines: 6
  cell=23 exec=69 SOURCE:11 [V5 MODEL / DATA PIPELINE]
    test_loader = torch.utils.data.DataLoader(dataset=test_dataset, batch_size=config.batch_size, shuffle=False)
  cell=25 exec=70 SOURCE:24 [V5 MODEL / DATA PIPELINE]
            for images, labels in test_loader:
  cell=35 exec=59 SOURCE:7 [TARGET / PREDICTION]
            predictions = model.predict(test_images)
  cell=35 exec=59 SOURCE:8 [TARGET / PREDICTION,GENERATION / DECODING]
            predicted_labels = np.argmax(predictions, axis=1)
  cell=35 exec=59 SOURCE:9 [TARGET / PREDICTION]
            ground_truth_labels = y_test[test_indices]
  cell=35 exec=59 SOURCE:13 [TARGET / PREDICTION]
                                                                caption=f"Predicted: {predicted_labels[i]}, Ground Truth: {ground_truth_labels[i]}")

NOTEBOOK: /content/drive/MyDrive/Colab Notebooks/Bài_2.ipynb
Modified: 2025-01-24 11:29:20 | matching lines: 4
  cell=28 exec=85 SOURCE:7 [TARGET / PREDICTION]
        y_pred = model.predict(X_val)
  cell=28 exec=85 SOURCE:8 [TARGET / PREDICTION]
        mse = mean_squared_error(y_val, y_pred)
  cell=30 exec=86 SOURCE:8 [TARGET / PREDICTION]
    y_pred = model.predict(X_test)
  cell=30 exec=86 SOURCE:9 [TARGET / PREDICTION]
    mse = mean_squared_error(y_test, y_pred)

NOTEBOOK: /content/drive/MyDrive/Colab Notebooks/Copy of Bài_1_.ipynb
Modified: 2025-01-16 08:11:45 | matching lines: 2
  cell=8 exec=15 SOURCE:16 [TARGET / PREDICTION]
        y_pred = model.predict(X_val) # Predict trên tập X_val
  cell=8 exec=15 SOURCE:19 [TARGET / PREDICTION]
        print('Lambda = ' + str(a_lambda) + '; RMSE = ' + str(math.sqrt(mean_squared_error(y_val, y_pred))))

NOTEBOOK: /content/drive/MyDrive/Colab Notebooks/Copy of Customer_Classification.ipynb
Modified: 2025-03-12 05:15:20 | matching lines: 4
  cell=10 exec=11 SOURCE:10 [TARGET / PREDICTION]
    full_tree_pred = full_tree_fit.predict(x_test)
  cell=10 exec=11 SOURCE:21 [TARGET / PREDICTION]
                                                y_score = full_tree_pred))
  cell=10 exec=11 SOURCE:31 [TARGET / PREDICTION]
                                          y_score = full_tree_pred) # auc
  cell=11 exec=None SOURCE:5 [TARGET / PREDICTION]
    full_tree_tp = confusion_matrix(y_true = y_test, y_pred = full_tree_pred).ravel()

NOTEBOOK: /content/drive/MyDrive/Colab Notebooks/Copy of KMeans.ipynb
Modified: 2025-01-28 15:57:10 | matching lines: 3
  cell=15 exec=7 SOURCE:1 [TARGET / PREDICTION]
    y_pred = k_mean_model.predict(X)
  cell=15 exec=7 SOURCE:3 [TARGET / PREDICTION]
    print(y_pred[:5])
  cell=15 exec=7 SOURCE:7 [TARGET / PREDICTION]
    plt.scatter(X[:, 0], X[:, 1], c=y_pred)

NOTEBOOK: /content/drive/MyDrive/Colab Notebooks/Copy of Pytorch Training.ipynb
Modified: 2025-09-20 12:02:17 | matching lines: 46
  cell=24 exec=165 SOURCE:113 [FILE WRITING / EXPORT]
        with open(out_path, "w") as f:
  cell=14 exec=156 SOURCE:5 [CHECKPOINT / MODEL LOADING]
                   ckpt_path="lstm_best.pt"):
  cell=15 exec=157 SOURCE:11 [CHECKPOINT / MODEL LOADING]
    ckpt_path = 'rnn_best.pt'
  cell=16 exec=158 OUTPUT[1]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=158 OUTPUT[3]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=158 OUTPUT[5]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=158 OUTPUT[7]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=158 OUTPUT[9]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=158 OUTPUT[11]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=158 OUTPUT[13]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=158 OUTPUT[15]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=158 OUTPUT[17]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=158 OUTPUT[19]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=158 OUTPUT[21]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=158 OUTPUT[23]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  cell=16 exec=158 OUTPUT[25]:3 [CHECKPOINT / MODEL LOADING]
    Saved new best weights to rnn_best.pt
  ... 30 more matching lines omitted

NOTEBOOK: /content/drive/MyDrive/Colab Notebooks/Copy of VAIC_Paraphrase_Colab_T4.ipynb
Modified: 2025-09-20 09:13:12 | matching lines: 19
  cell=24 exec=43 SOURCE:18 [FILE WRITING / EXPORT]
    pd.DataFrame({"label": yhat_pub}).to_csv(CFG["out_public"], index=False)
  cell=24 exec=43 SOURCE:39 [FILE WRITING / EXPORT]
        pd.DataFrame({"label": yhat_priv}).to_csv(CFG["out_private"], index=False)
  cell=0 exec=None SOURCE:9 [TARGET / PREDICTION]
    - **Stratified 5‑fold CV** with out‑of‑fold (OOF) predictions.
  cell=0 exec=None SOURCE:12 [TARGET / PREDICTION]
    - **Final training** on full train and predictions for `public_test.csv` and `test_X.csv`.
  cell=12 exec=62 SOURCE:50 [TARGET / PREDICTION]
    def build_baseline_features_infer(df, tfidf, scaler):

KeyboardInterrupt:

In [8]:
# === ENT V5 — read-only provenance + decoding audit (no checkpoint load, no GPU) ===
from google.colab import drive
drive.mount('/content/drive')

import os, re, json, datetime, unicodedata
import pandas as pd

ROOT = '/content/drive/MyDrive/NoiSoi_Matching'
V5   = f'{ROOT}/baseline_model_v5'
AUD  = f'{V5}/diagnostics/audit_20261015'
OUT_DIR = f'{V5}/diagnostics/audit_20261015_review'      # NEW folder, existing files untouched
os.makedirs(OUT_DIR, exist_ok=True)
REPORT = f'{OUT_DIR}/provenance_review_{datetime.datetime.now():%Y%m%d_%H%M%S}.txt'

lines = []
def log(*a):
    s = ' '.join(str(x) for x in a); print(s); lines.append(s)
def stat(p):
    if not os.path.exists(p): return 'MISSING'
    st = os.stat(p)
    return f'{st.st_size:,} B | modified {datetime.datetime.fromtimestamp(st.st_mtime)} (runtime clock, usually UTC)'

# ---------- 1. File status ----------
FILES = {
    'cell11':    f'{AUD}/cell11_prediction_generation_source.txt',
    'cell12':    f'{AUD}/cell12_checkpoint_and_prediction_source.txt',
    'cell13':    f'{AUD}/cell13_full_notebook_prediction_trace.txt',
    'summary':   f'{V5}/diagnostics/v5_final_training_summary.json',
    'paths':     f'{V5}/runtime_state/paths.json',
    'v4_status': f'{ROOT}/baseline_model_v4/v4_status_2026-09-24.txt',
}
log('=== 1. FILE STATUS ===')
for k, p in FILES.items():
    log(f'{k:10s} {stat(p)}  {p}')
for p in [f'{V5}/test_predictions_712.csv', f'{V5}/checkpoints/best.pt', f'{V5}/checkpoints/last.pt']:
    log(f'{"":10s} {stat(p)}  {p}')

texts = {}
for k, p in FILES.items():
    if os.path.exists(p):
        with open(p, encoding='utf-8', errors='replace') as f:
            texts[k] = f.read()

# ---------- 2. Keyword hits with context ----------
PATTERNS = [r'test_predictions', r'to_csv', r'best\.pt', r'last\.pt', r'torch\.load', r'load_state_dict',
            r'strict\s*=', r'missing_keys|unexpected_keys', r'def\s+\w*(generate|decode)\w*', r'\.generate\(',
            r'argmax', r'max_new_tokens', r'decoder_start_token_id', r'eos_token_id', r'pad_token_id',
            r'extra_id', r'skip_special_tokens', r'num_beams', r'max_target', r'max_images|MAX_IMAGES',
            r'NO_SIGNAL', r'model\.eval|\.eval\(\)', r'no_grad|inference_mode', r'\.lower\(\)|\.upper\(\)',
            r'execution_count']
log('\n=== 2. KEYWORD HITS (±2 lines, max 12 per pattern per file) ===')
for k, t in texts.items():
    if k in ('summary', 'paths'):
        continue
    L = t.splitlines()
    log(f'\n##### {k}: {len(L)} lines #####')
    for pat in PATTERNS:
        idx = [i for i, l in enumerate(L) if re.search(pat, l)]
        if not idx:
            continue
        log(f'\n-- /{pat}/ : {len(idx)} hits')
        for i in idx[:12]:
            for j in range(max(0, i-2), min(len(L), i+3)):
                log(f'{">>" if j == i else "  "} {j+1:5d}: {L[j][:220]}')
            log('   ...')

for k in ('summary', 'paths'):
    if k in texts:
        log(f'\n=== {k} (full) ===\n{texts[k]}')

# ---------- 3. Recompute prediction stats (CSV read-only) ----------
log('\n=== 3. PREDICTION CSV STATS ===')
df = pd.read_csv(f'{V5}/test_predictions_712.csv')
norm = lambda s: re.sub(r'\s+', ' ', str(s)).strip().lower()
pn, gn = df['prediction'].map(norm), df['ground_truth'].map(norm)
vc = pn.value_counts()
log('rows', len(df), '| unique pred', pn.nunique(), '| unique GT', gn.nunique())
log('top1 share', round(vc.iloc[0]/len(df), 4), '| top2 share', round(vc.iloc[:2].sum()/len(df), 4))
log('exact match', round((pn == gn).mean(), 4))
log('empty preds', (pn.str.len() == 0).sum(),
    '| preds w/ special tokens', df['prediction'].astype(str).str.contains(r'<extra_id|<pad>|</s>|<unk>').sum())
log('pred top 16:\n' + vc.head(16).to_string())
log('pred word count:', pn.str.split().str.len().describe().round(2).to_dict())
log('GT   word count:', gn.str.split().str.len().describe().round(2).to_dict())

# Unicode consistency (NFC vs NFD Vietnamese diacritics can silently split labels)
for name, col in [('GT', df['ground_truth']), ('pred', df['prediction'])]:
    nonnfc = col.astype(str).map(lambda s: unicodedata.normalize('NFC', s) != s).sum()
    log(f'{name}: strings not in NFC form = {nonnfc}')

# ---------- 4. Token lengths vs the 20-token generation cap ----------
log('\n=== 4. mT5 TOKEN LENGTHS ===')
try:
    from transformers import AutoTokenizer
    tok = AutoTokenizer.from_pretrained('google/mt5-small')
    ids = lambda s: tok(str(s), add_special_tokens=True)['input_ids']    # includes </s>
    def lens(series): return series.map(lambda s: len(ids(s)))
    gt_len, pr_len = lens(df['ground_truth']), lens(df['prediction'])
    log('test GT tokens:', gt_len.describe().round(2).to_dict())
    log('test GT > 20 tokens:', (gt_len > 20).sum(), f'({(gt_len > 20).mean():.1%})', '| > 96:', (gt_len > 96).sum())
    log('pred tokens:', pr_len.describe().round(2).to_dict(), '| preds with >= 20 tokens:', (pr_len >= 20).sum())
    unk = tok.unk_token_id
    log('GT strings containing <unk> after tokenization:', df['ground_truth'].map(lambda s: unk in ids(s)).sum())
    rt = df['ground_truth'].map(lambda s: norm(tok.decode(ids(s), skip_special_tokens=True)) != norm(s)).sum()
    log('GT strings that do not round-trip through tokenizer:', rt)
    man = pd.read_csv(f'{ROOT}/baseline_model_v4/v4_training_manifest.csv', usecols=['split', 'ket_luan'])
    tr_len = lens(man.loc[man['split'] == 'train', 'ket_luan'].dropna())
    log('train GT tokens:', tr_len.describe().round(2).to_dict())
    log('train GT > 20 tokens:', (tr_len > 20).sum(), f'({(tr_len > 20).mean():.1%})')
except Exception as e:
    log('Tokenizer check skipped:', repr(e))

# ---------- Save report (summary + full source texts) ----------
with open(REPORT, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))
    f.write('\n\n=== FULL SOURCE TEXTS ===\n')
    for k, t in texts.items():
        f.write(f'\n\n##### {k} ({FILES[k]}) #####\n{t}')
print('\nReport saved to:', REPORT)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
=== 1. FILE STATUS ===
cell11     8,891 B | modified 2026-10-14 20:53:50 (runtime clock, usually UTC)  /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell11_prediction_generation_source.txt
cell12     32,874 B | modified 2026-10-14 20:54:25 (runtime clock, usually UTC)  /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell12_checkpoint_and_prediction_source.txt
cell13     5,548 B | modified 2026-10-14 20:55:51 (runtime clock, usually UTC)  /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015/cell13_full_notebook_prediction_trace.txt
summary    649 B | modified 2026-09-29 04:23:10 (runtime clock, usually UTC)  /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/v5_final_training_summary.json
paths      719 B | modified 2026-09-28 08:24:55 (runtime clock, usually UTC)  /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/runtime_state/paths.json
v4_status  1,118 B | modified 2026-09-24 08:42:08 (runtime clock, usually UTC)  /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/v4_status_2026-09-24.txt
           62,941 B | modified 2026-09-30 16:34:27 (runtime clock, usually UTC)  /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/test_predictions_712.csv
           4,640,037,647 B | modified 2026-09-29 04:20:44 (runtime clock, usually UTC)  /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/best.pt
           4,640,037,647 B | modified 2026-09-29 04:25:51 (runtime clock, usually UTC)  /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/checkpoints/last.pt

=== 2. KEYWORD HITS (±2 lines, max 12 per pattern per file) ===

##### cell11: 278 lines #####

-- /def\s+\w*(generate|decode)\w*/ : 3 hits
       6: 1117: # ================================================================
       7: 1118:
>>     8: 1119: def safe_decode(ids):
       9: 1120:
      10: 1121:     if torch.is_tensor(ids):
   ...
      30: 1414:
      31: 1415: @torch.no_grad()
>>    32: 1416: def exact_generate(
      33: 1417:     cond,
      34: 1418:     max_new_tokens=20,
   ...
     109:    3: # ============================================================
     110:    4:
>>   111:    5: def safe_decode(token_ids):
     112:    6:     """
     113:    7:     Decode generated mT5 token IDs while removing
   ...

-- /argmax/ : 12 hits
      38: 1457:         )
      39: 1458:
>>    40: 1459:         next_token = torch.argmax(
      41: 1460:             out.logits[:, -1, :],
      42: 1461:             dim=-1,
   ...
     137:  212:         )
     138:  213:
>>   139:  214:         next_token = torch.argmax(
     140:  215:             out.logits[:, -1, :],
     141:  216:             dim=-1,
   ...
     164:  125:             ).item()
     165:  126:
>>   166:  127:             # Does argmax change?
     167:  128:             full_argmax = int(torch.argmax(full))
     168:  129:             other_argmax = int(torch.argmax(other))
   ...
     165:  126:
     166:  127:             # Does argmax change?
>>   167:  128:             full_argmax = int(torch.argmax(full))
     168:  129:             other_argmax = int(torch.argmax(other))
     169:  130:
   ...
     166:  127:             # Does argmax change?
     167:  128:             full_argmax = int(torch.argmax(full))
>>   168:  129:             other_argmax = int(torch.argmax(other))
     169:  130:
     170:  131:             argmax_changed = (
   ...
     168:  129:             other_argmax = int(torch.argmax(other))
     169:  130:
>>   170:  131:             argmax_changed = (
     171:  132:                 full_argmax != other_argmax
     172:  133:             )
   ...
     169:  130:
     170:  131:             argmax_changed = (
>>   171:  132:                 full_argmax != other_argmax
     172:  133:             )
     173:  140:                 "max_abs_logit_diff": max_abs_diff,
   ...
     173:  140:                 "max_abs_logit_diff": max_abs_diff,
     174:  141:                 "cosine_similarity": cosine,
>>   175:  142:                 "argmax_changed": argmax_changed,
     176:  143:                 "full_top_token": tokenizer.decode(
     177:  144:                     [full_argmax],
   ...
     175:  142:                 "argmax_changed": argmax_changed,
     176:  143:                 "full_top_token": tokenizer.decode(
>>   177:  144:                     [full_argmax],
     178:  145:                     skip_special_tokens=False,
     179:  146:                 ),
   ...
     179:  146:                 ),
     180:  147:                 "other_top_token": tokenizer.decode(
>>   181:  148:                     [other_argmax],
     182:  149:                     skip_special_tokens=False,
     183:  150:                 ),
   ...
     190:   94:     other_probs = torch.softmax(other, dim=-1)
     191:   95:
>>   192:   96:     full_top = full.argmax(dim=-1)
     193:   97:     other_top = other.argmax(dim=-1)
     194:   98:
   ...
     191:   95:
     192:   96:     full_top = full.argmax(dim=-1)
>>   193:   97:     other_top = other.argmax(dim=-1)
     194:   98:
     195:   99:     # Probability assigned to FULL's preferred token
   ...

-- /max_new_tokens/ : 1 hits
      32: 1416: def exact_generate(
      33: 1417:     cond,
>>    34: 1418:     max_new_tokens=20,
      35: 1419: ):
      36: 1420:
   ...

-- /eos_token_id/ : 1 hits
     125:   25:
     126:   26: # sanity check
>>   127:   27: test_text = safe_decode([tokenizer.eos_token_id])
     128:   28: print("Test decode:", repr(test_text))
     129:   29:
   ...

-- /skip_special_tokens/ : 5 hits
      16: 1131:     return tokenizer.decode(
      17: 1132:         ids,
>>    18: 1133:         skip_special_tokens=True,
      19: 1134:     ).strip()
      20: 1135:
   ...
     119:   16:     return tokenizer.decode(
     120:   17:         token_ids,
>>   121:   18:         skip_special_tokens=True,
     122:   19:         clean_up_tokenization_spaces=True,
     123:   20:     )
   ...
     159:   37:         token = tokenizer.decode(
     160:   38:             [token_id],
>>   161:   39:             skip_special_tokens=False,
     162:   40:         )
     163:   41:         result.append({
   ...
     176:  143:                 "full_top_token": tokenizer.decode(
     177:  144:                     [full_argmax],
>>   178:  145:                     skip_special_tokens=False,
     179:  146:                 ),
     180:  147:                 "other_top_token": tokenizer.decode(
   ...
     180:  147:                 "other_top_token": tokenizer.decode(
     181:  148:                     [other_argmax],
>>   182:  149:                     skip_special_tokens=False,
     183:  150:                 ),
     184:  151:             })
   ...

-- /no_grad|inference_mode/ : 1 hits
      29: 1413: # ================================================================
      30: 1414:
>>    31: 1415: @torch.no_grad()
      32: 1416: def exact_generate(
      33: 1417:     cond,
   ...

-- /execution_count/ : 10 hits
       1:
       2: ==============================================================================
>>     3: CELL 1 | execution_count=None | lines=1914
       4: ==============================================================================
       5: 1116: # SAFE DECODE
   ...
     104:
     105: ==============================================================================
>>   106: CELL 4 | execution_count=None | lines=32
     107: ==============================================================================
     108:    2: # RESTORE SAFE DECODE HELPER
   ...
     132:
     133: ==============================================================================
>>   134: CELL 5 | execution_count=None | lines=445
     135: ==============================================================================
     136:  211:             return_dict=True,
   ...
     152:
     153: ==============================================================================
>>   154: CELL 6 | execution_count=None | lines=233
     155: ==============================================================================
     156:   34:     result = []
   ...
     185:
     186: ==============================================================================
>>   187: CELL 7 | execution_count=None | lines=368
     188: ==============================================================================
     189:   93:     full_probs = torch.softmax(full, dim=-1)
   ...
     198:
     199: ==============================================================================
>>   200: CELL 16 | execution_count=None | lines=203
     201: ==============================================================================
     202:   53:     )
   ...
     210:
     211: ==============================================================================
>>   212: CELL 25 | execution_count=None | lines=52
     213: ==============================================================================
     214:    8: candidate_names = [
   ...
     222:
     223: ==============================================================================
>>   224: CELL 81 | execution_count=None | lines=373
     225: ==============================================================================
     226:  118:             out_dim=512
   ...
     242:
     243: ==============================================================================
>>   244: CELL 123 | execution_count=15 | lines=398
     245: ==============================================================================
     246:  238:     drop_last=False
   ...
     267:
     268: ==============================================================================
>>   269: CELL 139 | execution_count=15 | lines=2121
     270: ==============================================================================
     271:  889:     collate_fn=collate_v5,
   ...

##### cell12: 837 lines #####

-- /to_csv/ : 2 hits
     201: === CELL 7 | execution_count=None | outputs=10 ===
     202: 40: model.load_state_dict(E3["model_state"], strict=True)
>>   203: 350: sensitivity_df.to_csv(
     204: 355: summary_df.to_csv(
     205: OUTPUT 0: ======================================================================
   ...
     202: 40: model.load_state_dict(E3["model_state"], strict=True)
     203: 350: sensitivity_df.to_csv(
>>   204: 355: summary_df.to_csv(
     205: OUTPUT 0: ======================================================================
     206: V4 E3 — VALIDATION SENSITIVITY
   ...

-- /best\.pt/ : 26 hits
       2: === CELL 0 | execution_count=None | outputs=1 ===
       3: 72: BEST_CKPT = (
>>     4: 73: f"{V4_DIR}/checkpoints/best.pt"
       5: OUTPUT 0: ======================================================================
       6: V4 NEW-NOTEBOOK BOOTSTRAP
   ...
      11: === CELL 1 | execution_count=None | outputs=24 ===
      12: 89: BEST_CKPT = (
>>    13: 90: f"{V4_DIR}/checkpoints/best.pt"
      14: 104: "Best checkpoint": BEST_CKPT,
      15: 988: E2 = torch.load(
   ...
     348: === CELL 24 | execution_count=None | outputs=2 ===
     349: 262: checkpoint_paths["last"] = os.path.join(CKPT_DIR, "last.pt")
>>   350: 263: checkpoint_paths["best"] = os.path.join(CKPT_DIR, "best.pt")
     351: OUTPUT 0: ========== V5 TRAINING PRE-FLIGHT ==========
     352: Device       : NVIDIA A100-SXM4-40GB
   ...
     380:
     381: === CELL 75 | execution_count=None | outputs=2 ===
>>   382: 35: os.path.join(V4_CKPT_DIR, "best.pt"),
     383: 89: ckpt = torch.load(
     384: 139: load_result = v5.load_state_dict(
   ...
     625: === CELL 126 | execution_count=1 | outputs=2 ===
     626: 8: #   - last.pt
>>   627: 10: #   - best.pt
     628: 92: V5_CKPT_DIR / "last.pt"
     629: 95: BEST_CKPT = (
   ...
     628: 92: V5_CKPT_DIR / "last.pt"
     629: 95: BEST_CKPT = (
>>   630: 96: V5_CKPT_DIR / "best.pt"
     631: 316: ckpt = torch.load(
     632: 411: checkpoint = torch.load(
   ...
     637: 1169: BEST_CKPT,
     638: 1280: f"last.pt exists  : {LAST_CKPT.exists()}"
>>   639: 1284: f"best.pt exists  : {BEST_CKPT.exists()}"
     640: 1291: assert BEST_CKPT.exists()
     641: 1327: "last.pt:",
   ...
     640: 1291: assert BEST_CKPT.exists()
     641: 1327: "last.pt:",
>>   642: 1332: "best.pt:",
     643: 1333: BEST_CKPT.exists()
     644: 1339: assert BEST_CKPT.exists()
   ...
     644: 1339: assert BEST_CKPT.exists()
     645: 1343: print("PASS: last.pt maintained.")
>>   646: 1344: print("PASS: best.pt maintained.")
     647: OUTPUT 0: ================================================================================
     648: V5 RESUME-SAFE TRAINING — FREQUENT CHECKPOINT
   ...
     653: 103: V5_CKPT_DIR / "last.pt"
     654: 106: BEST_CKPT = (
>>   655: 107: V5_CKPT_DIR / "best.pt"
     656: 448: ckpt = torch.load(
     657: 547: checkpoint = torch.load(
   ...
     661: 1260: BEST_CKPT,
     662: 1399: "last.pt:",
>>   663: 1404: "best.pt:",
     664: 1405: BEST_CKPT.exists()
     665: 1419: assert BEST_CKPT.exists()
   ...
     699:
     700: === CELL 139 | execution_count=15 | outputs=2 ===
>>   701: 24: #   best.pt
     702: 25: #   last.pt
     703: 161: "last.pt"
   ...

-- /last\.pt/ : 24 hits
     347:
     348: === CELL 24 | execution_count=None | outputs=2 ===
>>   349: 262: checkpoint_paths["last"] = os.path.join(CKPT_DIR, "last.pt")
     350: 263: checkpoint_paths["best"] = os.path.join(CKPT_DIR, "best.pt")
     351: OUTPUT 0: ========== V5 TRAINING PRE-FLIGHT ==========
   ...
     624:
     625: === CELL 126 | execution_count=1 | outputs=2 ===
>>   626: 8: #   - last.pt
     627: 10: #   - best.pt
     628: 92: V5_CKPT_DIR / "last.pt"
   ...
     626: 8: #   - last.pt
     627: 10: #   - best.pt
>>   628: 92: V5_CKPT_DIR / "last.pt"
     629: 95: BEST_CKPT = (
     630: 96: V5_CKPT_DIR / "best.pt"
   ...
     634: 435: optimizer_v5.load_state_dict(
     635: 443: scheduler_v5.load_state_dict(
>>   636: 880: # Also update last.pt
     637: 1169: BEST_CKPT,
     638: 1280: f"last.pt exists  : {LAST_CKPT.exists()}"
   ...
     636: 880: # Also update last.pt
     637: 1169: BEST_CKPT,
>>   638: 1280: f"last.pt exists  : {LAST_CKPT.exists()}"
     639: 1284: f"best.pt exists  : {BEST_CKPT.exists()}"
     640: 1291: assert BEST_CKPT.exists()
   ...
     639: 1284: f"best.pt exists  : {BEST_CKPT.exists()}"
     640: 1291: assert BEST_CKPT.exists()
>>   641: 1327: "last.pt:",
     642: 1332: "best.pt:",
     643: 1333: BEST_CKPT.exists()
   ...
     643: 1333: BEST_CKPT.exists()
     644: 1339: assert BEST_CKPT.exists()
>>   645: 1343: print("PASS: last.pt maintained.")
     646: 1344: print("PASS: best.pt maintained.")
     647: OUTPUT 0: ================================================================================
   ...
     651:
     652: === CELL 127 | execution_count=3 | outputs=2 ===
>>   653: 103: V5_CKPT_DIR / "last.pt"
     654: 106: BEST_CKPT = (
     655: 107: V5_CKPT_DIR / "best.pt"
   ...
     660: 579: scheduler_v5.load_state_dict(
     661: 1260: BEST_CKPT,
>>   662: 1399: "last.pt:",
     663: 1404: "best.pt:",
     664: 1405: BEST_CKPT.exists()
   ...
     700: === CELL 139 | execution_count=15 | outputs=2 ===
     701: 24: #   best.pt
>>   702: 25: #   last.pt
     703: 161: "last.pt"
     704: 164: BEST_CKPT = (
   ...
     701: 24: #   best.pt
     702: 25: #   last.pt
>>   703: 161: "last.pt"
     704: 164: BEST_CKPT = (
     705: 166: "best.pt"
   ...
     710: 1354: scheduler_v5.load_state_dict(
     711: 1991: BEST_CKPT,
>>   712: 2101: "last.pt:",
     713: 2106: "best.pt:",
     714: 2107: BEST_CKPT.exists()
   ...

-- /torch\.load/ : 24 hits
      13: 90: f"{V4_DIR}/checkpoints/best.pt"
      14: 104: "Best checkpoint": BEST_CKPT,
>>    15: 988: E2 = torch.load(
      16: 994: E3 = torch.load(
      17: 1017: load_result = model.load_state_dict(
   ...
      14: 104: "Best checkpoint": BEST_CKPT,
      15: 988: E2 = torch.load(
>>    16: 994: E3 = torch.load(
      17: 1017: load_result = model.load_state_dict(
      18: 1031: model.load_state_dict(
   ...
     296:
     297: === CELL 23 | execution_count=None | outputs=6 ===
>>   298: 188: loaded = torch.load(
     299: 205: v5_restore.load_state_dict(
     300: 246: optimizer_restore.load_state_dict(
   ...
     363:
     364: === CELL 54 | execution_count=None | outputs=1 ===
>>   365: 21: ckpt = torch.load(
     366: OUTPUT 0: Checkpoint: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v4/checkpoints/epoch_03.pt
     367: Size (MB): 4425.15
   ...
     381: === CELL 75 | execution_count=None | outputs=2 ===
     382: 35: os.path.join(V4_CKPT_DIR, "best.pt"),
>>   383: 89: ckpt = torch.load(
     384: 139: load_result = v5.load_state_dict(
     385: OUTPUT 0: ================================================================================
   ...
     392:
     393: === CELL 82 | execution_count=None | outputs=2 ===
>>   394: 105: checkpoint = torch.load(
     395: 210: load_result = v5.load_state_dict(
     396: OUTPUT 0: ================================================================================
   ...
     451:
     452: === CELL 96 | execution_count=None | outputs=2 ===
>>   453: 278: checkpoint = torch.load(
     454: 307: model.load_state_dict(
     455: 311: optimizer.load_state_dict(
   ...
     466:
     467: === CELL 97 | execution_count=None | outputs=2 ===
>>   468: 165: checkpoint = torch.load(
     469: OUTPUT 0: ================================================================================
     470: CELL 27A — RESTORE V5 RUNTIME AFTER SESSION RESET
   ...
     482:
     483: === CELL 104 | execution_count=None | outputs=1 ===
>>   484: 66: v4_ckpt = torch.load(
     485: 493: v4_ckpt_after = torch.load(
     486: OUTPUT 0: ================================================================================
   ...
     483: === CELL 104 | execution_count=None | outputs=1 ===
     484: 66: v4_ckpt = torch.load(
>>   485: 493: v4_ckpt_after = torch.load(
     486: OUTPUT 0: ================================================================================
     487: CELL 28 — V4 EPOCH 3 → V5 WARM-START AUDIT
   ...
     502:
     503: === CELL 105 | execution_count=None | outputs=2 ===
>>   504: 7: v4_ckpt_after = torch.load(
     505: OUTPUT 0:
     506: [V4 CHECKPOINT SAFETY]
   ...
     508:
     509: === CELL 106 | execution_count=None | outputs=7 ===
>>   510: 217: v4_ckpt = torch.load(
     511: 433: v4_check_after = torch.load(
     512: OUTPUT 0: ================================================================================
   ...

-- /load_state_dict/ : 40 hits
      15: 988: E2 = torch.load(
      16: 994: E3 = torch.load(
>>    17: 1017: load_result = model.load_state_dict(
      18: 1031: model.load_state_dict(
      19: 1102: model.load_state_dict(
   ...
      16: 994: E3 = torch.load(
      17: 1017: load_result = model.load_state_dict(
>>    18: 1031: model.load_state_dict(
      19: 1102: model.load_state_dict(
      20: 1507: model.load_state_dict(
   ...
      17: 1017: load_result = model.load_state_dict(
      18: 1031: model.load_state_dict(
>>    19: 1102: model.load_state_dict(
      20: 1507: model.load_state_dict(
      21: 1902: model.load_state_dict(
   ...
      18: 1031: model.load_state_dict(
      19: 1102: model.load_state_dict(
>>    20: 1507: model.load_state_dict(
      21: 1902: model.load_state_dict(
      22: OUTPUT 0: ======================================================================
   ...
      19: 1102: model.load_state_dict(
      20: 1507: model.load_state_dict(
>>    21: 1902: model.load_state_dict(
      22: OUTPUT 0: ======================================================================
      23: V4 NEW-NOTEBOOK BOOTSTRAP
   ...
      93:
      94: === CELL 2 | execution_count=None | outputs=6 ===

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/553 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/82.0 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/4.31M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/99.0 [00:00<?, ?B/s]

test GT tokens: {'count': 712.0, 'mean': 20.92, 'std': 12.01, 'min': 2.0, '25%': 10.0, '50%': 18.0, '75%': 30.0, 'max': 66.0}
test GT > 20 tokens: 321 (45.1%) | > 96: 0
pred tokens: {'count': 712.0, 'mean': 14.94, 'std': 7.15, 'min': 7.0, '25%': 10.0, '50%': 10.0, '75%': 22.0, 'max': 30.0} | preds with >= 20 tokens: 214
GT strings containing <unk> after tokenization: 0
GT strings that do not round-trip through tokenizer: 0
train GT tokens: {'count': 6138.0, 'mean': 19.75, 'std': 11.54, 'min': 2.0, '25%': 10.0, '50%': 17.0, '75%': 27.0, 'max': 70.0}
train GT > 20 tokens: 2491 (40.6%)

Report saved to: /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015_review/provenance_review_20261015_125928.txt

In [9]:
# === Region-level collapse check (read-only, CPU) ===
from google.colab import drive
drive.mount('/content/drive')

import os, re, datetime
import pandas as pd

ROOT = '/content/drive/MyDrive/NoiSoi_Matching'
V5   = f'{ROOT}/baseline_model_v5'
OUT  = f'{V5}/diagnostics/audit_20261015_review'      # new folder only
os.makedirs(OUT, exist_ok=True)
ts = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')

df = pd.read_csv(f'{V5}/test_predictions_712.csv')    # read-only
REG = {
    'Tai':  r'\b(tai|nhĩ)\b',
    'Mũi':  r'\b(mũi|xoang|va|polyp|cuốn)\b',
    'Họng': r'\b(họng|thanh quản|amidan|amiđan|dị vật|trào ngược|xương cá)\b',
}
def regions(s):
    s = str(s).lower()
    r = [k for k, p in REG.items() if re.search(p, s)]
    return '+'.join(r) if r else 'Khác'

df['gt_region']   = df['ground_truth'].map(regions)
df['pred_region'] = df['prediction'].map(regions)

ct = pd.crosstab(df['gt_region'], df['pred_region'], margins=True)
print('=== GT region (rows) vs predicted region (cols) ===\n', ct, '\n')

print('=== Single-region GT cases ===')
rows = []
for reg in REG:
    sub = df[df['gt_region'] == reg]
    if sub.empty:
        continue
    r = {
        'region': reg, 'cases': len(sub),
        'pred_region_correct': round(sub['pred_region'].str.contains(reg).mean(), 3),
        'unique_GT': sub['ground_truth'].str.lower().str.strip().nunique(),
        'unique_pred': sub['prediction'].str.lower().str.strip().nunique(),
        'top_pred_share': round(sub['prediction'].str.lower().value_counts(normalize=True).iloc[0], 3),
        'exact': round((sub['prediction'].str.lower().str.strip() == sub['ground_truth'].str.lower().str.strip()).mean(), 3),
    }
    rows.append(r); print(r)

ct.to_csv(f'{OUT}/region_crosstab_{ts}.csv')
pd.DataFrame(rows).to_csv(f'{OUT}/region_summary_{ts}.csv', index=False)
print('\nSaved to', OUT)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
=== GT region (rows) vs predicted region (cols) ===
 pred_region   Họng  Mũi  Tai  Tai+Mũi  All
gt_region
Họng            75    0    0        0   75
Khác             5    0    0        0    5
Mũi              1  326   23        2  352
Mũi+Họng         0    7    0        0    7
Tai              0   20   97        2  119
Tai+Họng         0    0    1        0    1
Tai+Mũi          0   78   66        8  152
Tai+Mũi+Họng     0    0    1        0    1
All             81  431  188       12  712

=== Single-region GT cases ===
{'region': 'Tai', 'cases': 119, 'pred_region_correct': np.float64(0.832), 'unique_GT': 53, 'unique_pred': 10, 'top_pred_share': np.float64(0.613), 'exact': np.float64(0.042)}
{'region': 'Mũi', 'cases': 352, 'pred_region_correct': np.float64(0.932), 'unique_GT': 78, 'unique_pred': 10, 'top_pred_share': np.float64(0.713), 'exact': np.float64(0.213)}
{'region': 'Họng', 'cases': 75, 'pred_region_correct': np.float64(1.0), 'unique_GT': 22, 'unique_pred': 1, 'top_pred_share': np.float64(1.0), 'exact': np.float64(0.68)}

Saved to /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015_review

In [10]:
# === V5 vs region lookup-table baselines (read-only, CPU) ===
from google.colab import drive
drive.mount('/content/drive')

import os, re, datetime, collections
import pandas as pd

ROOT = '/content/drive/MyDrive/NoiSoi_Matching'
V5   = f'{ROOT}/baseline_model_v5'
OUT  = f'{V5}/diagnostics/audit_20261015_review'
os.makedirs(OUT, exist_ok=True)
ts = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')

REG = {
    'Tai':  r'\b(tai|nhĩ)\b',
    'Mũi':  r'\b(mũi|xoang|va|polyp|cuốn)\b',
    'Họng': r'\b(họng|thanh quản|amidan|amiđan|dị vật|trào ngược|xương cá)\b',
}
def regions(s):
    s = str(s).lower()
    r = [k for k, p in REG.items() if re.search(p, s)]
    return '+'.join(r) if r else 'Khác'
def norm(s):
    s = re.sub(r'[.,;:()\-–]', ' ', str(s).lower())
    return re.sub(r'\s+', ' ', s).strip()
def f1(p, g):
    pt, gt = norm(p).split(), norm(g).split()
    if not pt or not gt:
        return float(pt == gt)
    common = sum((collections.Counter(pt) & collections.Counter(gt)).values())
    if common == 0:
        return 0.0
    pr, rc = common / len(pt), common / len(gt)
    return 2 * pr * rc / (pr + rc)

# Lookup table from TRAIN labels only
man = pd.read_csv(f'{ROOT}/baseline_model_v4/v4_training_manifest.csv', usecols=['split', 'ket_luan'])
train = man[man['split'] == 'train'].dropna(subset=['ket_luan']).copy()
train['region'] = train['ket_luan'].map(regions)
train['n'] = train['ket_luan'].map(norm)
lookup = train.groupby('region')['n'].agg(lambda s: s.value_counts().index[0])
global_mode = train['n'].value_counts().index[0]
print('=== Most common TRAIN label per region ===')
print(lookup.to_string(), '\n')

df = pd.read_csv(f'{V5}/test_predictions_712.csv')          # read-only
df['gt_region']  = df['ground_truth'].map(regions)
df['v5_region']  = df['prediction'].map(regions)
df['gt_n']       = df['ground_truth'].map(norm)
df['V5 model']   = df['prediction'].map(norm)
df["Lookup (V5's region)"]  = df['v5_region'].map(lookup).fillna(global_mode)
df['Lookup (true region)']  = df['gt_region'].map(lookup).fillna(global_mode)
df['Always top label']      = global_mode

methods = ['V5 model', "Lookup (V5's region)", 'Lookup (true region)', 'Always top label']
rows = []
for m in methods:
    rows.append({
        'method': m,
        'exact': round((df[m] == df['gt_n']).mean(), 4),
        'token_f1': round(df.apply(lambda r: f1(r[m], r['gt_n']), axis=1).mean(), 4),
        'unique_outputs': df[m].nunique(),
    })
overall = pd.DataFrame(rows)
print('=== Overall (712 test cases) ===\n', overall.to_string(index=False), '\n')

per = []
for reg, sub in df.groupby('gt_region'):
    r = {'gt_region': reg, 'cases': len(sub)}
    for m in methods:
        r[f'{m} | exact'] = round((sub[m] == sub['gt_n']).mean(), 3)
        r[f'{m} | F1']    = round(sub.apply(lambda x: f1(x[m], x['gt_n']), axis=1).mean(), 3)
    per.append(r)
per = pd.DataFrame(per).sort_values('cases', ascending=False)
print('=== By GT region ===\n', per.to_string(index=False))

agree = (df['V5 model'] == df["Lookup (V5's region)"]).mean()
print(f"\nV5 output identical to lookup-by-its-own-region: {agree:.1%}")

overall.to_csv(f'{OUT}/v5_vs_lookup_overall_{ts}.csv', index=False)
per.to_csv(f'{OUT}/v5_vs_lookup_by_region_{ts}.csv', index=False)
print('Saved to', OUT)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
=== Most common TRAIN label per region ===
region
Họng                    viêm họng mạn theo dõi trào ngược dịch vị
Khác                                            a mi đan quá phát
Mũi                                                      viêm mũi
Mũi+Họng                                        viêm họng mũi cấp
Tai             hiện không thấy hình ảnh bệnh lý tai ngoài tai...
Tai+Họng                                      dị vật tai p đã lấy
Tai+Mũi         hiện không thấy hình ảnh bệnh lý tai ngoài tai...
Tai+Mũi+Họng                viêm tai giữa p cấp viêm họng mũi cấp

=== Overall (712 test cases) ===
               method  exact  token_f1  unique_outputs
            V5 model 0.1896    0.5979              16
Lookup (V5's region) 0.1713    0.5128               4
Lookup (true region) 0.2163    0.5993               8
    Always top label 0.0941    0.4575               1

=== By GT region ===
    gt_region  cases  V5 model | exact  V5 model | F1  Lookup (V5's region) | exact  Lookup (V5's region) | F1  Lookup (true region) | exact  Lookup (true region) | F1  Always top label | exact  Always top label | F1
         Mũi    352             0.224          0.683                         0.173                      0.651                         0.190                      0.702                      0.19                  0.702
     Tai+Mũi    152             0.000          0.402                         0.000                      0.260                         0.053                      0.453                      0.00                  0.284
         Tai    119             0.042          0.472                         0.084                      0.235                         0.193                      0.326                      0.00                  0.150
        Họng     75             0.680          0.843                         0.680                      0.843                         0.680                      0.843                      0.00                  0.168
    Mũi+Họng      7             0.000          0.526                         0.000                      0.575                         0.714                      0.847                      0.00                  0.575
        Khác      5             0.000          0.064                         0.000                      0.064                         0.000                      0.344                      0.00                  0.147
    Tai+Họng      1             0.000          0.667                         0.000                      0.207                         0.000                      0.571                      0.00                  0.118
Tai+Mũi+Họng      1             0.000          0.296                         0.000                      0.625                         0.000                      0.444                      0.00                  0.200

V5 output identical to lookup-by-its-own-region: 11.5%
Saved to /content/drive/MyDrive/NoiSoi_Matching/baseline_model_v5/diagnostics/audit_20261015_review